export const designer_data = {
  past: [],
  present: {
    filterCounter: 0,
    parameterDrawerStatus: true,
    designerSettings: [
      {
        key: "parameters",
        values: {
          enable: true,
          orientation: "right",
          enableApplyButton: true,
        },
      },
    ],
    previewMode: false,
    designerMode: "create",
    dashboardVariables: {},
    dashboardUUID: "",
    variables: [],
    components: {},
    dashboardConfig: {
      id: "dashboard",
    },
    css: "",
    script: "",
    printOptions: {
      templateId: "Dashboard",
      title: "Dashboard",
    },
    componentSettings: {},
    toggleIframes: false,
    gridItemsData: [],
    layout: [],
    dashboardDrawerStatus: false,
    gridItemDrawerStatus: false,
    currentGroupId: "",
    groupId: "",
    gridItemId: "",
    drawerPositions: ["right", "bottom", "left", "top"],
    currentDrawerPosition: 0,
    gridSettings: [
      {
        key: "breakpoints",
        values: [
          {
            key: "lg",
            name: "Large Screens",
            value: 1200,
            tooltip: "Large Screens(lg)",
          },
          {
            key: "md",
            name: "Medium Screens",
            value: 996,
            tooltip: "Medium Screens(md)",
          },
          {
            key: "sm",
            name: "Small Screens",
            value: 768,
            tooltip: "Small Screens(sm)",
          },
          {
            key: "xs",
            name: "Extra Small Screens",
            value: 480,
            tooltip: "Extra Small Screens(xs)",
          },
          {
            key: "xxs",
            name: "Extra Extra Small Screens",
            value: 240,
            tooltip: "Extra Extra Small Screens(xxs)",
          },
        ],
      },
      {
        key: "columns",
        values: [
          {
            key: "lg",
            name: "Large Screens",
            value: 12,
            tooltip: "Large Screens(lg)",
          },
          {
            key: "md",
            name: "Medium Screens",
            value: 12,
            tooltip: "Medium Screens(md)",
          },
          {
            key: "sm",
            name: "Small Screens",
            value: 6,
            tooltip: "Small Screens(sm)",
          },
          {
            key: "xs",
            name: "Extra Small Screens",
            value: 4,
            tooltip: "Extra Small Screens(xs)",
          },
          {
            key: "xxs",
            name: "Extra Extra Small Screens",
            value: 2,
            tooltip: "Extra Extra Small Screens(xxs)",
          },
        ],
      },
      {
        key: "grid",
        values: {
          autoSize: true,
          compactType: null,
          rowHeight: 100,
          isDroppable: false,
          preventCollision: true,
          measureBeforeMount: false,
          isDraggable: true,
          isResizable: true,
        },
      },
      {
        key: "header",
        values: {
          enable: false,
          title: "<p><br></p>",
          placeholder: "Edit/Add your header content here",
          link: "",
          backgroundColor: {
            r: 255,
            g: 255,
            b: 255,
            a: 100,
          },
          position: "left",
        },
      },
      {
        key: "shadow",
        values: {
          enable: false,
          xOffset: 0,
          yOffset: 0,
          blur: 0,
          spread: 0,
          color: {
            r: 255,
            g: 255,
            b: 255,
            a: 100,
          },
        },
      },
      {
        key: "background",
        values: {
          enable: false,
          backgroundColor: {
            r: 255,
            g: 255,
            b: 255,
            a: 100,
          },
          image: "",
          opacity: 100,
          backgroundSize: "auto",
          backgroundRepeat: "initial",
        },
      },
      {
        key: "border",
        values: {
          enable: false,
          borderWidth: 1,
          borderStyle: "solid",
          color: {
            r: 255,
            g: 255,
            b: 255,
            a: 100,
          },
          borderPosition: "border",
          borderRadius: 0,
        },
      },
      {
        key: "html",
        values: {
          enable: false,
          value: "",
        },
      },
      {
        key: "css",
        values: {
          enable: false,
          value: "",
        },
      },
      {
        key: "javascript",
        values: {
          enable: false,
          value: "",
        },
      },
    ],
    filterItemsData: [],
    maximizedGridItem: {},
    maximizingStatus: false,
    gridIndex: 0,
    isLoading: false,
    reportId: "",
    applyDashboardFilters: null,
    isSaving: false,
    expandDesignerDrawers: false,
    hasUnsavedData: true,
    savedReportName: "",
    designerLayout: [],
    toggleToolsAreaShelf: true,
  },
  future: [],
};

export const _designer_data_ = {
  past: [],
  present: {
    filterCounter: 0,
    parameterDrawerStatus: false,
    designerSettings: [
      {
        key: "parameters",
        values: {
          enable: true,
          orientation: "right",
          enableApplyButton: true,
        },
      },
    ],
    previewMode: false,
    designerMode: "create",
    dashboardVariables: {},
    dashboardUUID: "",
    variables: [],
    components: {},
    dashboardConfig: {
      id: "dashboard",
    },
    css: "",
    script: "",
    printOptions: {
      templateId: "Dashboard",
      title: "Dashboard",
    },
    componentSettings: {},
    toggleIframes: false,
    gridItemsData: [
      {
        id: "item-6eo1G",
        compType: "dashboard-designer-component",
        isGrouped: false,
        isSaved: false,
        initialPosition: {
          x: 0,
          y: 0,
          w: 2,
          h: 2,
          i: "item-6eo1G",
          static: false,
        },
        gridItemConfig: [
          {
            key: "header",
            values: {
              enable: true,
              title: "grid_aggregate",
              placeholder: "Edit/Add your header content here",
              link: "",
              backgroundColor: {
                r: 24,
                g: 144,
                b: 255,
                a: 100,
              },
              position: "left",
              enableTooltip: false,
              tooltipText: "",
            },
          },
          {
            key: "shadow",
            values: {
              enable: false,
              xOffset: 1,
              yOffset: 1,
              blur: 1,
              spread: 1,
              color: {
                r: 24,
                g: 144,
                b: 255,
                a: 100,
              },
            },
          },
          {
            key: "background",
            values: {
              enable: false,
              backgroundColor: {
                r: 255,
                g: 255,
                b: 255,
                a: 100,
              },
              image: "",
              opacity: 100,
              backgroundSize: "auto",
              backgroundRepeat: "initial",
            },
          },
          {
            key: "border",
            values: {
              enable: false,
              borderWidth: 1,
              borderStyle: "solid",
              color: {
                r: 24,
                g: 144,
                b: 255,
                a: 100,
              },
              borderPosition: "border",
              borderRadius: 0,
            },
          },
          {
            key: "html",
            values: {
              enable: false,
              value: "",
            },
          },
          {
            key: "css",
            values: {
              enable: false,
              value: "",
            },
          },
          {
            key: "javascript",
            values: {
              enable: false,
              value: "",
            },
          },
          {
            key: "griditemsettings",
            values: {
              export: false,
              edit: false,
              maximize: false,
            },
          },
        ],
        reportInfo: {
          file: {
            path: "03_02/grid_aggregate.hr",
            name: "grid_aggregate.hr",
            title: "grid_aggregate",
          },
          mode: "dashboard",
          filters: [],
          component: "hreport",
          extension: "hr",
        },
        filters: [],
        listeners: [],
        reportId: "914ccf66-c47a-415d-8ef5-97b8af884cb0",
      },
    ],
    layout: [
      {
        w: 4,
        h: 3,
        x: 0,
        y: 0,
        i: "item-6eo1G",
        moved: false,
        static: false,
      },
    ],
    dashboardDrawerStatus: false,
    gridItemDrawerStatus: false,
    currentGroupId: "",
    groupId: "",
    gridItemId: "",
    drawerPositions: ["right", "bottom", "left", "top"],
    currentDrawerPosition: 0,
    gridSettings: [
      {
        key: "breakpoints",
        values: [
          {
            key: "lg",
            name: "Large Screens",
            value: 1200,
            tooltip: "Large Screens(lg)",
          },
          {
            key: "md",
            name: "Medium Screens",
            value: 996,
            tooltip: "Medium Screens(md)",
          },
          {
            key: "sm",
            name: "Small Screens",
            value: 768,
            tooltip: "Small Screens(sm)",
          },
          {
            key: "xs",
            name: "Extra Small Screens",
            value: 480,
            tooltip: "Extra Small Screens(xs)",
          },
          {
            key: "xxs",
            name: "Extra Extra Small Screens",
            value: 240,
            tooltip: "Extra Extra Small Screens(xxs)",
          },
        ],
      },
      {
        key: "columns",
        values: [
          {
            key: "lg",
            name: "Large Screens",
            value: 12,
            tooltip: "Large Screens(lg)",
          },
          {
            key: "md",
            name: "Medium Screens",
            value: 12,
            tooltip: "Medium Screens(md)",
          },
          {
            key: "sm",
            name: "Small Screens",
            value: 6,
            tooltip: "Small Screens(sm)",
          },
          {
            key: "xs",
            name: "Extra Small Screens",
            value: 4,
            tooltip: "Extra Small Screens(xs)",
          },
          {
            key: "xxs",
            name: "Extra Extra Small Screens",
            value: 2,
            tooltip: "Extra Extra Small Screens(xxs)",
          },
        ],
      },
      {
        key: "grid",
        values: {
          autoSize: true,
          compactType: null,
          rowHeight: 100,
          isDroppable: false,
          preventCollision: true,
          measureBeforeMount: false,
          isDraggable: true,
          isResizable: true,
        },
      },
      {
        key: "header",
        values: {
          enable: false,
          title: "<p><br></p>",
          placeholder: "Edit/Add your header content here",
          link: "",
          backgroundColor: {
            r: 255,
            g: 255,
            b: 255,
            a: 100,
          },
          position: "left",
        },
      },
      {
        key: "shadow",
        values: {
          enable: false,
          xOffset: 0,
          yOffset: 0,
          blur: 0,
          spread: 0,
          color: {
            r: 255,
            g: 255,
            b: 255,
            a: 100,
          },
        },
      },
      {
        key: "background",
        values: {
          enable: false,
          backgroundColor: {
            r: 255,
            g: 255,
            b: 255,
            a: 100,
          },
          image: "",
          opacity: 100,
          backgroundSize: "auto",
          backgroundRepeat: "initial",
        },
      },
      {
        key: "border",
        values: {
          enable: false,
          borderWidth: 1,
          borderStyle: "solid",
          color: {
            r: 255,
            g: 255,
            b: 255,
            a: 100,
          },
          borderPosition: "border",
          borderRadius: 0,
        },
      },
      {
        key: "html",
        values: {
          enable: false,
          value: "",
        },
      },
      {
        key: "css",
        values: {
          enable: false,
          value: "",
        },
      },
      {
        key: "javascript",
        values: {
          enable: false,
          value: "",
        },
      },
    ],
    filterItemsData: [],
    maximizedGridItem: {},
    maximizingStatus: false,
    gridIndex: 0,
    isLoading: false,
    reportId: "",
    applyDashboardFilters: null,
    isSaving: false,
    expandDesignerDrawers: false,
    hasUnsavedData: true,
    savedReportName: "",
    designerLayout: [
      {
        w: 4,
        h: 3,
        x: 0,
        y: 0,
        i: "item-6eo1G",
        moved: false,
        static: false,
      },
    ],
    toggleToolsAreaShelf: true,
    itemAddedStatus: 1683203639458,
  },
  future: [],
};
