

export const getTableUniqueKey = ({mode, id, dbId}) => {
    //assuming dbId is generated by frontend at create mode and is part of table object otherwise use correct object to get db id
    if(!id || !mode) 
     throw new Error("error in getTableUniqueKey func. id or mode is missing");
    if(mode === "create") {
        if(!dbId)
        throw new Error("error in getTableUniqueKey func. dbId is missing");
        return id + "_" + dbId;
    }
    if(mode === "edit") 
        return id;
}

export const getViewUniqueKey = ({mode, id, dbId}) => {
    //assuming dbId is generated by frontend at create mode and is part of table object otherwise use correct object to get db id
    if(!id || !mode) 
     throw new Error("error in getViewUniqueKey func. id or mode is missing");
    if(mode === "create") {
        if(!dbId)
        throw new Error("error in getViewUniqueKey func. dbId is missing");
        return id + "_" + dbId;
    }
    if(mode === "edit") 
        return id;
}

export const getColumnUniqueKey = ({mode, id, dbId}) => {
    //assuming dbId is generated by frontend at create mode and is part of table object otherwise use correct object to get db id
    if(!id || !mode) 
    throw new Error("error in getColumnUniqueKey func. id or mode is missing");
    if(mode === "create") {
        if(!dbId)
        throw new Error("error in getColumnUniqueKey func. dbId is missing");
        return id +"_" + dbId;
    }
    if(mode === "edit") 
        return id;
}

// export const getTableDetails = (uniqueKey, tables) => {
//     return Object.values(tables).find(table => table.uniqueKey === uniqueKey)
// }

export const transformSecurityTable = ({mappedUniqueKeys, securityTableData, testPurpose= false}) => {
    return securityTableData.map(entity => {
        entity.securityKeysToBeCheck = entity.securityKeysToBeCheck.reduce((acc, key) => {
            if(testPurpose) {
                let val = mappedUniqueKeys.find(ele => ele.key === key);
                if(val) {
                    acc.push(val.value);
                } else {
                    acc.push(key);
                }
                return acc;
            }
            if(mappedUniqueKeys.has(key)) {
                acc.push(mappedUniqueKeys.get(key));
            } else {
                acc.push(key);
            }
            return acc;
        }, [])
        return entity;
     })
}

export const mapStoredTablesUniqueKeysWithFetchedTables = (oldTables = {}, newTables = {}) => {
    const mappedUniqueKeys = new Map();
    const oldTablesValues = Object.values(oldTables);
    const newTablesValues = Object.values(newTables);
    oldTablesValues.forEach(oldTable => {
        newTablesValues.find(newTable => {
            if((oldTable.alias === newTable.alias) && (oldTable.dataSource?.id === newTable.dataSource?.id) && (oldTable.dataSource?.type === newTable.dataSource?.type)) {
                mappedUniqueKeys.set(oldTable.uniqueKey, newTable.uniqueKey);
                Object.values(oldTable.columns || {}).forEach(oldCol => {
                    Object.values(newTable.columns || {}).find(newCol => {
                        if((oldCol.alias === newCol.alias)) {
                            mappedUniqueKeys.set(oldCol.uniqueKey, newCol.uniqueKey);
                            return true
                        }
                    })
                }) 
                return true;
            }
        })
    })
    return mappedUniqueKeys;
}