worker_processes auto;

events {
    worker_connections 1024;
}

http {

   proxy_read_timeout 1h;
   proxy_connect_timeout 1h;
   proxy_send_timeout 1h;
	
	
    upstream appservers { 
        #ip_hash;
    	server hiee:8080;
        #server localhost:8080;
    }
		
      server {
        listen 443 ssl;
        server_name localhost;
        ssl_certificate /etc/nginx/ssl/helical.cert;
        ssl_certificate_key /etc/nginx/ssl/helical.key;
        ssl_password_file /etc/nginx/ssl/pass.txt;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
		ssl_ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!dSS;
		ssl_prefer_server_ciphers   on;

		ssl_session_cache   shared:SSL:20m;
		ssl_session_timeout 60m;

		add_header Strict-Transport-Security "max-age=31536000";
		add_header X-Content-Type-Options nosniff;


    location /hi-ee/services {
        
        proxy_buffering             off;
        proxy_cache                 off;
        chunked_transfer_encoding   on;
        proxy_pass                  http://appservers;
        proxy_http_version          1.1;
        proxy_set_header Connection "keep-alive";
        proxy_read_timeout          1h;
        proxy_send_timeout          1h;
    }
        
	location / {
        proxy_pass                  http://appservers;
        proxy_set_header 		    X-Real-IP $remote_addr;
        proxy_set_header 		    X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header 		    X-Forwarded-Proto $scheme;
        include  			        /etc/nginx/mime.types;
        proxy_http_version          1.1;
        proxy_set_header 		    Upgrade $http_upgrade;
        proxy_set_header 		    Connection keep-alive;

	    proxy_set_header            X-Forwarded-Proto https;
	    proxy_set_header            X-Forwarded-Port 443;
	    proxy_set_header            Host $host;
	    proxy_set_header            X-Forwarded-Host $http_host;
	    proxy_set_header            HTTPS "on";
	    client_max_body_size 	    100M;
        }
    }
}
