import actionTypes from "../actions/actionTypes";


export const cannedReportIncludingTypes = [
    actionTypes.ADD_GRID_ITEM,
    actionTypes.UPDATE_GRID_LAYOUT,
    actionTypes.UPDATE_GRID_ITEM_STYLES,
    actionTypes.CHANGE_IS_DRAGGABLE_GRID_ITEM,
    actionTypes.CHANGE_IS_SELECTED_GRID_ITEM,
    actionTypes.UNGROUP_GRID_ITEM,
    actionTypes.DELETE_GRID_ITEM,
    actionTypes.UPDATE_NESTED_GRID_LAYOUT,
    actionTypes.UPDATE_DESIGNER_SETTINGS,
    actionTypes.UPDATE_PARAMETER_DRAWER_STATUS,
    actionTypes.APPLY_DASHBOARD_FILTERS,
    actionTypes.MAXIMISE_GRID_ITEM,
    actionTypes.TOGGLE_TOOLS_AREA_SHELF,
    actionTypes.UPDATE_GRID_SETTINGS,
    actionTypes.ADD_TO_TAB,
    actionTypes.CHANGE_THE_REPORT,
    actionTypes.HCR_ADD_NODE,
    actionTypes.HCR_EDIT_NODE,
    actionTypes.HCR_DELETE_NODE,
    actionTypes.HCR_DELETE_NODES,
    actionTypes.HCR_EDIT_NODES,
    actionTypes.HCR_HANDLE_EDITING_DS_PANE_ITEM,
    actionTypes.HCR_SET_SELECT_CONNECTION,
    actionTypes.HCR_SET_EXECUTE_QUERY_DATA,
    actionTypes.ADD_HCR_TAB_DATA,
    actionTypes.REMOVE_HCR_TAB,
    actionTypes.HCR_DS_PANE_ITEM_DELETE,
    actionTypes.HCR_DS_PANE_ITEM_EDIT,
    actionTypes.HCR_DS_PANE_ITEM_ADD,
    actionTypes.HCR_SIDEBAR_PANE_ACTIVE_KEY,
    actionTypes.HCR_CANVAS_LAYOUT_SIZE,
    actionTypes.HCR_ORIENTATION,
    actionTypes.HCR_CANVAS_MARGIN,
    actionTypes.HCR_CANVAS_PAGE_PROPS,
    actionTypes.HCR_CANVAS_CALCULATIONS,
    actionTypes.HCR_CANVAS_PREVIEW_PARAMS,
    actionTypes.HCR_CANVAS_GROUP_PROPERTIES,
    actionTypes.HCR_CANVAS_PAGE_STYLES,
    actionTypes.HCR_RESIZE_NODE,
    actionTypes.HCR_DIAGRAM_NODES_DATA,
    actionTypes.HCR_UPDATE_CANVAS_TAB_VIEW_COMPONENT,
]