export const storeData = {
  metadata: {
    dataFetchedFor: {
      getDatasource: true,
      joins: false,
      viewSessionVariables: false,
      listDataSources: true,
      "b09l-0fng-gpfn-yhza-qj": false,
      d324e793296ff76020c708f1c8fbb704_dq993: false,
    },
    loadingStatus: {
      getDatasource: true,
      listDataSources: true,
      "b09l-0fng-gpfn-yhza-qj": false,
      d324e793296ff76020c708f1c8fbb704_dq993: false,
    },
    joinsLoadingStatus: "",
    serviceErrorStatus: {},
    fetchedDSInfo: {},
    listDataSource: [],
    supportedDataSourceTypes: [
      {
        name: "Access",
        categoryType: "supported",
        categoryName: "Supported",
      },
      {
        name: "Amazon Dynamodb",
        categoryType: "supported",
        categoryName: "Supported",
      },
      {
        name: "Amazon Redshift",
        categoryType: "supported",
        categoryName: "Supported",
      },
      {
        name: "Dremio",
        categoryType: "supported",
        categoryName: "Supported",
      },
      {
        name: "Google Bigquery",
        categoryType: "supported",
        categoryName: "Supported",
      },
      {
        name: "Microsoft Sqlserver",
        categoryType: "supported",
        categoryName: "Supported",
      },
      {
        name: "Teradata",
        categoryType: "supported",
        categoryName: "Supported",
      },
      {
        name: "Ξ Add Driver Ξ",
        categoryType: "supported",
        categoryName: "Supported",
      },
    ],
    allDataSourceTypes: [
      {
        name: "Access",
        categoryType: "supported",
        categoryName: "Supported",
      },
      {
        name: "Amazon Dynamodb",
        categoryType: "supported",
        categoryName: "Supported",
      },
      {
        name: "Amazon Redshift",
        categoryType: "supported",
        categoryName: "Supported",
      },
      {
        driver: "org.apache.drill.jdbc.Driver",
        databaseDialect: "drill",
        enabledTypes: true,
        name: "Apache Drill",
        categoryName: "Big Data",
        categoryType: "big_data",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:drill:{{hostName}}:{{port}}",
        parameters: {
          port: "31010",
          hostName: "drillbit=localhost",
        },
      },
      {
        driver: "com.simba.athena.jdbc.Driver",
        databaseDialect: "athena",
        name: "Athena",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:awsathena://{{hostName}}",
        parameters: {
          hostName: "localhost",
        },
      },
      {
        driver: "com.helicalinsight.avro",
        databaseDialect: "",
        name: "Avro",
        categoryName: "Flat Files",
        categoryType: "flat_files",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        fileUpload: true,
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
      },
      {
        driver: "ru.yandex.clickhouse.ClickHouseDriver",
        databaseDialect: "clickhouse",
        name: "Clickhouse",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:clickhouse://{{hostName}}:{{port}}/{{database}}",
        parameters: {
          port: "8123",
          hostName: "localhost",
          database: "database",
        },
      },
      {
        driver: "com.helicalinsight.csv",
        databaseDialect: "",
        name: "Csv",
        categoryName: "Flat Files",
        categoryType: "flat_files",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        fileUpload: true,
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
      },
      {
        driver: "com.helicalinsight.csvh",
        databaseDialect: "",
        name: "Csvh",
        categoryName: "Flat Files",
        categoryType: "flat_files",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        fileUpload: true,
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
      },
      {
        driver: "com.databricks.client.jdbc.Driver",
        databaseDialect: "databricks",
        name: "Databricks Client",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:databricks://{{hostName}}:{{port}};{{database}}",
        parameters: {
          port: "443",
          hostName: "localhost",
          database: "database",
        },
      },
      {
        driver: "org.apache.derby.jdbc.ClientDriver",
        databaseDialect: "derby",
        name: "Derby",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:derby://{{hostName}}:{{port}}/{{database}}",
        parameters: {
          port: "1527",
          hostName: "localhost",
          database: "database",
        },
      },
      {
        driver: "org.apache.derby.jdbc.AutoloadedDriver",
        databaseDialect: "derby",
        name: "Derby",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:derby:{{database}}",
        parameters: {
          database: "database",
        },
      },
      {
        name: "Dremio",
        categoryType: "supported",
        categoryName: "Supported",
      },
      {
        driver: "dynamicSwitch",
        databaseDialect: "",
        name: "DynamicSwitch",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
      },
      {
        driver: "org.elasticsearch.xpack.sql.jdbc.EsDriver",
        databaseDialect: "elasticsearchsql",
        name: "Elasticsearch",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:es://{{hostName}}",
        parameters: {
          hostName: "localhost",
        },
      },
      {
        driver: "com.helicalinsight.excel",
        databaseDialect: "",
        name: "Excel",
        categoryName: "Flat Files",
        categoryType: "flat_files",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        fileUpload: true,
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
      },
      {
        name: "Google Bigquery",
        categoryType: "supported",
        categoryName: "Supported",
      },
      {
        driver: "com.helical.mongodb.MongoJdbcDriver",
        databaseDialect: "himongo",
        name: "Helical Mongodb",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
      },
      {
        driver: "org.apache.hive.jdbc.HiveDriver",
        databaseDialect: "spark",
        name: "Hive",
        categoryName: "Big Data",
        categoryType: "big_data",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:hive2://{{hostName}}:{{port}}/{{database}}",
        parameters: {
          port: "10001",
          hostName: "localhost",
          database: "database",
        },
      },
      {
        driver: "com.ibm.db2.jcc.DB2Driver",
        databaseDialect: "db2",
        name: "IBM Db2",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:db2://{{hostName}}:{{port}}/{{database}}",
        parameters: {
          port: "50000",
          hostName: "localhost",
          database: "database",
        },
      },
      {
        driver: "com.informix.jdbc.IfxDriver",
        databaseDialect: "informix",
        name: "Informix",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:informix-sqli://{{hostName}}:{{port}}/{{database}}:delimident=y",
        parameters: {
          port: "1526",
          hostName: "localhost",
          database: "database",
        },
      },
      {
        driver: "com.helicalinsight.json",
        databaseDialect: "",
        name: "Json",
        categoryName: "Flat Files",
        categoryType: "flat_files",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        fileUpload: true,
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
      },
      {
        driver: "com.helicalinsight.ltsv",
        databaseDialect: "",
        name: "Ltsv",
        categoryName: "Flat Files",
        categoryType: "flat_files",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        fileUpload: true,
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
      },
      {
        driver: "org.mariadb.jdbc.Driver",
        databaseDialect: "mysql",
        name: "Mariadb",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:mariadb://{{hostName}}:{{port}}/{{database}}",
        parameters: {
          port: "3306",
          hostName: "localhost",
          database: "database",
        },
      },
      {
        name: "Microsoft Sqlserver",
        categoryType: "supported",
        categoryName: "Supported",
      },
      {
        driver: "net.sourceforge.jtds.jdbc.Driver",
        databaseDialect: "sqlserver",
        name: "Microsoft Sqlserver(sourceforge)",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:jtds:sqlserver://{{hostName}}:{{port}}/{{database}}",
        parameters: {
          port: "1433",
          hostName: "localhost",
          database: "database",
        },
      },
      {
        name: "Mongodb",
        classifier: "global",
        categoryName: "No SQL & Big Data",
        categoryType: "nosql_bigdata",
        type: "global.jdbc",
        driver: "com.helicalinsight.nosql.mongo",
        url: "mongodb://{{hostName}}:{{port}}/{{database}}",
        parameters: {
          port: "27017",
          hostName: "localhost",
          database: "database",
          collection: "collection",
          sslPort: "3345",
        },
        dataSourceProvider: "noSql",
      },
      {
        driver: "com.mysql.jdbc.Driver",
        databaseDialect: "mysql",
        name: "Mysql",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
        parameters: {
          port: "3306",
          hostName: "localhost",
          database: "database",
        },
      },
      {
        driver: "oracle.jdbc.OracleDriver",
        databaseDialect: "oracle",
        name: "Oracle",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:oracle:thin:@{{hostName}}:{{port}}:{{database}}",
        parameters: {
          port: "1521",
          hostName: "localhost",
          database: "database",
        },
      },
      {
        driver: "com.helicalinsight.parquet",
        databaseDialect: "",
        name: "Parquet",
        categoryName: "Flat Files",
        categoryType: "flat_files",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        fileUpload: true,
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
      },
      {
        driver: "com.helicalinsight.pcap",
        databaseDialect: "",
        name: "Pcap",
        categoryName: "Flat Files",
        categoryType: "flat_files",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        fileUpload: true,
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
      },
      {
        driver: "com.helicalinsight.pcapng",
        databaseDialect: "",
        name: "Pcapng",
        categoryName: "Flat Files",
        categoryType: "flat_files",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        fileUpload: true,
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
      },
      {
        driver: "org.postgresql.Driver",
        databaseDialect: "postgresql",
        name: "Postgresql",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:postgresql://{{hostName}}:{{port}}/{{database}}",
        parameters: {
          port: "5432",
          hostName: "localhost",
          database: "database",
        },
      },
      {
        driver: "com.facebook.presto.jdbc.PrestoDriver",
        databaseDialect: "presto",
        name: "Presto",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:presto://{{hostName}}:{{port}}",
        parameters: {
          port: "8090",
          hostName: "localhost",
        },
      },
      {
        driver: "com.helicalinsight.psv",
        databaseDialect: "",
        name: "Psv",
        categoryName: "Flat Files",
        categoryType: "flat_files",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        fileUpload: true,
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
      },
      {
        driver: "com.helicalinsight.sequencefile",
        databaseDialect: "",
        name: "Sequencefile",
        categoryName: "Flat Files",
        categoryType: "flat_files",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        fileUpload: true,
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
      },
      {
        driver: "com.helicalinsight.shp",
        databaseDialect: "",
        name: "Shp",
        categoryName: "Flat Files",
        categoryType: "flat_files",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        fileUpload: true,
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
      },
      {
        driver: "net.snowflake.client.jdbc.SnowflakeDriver",
        databaseDialect: "snowflake",
        name: "Snowflake Client",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:snowflake://{{hostName}}",
        parameters: {
          hostName: "localhost",
        },
      },
      {
        driver: "org.sqlite.JDBC",
        databaseDialect: "sqlite",
        name: "Sqlite",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:sqlite:{{database}}",
        parameters: {
          database: "database",
        },
      },
      {
        driver: "com.helicalinsight.syslog",
        databaseDialect: "",
        name: "Syslog",
        categoryName: "Flat Files",
        categoryType: "flat_files",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        fileUpload: true,
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
      },
      {
        name: "Teradata",
        categoryType: "supported",
        categoryName: "Supported",
      },
      {
        driver: "com.helicalinsight.tsv",
        databaseDialect: "",
        name: "Tsv",
        categoryName: "Flat Files",
        categoryType: "flat_files",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        fileUpload: true,
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
      },
      {
        name: "Ξ Add Driver Ξ",
        categoryType: "supported",
        categoryName: "Supported",
      },
    ],
    metaDataSourceList: [
      {
        driver: "org.apache.drill.jdbc.Driver",
        databaseDialect: "drill",
        enabledTypes: true,
        name: "Apache Drill",
        categoryName: "Big Data",
        categoryType: "big_data",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:drill:{{hostName}}:{{port}}",
        parameters: {
          port: "31010",
          hostName: "drillbit=localhost",
        },
      },
      {
        driver: "com.simba.athena.jdbc.Driver",
        databaseDialect: "athena",
        name: "Athena",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:awsathena://{{hostName}}",
        parameters: {
          hostName: "localhost",
        },
      },
      {
        driver: "com.helicalinsight.avro",
        databaseDialect: "",
        name: "Avro",
        categoryName: "Flat Files",
        categoryType: "flat_files",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        fileUpload: true,
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
      },
      {
        driver: "ru.yandex.clickhouse.ClickHouseDriver",
        databaseDialect: "clickhouse",
        name: "Clickhouse",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:clickhouse://{{hostName}}:{{port}}/{{database}}",
        parameters: {
          port: "8123",
          hostName: "localhost",
          database: "database",
        },
      },
      {
        driver: "com.helicalinsight.csv",
        databaseDialect: "",
        name: "Csv",
        categoryName: "Flat Files",
        categoryType: "flat_files",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        fileUpload: true,
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
      },
      {
        driver: "com.helicalinsight.csvh",
        databaseDialect: "",
        name: "Csvh",
        categoryName: "Flat Files",
        categoryType: "flat_files",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        fileUpload: true,
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
      },
      {
        driver: "com.databricks.client.jdbc.Driver",
        databaseDialect: "databricks",
        name: "Databricks Client",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:databricks://{{hostName}}:{{port}};{{database}}",
        parameters: {
          port: "443",
          hostName: "localhost",
          database: "database",
        },
      },
      {
        driver: "org.apache.derby.jdbc.ClientDriver",
        databaseDialect: "derby",
        name: "Derby",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:derby://{{hostName}}:{{port}}/{{database}}",
        parameters: {
          port: "1527",
          hostName: "localhost",
          database: "database",
        },
      },
      {
        driver: "org.apache.derby.jdbc.AutoloadedDriver",
        databaseDialect: "derby",
        name: "Derby",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:derby:{{database}}",
        parameters: {
          database: "database",
        },
      },
      {
        driver: "dynamicSwitch",
        databaseDialect: "",
        name: "DynamicSwitch",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
      },
      {
        driver: "org.elasticsearch.xpack.sql.jdbc.EsDriver",
        databaseDialect: "elasticsearchsql",
        name: "Elasticsearch",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:es://{{hostName}}",
        parameters: {
          hostName: "localhost",
        },
      },
      {
        driver: "com.helicalinsight.excel",
        databaseDialect: "",
        name: "Excel",
        categoryName: "Flat Files",
        categoryType: "flat_files",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        fileUpload: true,
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
      },
      {
        driver: "com.helical.mongodb.MongoJdbcDriver",
        databaseDialect: "himongo",
        name: "Helical Mongodb",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
      },
      {
        driver: "org.apache.hive.jdbc.HiveDriver",
        databaseDialect: "spark",
        name: "Hive",
        categoryName: "Big Data",
        categoryType: "big_data",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:hive2://{{hostName}}:{{port}}/{{database}}",
        parameters: {
          port: "10001",
          hostName: "localhost",
          database: "database",
        },
      },
      {
        driver: "com.ibm.db2.jcc.DB2Driver",
        databaseDialect: "db2",
        name: "IBM Db2",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:db2://{{hostName}}:{{port}}/{{database}}",
        parameters: {
          port: "50000",
          hostName: "localhost",
          database: "database",
        },
      },
      {
        driver: "com.informix.jdbc.IfxDriver",
        databaseDialect: "informix",
        name: "Informix",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:informix-sqli://{{hostName}}:{{port}}/{{database}}:delimident=y",
        parameters: {
          port: "1526",
          hostName: "localhost",
          database: "database",
        },
      },
      {
        driver: "com.helicalinsight.json",
        databaseDialect: "",
        name: "Json",
        categoryName: "Flat Files",
        categoryType: "flat_files",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        fileUpload: true,
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
      },
      {
        driver: "com.helicalinsight.ltsv",
        databaseDialect: "",
        name: "Ltsv",
        categoryName: "Flat Files",
        categoryType: "flat_files",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        fileUpload: true,
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
      },
      {
        driver: "org.mariadb.jdbc.Driver",
        databaseDialect: "mysql",
        name: "Mariadb",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:mariadb://{{hostName}}:{{port}}/{{database}}",
        parameters: {
          port: "3306",
          hostName: "localhost",
          database: "database",
        },
      },
      {
        driver: "net.sourceforge.jtds.jdbc.Driver",
        databaseDialect: "sqlserver",
        name: "Microsoft Sqlserver(sourceforge)",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:jtds:sqlserver://{{hostName}}:{{port}}/{{database}}",
        parameters: {
          port: "1433",
          hostName: "localhost",
          database: "database",
        },
      },
      {
        name: "Mongodb",
        classifier: "global",
        categoryName: "No SQL & Big Data",
        categoryType: "nosql_bigdata",
        type: "global.jdbc",
        driver: "com.helicalinsight.nosql.mongo",
        url: "mongodb://{{hostName}}:{{port}}/{{database}}",
        parameters: {
          port: "27017",
          hostName: "localhost",
          database: "database",
          collection: "collection",
          sslPort: "3345",
        },
        dataSourceProvider: "noSql",
      },
      {
        driver: "com.mysql.jdbc.Driver",
        databaseDialect: "mysql",
        name: "Mysql",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
        parameters: {
          port: "3306",
          hostName: "localhost",
          database: "database",
        },
      },
      {
        driver: "oracle.jdbc.OracleDriver",
        databaseDialect: "oracle",
        name: "Oracle",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:oracle:thin:@{{hostName}}:{{port}}:{{database}}",
        parameters: {
          port: "1521",
          hostName: "localhost",
          database: "database",
        },
      },
      {
        driver: "com.helicalinsight.parquet",
        databaseDialect: "",
        name: "Parquet",
        categoryName: "Flat Files",
        categoryType: "flat_files",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        fileUpload: true,
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
      },
      {
        driver: "com.helicalinsight.pcap",
        databaseDialect: "",
        name: "Pcap",
        categoryName: "Flat Files",
        categoryType: "flat_files",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        fileUpload: true,
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
      },
      {
        driver: "com.helicalinsight.pcapng",
        databaseDialect: "",
        name: "Pcapng",
        categoryName: "Flat Files",
        categoryType: "flat_files",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        fileUpload: true,
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
      },
      {
        driver: "org.postgresql.Driver",
        databaseDialect: "postgresql",
        name: "Postgresql",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:postgresql://{{hostName}}:{{port}}/{{database}}",
        parameters: {
          port: "5432",
          hostName: "localhost",
          database: "database",
        },
      },
      {
        driver: "com.facebook.presto.jdbc.PrestoDriver",
        databaseDialect: "presto",
        name: "Presto",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:presto://{{hostName}}:{{port}}",
        parameters: {
          port: "8090",
          hostName: "localhost",
        },
      },
      {
        driver: "com.helicalinsight.psv",
        databaseDialect: "",
        name: "Psv",
        categoryName: "Flat Files",
        categoryType: "flat_files",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        fileUpload: true,
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
      },
      {
        driver: "com.helicalinsight.sequencefile",
        databaseDialect: "",
        name: "Sequencefile",
        categoryName: "Flat Files",
        categoryType: "flat_files",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        fileUpload: true,
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
      },
      {
        driver: "com.helicalinsight.shp",
        databaseDialect: "",
        name: "Shp",
        categoryName: "Flat Files",
        categoryType: "flat_files",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        fileUpload: true,
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
      },
      {
        driver: "net.snowflake.client.jdbc.SnowflakeDriver",
        databaseDialect: "snowflake",
        name: "Snowflake Client",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:snowflake://{{hostName}}",
        parameters: {
          hostName: "localhost",
        },
      },
      {
        driver: "org.sqlite.JDBC",
        databaseDialect: "sqlite",
        name: "Sqlite",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:sqlite:{{database}}",
        parameters: {
          database: "database",
        },
      },
      {
        driver: "com.helicalinsight.syslog",
        databaseDialect: "",
        name: "Syslog",
        categoryName: "Flat Files",
        categoryType: "flat_files",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        fileUpload: true,
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
      },
      {
        driver: "com.helicalinsight.tsv",
        databaseDialect: "",
        name: "Tsv",
        categoryName: "Flat Files",
        categoryType: "flat_files",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        fileUpload: true,
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
      },
    ],
    driversList: [
      {
        driver: "com.helicalinsight.avro",
        available: "true",
        fileUpload: true,
        parameter: {
          "@type": "avro",
          "@extensions": ".avro",
        },
      },
      {
        driver: "com.helicalinsight.csv",
        available: "true",
        fileUpload: true,
        parameter: {
          "@delimiter": ",",
          "@extensions": ".csv",
          "@extractHeader": "true",
          "@type": "text",
        },
      },
      {
        driver: "com.helicalinsight.csvh",
        available: "true",
        fileUpload: true,
        parameter: {
          "@delimiter": ",",
          "@extensions": ".csvh",
          "@extractHeader": "true",
          "@type": "text",
        },
      },
      {
        driver: "com.helicalinsight.excel",
        available: "true",
        fileUpload: true,
        parameter: {
          "@type": "excel",
          "@extensions": ".excel",
        },
      },
      {
        driver: "com.helicalinsight.json",
        available: "true",
        fileUpload: true,
        parameter: {
          "@extensions": ".json",
          "@type": "json",
        },
      },
      {
        driver: "com.helicalinsight.ltsv",
        available: "true",
        fileUpload: true,
        parameter: {
          "@extensions": ".ltsv",
          "@type": "ltsv",
        },
      },
      {
        driver: "com.helicalinsight.parquet",
        available: "true",
        fileUpload: true,
        parameter: {
          "@type": "parquet",
          "@extensions": ".parquet",
        },
      },
      {
        driver: "com.helicalinsight.pcap",
        available: "true",
        fileUpload: true,
        parameter: {
          "@extensions": ".pcap",
          "@type": "pcap",
        },
      },
      {
        driver: "com.helicalinsight.pcapng",
        available: "true",
        fileUpload: true,
        parameter: {
          "@extensions": ".pcapng",
          "@type": "pcapng",
        },
      },
      {
        driver: "com.helicalinsight.psv",
        available: "true",
        fileUpload: true,
        parameter: {
          "@delimiter": "|",
          "@extensions": ".psv",
          "@extractHeader": "true",
          "@type": "text",
        },
      },
      {
        driver: "com.helicalinsight.sequencefile",
        available: "true",
        fileUpload: true,
        parameter: {
          "@extensions": ".sequencefile",
          "@type": "sequencefile",
        },
      },
      {
        driver: "com.helicalinsight.shp",
        available: "true",
        fileUpload: true,
        parameter: {
          "@type": "shp",
          "@extensions": ".shp",
        },
      },
      {
        driver: "com.helicalinsight.syslog",
        available: "true",
        fileUpload: true,
        parameter: {
          "@extensions": ".syslog",
          "@type": "syslog",
        },
      },
      {
        driver: "com.helicalinsight.tsv",
        available: "true",
        fileUpload: true,
        parameter: {
          "@delimiter": "\t",
          "@extensions": ".tsv",
          "@extractHeader": "true",
          "@type": "text",
        },
      },
      {
        driver: "com.helicalinsight.nosql.mongo",
        available: "true",
        url: "mongodb://{{hostName}}:{{port}}/{{database}}",
        parameters: {
          port: "27017",
          hostName: "localhost",
          database: "database",
          collection: "collection",
          sslPort: "3345",
        },
      },
      {
        driver: "dynamicSwitch",
        showInDatasource: "false",
        available: "true",
        parameters: [],
      },
      {
        url: "jdbc:derby:{{database}}",
        driver: "org.apache.derby.jdbc.AutoloadedDriver",
        available: "true",
        parameters: {
          database: "database",
        },
      },
      {
        url: "jdbc:es://{{hostName}}",
        driver: "org.elasticsearch.xpack.sql.jdbc.EsDriver",
        available: "true",
        parameters: {
          hostName: "localhost",
        },
      },
      {
        url: "jdbc:awsathena://{{hostName}}",
        driver: "com.simba.athena.jdbc.Driver",
        available: "true",
        parameters: {
          hostName: "localhost",
        },
      },
      {
        url: "jdbc:jtds:sqlserver://{{hostName}}:{{port}}/{{database}}",
        driver: "net.sourceforge.jtds.jdbc.Driver",
        available: "true",
        parameters: {
          port: "1433",
          hostName: "localhost",
          database: "database",
        },
      },
      {
        url: "jdbc:clickhouse://{{hostName}}:{{port}}/{{database}}",
        driver: "ru.yandex.clickhouse.ClickHouseDriver",
        available: "true",
        parameters: {
          port: "8123",
          hostName: "localhost",
          database: "database",
        },
      },
      {
        url: "jdbc:oracle:thin:@{{hostName}}:{{port}}:{{database}}",
        driver: "oracle.jdbc.OracleDriver",
        available: "true",
        parameters: {
          port: "1521",
          hostName: "localhost",
          database: "database",
        },
      },
      {
        url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
        driver: "com.mysql.jdbc.Driver",
        available: "true",
        parameters: {
          port: "3306",
          hostName: "localhost",
          database: "database",
        },
      },
      {
        url: "jdbc:postgresql://{{hostName}}:{{port}}/{{database}}",
        driver: "org.postgresql.Driver",
        available: "true",
        parameters: {
          port: "5432",
          hostName: "localhost",
          database: "database",
        },
      },
      {
        available: "true",
        driver: "com.helical.mongodb.MongoJdbcDriver",
      },
      {
        url: "jdbc:hive2://{{hostName}}:{{port}}/{{database}}",
        driver: "org.apache.hive.jdbc.HiveDriver",
        available: "true",
        parameters: {
          port: "10001",
          hostName: "localhost",
          database: "database",
        },
      },
      {
        url: "jdbc:drill:{{hostName}}:{{port}}",
        driver: "org.apache.drill.jdbc.Driver",
        available: "true",
        parameters: {
          port: "31010",
          hostName: "drillbit=localhost",
        },
      },
      {
        url: "jdbc:informix-sqli://{{hostName}}:{{port}}/{{database}}:delimident=y",
        driver: "com.informix.jdbc.IfxDriver",
        available: "true",
        parameters: {
          port: "1526",
          hostName: "localhost",
          database: "database",
        },
      },
      {
        url: "jdbc:db2://{{hostName}}:{{port}}/{{database}}",
        driver: "com.ibm.db2.jcc.DB2Driver",
        available: "true",
        parameters: {
          port: "50000",
          hostName: "localhost",
          database: "database",
        },
      },
      {
        url: "jdbc:mariadb://{{hostName}}:{{port}}/{{database}}",
        driver: "org.mariadb.jdbc.Driver",
        available: "true",
        parameters: {
          port: "3306",
          hostName: "localhost",
          database: "database",
        },
      },
      {
        url: "jdbc:presto://{{hostName}}:{{port}}",
        driver: "com.facebook.presto.jdbc.PrestoDriver",
        available: "true",
        parameters: {
          port: "8090",
          hostName: "localhost",
        },
      },
      {
        url: "jdbc:databricks://{{hostName}}:{{port}};{{database}}",
        driver: "com.databricks.client.jdbc.Driver",
        available: "true",
        parameters: {
          port: "443",
          hostName: "localhost",
          database: "database",
        },
      },
      {
        url: "jdbc:snowflake://{{hostName}}",
        driver: "net.snowflake.client.jdbc.SnowflakeDriver",
        available: "true",
        parameters: {
          hostName: "localhost",
        },
      },
      {
        url: "jdbc:es://{{hostName}}",
        driver: "org.elasticsearch.xpack.sql.jdbc.EsDriver",
        available: "true",
        parameters: {
          hostName: "localhost",
        },
      },
      {
        url: "jdbc:es://{{hostName}}",
        driver: "org.elasticsearch.xpack.sql.jdbc.EsDriver",
        available: "true",
        parameters: {
          hostName: "localhost",
        },
      },
      {
        url: "jdbc:postgresql://{{hostName}}:{{port}}/{{database}}",
        driver: "org.postgresql.Driver",
        available: "true",
        parameters: {
          port: "5432",
          hostName: "localhost",
          database: "database",
        },
      },
      {
        url: "jdbc:derby://{{hostName}}:{{port}}/{{database}}",
        driver: "org.apache.derby.jdbc.ClientDriver",
        available: "true",
        parameters: {
          port: "1527",
          hostName: "localhost",
          database: "database",
        },
      },
      {
        url: "jdbc:sqlite:{{database}}",
        driver: "org.sqlite.JDBC",
        available: "true",
        parameters: {
          database: "database",
        },
      },
    ],
    allDataSources: [
      {
        permissionLevel: 5,
        driver: "dynamicSwitch",
        name: "Groovy 1",
        classifier: "efwd",
        type: "sql.jdbc.groovy.managed",
        data: {
          dir: "Gagan",
          driverName: null,
          type: "sql.jdbc.groovy.managed",
          id: 1,
          userName: null,
          password: null,
          condition:
            'import groovy.sql.Sql;\n      import net.sf.json.JSONObject;\n      import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n      public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        if (userName.equals("hiadmin")) {\n          responseJson.put("globalId", 1001);\n        }\n      \n        if (userName.equals("hiuser")) {\n          responseJson.put("globalId", 3);\n        }\n      \n        if (userName.equals("test")) {\n          responseJson.put("globalId", 4);\n        }\n      \n        responseJson.put("type", "global.jdbc");\n      \n        //throw new RuntimeException("This is a test exception" +responseJson);\n        return responseJson;\n      }',
          jdbcUrl: null,
          driver: "dynamicSwitch",
        },
        dataSourceType: "",
      },
      {
        permissionLevel: 5,
        driver: "org.apache.derby.jdbc.AutoloadedDriver",
        name: "Plain Jdbc",
        classifier: "efwd",
        type: "sql.jdbc",
        data: {
          dir: "datasources",
          driverName: "org.apache.derby.jdbc.AutoloadedDriver",
          type: "sql.jdbc",
          id: 501,
          userName: "hiuser",
          password: "hiuser",
          jdbcUrl:
            "jdbc:derby:/home/helical/Performance/hi/db/SampleTravelData",
        },
        dataSourceType: "Plain Jdbc DataSource",
      },
      {
        permissionLevel: 5,
        driver: "dynamicSwitch",
        name: "GroovyManaged",
        classifier: "efwd",
        type: "sql.jdbc.groovy.managed",
        data: {
          dir: "sai_ganesh",
          driverName: null,
          type: "sql.jdbc.groovy.managed",
          id: 601,
          userName: null,
          password: null,
          condition:
            'import groovy.sql.Sql;\n      import net.sf.json.JSONObject;\n      import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n      public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        if (userName.equals("hiadmin")) {\n          responseJson.put("globalId", 0);\n        }\n      \n        if (userName.equals("hiuser")) {\n          responseJson.put("globalId", 300);\n        }\n      \n        if (userName.equals("test")) {\n          responseJson.put("globalId", 4);\n        }\n      \n        responseJson.put("type", "global.jdbc");\n      \n        //throw new RuntimeException("This is a test exception" +responseJson);\n        return responseJson;\n      }',
          jdbcUrl: null,
          driver: "dynamicSwitch",
        },
        dataSourceType: "",
      },
      {
        permissionLevel: 5,
        driver: "org.apache.derby.jdbc.AutoloadedDriver",
        name: "5722",
        classifier: "efwd",
        type: "sql.jdbc",
        data: {
          dir: "sai_ganesh",
          driverName: "org.apache.derby.jdbc.AutoloadedDriver",
          type: "sql.jdbc",
          id: 701,
          userName: "hiuser",
          password: "hiuser",
          jdbcUrl:
            "jdbc:derby:/home/helical/Performance/hi/db/SampleTravelData",
        },
        dataSourceType: "Plain Jdbc DataSource",
      },
      {
        data: {
          id: "1",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.apache.derby.jdbc.AutoloadedDriver",
        name: "SampleTravelDataDerby",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
      {
        data: {
          id: "1000",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.apache.derby.jdbc.AutoloadedDriver",
        name: "hiee",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
      {
        data: {
          id: "1001",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.postgresql.Driver",
        name: "booking",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
      {
        data: {
          id: "1101",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.apache.derby.jdbc.AutoloadedDriver",
        name: "derby2",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
      {
        data: {
          id: "1201",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.sqlite.JDBC",
        name: "SampleTravelData",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
      {
        data: {
          id: "1302",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.sqlite.JDBC",
        name: "Sqlite",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
      {
        data: {
          id: "1401",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.postgresql.Driver",
        name: "booking",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
      {
        data: {
          id: "1801",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.apache.derby.jdbc.AutoloadedDriver",
        name: "Dump",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
      {
        data: {
          id: "1901",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "net.snowflake.client.jdbc.SnowflakeDriver",
        name: "SnowflakeDS",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
      {
        data: {
          id: "1902",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "net.snowflake.client.jdbc.SnowflakeDriver",
        name: "SnowFlakeDSWorking",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
      {
        data: {
          id: "2001",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "oracle.jdbc.OracleDriver",
        name: "Oracle_12",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
      {
        data: {
          id: "2101",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "com.snowflake.client.jdbc.SnowflakeDriver",
        name: "Edit",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
      {
        data: {
          id: "2202",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.postgresql.Driver",
        name: "SampleTravelData",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
      {
        data: {
          id: "2301",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.apache.derby.jdbc.AutoloadedDriver",
        name: "SampleTravelData",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
      {
        data: {
          id: "2402",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "com.mysql.jdbc.Driver",
        name: "mysql",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
      {
        data: {
          id: "2403",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "net.snowflake.client.jdbc.SnowflakeDriver",
        name: "testdata",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
      {
        data: {
          id: "2501",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "net.snowflake.client.jdbc.SnowflakeDriver",
        name: "60045",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
      {
        data: {
          id: "2601",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.apache.derby.jdbc.AutoloadedDriver",
        name: "AnotherDerby",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
    ],
    dataSourceTypes: [
      {
        type: "sql.jdbc.groovy.managed",
        name: "Groovy Managed Jdbc DataSource",
        classifier: "efwd",
        categoryName: "advanced",
        categoryType: "advanced",
      },
      {
        type: "sql.jdbc.groovy",
        name: "Groovy Plain Jdbc DataSource",
        classifier: "efwd",
        categoryName: "advanced",
        categoryType: "advanced",
      },
      {
        type: "global.jdbc",
        name: "Managed DataSource",
        classifier: "global",
        categoryName: "advanced",
        categoryType: "advanced",
      },
      {
        type: "sql.jdbc",
        name: "Plain Jdbc DataSource",
        classifier: "efwd",
        categoryName: "advanced",
        categoryType: "advanced",
      },
    ],
    datasourceListToRender: [
      {
        name: "Derby",
        children: [
          {
            permissionLevel: 5,
            driver: "org.apache.derby.jdbc.AutoloadedDriver",
            name: "Plain Jdbc",
            classifier: "efwd",
            type: "sql.jdbc",
            data: {
              dir: "datasources",
              driverName: "org.apache.derby.jdbc.AutoloadedDriver",
              type: "sql.jdbc",
              id: 501,
              userName: "hiuser",
              password: "hiuser",
              jdbcUrl:
                "jdbc:derby:/home/helical/Performance/hi/db/SampleTravelData",
            },
            dataSourceType: "Plain Jdbc DataSource",
            category: "dataSource",
            children: [],
            driverType: "Derby",
            keyPath: "u1s3-a6ap-vr1v-xnu5-g6/54g5-i24q-p6rz-4op1-s0",
            key: "54g5-i24q-p6rz-4op1-s0",
            uuid: "54g5-i24q-p6rz-4op1-s0",
          },
          {
            permissionLevel: 5,
            driver: "org.apache.derby.jdbc.AutoloadedDriver",
            name: "5722",
            classifier: "efwd",
            type: "sql.jdbc",
            data: {
              dir: "sai_ganesh",
              driverName: "org.apache.derby.jdbc.AutoloadedDriver",
              type: "sql.jdbc",
              id: 701,
              userName: "hiuser",
              password: "hiuser",
              jdbcUrl:
                "jdbc:derby:/home/helical/Performance/hi/db/SampleTravelData",
            },
            dataSourceType: "Plain Jdbc DataSource",
            category: "dataSource",
            children: [],
            driverType: "Derby",
            keyPath: "u1s3-a6ap-vr1v-xnu5-g6/i4n8-f6l9-4q0x-tdzg-gb",
            key: "i4n8-f6l9-4q0x-tdzg-gb",
            uuid: "i4n8-f6l9-4q0x-tdzg-gb",
          },
          {
            data: {
              id: "1",
              type: "dynamicDataSource",
            },
            dataSourceProvider: "tomcat",
            type: "dynamicDataSource",
            permissionLevel: 5,
            driver: "org.apache.derby.jdbc.AutoloadedDriver",
            name: "SampleTravelDataDerby",
            classifier: "global",
            dataSourceType: "Managed DataSource",
            category: "dataSource",
            children: [],
            driverType: "Derby",
            keyPath: "u1s3-a6ap-vr1v-xnu5-g6/vwse-9t9c-hijl-jprx-o3",
            key: "vwse-9t9c-hijl-jprx-o3",
            uuid: "vwse-9t9c-hijl-jprx-o3",
          },
          {
            data: {
              id: "1000",
              type: "dynamicDataSource",
            },
            dataSourceProvider: "tomcat",
            type: "dynamicDataSource",
            permissionLevel: 5,
            driver: "org.apache.derby.jdbc.AutoloadedDriver",
            name: "hiee",
            classifier: "global",
            dataSourceType: "Managed DataSource",
            category: "dataSource",
            children: [],
            driverType: "Derby",
            keyPath: "u1s3-a6ap-vr1v-xnu5-g6/s3u7-mefn-bik7-1mx4-qk",
            key: "s3u7-mefn-bik7-1mx4-qk",
            uuid: "s3u7-mefn-bik7-1mx4-qk",
          },
          {
            data: {
              id: "1101",
              type: "dynamicDataSource",
            },
            dataSourceProvider: "tomcat",
            type: "dynamicDataSource",
            permissionLevel: 5,
            driver: "org.apache.derby.jdbc.AutoloadedDriver",
            name: "derby2",
            classifier: "global",
            dataSourceType: "Managed DataSource",
            category: "dataSource",
            children: [],
            driverType: "Derby",
            keyPath: "u1s3-a6ap-vr1v-xnu5-g6/1oi7-62lw-uyc9-ychr-c8",
            key: "1oi7-62lw-uyc9-ychr-c8",
            uuid: "1oi7-62lw-uyc9-ychr-c8",
          },
          {
            data: {
              id: "1801",
              type: "dynamicDataSource",
            },
            dataSourceProvider: "tomcat",
            type: "dynamicDataSource",
            permissionLevel: 5,
            driver: "org.apache.derby.jdbc.AutoloadedDriver",
            name: "Dump",
            classifier: "global",
            dataSourceType: "Managed DataSource",
            category: "dataSource",
            children: [],
            driverType: "Derby",
            keyPath: "u1s3-a6ap-vr1v-xnu5-g6/tx06-b63c-r9wk-xbhw-3l",
            key: "tx06-b63c-r9wk-xbhw-3l",
            uuid: "tx06-b63c-r9wk-xbhw-3l",
          },
          {
            data: {
              id: "2301",
              type: "dynamicDataSource",
            },
            dataSourceProvider: "tomcat",
            type: "dynamicDataSource",
            permissionLevel: 5,
            driver: "org.apache.derby.jdbc.AutoloadedDriver",
            name: "SampleTravelData",
            classifier: "global",
            dataSourceType: "Managed DataSource",
            category: "dataSource",
            children: [],
            driverType: "Derby",
            keyPath: "u1s3-a6ap-vr1v-xnu5-g6/1qws-wgbj-ywdl-p4v6-mu",
            key: "1qws-wgbj-ywdl-p4v6-mu",
            uuid: "1qws-wgbj-ywdl-p4v6-mu",
          },
          {
            data: {
              id: "2601",
              type: "dynamicDataSource",
            },
            dataSourceProvider: "tomcat",
            type: "dynamicDataSource",
            permissionLevel: 5,
            driver: "org.apache.derby.jdbc.AutoloadedDriver",
            name: "AnotherDerby",
            classifier: "global",
            dataSourceType: "Managed DataSource",
            category: "dataSource",
            children: [],
            driverType: "Derby",
            keyPath: "u1s3-a6ap-vr1v-xnu5-g6/970f-f0jb-cjo5-zewu-zl",
            key: "970f-f0jb-cjo5-zewu-zl",
            uuid: "970f-f0jb-cjo5-zewu-zl",
          },
        ],
        key: "u1s3-a6ap-vr1v-xnu5-g6",
        uuid: "u1s3-a6ap-vr1v-xnu5-g6",
        keyPath: "u1s3-a6ap-vr1v-xnu5-g6",
        category: "dsGroup",
        imgUrl: "images/data_sources/defaut_datasource.png",
      },
      {
        name: "DynamicSwitch",
        children: [
          {
            permissionLevel: 5,
            driver: "dynamicSwitch",
            name: "Groovy 1",
            classifier: "efwd",
            type: "sql.jdbc.groovy.managed",
            data: {
              dir: "Gagan",
              driverName: null,
              type: "sql.jdbc.groovy.managed",
              id: 1,
              userName: null,
              password: null,
              condition:
                'import groovy.sql.Sql;\n      import net.sf.json.JSONObject;\n      import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n      public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        if (userName.equals("hiadmin")) {\n          responseJson.put("globalId", 1001);\n        }\n      \n        if (userName.equals("hiuser")) {\n          responseJson.put("globalId", 3);\n        }\n      \n        if (userName.equals("test")) {\n          responseJson.put("globalId", 4);\n        }\n      \n        responseJson.put("type", "global.jdbc");\n      \n        //throw new RuntimeException("This is a test exception" +responseJson);\n        return responseJson;\n      }',
              jdbcUrl: null,
              driver: "dynamicSwitch",
            },
            dataSourceType: "",
            category: "dataSource",
            children: [],
            driverType: "DynamicSwitch",
            keyPath: "d3k0-ojp4-iuzm-7h0f-7i/kesw-fxnw-7wsq-k85o-1b",
            key: "kesw-fxnw-7wsq-k85o-1b",
            uuid: "kesw-fxnw-7wsq-k85o-1b",
          },
          {
            permissionLevel: 5,
            driver: "dynamicSwitch",
            name: "GroovyManaged",
            classifier: "efwd",
            type: "sql.jdbc.groovy.managed",
            data: {
              dir: "sai_ganesh",
              driverName: null,
              type: "sql.jdbc.groovy.managed",
              id: 601,
              userName: null,
              password: null,
              condition:
                'import groovy.sql.Sql;\n      import net.sf.json.JSONObject;\n      import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n      public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        if (userName.equals("hiadmin")) {\n          responseJson.put("globalId", 0);\n        }\n      \n        if (userName.equals("hiuser")) {\n          responseJson.put("globalId", 300);\n        }\n      \n        if (userName.equals("test")) {\n          responseJson.put("globalId", 4);\n        }\n      \n        responseJson.put("type", "global.jdbc");\n      \n        //throw new RuntimeException("This is a test exception" +responseJson);\n        return responseJson;\n      }',
              jdbcUrl: null,
              driver: "dynamicSwitch",
            },
            dataSourceType: "",
            category: "dataSource",
            children: [],
            driverType: "DynamicSwitch",
            keyPath: "d3k0-ojp4-iuzm-7h0f-7i/zk1s-0nv4-0rex-cql2-pk",
            key: "zk1s-0nv4-0rex-cql2-pk",
            uuid: "zk1s-0nv4-0rex-cql2-pk",
          },
        ],
        key: "d3k0-ojp4-iuzm-7h0f-7i",
        uuid: "d3k0-ojp4-iuzm-7h0f-7i",
        keyPath: "d3k0-ojp4-iuzm-7h0f-7i",
        category: "dsGroup",
        imgUrl: "images/data_sources/defaut_datasource.png",
      },
      {
        name: "Mysql",
        children: [
          {
            data: {
              id: "2402",
              type: "dynamicDataSource",
            },
            dataSourceProvider: "tomcat",
            type: "dynamicDataSource",
            permissionLevel: 5,
            driver: "com.mysql.jdbc.Driver",
            name: "mysql",
            classifier: "global",
            dataSourceType: "Managed DataSource",
            category: "dataSource",
            children: [],
            driverType: "Mysql",
            keyPath: "2a0f-qbnu-m692-ww6j-c9/3yg9-2nvc-d1wc-p9d1-xw",
            key: "3yg9-2nvc-d1wc-p9d1-xw",
            uuid: "3yg9-2nvc-d1wc-p9d1-xw",
          },
        ],
        key: "2a0f-qbnu-m692-ww6j-c9",
        uuid: "2a0f-qbnu-m692-ww6j-c9",
        keyPath: "2a0f-qbnu-m692-ww6j-c9",
        category: "dsGroup",
        imgUrl: "images/data_sources/defaut_datasource.png",
      },
      {
        name: "Oracle",
        children: [
          {
            data: {
              id: "2001",
              type: "dynamicDataSource",
            },
            dataSourceProvider: "tomcat",
            type: "dynamicDataSource",
            permissionLevel: 5,
            driver: "oracle.jdbc.OracleDriver",
            name: "Oracle_12",
            classifier: "global",
            dataSourceType: "Managed DataSource",
            category: "dataSource",
            children: [],
            driverType: "Oracle",
            keyPath: "4lin-ro8z-r2wl-dnqp-90/u6b7-j0w3-n5n0-q1jr-8q",
            key: "u6b7-j0w3-n5n0-q1jr-8q",
            uuid: "u6b7-j0w3-n5n0-q1jr-8q",
          },
        ],
        key: "4lin-ro8z-r2wl-dnqp-90",
        uuid: "4lin-ro8z-r2wl-dnqp-90",
        keyPath: "4lin-ro8z-r2wl-dnqp-90",
        category: "dsGroup",
        imgUrl: "images/data_sources/defaut_datasource.png",
      },
      {
        name: "Postgresql",
        children: [
          {
            data: {
              id: "1001",
              type: "dynamicDataSource",
            },
            dataSourceProvider: "tomcat",
            type: "dynamicDataSource",
            permissionLevel: 5,
            driver: "org.postgresql.Driver",
            name: "booking",
            classifier: "global",
            dataSourceType: "Managed DataSource",
            category: "dataSource",
            children: [],
            driverType: "Postgresql",
            keyPath: "p82a-quwc-3ryq-k9fg-vq/3e8h-f2j8-jjnh-eff0-ox",
            key: "3e8h-f2j8-jjnh-eff0-ox",
            uuid: "3e8h-f2j8-jjnh-eff0-ox",
          },
          {
            data: {
              id: "1401",
              type: "dynamicDataSource",
            },
            dataSourceProvider: "tomcat",
            type: "dynamicDataSource",
            permissionLevel: 5,
            driver: "org.postgresql.Driver",
            name: "booking",
            classifier: "global",
            dataSourceType: "Managed DataSource",
            category: "dataSource",
            children: [],
            driverType: "Postgresql",
            keyPath: "p82a-quwc-3ryq-k9fg-vq/x35u-umd9-iyia-bt40-iu",
            key: "x35u-umd9-iyia-bt40-iu",
            uuid: "x35u-umd9-iyia-bt40-iu",
          },
          {
            data: {
              id: "2202",
              type: "dynamicDataSource",
            },
            dataSourceProvider: "tomcat",
            type: "dynamicDataSource",
            permissionLevel: 5,
            driver: "org.postgresql.Driver",
            name: "SampleTravelData",
            classifier: "global",
            dataSourceType: "Managed DataSource",
            category: "dataSource",
            children: [],
            driverType: "Postgresql",
            keyPath: "p82a-quwc-3ryq-k9fg-vq/e7iz-c4wi-ernz-67zt-q9",
            key: "e7iz-c4wi-ernz-67zt-q9",
            uuid: "e7iz-c4wi-ernz-67zt-q9",
          },
        ],
        key: "p82a-quwc-3ryq-k9fg-vq",
        uuid: "p82a-quwc-3ryq-k9fg-vq",
        keyPath: "p82a-quwc-3ryq-k9fg-vq",
        category: "dsGroup",
        imgUrl: "images/data_sources/defaut_datasource.png",
      },
      {
        name: "Snowflake Client",
        children: [
          {
            data: {
              id: "1901",
              type: "dynamicDataSource",
            },
            dataSourceProvider: "tomcat",
            type: "dynamicDataSource",
            permissionLevel: 5,
            driver: "net.snowflake.client.jdbc.SnowflakeDriver",
            name: "SnowflakeDS",
            classifier: "global",
            dataSourceType: "Managed DataSource",
            category: "dataSource",
            children: [],
            driverType: "Snowflake Client",
            keyPath: "6uxn-x499-0l90-dp7i-gj/uawi-fys5-2ijq-q9u5-6w",
            key: "uawi-fys5-2ijq-q9u5-6w",
            uuid: "uawi-fys5-2ijq-q9u5-6w",
          },
          {
            data: {
              id: "1902",
              type: "dynamicDataSource",
            },
            dataSourceProvider: "tomcat",
            type: "dynamicDataSource",
            permissionLevel: 5,
            driver: "net.snowflake.client.jdbc.SnowflakeDriver",
            name: "SnowFlakeDSWorking",
            classifier: "global",
            dataSourceType: "Managed DataSource",
            category: "dataSource",
            children: [],
            driverType: "Snowflake Client",
            keyPath: "6uxn-x499-0l90-dp7i-gj/0eyp-hf6o-2uwv-4jc0-wo",
            key: "0eyp-hf6o-2uwv-4jc0-wo",
            uuid: "0eyp-hf6o-2uwv-4jc0-wo",
          },
          {
            data: {
              id: "2403",
              type: "dynamicDataSource",
            },
            dataSourceProvider: "tomcat",
            type: "dynamicDataSource",
            permissionLevel: 5,
            driver: "net.snowflake.client.jdbc.SnowflakeDriver",
            name: "testdata",
            classifier: "global",
            dataSourceType: "Managed DataSource",
            category: "dataSource",
            children: [],
            driverType: "Snowflake Client",
            keyPath: "6uxn-x499-0l90-dp7i-gj/dp1v-g93r-gmce-0xg1-es",
            key: "dp1v-g93r-gmce-0xg1-es",
            uuid: "dp1v-g93r-gmce-0xg1-es",
          },
          {
            data: {
              id: "2501",
              type: "dynamicDataSource",
            },
            dataSourceProvider: "tomcat",
            type: "dynamicDataSource",
            permissionLevel: 5,
            driver: "net.snowflake.client.jdbc.SnowflakeDriver",
            name: "60045",
            classifier: "global",
            dataSourceType: "Managed DataSource",
            category: "dataSource",
            children: [],
            driverType: "Snowflake Client",
            keyPath: "6uxn-x499-0l90-dp7i-gj/h0d7-gaqw-l55q-wimg-3g",
            key: "h0d7-gaqw-l55q-wimg-3g",
            uuid: "h0d7-gaqw-l55q-wimg-3g",
          },
        ],
        key: "6uxn-x499-0l90-dp7i-gj",
        uuid: "6uxn-x499-0l90-dp7i-gj",
        keyPath: "6uxn-x499-0l90-dp7i-gj",
        category: "dsGroup",
        imgUrl: "images/data_sources/defaut_datasource.png",
      },
      {
        name: "Sqlite",
        children: [
          {
            data: {
              id: "1201",
              type: "dynamicDataSource",
            },
            dataSourceProvider: "tomcat",
            type: "dynamicDataSource",
            permissionLevel: 5,
            driver: "org.sqlite.JDBC",
            name: "SampleTravelData",
            classifier: "global",
            dataSourceType: "Managed DataSource",
            category: "dataSource",
            children: [
              {
                id: "d324e793296ff76020c708f1c8fbb704",
                name: "dimdate",
                alias: "dimdate",
                dataSource: {
                  id: "1201",
                  type: "dynamicDataSource",
                  baseType: "global.jdbc",
                  catSchemaPredicted: false,
                  sync: false,
                  catalog: "",
                  schema: "",
                  connId: "dq993",
                  dbId: "dq993",
                  classifier: "db.workflow",
                  datasourceName: "SampleTravelData",
                  dsKeyPath: "2s8s-g8u0-hir9-10pd-2m/b09l-0fng-gpfn-yhza-qj",
                  driverType: "Sqlite",
                  database: "SampleTravelData",
                },
                category: "table",
                connId: "dq993",
                keyPath:
                  "2s8s-g8u0-hir9-10pd-2m/b09l-0fng-gpfn-yhza-qj/7cwl-8c3a-7bj6-2ffo-g9",
                uniqueKey: "d324e793296ff76020c708f1c8fbb704_dq993",
                selected: true,
              },
              {
                id: "b161910cbebfd353351a6c0b46e6a02e",
                name: "employee_details",
                alias: "employee_details",
                dataSource: {
                  id: "1201",
                  type: "dynamicDataSource",
                  baseType: "global.jdbc",
                  catSchemaPredicted: false,
                  sync: false,
                  catalog: "",
                  schema: "",
                  connId: "dq993",
                  dbId: "dq993",
                  classifier: "db.workflow",
                  datasourceName: "SampleTravelData",
                  dsKeyPath: "2s8s-g8u0-hir9-10pd-2m/b09l-0fng-gpfn-yhza-qj",
                  driverType: "Sqlite",
                  database: "SampleTravelData",
                },
                category: "table",
                connId: "dq993",
                keyPath:
                  "2s8s-g8u0-hir9-10pd-2m/b09l-0fng-gpfn-yhza-qj/dakj-i7lb-kscw-w09h-bs",
                uniqueKey: "b161910cbebfd353351a6c0b46e6a02e_dq993",
                selected: true,
              },
              {
                id: "f2ff93c37589ef57f40dcb15fda6d7ea",
                name: "geo_cordinates",
                alias: "geo_cordinates",
                dataSource: {
                  id: "1201",
                  type: "dynamicDataSource",
                  baseType: "global.jdbc",
                  catSchemaPredicted: false,
                  sync: false,
                  catalog: "",
                  schema: "",
                  connId: "dq993",
                  dbId: "dq993",
                  classifier: "db.workflow",
                  datasourceName: "SampleTravelData",
                  dsKeyPath: "2s8s-g8u0-hir9-10pd-2m/b09l-0fng-gpfn-yhza-qj",
                  driverType: "Sqlite",
                  database: "SampleTravelData",
                },
                category: "table",
                connId: "dq993",
                keyPath:
                  "2s8s-g8u0-hir9-10pd-2m/b09l-0fng-gpfn-yhza-qj/ge3m-8wha-ojyz-ov83-11",
                uniqueKey: "f2ff93c37589ef57f40dcb15fda6d7ea_dq993",
                selected: false,
              },
              {
                id: "025fbfb381cb17d4519363c3585626fb",
                name: "meeting_details",
                alias: "meeting_details",
                dataSource: {
                  id: "1201",
                  type: "dynamicDataSource",
                  baseType: "global.jdbc",
                  catSchemaPredicted: false,
                  sync: false,
                  catalog: "",
                  schema: "",
                  connId: "dq993",
                  dbId: "dq993",
                  classifier: "db.workflow",
                  datasourceName: "SampleTravelData",
                  dsKeyPath: "2s8s-g8u0-hir9-10pd-2m/b09l-0fng-gpfn-yhza-qj",
                  driverType: "Sqlite",
                  database: "SampleTravelData",
                },
                category: "table",
                connId: "dq993",
                keyPath:
                  "2s8s-g8u0-hir9-10pd-2m/b09l-0fng-gpfn-yhza-qj/jck3-447j-h08k-yw6u-vi",
                uniqueKey: "025fbfb381cb17d4519363c3585626fb_dq993",
                selected: false,
              },
              {
                id: "21e1b86ae9680d0fc197ed543c3e37eb",
                name: "travel_details",
                alias: "travel_details",
                dataSource: {
                  id: "1201",
                  type: "dynamicDataSource",
                  baseType: "global.jdbc",
                  catSchemaPredicted: false,
                  sync: false,
                  catalog: "",
                  schema: "",
                  connId: "dq993",
                  dbId: "dq993",
                  classifier: "db.workflow",
                  datasourceName: "SampleTravelData",
                  dsKeyPath: "2s8s-g8u0-hir9-10pd-2m/b09l-0fng-gpfn-yhza-qj",
                  driverType: "Sqlite",
                  database: "SampleTravelData",
                },
                category: "table",
                connId: "dq993",
                keyPath:
                  "2s8s-g8u0-hir9-10pd-2m/b09l-0fng-gpfn-yhza-qj/onwm-y3jv-ze6l-grf4-av",
                uniqueKey: "21e1b86ae9680d0fc197ed543c3e37eb_dq993",
                selected: false,
              },
            ],
            driverType: "Sqlite",
            keyPath: "2s8s-g8u0-hir9-10pd-2m/b09l-0fng-gpfn-yhza-qj",
            key: "b09l-0fng-gpfn-yhza-qj",
            uuid: "b09l-0fng-gpfn-yhza-qj",
            fetched: true,
          },
          {
            data: {
              id: "1302",
              type: "dynamicDataSource",
            },
            dataSourceProvider: "tomcat",
            type: "dynamicDataSource",
            permissionLevel: 5,
            driver: "org.sqlite.JDBC",
            name: "Sqlite",
            classifier: "global",
            dataSourceType: "Managed DataSource",
            category: "dataSource",
            children: [],
            driverType: "Sqlite",
            keyPath: "2s8s-g8u0-hir9-10pd-2m/dhh6-fb1a-rrbm-om4m-zh",
            key: "dhh6-fb1a-rrbm-om4m-zh",
            uuid: "dhh6-fb1a-rrbm-om4m-zh",
          },
        ],
        key: "2s8s-g8u0-hir9-10pd-2m",
        uuid: "2s8s-g8u0-hir9-10pd-2m",
        keyPath: "2s8s-g8u0-hir9-10pd-2m",
        category: "dsGroup",
        imgUrl: "images/data_sources/defaut_datasource.png",
      },
    ],
    workFlow: {
      dataList: [
        {
          fetchSchemas: true,
          fetchCatalogs: true,
          working: true,
          connData: {
            id: "1201",
            type: "dynamicDataSource",
          },
          connId: "1201",
          dsUUID: "b09l-0fng-gpfn-yhza-qj",
          classifier: "db.workflow",
          metadata: {
            catalogs: [
              {
                name: "Null",
                schemas: [
                  {
                    name: "Null",
                    tables: [
                      {
                        id: "f2ff93c37589ef57f40dcb15fda6d7ea",
                        name: "geo_cordinates",
                      },
                      {
                        id: "025fbfb381cb17d4519363c3585626fb",
                        name: "meeting_details",
                      },
                      {
                        id: "b161910cbebfd353351a6c0b46e6a02e",
                        name: "employee_details",
                      },
                      {
                        id: "d324e793296ff76020c708f1c8fbb704",
                        name: "dimdate",
                      },
                      {
                        id: "21e1b86ae9680d0fc197ed543c3e37eb",
                        name: "travel_details",
                      },
                    ],
                  },
                ],
              },
            ],
            dataSource: {
              id: "1201",
              type: "dynamicDataSource",
              baseType: "global.jdbc",
              catSchemaPredicted: false,
              sync: false,
              catalog: "",
              schema: "",
              connId: "dq993",
              dbId: "dq993",
              classifier: "db.workflow",
              datasourceName: "SampleTravelData",
              dsKeyPath: "2s8s-g8u0-hir9-10pd-2m/b09l-0fng-gpfn-yhza-qj",
              driverType: "Sqlite",
              database: "SampleTravelData",
            },
            name: "",
          },
        },
      ],
    },
    dataSource: [
      {
        id: "1201",
        type: "dynamicDataSource",
        baseType: "global.jdbc",
        catSchemaPredicted: false,
        sync: false,
        catalog: "",
        schema: "",
        connId: "dq993",
        dbId: "dq993",
        classifier: "db.workflow",
        datasourceName: "SampleTravelData",
        dsKeyPath: "2s8s-g8u0-hir9-10pd-2m/b09l-0fng-gpfn-yhza-qj",
        driverType: "Sqlite",
        database: "",
      },
    ],
    tables: {
      dimdate: {
        id: "d324e793296ff76020c708f1c8fbb704",
        name: "dimdate",
        alias: "dimdate",
        dataSource: {
          id: "1201",
          type: "dynamicDataSource",
          baseType: "global.jdbc",
          catSchemaPredicted: false,
          sync: false,
          catalog: "",
          schema: "",
          connId: "dq993",
          dbId: "dq993",
          classifier: "db.workflow",
          datasourceName: "SampleTravelData",
          dsKeyPath: "2s8s-g8u0-hir9-10pd-2m/b09l-0fng-gpfn-yhza-qj",
          driverType: "Sqlite",
          database: "SampleTravelData",
        },
        category: "table",
        connId: "dq993",
        keyPath:
          "2s8s-g8u0-hir9-10pd-2m/b09l-0fng-gpfn-yhza-qj/7cwl-8c3a-7bj6-2ffo-g9",
        uniqueKey: "d324e793296ff76020c708f1c8fbb704_dq993",
        selected: true,
        keyName: "dimdate",
        columns: {
          dim_id: {
            alias: "test",
            fullyQualifiedColumn: "dimdate.dim_id",
            id: "28e1264e-6563-4b43-ba36-55a4a049fd33",
            defaultFunction: "db.generic.aggregate.sum",
            type: {
              "java.lang.Integer": "numeric",
            },
            category: "column",
            uniqueKey: "28e1264e-6563-4b43-ba36-55a4a049fd33_dq993",
            name: "dim_id",
            tableKey: "dimdate",
            connId: "dq993",
            columnKey: "dim_id",
            tableId: "d324e793296ff76020c708f1c8fbb704",
          },
          fiscal_year: {
            alias: "fiscal_year",
            fullyQualifiedColumn: "dimdate.fiscal_year",
            id: "42fb2903-d70c-4f34-82e7-09baf1eb688f",
            defaultFunction: "db.generic.groupBy.group",
            type: {
              "java.lang.String": "text",
            },
            category: "column",
            uniqueKey: "42fb2903-d70c-4f34-82e7-09baf1eb688f_dq993",
            name: "fiscal_year",
            tableKey: "dimdate",
            connId: "dq993",
            columnKey: "fiscal_year",
            tableId: "d324e793296ff76020c708f1c8fbb704",
          },
          modified_date: {
            alias: "modified_date",
            fullyQualifiedColumn: "dimdate.modified_date",
            id: "ab5e51a9-b0f2-4086-8caa-d4f0b9866873",
            defaultFunction: "db.generic.groupBy.group",
            type: {
              "java.lang.String": "text",
            },
            category: "column",
            uniqueKey: "ab5e51a9-b0f2-4086-8caa-d4f0b9866873_dq993",
            name: "modified_date",
            tableKey: "dimdate",
            connId: "dq993",
            columnKey: "modified_date",
            tableId: "d324e793296ff76020c708f1c8fbb704",
          },
          date_key: {
            alias: "date_key",
            fullyQualifiedColumn: "dimdate.date_key",
            id: "7c145afc-71c8-424e-b93c-25bb16571c0c",
            defaultFunction: "db.generic.groupBy.group",
            type: {
              "java.lang.String": "text",
            },
            category: "column",
            uniqueKey: "7c145afc-71c8-424e-b93c-25bb16571c0c_dq993",
            name: "date_key",
            tableKey: "dimdate",
            connId: "dq993",
            columnKey: "date_key",
            tableId: "d324e793296ff76020c708f1c8fbb704",
          },
          day_number: {
            alias: "day_number",
            fullyQualifiedColumn: "dimdate.day_number",
            id: "d7d3b95f-e6df-47ca-ae09-e1f33a79f1f6",
            defaultFunction: "db.generic.groupBy.group",
            type: {
              "java.lang.String": "text",
            },
            category: "column",
            uniqueKey: "d7d3b95f-e6df-47ca-ae09-e1f33a79f1f6_dq993",
            name: "day_number",
            tableKey: "dimdate",
            connId: "dq993",
            columnKey: "day_number",
            tableId: "d324e793296ff76020c708f1c8fbb704",
          },
          fiscal_month_name: {
            alias: "fiscal_month_name",
            fullyQualifiedColumn: "dimdate.fiscal_month_name",
            id: "670b31f5-0d8c-42cf-94af-d9734b1f0260",
            defaultFunction: "db.generic.groupBy.group",
            type: {
              "java.lang.String": "text",
            },
            category: "column",
            uniqueKey: "670b31f5-0d8c-42cf-94af-d9734b1f0260_dq993",
            name: "fiscal_month_name",
            tableKey: "dimdate",
            connId: "dq993",
            columnKey: "fiscal_month_name",
            tableId: "d324e793296ff76020c708f1c8fbb704",
          },
          fiscal_month_label: {
            alias: "fiscal_month_label",
            fullyQualifiedColumn: "dimdate.fiscal_month_label",
            id: "e538c9b8-538e-4c9e-bedd-1960dbffb38f",
            defaultFunction: "db.generic.groupBy.group",
            type: {
              "java.lang.String": "text",
            },
            category: "column",
            uniqueKey: "e538c9b8-538e-4c9e-bedd-1960dbffb38f_dq993",
            name: "fiscal_month_label",
            tableKey: "dimdate",
            connId: "dq993",
            columnKey: "fiscal_month_label",
            tableId: "d324e793296ff76020c708f1c8fbb704",
          },
          created_date: {
            alias: "created_date",
            fullyQualifiedColumn: "dimdate.created_date",
            id: "68456af1-7e01-412b-b42a-491b4355ef93",
            defaultFunction: "db.generic.groupBy.group",
            type: {
              "java.lang.String": "text",
            },
            category: "column",
            uniqueKey: "68456af1-7e01-412b-b42a-491b4355ef93_dq993",
            name: "created_date",
            tableKey: "dimdate",
            connId: "dq993",
            columnKey: "created_date",
            tableId: "d324e793296ff76020c708f1c8fbb704",
          },
          created_time: {
            alias: "created_time",
            fullyQualifiedColumn: "dimdate.created_time",
            id: "e1470c4a-9a78-4fbf-bf50-7c406f9caf95",
            defaultFunction: "db.generic.groupBy.group",
            type: {
              "java.lang.String": "text",
            },
            category: "column",
            uniqueKey: "e1470c4a-9a78-4fbf-bf50-7c406f9caf95_dq993",
            name: "created_time",
            tableKey: "dimdate",
            connId: "dq993",
            columnKey: "created_time",
            tableId: "d324e793296ff76020c708f1c8fbb704",
          },
          rating: {
            alias: "rating",
            fullyQualifiedColumn: "dimdate.rating",
            id: "ebfa16cf-0667-47f6-817e-1d990ae70c48",
            defaultFunction: "db.generic.groupBy.group",
            type: {
              "java.lang.String": "text",
            },
            category: "column",
            uniqueKey: "ebfa16cf-0667-47f6-817e-1d990ae70c48_dq993",
            name: "rating",
            tableKey: "dimdate",
            connId: "dq993",
            columnKey: "rating",
            tableId: "d324e793296ff76020c708f1c8fbb704",
          },
        },
        columnsFetched: true,
      },
      employee_details: {
        id: "b161910cbebfd353351a6c0b46e6a02e",
        name: "employee_details",
        alias: "employee_details",
        dataSource: {
          id: "1201",
          type: "dynamicDataSource",
          baseType: "global.jdbc",
          catSchemaPredicted: false,
          sync: false,
          catalog: "",
          schema: "",
          connId: "dq993",
          dbId: "dq993",
          classifier: "db.workflow",
          datasourceName: "SampleTravelData",
          dsKeyPath: "2s8s-g8u0-hir9-10pd-2m/b09l-0fng-gpfn-yhza-qj",
          driverType: "Sqlite",
          database: "SampleTravelData",
        },
        category: "table",
        connId: "dq993",
        keyPath:
          "2s8s-g8u0-hir9-10pd-2m/b09l-0fng-gpfn-yhza-qj/dakj-i7lb-kscw-w09h-bs",
        uniqueKey: "b161910cbebfd353351a6c0b46e6a02e_dq993",
        selected: true,
        keyName: "employee_details",
      },
    },
    views: [],
    activeView: false,
    categories: {
      "u1s3-a6ap-vr1v-xnu5-g6": {
        ds: {
          permissionLevel: 5,
          driver: "org.apache.derby.jdbc.AutoloadedDriver",
          name: "Plain Jdbc",
          classifier: "efwd",
          type: "sql.jdbc",
          data: {
            dir: "datasources",
            driverName: "org.apache.derby.jdbc.AutoloadedDriver",
            type: "sql.jdbc",
            id: 501,
            userName: "hiuser",
            password: "hiuser",
            jdbcUrl:
              "jdbc:derby:/home/helical/Performance/hi/db/SampleTravelData",
          },
          dataSourceType: "Plain Jdbc DataSource",
        },
        category: {
          driver: "org.apache.derby.jdbc.AutoloadedDriver",
          databaseDialect: "derby",
          name: "Derby",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:derby:{{database}}",
          parameters: {
            database: "database",
          },
        },
      },
      "d3k0-ojp4-iuzm-7h0f-7i": {
        ds: {
          permissionLevel: 5,
          driver: "dynamicSwitch",
          name: "Groovy 1",
          classifier: "efwd",
          type: "sql.jdbc.groovy.managed",
          data: {
            dir: "Gagan",
            driverName: null,
            type: "sql.jdbc.groovy.managed",
            id: 1,
            userName: null,
            password: null,
            condition:
              'import groovy.sql.Sql;\n      import net.sf.json.JSONObject;\n      import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n      public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        if (userName.equals("hiadmin")) {\n          responseJson.put("globalId", 1001);\n        }\n      \n        if (userName.equals("hiuser")) {\n          responseJson.put("globalId", 3);\n        }\n      \n        if (userName.equals("test")) {\n          responseJson.put("globalId", 4);\n        }\n      \n        responseJson.put("type", "global.jdbc");\n      \n        //throw new RuntimeException("This is a test exception" +responseJson);\n        return responseJson;\n      }',
            jdbcUrl: null,
            driver: "dynamicSwitch",
          },
          dataSourceType: "",
        },
        category: {
          driver: "dynamicSwitch",
          databaseDialect: "",
          name: "DynamicSwitch",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
        },
      },
      "2a0f-qbnu-m692-ww6j-c9": {
        ds: {
          data: {
            id: "2402",
            type: "dynamicDataSource",
          },
          dataSourceProvider: "tomcat",
          type: "dynamicDataSource",
          permissionLevel: 5,
          driver: "com.mysql.jdbc.Driver",
          name: "mysql",
          classifier: "global",
          dataSourceType: "Managed DataSource",
        },
        category: {
          driver: "com.mysql.jdbc.Driver",
          databaseDialect: "mysql",
          name: "Mysql",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "3306",
            hostName: "localhost",
            database: "database",
          },
        },
      },
      "4lin-ro8z-r2wl-dnqp-90": {
        ds: {
          data: {
            id: "2001",
            type: "dynamicDataSource",
          },
          dataSourceProvider: "tomcat",
          type: "dynamicDataSource",
          permissionLevel: 5,
          driver: "oracle.jdbc.OracleDriver",
          name: "Oracle_12",
          classifier: "global",
          dataSourceType: "Managed DataSource",
        },
        category: {
          driver: "oracle.jdbc.OracleDriver",
          databaseDialect: "oracle",
          name: "Oracle",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:oracle:thin:@{{hostName}}:{{port}}:{{database}}",
          parameters: {
            port: "1521",
            hostName: "localhost",
            database: "database",
          },
        },
      },
      "p82a-quwc-3ryq-k9fg-vq": {
        ds: {
          data: {
            id: "1001",
            type: "dynamicDataSource",
          },
          dataSourceProvider: "tomcat",
          type: "dynamicDataSource",
          permissionLevel: 5,
          driver: "org.postgresql.Driver",
          name: "booking",
          classifier: "global",
          dataSourceType: "Managed DataSource",
        },
        category: {
          driver: "org.postgresql.Driver",
          databaseDialect: "postgresql",
          name: "Postgresql",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:postgresql://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "5432",
            hostName: "localhost",
            database: "database",
          },
        },
      },
      "6uxn-x499-0l90-dp7i-gj": {
        ds: {
          data: {
            id: "1901",
            type: "dynamicDataSource",
          },
          dataSourceProvider: "tomcat",
          type: "dynamicDataSource",
          permissionLevel: 5,
          driver: "net.snowflake.client.jdbc.SnowflakeDriver",
          name: "SnowflakeDS",
          classifier: "global",
          dataSourceType: "Managed DataSource",
        },
        category: {
          driver: "net.snowflake.client.jdbc.SnowflakeDriver",
          databaseDialect: "snowflake",
          name: "Snowflake Client",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:snowflake://{{hostName}}",
          parameters: {
            hostName: "localhost",
          },
        },
      },
      "2s8s-g8u0-hir9-10pd-2m": {
        ds: {
          data: {
            id: "1201",
            type: "dynamicDataSource",
          },
          dataSourceProvider: "tomcat",
          type: "dynamicDataSource",
          permissionLevel: 5,
          driver: "org.sqlite.JDBC",
          name: "SampleTravelData",
          classifier: "global",
          dataSourceType: "Managed DataSource",
        },
        category: {
          driver: "org.sqlite.JDBC",
          databaseDialect: "sqlite",
          name: "Sqlite",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:sqlite:{{database}}",
          parameters: {
            database: "database",
          },
        },
      },
    },
    activeEditorTab: "info",
    dataSourcesAddedToMetadata: [
      {
        id: "1201",
        type: "dynamicDataSource",
        baseType: "global.jdbc",
        catSchemaPredicted: false,
        sync: false,
        catalog: "",
        schema: "",
        connId: "dq993",
        dbId: "dq993",
        classifier: "db.workflow",
        datasourceName: "SampleTravelData",
        dsKeyPath: "2s8s-g8u0-hir9-10pd-2m/b09l-0fng-gpfn-yhza-qj",
        driverType: "Sqlite",
        database: "",
      },
    ],
    changeDSList: {},
    changedTables: [],
    changedColumns: [
      {
        alias: "test",
        columnId: "28e1264e-6563-4b43-ba36-55a4a049fd33",
        connId: "dq993",
        tableId: "d324e793296ff76020c708f1c8fbb704",
        aliasChanged: true,
      },
    ],
    removedTables: [],
    removedColumns: [],
    removedDataSources: [],
    duplicateColumnList: [],
    duplicateTableList: [],
    unsavedViews: [],
    saveDetails: false,
    savedTableIds: [],
    savedColumnIds: [],
    joins: [],
    mode: "create",
    allTablesKeys: [
      "f2ff93c37589ef57f40dcb15fda6d7ea_dq993",
      "025fbfb381cb17d4519363c3585626fb_dq993",
      "b161910cbebfd353351a6c0b46e6a02e_dq993",
      "d324e793296ff76020c708f1c8fbb704_dq993",
      "21e1b86ae9680d0fc197ed543c3e37eb_dq993",
    ],
    selectedTableKeys: [],
    metadataName: "Metadata_1",
    activeDataSource: false,
    metadataToEdit: false,
    isSavingInProgress: false,
    editViewsTempData: {},
    inititalStateFromJest: false,
    timeStamp: 1677663979838,
    initialEditResponse: false,
    editorFullView: false,
    selectedTableOrColumnKey: {},
    expressionObj: [],
    securityConstants: {},
    edit: false,
    isAllowServiceCall: true,
    isValidatedTableShow: false,
    securityTableData: [],
    addOneMoreSecurity: false,
    viewSessionVariables: false,
    textEditingObj: {},
    selectedJoinNameData: {},
    filterbyData: [
      {
        value: "All",
        isChecked: true,
      },
      {
        value: "Table",
        isChecked: true,
      },
      {
        value: "Column",
        isChecked: true,
      },
      {
        value: "Global",
        isChecked: true,
      },
    ],
    isFirstRender: true,
    securityFormData: {},
    accessType: "deny",
    entityNames: [],
    executionType: "conditionIf",
    expressionName: null,
    expressionType: "",
    isApplyDisabled: true,
    isInfoShow: true,
    securityKeysChecked: [],
    hasUnsavedData: true,
    getSecurityTableData: {
      tables: [],
      columns: [],
    },
    doResetFormData: false,
    tablesMergeType: "reload",
    activeDsInfoId: "dq993",
    setMetadataLoading: {
      isDataSourceFetched: true,
    },
  },
};
