export const metadaStore = {
  metadata: {
    present: {
      dataFetchedFor: {
        getDatasource: true,
        joins: false,
        viewSessionVariables: false,
        listDataSources: true,
        "sktx-8ia7-z3ep-z2ln-oc": false,
        "pqz5-gd7d-od5l-3a64-2j": false,
        "apvb-b1nt-kmwm-9y6b-wc": false,
        "dt6i-ei6r-5dco-ekdl-dd": true,
      },
      loadingStatus: {
        getDatasource: true,
        listDataSources: true,
        "sktx-8ia7-z3ep-z2ln-oc": false,
        "pqz5-gd7d-od5l-3a64-2j": false,
        "apvb-b1nt-kmwm-9y6b-wc": false,
        "dt6i-ei6r-5dco-ekdl-dd": true,
      },
      joinsLoadingStatus: "",
      serviceErrorStatus: {},
      fetchedDSInfo: {},
      listDataSource: [],
      supportedDataSourceTypes: [
        {
          name: "Access",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          name: "Amazon Dynamodb",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          name: "Amazon Redshift",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          name: "Dremio",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          name: "Google Bigquery",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          name: "IBM Db2",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          name: "Informix",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          name: "Microsoft Sqlserver",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          name: "Oracle",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          name: "Presto",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          name: "Teradata",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          name: "Ξ Add Driver Ξ",
          categoryType: "supported",
          categoryName: "Supported",
        },
      ],
      allDataSourceTypes: [
        {
          name: "Access",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          name: "Amazon Dynamodb",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          name: "Amazon Redshift",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          driver: "org.apache.drill.jdbc.Driver",
          databaseDialect: "drill",
          enabledTypes: false,
          name: "Apache Drill",
          categoryName: "Big Data",
          categoryType: "big_data",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:drill:{{hostName}}:{{port}}",
          parameters: {
            port: "31010",
            hostName: "drillbit=localhost",
          },
        },
        {
          driver: "com.simba.athena.jdbc.Driver",
          databaseDialect: "athena",
          name: "Athena",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:awsathena://{{hostName}}",
          parameters: {
            hostName: "localhost",
          },
        },
        {
          driver: "ru.yandex.clickhouse.ClickHouseDriver",
          databaseDialect: "clickhouse",
          name: "Clickhouse",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:clickhouse://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "8123",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          driver: "com.databricks.client.jdbc.Driver",
          databaseDialect: "databricks",
          name: "Databricks Client",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:databricks://{{hostName}}:{{port}};{{database}}",
          parameters: {
            port: "443",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          driver: "org.apache.derby.jdbc.ClientDriver",
          databaseDialect: "derby",
          name: "Derby",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:derby://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "1527",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          driver: "org.apache.derby.jdbc.AutoloadedDriver",
          databaseDialect: "derby",
          name: "Derby",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:derby:{{database}}",
          parameters: {
            database: "database",
          },
        },
        {
          name: "Dremio",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          driver: "dynamicSwitch",
          databaseDialect: "",
          name: "DynamicSwitch",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
        },
        {
          name: "Google Bigquery",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          driver: "com.helical.mongodb.MongoJdbcDriver",
          databaseDialect: "himongo",
          name: "Helical Mongodb",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
        },
        {
          driver: "org.apache.hive.jdbc.HiveDriver",
          databaseDialect: "spark",
          name: "Hive",
          categoryName: "Big Data",
          categoryType: "big_data",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:hive2://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "10001",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          name: "IBM Db2",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          name: "Informix",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          driver: "org.mariadb.jdbc.Driver",
          databaseDialect: "mysql",
          name: "Mariadb",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:mariadb://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "3306",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          name: "Microsoft Sqlserver",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          driver: "net.sourceforge.jtds.jdbc.Driver",
          databaseDialect: "sqlserver",
          name: "Microsoft Sqlserver(sourceforge)",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:jtds:sqlserver://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "1433",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          driver: "com.mysql.jdbc.Driver",
          databaseDialect: "mysql",
          name: "Mysql",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "3306",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          driver: "com.mysql.cj.jdbc.Driver",
          databaseDialect: "mysql",
          name: "Mysql Cj",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "3306",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          name: "Oracle",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          driver: "org.postgresql.Driver",
          databaseDialect: "postgresql",
          name: "Postgresql",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:postgresql://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "5432",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          name: "Presto",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          driver: "org.sqlite.JDBC",
          databaseDialect: "sqlite",
          name: "Sqlite",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:sqlite:{{database}}",
          parameters: {
            database: "database",
          },
        },
        {
          name: "Teradata",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          name: "Ξ Add Driver Ξ",
          categoryType: "supported",
          categoryName: "Supported",
        },
      ],
      metaDataSourceList: [
        {
          driver: "org.apache.drill.jdbc.Driver",
          databaseDialect: "drill",
          enabledTypes: false,
          name: "Apache Drill",
          categoryName: "Big Data",
          categoryType: "big_data",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:drill:{{hostName}}:{{port}}",
          parameters: {
            port: "31010",
            hostName: "drillbit=localhost",
          },
        },
        {
          driver: "com.simba.athena.jdbc.Driver",
          databaseDialect: "athena",
          name: "Athena",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:awsathena://{{hostName}}",
          parameters: {
            hostName: "localhost",
          },
        },
        {
          driver: "ru.yandex.clickhouse.ClickHouseDriver",
          databaseDialect: "clickhouse",
          name: "Clickhouse",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:clickhouse://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "8123",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          driver: "com.databricks.client.jdbc.Driver",
          databaseDialect: "databricks",
          name: "Databricks Client",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:databricks://{{hostName}}:{{port}};{{database}}",
          parameters: {
            port: "443",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          driver: "org.apache.derby.jdbc.ClientDriver",
          databaseDialect: "derby",
          name: "Derby",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:derby://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "1527",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          driver: "org.apache.derby.jdbc.AutoloadedDriver",
          databaseDialect: "derby",
          name: "Derby",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:derby:{{database}}",
          parameters: {
            database: "database",
          },
        },
        {
          driver: "dynamicSwitch",
          databaseDialect: "",
          name: "DynamicSwitch",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
        },
        {
          driver: "com.helical.mongodb.MongoJdbcDriver",
          databaseDialect: "himongo",
          name: "Helical Mongodb",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
        },
        {
          driver: "org.apache.hive.jdbc.HiveDriver",
          databaseDialect: "spark",
          name: "Hive",
          categoryName: "Big Data",
          categoryType: "big_data",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:hive2://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "10001",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          driver: "org.mariadb.jdbc.Driver",
          databaseDialect: "mysql",
          name: "Mariadb",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:mariadb://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "3306",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          driver: "net.sourceforge.jtds.jdbc.Driver",
          databaseDialect: "sqlserver",
          name: "Microsoft Sqlserver(sourceforge)",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:jtds:sqlserver://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "1433",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          driver: "com.mysql.jdbc.Driver",
          databaseDialect: "mysql",
          name: "Mysql",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "3306",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          driver: "com.mysql.cj.jdbc.Driver",
          databaseDialect: "mysql",
          name: "Mysql Cj",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "3306",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          driver: "org.postgresql.Driver",
          databaseDialect: "postgresql",
          name: "Postgresql",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:postgresql://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "5432",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          driver: "org.sqlite.JDBC",
          databaseDialect: "sqlite",
          name: "Sqlite",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:sqlite:{{database}}",
          parameters: {
            database: "database",
          },
        },
      ],
      driversList: [
        {
          driver: "dynamicSwitch",
          showInDatasource: "false",
          available: "true",
          parameters: [],
        },
        {
          url: "jdbc:derby://{{hostName}}:{{port}}/{{database}}",
          driver: "org.apache.derby.jdbc.ClientDriver",
          available: "true",
          parameters: {
            port: "1527",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          url: "jdbc:derby:{{database}}",
          driver: "org.apache.derby.jdbc.AutoloadedDriver",
          available: "true",
          parameters: {
            database: "database",
          },
        },
        {
          url: "jdbc:awsathena://{{hostName}}",
          driver: "com.simba.athena.jdbc.Driver",
          available: "true",
          parameters: {
            hostName: "localhost",
          },
        },
        {
          url: "jdbc:jtds:sqlserver://{{hostName}}:{{port}}/{{database}}",
          driver: "net.sourceforge.jtds.jdbc.Driver",
          available: "true",
          parameters: {
            port: "1433",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          url: "jdbc:clickhouse://{{hostName}}:{{port}}/{{database}}",
          driver: "ru.yandex.clickhouse.ClickHouseDriver",
          available: "true",
          parameters: {
            port: "8123",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
          driver: "com.mysql.cj.jdbc.Driver",
          available: "true",
          parameters: {
            port: "3306",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
          driver: "com.mysql.jdbc.Driver",
          available: "true",
          parameters: {
            port: "3306",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          available: "true",
          driver: "com.helical.mongodb.MongoJdbcDriver",
        },
        {
          url: "jdbc:hive2://{{hostName}}:{{port}}/{{database}}",
          driver: "org.apache.hive.jdbc.HiveDriver",
          available: "true",
          parameters: {
            port: "10001",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          url: "jdbc:drill:{{hostName}}:{{port}}",
          driver: "org.apache.drill.jdbc.Driver",
          available: "true",
          parameters: {
            port: "31010",
            hostName: "drillbit=localhost",
          },
        },
        {
          url: "jdbc:mariadb://{{hostName}}:{{port}}/{{database}}",
          driver: "org.mariadb.jdbc.Driver",
          available: "true",
          parameters: {
            port: "3306",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          url: "jdbc:databricks://{{hostName}}:{{port}};{{database}}",
          driver: "com.databricks.client.jdbc.Driver",
          available: "true",
          parameters: {
            port: "443",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          url: "jdbc:postgresql://{{hostName}}:{{port}}/{{database}}",
          driver: "org.postgresql.Driver",
          available: "true",
          parameters: {
            port: "5432",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          url: "jdbc:derby://{{hostName}}:{{port}}/{{database}}",
          driver: "org.apache.derby.jdbc.ClientDriver",
          available: "true",
          parameters: {
            port: "1527",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          url: "jdbc:sqlite:{{database}}",
          driver: "org.sqlite.JDBC",
          available: "true",
          parameters: {
            database: "database",
          },
        },
      ],
      allDataSources: [
        {
          data: {
            id: "1",
            type: "dynamicDataSource",
          },
          dataSourceProvider: "tomcat",
          type: "dynamicDataSource",
          permissionLevel: 5,
          driver: "org.apache.derby.jdbc.ClientDriver",
          name: "SampleTravelDataDerby",
          classifier: "global",
          dataSourceType: "Managed DataSource",
        },
        {
          data: {
            id: "1001",
            type: "dynamicDataSource",
          },
          dataSourceProvider: "tomcat",
          type: "dynamicDataSource",
          permissionLevel: 5,
          driver: "com.mysql.jdbc.Driver",
          name: "MYSQLDS",
          classifier: "global",
          dataSourceType: "Managed DataSource",
        },
        {
          data: {
            id: "1002",
            type: "dynamicDataSource",
          },
          dataSourceProvider: "tomcat",
          type: "dynamicDataSource",
          permissionLevel: 5,
          driver: "org.apache.derby.jdbc.ClientDriver",
          name: "derby2",
          classifier: "global",
          dataSourceType: "Managed DataSource",
        },
      ],
      dataSourceTypes: [
        {
          type: "sql.jdbc.groovy.managed",
          name: "Groovy Managed Jdbc DataSource",
          classifier: "efwd",
          categoryName: "advanced",
          categoryType: "advanced",
        },
        {
          type: "sql.jdbc.groovy",
          name: "Groovy Plain Jdbc DataSource",
          classifier: "efwd",
          categoryName: "advanced",
          categoryType: "advanced",
        },
        {
          type: "global.jdbc",
          name: "Managed DataSource",
          classifier: "global",
          categoryName: "advanced",
          categoryType: "advanced",
        },
        {
          type: "sql.jdbc",
          name: "Plain Jdbc DataSource",
          classifier: "efwd",
          categoryName: "advanced",
          categoryType: "advanced",
        },
      ],
      datasourceListToRender: [
        {
          name: "Derby",
          children: [
            {
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "org.apache.derby.jdbc.ClientDriver",
              name: "SampleTravelDataDerby",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [
                {
                  name: "SQLJ",
                  children: [],
                  keyPath:
                    "bhxf-pi2c-r225-poaf-h4/apvb-b1nt-kmwm-9y6b-wc/6py9-gvsr-9b1o-73dy-dn",
                  key: "6py9-gvsr-9b1o-73dy-dn",
                  uuid: "6py9-gvsr-9b1o-73dy-dn",
                  data: {
                    id: "1",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "SampleTravelDataDerby",
                },
                {
                  name: "SYSFUN",
                  children: [],
                  keyPath:
                    "bhxf-pi2c-r225-poaf-h4/apvb-b1nt-kmwm-9y6b-wc/blyv-tui6-dpgm-b8y9-z7",
                  key: "blyv-tui6-dpgm-b8y9-z7",
                  uuid: "blyv-tui6-dpgm-b8y9-z7",
                  data: {
                    id: "1",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "SampleTravelDataDerby",
                },
                {
                  name: "SYSCAT",
                  children: [],
                  keyPath:
                    "bhxf-pi2c-r225-poaf-h4/apvb-b1nt-kmwm-9y6b-wc/v65u-c249-dpiv-lg3o-0s",
                  key: "v65u-c249-dpiv-lg3o-0s",
                  uuid: "v65u-c249-dpiv-lg3o-0s",
                  data: {
                    id: "1",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "SampleTravelDataDerby",
                },
                {
                  name: "HIUSER",
                  children: [],
                  keyPath:
                    "bhxf-pi2c-r225-poaf-h4/apvb-b1nt-kmwm-9y6b-wc/dt6i-ei6r-5dco-ekdl-dd",
                  key: "dt6i-ei6r-5dco-ekdl-dd",
                  uuid: "dt6i-ei6r-5dco-ekdl-dd",
                  data: {
                    id: "1",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "SampleTravelDataDerby",
                },
                {
                  name: "SYSCS_DIAG",
                  children: [],
                  keyPath:
                    "bhxf-pi2c-r225-poaf-h4/apvb-b1nt-kmwm-9y6b-wc/0c3w-3qy0-wyly-5h0b-l0",
                  key: "0c3w-3qy0-wyly-5h0b-l0",
                  uuid: "0c3w-3qy0-wyly-5h0b-l0",
                  data: {
                    id: "1",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "SampleTravelDataDerby",
                },
                {
                  name: "SYSCS_UTIL",
                  children: [],
                  keyPath:
                    "bhxf-pi2c-r225-poaf-h4/apvb-b1nt-kmwm-9y6b-wc/9mf0-smig-0dtx-dvbh-ms",
                  key: "9mf0-smig-0dtx-dvbh-ms",
                  uuid: "9mf0-smig-0dtx-dvbh-ms",
                  data: {
                    id: "1",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "SampleTravelDataDerby",
                },
                {
                  name: "SYSIBM",
                  children: [],
                  keyPath:
                    "bhxf-pi2c-r225-poaf-h4/apvb-b1nt-kmwm-9y6b-wc/uvcc-19tq-zlgv-b07o-uf",
                  key: "uvcc-19tq-zlgv-b07o-uf",
                  uuid: "uvcc-19tq-zlgv-b07o-uf",
                  data: {
                    id: "1",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "SampleTravelDataDerby",
                },
                {
                  name: "APP",
                  children: [],
                  keyPath:
                    "bhxf-pi2c-r225-poaf-h4/apvb-b1nt-kmwm-9y6b-wc/51ym-pauf-ey21-tdaj-05",
                  key: "51ym-pauf-ey21-tdaj-05",
                  uuid: "51ym-pauf-ey21-tdaj-05",
                  data: {
                    id: "1",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "SampleTravelDataDerby",
                },
                {
                  name: "NULLID",
                  children: [],
                  keyPath:
                    "bhxf-pi2c-r225-poaf-h4/apvb-b1nt-kmwm-9y6b-wc/zie1-ydy2-l1vm-v6fk-vv",
                  key: "zie1-ydy2-l1vm-v6fk-vv",
                  uuid: "zie1-ydy2-l1vm-v6fk-vv",
                  data: {
                    id: "1",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "SampleTravelDataDerby",
                },
                {
                  name: "SYSPROC",
                  children: [],
                  keyPath:
                    "bhxf-pi2c-r225-poaf-h4/apvb-b1nt-kmwm-9y6b-wc/qkxl-xs7n-0o6j-5o3m-p6",
                  key: "qkxl-xs7n-0o6j-5o3m-p6",
                  uuid: "qkxl-xs7n-0o6j-5o3m-p6",
                  data: {
                    id: "1",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "SampleTravelDataDerby",
                },
                {
                  name: "SYS",
                  children: [],
                  keyPath:
                    "bhxf-pi2c-r225-poaf-h4/apvb-b1nt-kmwm-9y6b-wc/ddz1-in6l-imsu-kyvr-kb",
                  key: "ddz1-in6l-imsu-kyvr-kb",
                  uuid: "ddz1-in6l-imsu-kyvr-kb",
                  data: {
                    id: "1",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "SampleTravelDataDerby",
                },
                {
                  name: "SYSSTAT",
                  children: [],
                  keyPath:
                    "bhxf-pi2c-r225-poaf-h4/apvb-b1nt-kmwm-9y6b-wc/lo12-t8uz-jf2j-kurb-bg",
                  key: "lo12-t8uz-jf2j-kurb-bg",
                  uuid: "lo12-t8uz-jf2j-kurb-bg",
                  data: {
                    id: "1",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "SampleTravelDataDerby",
                },
              ],
              driverType: "Derby",
              keyPath: "bhxf-pi2c-r225-poaf-h4/apvb-b1nt-kmwm-9y6b-wc",
              key: "apvb-b1nt-kmwm-9y6b-wc",
              uuid: "apvb-b1nt-kmwm-9y6b-wc",
              fetched: true,
            },
            {
              data: {
                id: "1002",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "org.apache.derby.jdbc.ClientDriver",
              name: "derby2",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [
                {
                  name: "SQLJ",
                  children: [],
                  keyPath:
                    "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/j2b6-2d5u-2m9i-jii7-fg",
                  key: "j2b6-2d5u-2m9i-jii7-fg",
                  uuid: "j2b6-2d5u-2m9i-jii7-fg",
                  data: {
                    id: "1002",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "derby2",
                },
                {
                  name: "SYSFUN",
                  children: [],
                  keyPath:
                    "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/5s8f-s7o6-5i6m-7u8q-c8",
                  key: "5s8f-s7o6-5i6m-7u8q-c8",
                  uuid: "5s8f-s7o6-5i6m-7u8q-c8",
                  data: {
                    id: "1002",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "derby2",
                },
                {
                  name: "SYSCAT",
                  children: [],
                  keyPath:
                    "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/s3d8-87kr-kbf9-mtrc-wo",
                  key: "s3d8-87kr-kbf9-mtrc-wo",
                  uuid: "s3d8-87kr-kbf9-mtrc-wo",
                  data: {
                    id: "1002",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "derby2",
                },
                {
                  name: "HIUSER",
                  children: [
                    {
                      id: "4ac5d9f68b58bd7c0d179146e46795be",
                      name: "dimdate",
                      data: {
                        id: "1002",
                        type: "dynamicDataSource",
                      },
                      keyPath:
                        "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j/5zj2-xmk5-2ii4-3hi1-in",
                      key: "5zj2-xmk5-2ii4-3hi1-in",
                      alias: "dimdate",
                      uuid: "5zj2-xmk5-2ii4-3hi1-in",
                      connId: "sb7q5",
                      dataSource: {
                        id: "1002",
                        type: "dynamicDataSource",
                        baseType: "global.jdbc",
                        catSchemaPredicted: false,
                        sync: false,
                        catalog: "",
                        schema: "HIUSER",
                        connId: "sb7q5",
                        classifier: "db.workflow",
                        datasourceName: "derby2",
                        dsKeyPath:
                          "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j",
                        driverType: "Derby",
                        database: "HIUSER",
                      },
                      dataSourceName: "derby2",
                      category: "table",
                      nameWithConnId: "dimdate_sb7q5",
                      database: "HIUSER",
                      schema: "HIUSER",
                      selected: true,
                    },
                    {
                      id: "4e1fd245f4d13b77be423a43f01d80b2",
                      name: "employee_details",
                      data: {
                        id: "1002",
                        type: "dynamicDataSource",
                      },
                      keyPath:
                        "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j/otmo-kzra-3614-9gzz-co",
                      key: "otmo-kzra-3614-9gzz-co",
                      alias: "employee_details",
                      uuid: "otmo-kzra-3614-9gzz-co",
                      connId: "sb7q5",
                      dataSource: {
                        id: "1002",
                        type: "dynamicDataSource",
                        baseType: "global.jdbc",
                        catSchemaPredicted: false,
                        sync: false,
                        catalog: "",
                        schema: "HIUSER",
                        connId: "sb7q5",
                        classifier: "db.workflow",
                        datasourceName: "derby2",
                        dsKeyPath:
                          "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j",
                        driverType: "Derby",
                        database: "HIUSER",
                      },
                      dataSourceName: "derby2",
                      category: "table",
                      nameWithConnId: "employee_details_sb7q5",
                      database: "HIUSER",
                      schema: "HIUSER",
                      selected: true,
                    },
                    {
                      id: "be534112989b616b194bc59c2fb25a42",
                      name: "geo_cordinates",
                      data: {
                        id: "1002",
                        type: "dynamicDataSource",
                      },
                      keyPath:
                        "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j/kllc-jq68-n6k8-ggme-kj",
                      key: "kllc-jq68-n6k8-ggme-kj",
                      alias: "geo_cordinates",
                      uuid: "kllc-jq68-n6k8-ggme-kj",
                      connId: "sb7q5",
                      dataSource: {
                        id: "1002",
                        type: "dynamicDataSource",
                        baseType: "global.jdbc",
                        catSchemaPredicted: false,
                        sync: false,
                        catalog: "",
                        schema: "HIUSER",
                        connId: "sb7q5",
                        classifier: "db.workflow",
                        datasourceName: "derby2",
                        dsKeyPath:
                          "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j",
                        driverType: "Derby",
                        database: "HIUSER",
                      },
                      dataSourceName: "derby2",
                      category: "table",
                      nameWithConnId: "geo_cordinates_sb7q5",
                      database: "HIUSER",
                      schema: "HIUSER",
                      selected: true,
                    },
                    {
                      id: "9645c648a1c0dbeec1287aaf1e996db3",
                      name: "meeting_details",
                      data: {
                        id: "1002",
                        type: "dynamicDataSource",
                      },
                      keyPath:
                        "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j/bwvi-4675-b2yo-11p4-o3",
                      key: "bwvi-4675-b2yo-11p4-o3",
                      alias: "meeting_details",
                      uuid: "bwvi-4675-b2yo-11p4-o3",
                      connId: "sb7q5",
                      dataSource: {
                        id: "1002",
                        type: "dynamicDataSource",
                        baseType: "global.jdbc",
                        catSchemaPredicted: false,
                        sync: false,
                        catalog: "",
                        schema: "HIUSER",
                        connId: "sb7q5",
                        classifier: "db.workflow",
                        datasourceName: "derby2",
                        dsKeyPath:
                          "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j",
                        driverType: "Derby",
                        database: "HIUSER",
                      },
                      dataSourceName: "derby2",
                      category: "table",
                      nameWithConnId: "meeting_details_sb7q5",
                      database: "HIUSER",
                      schema: "HIUSER",
                      selected: true,
                    },
                    {
                      id: "8a28627d07d04ef096d9935f12e0c7e9",
                      name: "travel_details",
                      data: {
                        id: "1002",
                        type: "dynamicDataSource",
                      },
                      keyPath:
                        "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j/gxh3-5as5-hcyc-o7mh-3d",
                      key: "gxh3-5as5-hcyc-o7mh-3d",
                      alias: "travel_details",
                      uuid: "gxh3-5as5-hcyc-o7mh-3d",
                      connId: "sb7q5",
                      dataSource: {
                        id: "1002",
                        type: "dynamicDataSource",
                        baseType: "global.jdbc",
                        catSchemaPredicted: false,
                        sync: false,
                        catalog: "",
                        schema: "HIUSER",
                        connId: "sb7q5",
                        classifier: "db.workflow",
                        datasourceName: "derby2",
                        dsKeyPath:
                          "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j",
                        driverType: "Derby",
                        database: "HIUSER",
                      },
                      dataSourceName: "derby2",
                      category: "table",
                      nameWithConnId: "travel_details_sb7q5",
                      database: "HIUSER",
                      schema: "HIUSER",
                      selected: true,
                    },
                  ],
                  keyPath:
                    "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j",
                  key: "pqz5-gd7d-od5l-3a64-2j",
                  uuid: "pqz5-gd7d-od5l-3a64-2j",
                  data: {
                    id: "1002",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "derby2",
                  fetched: true,
                },
                {
                  name: "SYSCS_DIAG",
                  children: [],
                  keyPath:
                    "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/am0v-q7ra-lknz-q44m-60",
                  key: "am0v-q7ra-lknz-q44m-60",
                  uuid: "am0v-q7ra-lknz-q44m-60",
                  data: {
                    id: "1002",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "derby2",
                },
                {
                  name: "SYSCS_UTIL",
                  children: [],
                  keyPath:
                    "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/1n13-q8l9-6dz8-b3ut-gi",
                  key: "1n13-q8l9-6dz8-b3ut-gi",
                  uuid: "1n13-q8l9-6dz8-b3ut-gi",
                  data: {
                    id: "1002",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "derby2",
                },
                {
                  name: "SYSIBM",
                  children: [],
                  keyPath:
                    "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/ll4g-mqy2-bm0q-uuf2-4q",
                  key: "ll4g-mqy2-bm0q-uuf2-4q",
                  uuid: "ll4g-mqy2-bm0q-uuf2-4q",
                  data: {
                    id: "1002",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "derby2",
                },
                {
                  name: "APP",
                  children: [],
                  keyPath:
                    "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/89rd-nrjq-hgma-4y9q-lj",
                  key: "89rd-nrjq-hgma-4y9q-lj",
                  uuid: "89rd-nrjq-hgma-4y9q-lj",
                  data: {
                    id: "1002",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "derby2",
                },
                {
                  name: "NULLID",
                  children: [],
                  keyPath:
                    "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/n1ln-ihjw-8tt8-h5dt-r7",
                  key: "n1ln-ihjw-8tt8-h5dt-r7",
                  uuid: "n1ln-ihjw-8tt8-h5dt-r7",
                  data: {
                    id: "1002",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "derby2",
                },
                {
                  name: "SYSPROC",
                  children: [],
                  keyPath:
                    "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/2hbf-fd4v-mflo-frnq-8a",
                  key: "2hbf-fd4v-mflo-frnq-8a",
                  uuid: "2hbf-fd4v-mflo-frnq-8a",
                  data: {
                    id: "1002",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "derby2",
                },
                {
                  name: "SYS",
                  children: [],
                  keyPath:
                    "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/oewj-kw6z-bm5x-39am-qj",
                  key: "oewj-kw6z-bm5x-39am-qj",
                  uuid: "oewj-kw6z-bm5x-39am-qj",
                  data: {
                    id: "1002",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "derby2",
                },
                {
                  name: "SYSSTAT",
                  children: [],
                  keyPath:
                    "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/ca1d-baqf-8nys-ogo7-u6",
                  key: "ca1d-baqf-8nys-ogo7-u6",
                  uuid: "ca1d-baqf-8nys-ogo7-u6",
                  data: {
                    id: "1002",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "derby2",
                },
              ],
              driverType: "Derby",
              keyPath: "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc",
              key: "sktx-8ia7-z3ep-z2ln-oc",
              uuid: "sktx-8ia7-z3ep-z2ln-oc",
              fetched: true,
            },
          ],
          key: "bhxf-pi2c-r225-poaf-h4",
          uuid: "bhxf-pi2c-r225-poaf-h4",
          keyPath: "bhxf-pi2c-r225-poaf-h4",
          category: "dsGroup",
          imgUrl: "images/data_sources/defaut_datasource.png",
        },
        {
          name: "Mysql",
          children: [
            {
              data: {
                id: "1001",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "com.mysql.jdbc.Driver",
              name: "MYSQLDS",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Mysql",
              keyPath: "z146-48v6-vc54-wxfh-el/apzn-z3qf-leag-ugr1-g1",
              key: "apzn-z3qf-leag-ugr1-g1",
              uuid: "apzn-z3qf-leag-ugr1-g1",
            },
          ],
          key: "z146-48v6-vc54-wxfh-el",
          uuid: "z146-48v6-vc54-wxfh-el",
          keyPath: "z146-48v6-vc54-wxfh-el",
          category: "dsGroup",
          imgUrl: "images/data_sources/defaut_datasource.png",
        },
      ],
      workFlow: {
        dataList: [
          {
            fetchSchemas: true,
            fetchCatalogs: true,
            working: true,
            connData: {
              id: "1002",
              type: "dynamicDataSource",
            },
            connId: "1002",
            dsUUID: "sktx-8ia7-z3ep-z2ln-oc",
            classifier: "db.workflow",
            metadata: {
              catalogs: [
                {
                  name: "Null",
                  schemas: [
                    {
                      name: "SQLJ",
                    },
                    {
                      name: "SYSFUN",
                    },
                    {
                      name: "SYSCAT",
                    },
                    {
                      name: "HIUSER",
                    },
                    {
                      name: "SYSCS_DIAG",
                    },
                    {
                      name: "SYSCS_UTIL",
                    },
                    {
                      name: "SYSIBM",
                    },
                    {
                      name: "APP",
                    },
                    {
                      name: "NULLID",
                    },
                    {
                      name: "SYSPROC",
                    },
                    {
                      name: "SYS",
                    },
                    {
                      name: "SYSSTAT",
                    },
                  ],
                },
              ],
            },
          },
          {
            classifier: "db.workflow",
            metadata: {
              catalogs: [
                {
                  name: "Null",
                  schemas: [
                    {
                      name: "HIUSER",
                      tables: [
                        {
                          id: "be534112989b616b194bc59c2fb25a42",
                          name: "geo_cordinates",
                        },
                        {
                          id: "9645c648a1c0dbeec1287aaf1e996db3",
                          name: "meeting_details",
                        },
                        {
                          id: "4e1fd245f4d13b77be423a43f01d80b2",
                          name: "employee_details",
                        },
                        {
                          id: "4ac5d9f68b58bd7c0d179146e46795be",
                          name: "dimdate",
                        },
                        {
                          id: "8a28627d07d04ef096d9935f12e0c7e9",
                          name: "travel_details",
                        },
                      ],
                    },
                  ],
                },
              ],
              dataSource: {
                id: "1002",
                type: "dynamicDataSource",
                baseType: "global.jdbc",
                catSchemaPredicted: false,
                sync: false,
                catalog: "",
                schema: "HIUSER",
                connId: "sb7q5",
                classifier: "db.workflow",
                datasourceName: "derby2",
                dsKeyPath:
                  "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j",
                driverType: "Derby",
                database: "HIUSER",
              },
              name: "HIUSER",
            },
          },
          {
            fetchSchemas: true,
            fetchCatalogs: true,
            working: true,
            connData: {
              id: "1",
              type: "dynamicDataSource",
            },
            connId: "1",
            dsUUID: "apvb-b1nt-kmwm-9y6b-wc",
            classifier: "db.workflow",
            metadata: {
              catalogs: [
                {
                  name: "Null",
                  schemas: [
                    {
                      name: "SQLJ",
                    },
                    {
                      name: "SYSFUN",
                    },
                    {
                      name: "SYSCAT",
                    },
                    {
                      name: "HIUSER",
                    },
                    {
                      name: "SYSCS_DIAG",
                    },
                    {
                      name: "SYSCS_UTIL",
                    },
                    {
                      name: "SYSIBM",
                    },
                    {
                      name: "APP",
                    },
                    {
                      name: "NULLID",
                    },
                    {
                      name: "SYSPROC",
                    },
                    {
                      name: "SYS",
                    },
                    {
                      name: "SYSSTAT",
                    },
                  ],
                },
              ],
            },
          },
        ],
      },
      dataSource: [
        {
          id: "1002",
          type: "dynamicDataSource",
          baseType: "global.jdbc",
          catSchemaPredicted: false,
          sync: false,
          catalog: "",
          schema: "HIUSER",
          connId: "sb7q5",
          classifier: "db.workflow",
          datasourceName: "derby2",
          dsKeyPath:
            "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j",
          driverType: "Derby",
          database: "HIUSER",
        },
      ],
      tables: {
        dimdate: {
          id: "4ac5d9f68b58bd7c0d179146e46795be",
          name: "dimdate",
          data: {
            id: "1002",
            type: "dynamicDataSource",
          },
          keyPath:
            "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j/5zj2-xmk5-2ii4-3hi1-in",
          key: "5zj2-xmk5-2ii4-3hi1-in",
          alias: "dimdate",
          uuid: "5zj2-xmk5-2ii4-3hi1-in",
          connId: "sb7q5",
          dataSource: {
            id: "1002",
            type: "dynamicDataSource",
            baseType: "global.jdbc",
            catSchemaPredicted: false,
            sync: false,
            catalog: "",
            schema: "HIUSER",
            connId: "sb7q5",
            classifier: "db.workflow",
            datasourceName: "derby2",
            dsKeyPath:
              "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j",
            driverType: "Derby",
            database: "HIUSER",
          },
          dataSourceName: "derby2",
          category: "table",
          nameWithConnId: "dimdate_sb7q5",
          database: "HIUSER",
          schema: "HIUSER",
          selected: true,
          keyName: "dimdate",
        },
        employee_details: {
          id: "4e1fd245f4d13b77be423a43f01d80b2",
          name: "employee_details",
          data: {
            id: "1002",
            type: "dynamicDataSource",
          },
          keyPath:
            "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j/otmo-kzra-3614-9gzz-co",
          key: "otmo-kzra-3614-9gzz-co",
          alias: "employee_details",
          uuid: "otmo-kzra-3614-9gzz-co",
          connId: "sb7q5",
          dataSource: {
            id: "1002",
            type: "dynamicDataSource",
            baseType: "global.jdbc",
            catSchemaPredicted: false,
            sync: false,
            catalog: "",
            schema: "HIUSER",
            connId: "sb7q5",
            classifier: "db.workflow",
            datasourceName: "derby2",
            dsKeyPath:
              "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j",
            driverType: "Derby",
            database: "HIUSER",
          },
          dataSourceName: "derby2",
          category: "table",
          nameWithConnId: "employee_details_sb7q5",
          database: "HIUSER",
          schema: "HIUSER",
          selected: true,
          keyName: "employee_details",
        },
        geo_cordinates: {
          id: "be534112989b616b194bc59c2fb25a42",
          name: "geo_cordinates",
          data: {
            id: "1002",
            type: "dynamicDataSource",
          },
          keyPath:
            "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j/kllc-jq68-n6k8-ggme-kj",
          key: "kllc-jq68-n6k8-ggme-kj",
          alias: "geo_cordinates",
          uuid: "kllc-jq68-n6k8-ggme-kj",
          connId: "sb7q5",
          dataSource: {
            id: "1002",
            type: "dynamicDataSource",
            baseType: "global.jdbc",
            catSchemaPredicted: false,
            sync: false,
            catalog: "",
            schema: "HIUSER",
            connId: "sb7q5",
            classifier: "db.workflow",
            datasourceName: "derby2",
            dsKeyPath:
              "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j",
            driverType: "Derby",
            database: "HIUSER",
          },
          dataSourceName: "derby2",
          category: "table",
          nameWithConnId: "geo_cordinates_sb7q5",
          database: "HIUSER",
          schema: "HIUSER",
          selected: true,
          keyName: "geo_cordinates",
        },
        meeting_details: {
          id: "9645c648a1c0dbeec1287aaf1e996db3",
          name: "meeting_details",
          data: {
            id: "1002",
            type: "dynamicDataSource",
          },
          keyPath:
            "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j/bwvi-4675-b2yo-11p4-o3",
          key: "bwvi-4675-b2yo-11p4-o3",
          alias: "meeting_details",
          uuid: "bwvi-4675-b2yo-11p4-o3",
          connId: "sb7q5",
          dataSource: {
            id: "1002",
            type: "dynamicDataSource",
            baseType: "global.jdbc",
            catSchemaPredicted: false,
            sync: false,
            catalog: "",
            schema: "HIUSER",
            connId: "sb7q5",
            classifier: "db.workflow",
            datasourceName: "derby2",
            dsKeyPath:
              "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j",
            driverType: "Derby",
            database: "HIUSER",
          },
          dataSourceName: "derby2",
          category: "table",
          nameWithConnId: "meeting_details_sb7q5",
          database: "HIUSER",
          schema: "HIUSER",
          selected: true,
          keyName: "meeting_details",
        },
        travel_details: {
          id: "8a28627d07d04ef096d9935f12e0c7e9",
          name: "travel_details",
          data: {
            id: "1002",
            type: "dynamicDataSource",
          },
          keyPath:
            "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j/gxh3-5as5-hcyc-o7mh-3d",
          key: "gxh3-5as5-hcyc-o7mh-3d",
          alias: "travel_details",
          uuid: "gxh3-5as5-hcyc-o7mh-3d",
          connId: "sb7q5",
          dataSource: {
            id: "1002",
            type: "dynamicDataSource",
            baseType: "global.jdbc",
            catSchemaPredicted: false,
            sync: false,
            catalog: "",
            schema: "HIUSER",
            connId: "sb7q5",
            classifier: "db.workflow",
            datasourceName: "derby2",
            dsKeyPath:
              "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j",
            driverType: "Derby",
            database: "HIUSER",
          },
          dataSourceName: "derby2",
          category: "table",
          nameWithConnId: "travel_details_sb7q5",
          database: "HIUSER",
          schema: "HIUSER",
          selected: true,
          keyName: "travel_details",
        },
      },
      views: [],
      activeView: false,
      categories: {
        "bhxf-pi2c-r225-poaf-h4": {
          ds: {
            data: {
              id: "1",
              type: "dynamicDataSource",
            },
            dataSourceProvider: "tomcat",
            type: "dynamicDataSource",
            permissionLevel: 5,
            driver: "org.apache.derby.jdbc.ClientDriver",
            name: "SampleTravelDataDerby",
            classifier: "global",
            dataSourceType: "Managed DataSource",
          },
          category: {
            driver: "org.apache.derby.jdbc.ClientDriver",
            databaseDialect: "derby",
            name: "Derby",
            categoryName: "RDBMS",
            categoryType: "rdbms",
            type: "global.jdbc",
            dataSourceProvider: "tomcat",
            classifier: "global",
            imgUrl: "../images/data_sources/defaut_datasource.png",
            url: "jdbc:derby://{{hostName}}:{{port}}/{{database}}",
            parameters: {
              port: "1527",
              hostName: "localhost",
              database: "database",
            },
          },
        },
        "z146-48v6-vc54-wxfh-el": {
          ds: {
            data: {
              id: "1001",
              type: "dynamicDataSource",
            },
            dataSourceProvider: "tomcat",
            type: "dynamicDataSource",
            permissionLevel: 5,
            driver: "com.mysql.jdbc.Driver",
            name: "MYSQLDS",
            classifier: "global",
            dataSourceType: "Managed DataSource",
          },
          category: {
            driver: "com.mysql.jdbc.Driver",
            databaseDialect: "mysql",
            name: "Mysql",
            categoryName: "RDBMS",
            categoryType: "rdbms",
            type: "global.jdbc",
            dataSourceProvider: "tomcat",
            classifier: "global",
            imgUrl: "../images/data_sources/defaut_datasource.png",
            url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
            parameters: {
              port: "3306",
              hostName: "localhost",
              database: "database",
            },
          },
        },
      },
      activeEditorTab: "info",
      dataSourcesAddedToMetadata: [
        {
          id: "1002",
          type: "dynamicDataSource",
          baseType: "global.jdbc",
          catSchemaPredicted: false,
          sync: false,
          catalog: "",
          schema: "HIUSER",
          connId: "sb7q5",
          classifier: "db.workflow",
          datasourceName: "derby2",
          dsKeyPath:
            "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j",
          driverType: "Derby",
          database: "HIUSER",
        },
      ],
      changeDSList: {},
      changedTables: [],
      changedColumns: [],
      removedTables: [],
      removedColumns: [],
      removedDataSources: [],
      duplicateColumnList: [],
      duplicateTableList: [],
      unsavedViews: [],
      saveDetails: false,
      savedTableIds: [],
      savedColumnIds: [],
      joins: [],
      mode: "create",
      allTablesKeys: [
        "kllc-jq68-n6k8-ggme-kj",
        "bwvi-4675-b2yo-11p4-o3",
        "otmo-kzra-3614-9gzz-co",
        "5zj2-xmk5-2ii4-3hi1-in",
        "gxh3-5as5-hcyc-o7mh-3d",
      ],
      selectedTableKeys: [
        "5zj2-xmk5-2ii4-3hi1-in",
        "otmo-kzra-3614-9gzz-co",
        "kllc-jq68-n6k8-ggme-kj",
        "bwvi-4675-b2yo-11p4-o3",
        "gxh3-5as5-hcyc-o7mh-3d",
      ],
      metadataName: "Metadata_1",
      activeDataSource: false,
      metadataToEdit: false,
      isSavingInProgress: false,
      editViewsTempData: {},
      inititalStateFromJest: false,
      timeStamp: 1671009894873,
      initialEditResponse: false,
      editorFullView: false,
      selectedTableOrColumnKey: {},
      expressionObj: [],
      securityConstants: {},
      edit: false,
      isAllowServiceCall: true,
      isValidatedTableShow: false,
      securityTableData: [],
      addOneMoreSecurity: false,
      viewSessionVariables: false,
      textEditingObj: {},
      selectedJoinNameData: {},
      filterbyData: [
        {
          value: "All",
          isChecked: true,
        },
        {
          value: "Table",
          isChecked: true,
        },
        {
          value: "Column",
          isChecked: true,
        },
        {
          value: "Global",
          isChecked: true,
        },
      ],
      isFirstRender: true,
      securityFormData: {},
      accessType: "deny",
      entityNames: "",
      executionType: "conditionIf",
      expressionName: null,
      expressionType: "",
      isApplyDisabled: true,
      isInfoShow: true,
      securityKeysChecked: [],
      hasUnsavedData: true,
      getSecurityTableData: {
        tables: [],
        columns: [],
      },
      doResetFormData: false,
      tablesMergeType: "reload",
      activeDsInfoId: "sb7q5",
    },
  },
};

export const mockData = {
  result: {
    classifier: "db.workflow",
    metadata: {
      catalogs: [
        {
          name: "Null",
          schemas: [
            {
              name: "HIUSER",
              tables: [
                {
                  id: "be534112989b616b194bc59c2fb25a42",
                  name: "geo_cordinates",
                },
                {
                  id: "9645c648a1c0dbeec1287aaf1e996db3",
                  name: "meeting_details",
                },
                {
                  id: "4e1fd245f4d13b77be423a43f01d80b2",
                  name: "employee_details",
                },
                {
                  id: "4ac5d9f68b58bd7c0d179146e46795be",
                  name: "dimdate",
                },
                {
                  id: "8a28627d07d04ef096d9935f12e0c7e9",
                  name: "travel_details",
                },
              ],
            },
          ],
        },
      ],
      dataSource: {
        id: "1",
        type: "dynamicDataSource",
        baseType: "global.jdbc",
        catSchemaPredicted: false,
        sync: false,
        catalog: "",
        schema: "HIUSER",
      },
      name: "HIUSER",
    },
  },
  record: {
    name: "HIUSER",
    children: [],
    keyPath:
      "bhxf-pi2c-r225-poaf-h4/apvb-b1nt-kmwm-9y6b-wc/dt6i-ei6r-5dco-ekdl-dd",
    key: "dt6i-ei6r-5dco-ekdl-dd",
    uuid: "dt6i-ei6r-5dco-ekdl-dd",
    data: {
      id: "1",
      type: "dynamicDataSource",
    },
    category: "schema",
    datasourceName: "SampleTravelDataDerby",
  },
  datasourceListToRender: [
    {
      name: "Derby",
      children: [
        {
          data: {
            id: "1",
            type: "dynamicDataSource",
          },
          dataSourceProvider: "tomcat",
          type: "dynamicDataSource",
          permissionLevel: 5,
          driver: "org.apache.derby.jdbc.ClientDriver",
          name: "SampleTravelDataDerby",
          classifier: "global",
          dataSourceType: "Managed DataSource",
          category: "dataSource",
          children: [
            {
              name: "SQLJ",
              children: [],
              keyPath:
                "bhxf-pi2c-r225-poaf-h4/apvb-b1nt-kmwm-9y6b-wc/6py9-gvsr-9b1o-73dy-dn",
              key: "6py9-gvsr-9b1o-73dy-dn",
              uuid: "6py9-gvsr-9b1o-73dy-dn",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
            },
            {
              name: "SYSFUN",
              children: [],
              keyPath:
                "bhxf-pi2c-r225-poaf-h4/apvb-b1nt-kmwm-9y6b-wc/blyv-tui6-dpgm-b8y9-z7",
              key: "blyv-tui6-dpgm-b8y9-z7",
              uuid: "blyv-tui6-dpgm-b8y9-z7",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
            },
            {
              name: "SYSCAT",
              children: [],
              keyPath:
                "bhxf-pi2c-r225-poaf-h4/apvb-b1nt-kmwm-9y6b-wc/v65u-c249-dpiv-lg3o-0s",
              key: "v65u-c249-dpiv-lg3o-0s",
              uuid: "v65u-c249-dpiv-lg3o-0s",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
            },
            {
              name: "HIUSER",
              children: [],
              keyPath:
                "bhxf-pi2c-r225-poaf-h4/apvb-b1nt-kmwm-9y6b-wc/dt6i-ei6r-5dco-ekdl-dd",
              key: "dt6i-ei6r-5dco-ekdl-dd",
              uuid: "dt6i-ei6r-5dco-ekdl-dd",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
            },
            {
              name: "SYSCS_DIAG",
              children: [],
              keyPath:
                "bhxf-pi2c-r225-poaf-h4/apvb-b1nt-kmwm-9y6b-wc/0c3w-3qy0-wyly-5h0b-l0",
              key: "0c3w-3qy0-wyly-5h0b-l0",
              uuid: "0c3w-3qy0-wyly-5h0b-l0",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
            },
            {
              name: "SYSCS_UTIL",
              children: [],
              keyPath:
                "bhxf-pi2c-r225-poaf-h4/apvb-b1nt-kmwm-9y6b-wc/9mf0-smig-0dtx-dvbh-ms",
              key: "9mf0-smig-0dtx-dvbh-ms",
              uuid: "9mf0-smig-0dtx-dvbh-ms",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
            },
            {
              name: "SYSIBM",
              children: [],
              keyPath:
                "bhxf-pi2c-r225-poaf-h4/apvb-b1nt-kmwm-9y6b-wc/uvcc-19tq-zlgv-b07o-uf",
              key: "uvcc-19tq-zlgv-b07o-uf",
              uuid: "uvcc-19tq-zlgv-b07o-uf",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
            },
            {
              name: "APP",
              children: [],
              keyPath:
                "bhxf-pi2c-r225-poaf-h4/apvb-b1nt-kmwm-9y6b-wc/51ym-pauf-ey21-tdaj-05",
              key: "51ym-pauf-ey21-tdaj-05",
              uuid: "51ym-pauf-ey21-tdaj-05",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
            },
            {
              name: "NULLID",
              children: [],
              keyPath:
                "bhxf-pi2c-r225-poaf-h4/apvb-b1nt-kmwm-9y6b-wc/zie1-ydy2-l1vm-v6fk-vv",
              key: "zie1-ydy2-l1vm-v6fk-vv",
              uuid: "zie1-ydy2-l1vm-v6fk-vv",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
            },
            {
              name: "SYSPROC",
              children: [],
              keyPath:
                "bhxf-pi2c-r225-poaf-h4/apvb-b1nt-kmwm-9y6b-wc/qkxl-xs7n-0o6j-5o3m-p6",
              key: "qkxl-xs7n-0o6j-5o3m-p6",
              uuid: "qkxl-xs7n-0o6j-5o3m-p6",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
            },
            {
              name: "SYS",
              children: [],
              keyPath:
                "bhxf-pi2c-r225-poaf-h4/apvb-b1nt-kmwm-9y6b-wc/ddz1-in6l-imsu-kyvr-kb",
              key: "ddz1-in6l-imsu-kyvr-kb",
              uuid: "ddz1-in6l-imsu-kyvr-kb",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
            },
            {
              name: "SYSSTAT",
              children: [],
              keyPath:
                "bhxf-pi2c-r225-poaf-h4/apvb-b1nt-kmwm-9y6b-wc/lo12-t8uz-jf2j-kurb-bg",
              key: "lo12-t8uz-jf2j-kurb-bg",
              uuid: "lo12-t8uz-jf2j-kurb-bg",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
            },
          ],
          driverType: "Derby",
          keyPath: "bhxf-pi2c-r225-poaf-h4/apvb-b1nt-kmwm-9y6b-wc",
          key: "apvb-b1nt-kmwm-9y6b-wc",
          uuid: "apvb-b1nt-kmwm-9y6b-wc",
          fetched: true,
        },
        {
          data: {
            id: "1002",
            type: "dynamicDataSource",
          },
          dataSourceProvider: "tomcat",
          type: "dynamicDataSource",
          permissionLevel: 5,
          driver: "org.apache.derby.jdbc.ClientDriver",
          name: "derby2",
          classifier: "global",
          dataSourceType: "Managed DataSource",
          category: "dataSource",
          children: [
            {
              name: "SQLJ",
              children: [],
              keyPath:
                "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/j2b6-2d5u-2m9i-jii7-fg",
              key: "j2b6-2d5u-2m9i-jii7-fg",
              uuid: "j2b6-2d5u-2m9i-jii7-fg",
              data: {
                id: "1002",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "derby2",
            },
            {
              name: "SYSFUN",
              children: [],
              keyPath:
                "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/5s8f-s7o6-5i6m-7u8q-c8",
              key: "5s8f-s7o6-5i6m-7u8q-c8",
              uuid: "5s8f-s7o6-5i6m-7u8q-c8",
              data: {
                id: "1002",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "derby2",
            },
            {
              name: "SYSCAT",
              children: [],
              keyPath:
                "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/s3d8-87kr-kbf9-mtrc-wo",
              key: "s3d8-87kr-kbf9-mtrc-wo",
              uuid: "s3d8-87kr-kbf9-mtrc-wo",
              data: {
                id: "1002",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "derby2",
            },
            {
              name: "HIUSER",
              children: [
                {
                  id: "4ac5d9f68b58bd7c0d179146e46795be",
                  name: "dimdate",
                  data: {
                    id: "1002",
                    type: "dynamicDataSource",
                  },
                  keyPath:
                    "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j/5zj2-xmk5-2ii4-3hi1-in",
                  key: "5zj2-xmk5-2ii4-3hi1-in",
                  alias: "dimdate",
                  uuid: "5zj2-xmk5-2ii4-3hi1-in",
                  connId: "sb7q5",
                  dataSource: {
                    id: "1002",
                    type: "dynamicDataSource",
                    baseType: "global.jdbc",
                    catSchemaPredicted: false,
                    sync: false,
                    catalog: "",
                    schema: "HIUSER",
                    connId: "sb7q5",
                    classifier: "db.workflow",
                    datasourceName: "derby2",
                    dsKeyPath:
                      "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j",
                    driverType: "Derby",
                    database: "HIUSER",
                  },
                  dataSourceName: "derby2",
                  category: "table",
                  nameWithConnId: "dimdate_sb7q5",
                  database: "HIUSER",
                  schema: "HIUSER",
                  selected: true,
                },
                {
                  id: "4e1fd245f4d13b77be423a43f01d80b2",
                  name: "employee_details",
                  data: {
                    id: "1002",
                    type: "dynamicDataSource",
                  },
                  keyPath:
                    "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j/otmo-kzra-3614-9gzz-co",
                  key: "otmo-kzra-3614-9gzz-co",
                  alias: "employee_details",
                  uuid: "otmo-kzra-3614-9gzz-co",
                  connId: "sb7q5",
                  dataSource: {
                    id: "1002",
                    type: "dynamicDataSource",
                    baseType: "global.jdbc",
                    catSchemaPredicted: false,
                    sync: false,
                    catalog: "",
                    schema: "HIUSER",
                    connId: "sb7q5",
                    classifier: "db.workflow",
                    datasourceName: "derby2",
                    dsKeyPath:
                      "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j",
                    driverType: "Derby",
                    database: "HIUSER",
                  },
                  dataSourceName: "derby2",
                  category: "table",
                  nameWithConnId: "employee_details_sb7q5",
                  database: "HIUSER",
                  schema: "HIUSER",
                  selected: true,
                },
                {
                  id: "be534112989b616b194bc59c2fb25a42",
                  name: "geo_cordinates",
                  data: {
                    id: "1002",
                    type: "dynamicDataSource",
                  },
                  keyPath:
                    "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j/kllc-jq68-n6k8-ggme-kj",
                  key: "kllc-jq68-n6k8-ggme-kj",
                  alias: "geo_cordinates",
                  uuid: "kllc-jq68-n6k8-ggme-kj",
                  connId: "sb7q5",
                  dataSource: {
                    id: "1002",
                    type: "dynamicDataSource",
                    baseType: "global.jdbc",
                    catSchemaPredicted: false,
                    sync: false,
                    catalog: "",
                    schema: "HIUSER",
                    connId: "sb7q5",
                    classifier: "db.workflow",
                    datasourceName: "derby2",
                    dsKeyPath:
                      "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j",
                    driverType: "Derby",
                    database: "HIUSER",
                  },
                  dataSourceName: "derby2",
                  category: "table",
                  nameWithConnId: "geo_cordinates_sb7q5",
                  database: "HIUSER",
                  schema: "HIUSER",
                  selected: true,
                },
                {
                  id: "9645c648a1c0dbeec1287aaf1e996db3",
                  name: "meeting_details",
                  data: {
                    id: "1002",
                    type: "dynamicDataSource",
                  },
                  keyPath:
                    "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j/bwvi-4675-b2yo-11p4-o3",
                  key: "bwvi-4675-b2yo-11p4-o3",
                  alias: "meeting_details",
                  uuid: "bwvi-4675-b2yo-11p4-o3",
                  connId: "sb7q5",
                  dataSource: {
                    id: "1002",
                    type: "dynamicDataSource",
                    baseType: "global.jdbc",
                    catSchemaPredicted: false,
                    sync: false,
                    catalog: "",
                    schema: "HIUSER",
                    connId: "sb7q5",
                    classifier: "db.workflow",
                    datasourceName: "derby2",
                    dsKeyPath:
                      "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j",
                    driverType: "Derby",
                    database: "HIUSER",
                  },
                  dataSourceName: "derby2",
                  category: "table",
                  nameWithConnId: "meeting_details_sb7q5",
                  database: "HIUSER",
                  schema: "HIUSER",
                  selected: true,
                },
                {
                  id: "8a28627d07d04ef096d9935f12e0c7e9",
                  name: "travel_details",
                  data: {
                    id: "1002",
                    type: "dynamicDataSource",
                  },
                  keyPath:
                    "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j/gxh3-5as5-hcyc-o7mh-3d",
                  key: "gxh3-5as5-hcyc-o7mh-3d",
                  alias: "travel_details",
                  uuid: "gxh3-5as5-hcyc-o7mh-3d",
                  connId: "sb7q5",
                  dataSource: {
                    id: "1002",
                    type: "dynamicDataSource",
                    baseType: "global.jdbc",
                    catSchemaPredicted: false,
                    sync: false,
                    catalog: "",
                    schema: "HIUSER",
                    connId: "sb7q5",
                    classifier: "db.workflow",
                    datasourceName: "derby2",
                    dsKeyPath:
                      "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j",
                    driverType: "Derby",
                    database: "HIUSER",
                  },
                  dataSourceName: "derby2",
                  category: "table",
                  nameWithConnId: "travel_details_sb7q5",
                  database: "HIUSER",
                  schema: "HIUSER",
                  selected: true,
                },
              ],
              keyPath:
                "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/pqz5-gd7d-od5l-3a64-2j",
              key: "pqz5-gd7d-od5l-3a64-2j",
              uuid: "pqz5-gd7d-od5l-3a64-2j",
              data: {
                id: "1002",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "derby2",
              fetched: true,
            },
            {
              name: "SYSCS_DIAG",
              children: [],
              keyPath:
                "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/am0v-q7ra-lknz-q44m-60",
              key: "am0v-q7ra-lknz-q44m-60",
              uuid: "am0v-q7ra-lknz-q44m-60",
              data: {
                id: "1002",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "derby2",
            },
            {
              name: "SYSCS_UTIL",
              children: [],
              keyPath:
                "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/1n13-q8l9-6dz8-b3ut-gi",
              key: "1n13-q8l9-6dz8-b3ut-gi",
              uuid: "1n13-q8l9-6dz8-b3ut-gi",
              data: {
                id: "1002",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "derby2",
            },
            {
              name: "SYSIBM",
              children: [],
              keyPath:
                "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/ll4g-mqy2-bm0q-uuf2-4q",
              key: "ll4g-mqy2-bm0q-uuf2-4q",
              uuid: "ll4g-mqy2-bm0q-uuf2-4q",
              data: {
                id: "1002",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "derby2",
            },
            {
              name: "APP",
              children: [],
              keyPath:
                "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/89rd-nrjq-hgma-4y9q-lj",
              key: "89rd-nrjq-hgma-4y9q-lj",
              uuid: "89rd-nrjq-hgma-4y9q-lj",
              data: {
                id: "1002",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "derby2",
            },
            {
              name: "NULLID",
              children: [],
              keyPath:
                "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/n1ln-ihjw-8tt8-h5dt-r7",
              key: "n1ln-ihjw-8tt8-h5dt-r7",
              uuid: "n1ln-ihjw-8tt8-h5dt-r7",
              data: {
                id: "1002",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "derby2",
            },
            {
              name: "SYSPROC",
              children: [],
              keyPath:
                "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/2hbf-fd4v-mflo-frnq-8a",
              key: "2hbf-fd4v-mflo-frnq-8a",
              uuid: "2hbf-fd4v-mflo-frnq-8a",
              data: {
                id: "1002",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "derby2",
            },
            {
              name: "SYS",
              children: [],
              keyPath:
                "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/oewj-kw6z-bm5x-39am-qj",
              key: "oewj-kw6z-bm5x-39am-qj",
              uuid: "oewj-kw6z-bm5x-39am-qj",
              data: {
                id: "1002",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "derby2",
            },
            {
              name: "SYSSTAT",
              children: [],
              keyPath:
                "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc/ca1d-baqf-8nys-ogo7-u6",
              key: "ca1d-baqf-8nys-ogo7-u6",
              uuid: "ca1d-baqf-8nys-ogo7-u6",
              data: {
                id: "1002",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "derby2",
            },
          ],
          driverType: "Derby",
          keyPath: "bhxf-pi2c-r225-poaf-h4/sktx-8ia7-z3ep-z2ln-oc",
          key: "sktx-8ia7-z3ep-z2ln-oc",
          uuid: "sktx-8ia7-z3ep-z2ln-oc",
          fetched: true,
        },
      ],
      key: "bhxf-pi2c-r225-poaf-h4",
      uuid: "bhxf-pi2c-r225-poaf-h4",
      keyPath: "bhxf-pi2c-r225-poaf-h4",
      category: "dsGroup",
      imgUrl: "images/data_sources/defaut_datasource.png",
    },
    {
      name: "Mysql",
      children: [
        {
          data: {
            id: "1001",
            type: "dynamicDataSource",
          },
          dataSourceProvider: "tomcat",
          type: "dynamicDataSource",
          permissionLevel: 5,
          driver: "com.mysql.jdbc.Driver",
          name: "MYSQLDS",
          classifier: "global",
          dataSourceType: "Managed DataSource",
          category: "dataSource",
          children: [],
          driverType: "Mysql",
          keyPath: "z146-48v6-vc54-wxfh-el/apzn-z3qf-leag-ugr1-g1",
          key: "apzn-z3qf-leag-ugr1-g1",
          uuid: "apzn-z3qf-leag-ugr1-g1",
        },
      ],
      key: "z146-48v6-vc54-wxfh-el",
      uuid: "z146-48v6-vc54-wxfh-el",
      keyPath: "z146-48v6-vc54-wxfh-el",
      category: "dsGroup",
      imgUrl: "images/data_sources/defaut_datasource.png",
    },
  ],
  schema: "HIUSER",
  fetchedMetadata: false,
  catSchema: false,
  info: false,
  store: {
    getState: () => {
      return metadaStore;
    },
  },
};
