export const mockData5757 = {
  getStaticDSList: {
    status: 1,
    response: {
      driversList: [
        {
          driver: "dynamicSwitch",
          showInDatasource: "false",
          available: "true",
          parameters: [],
        },
        {
          url: "jdbc:derby:{{database}}",
          driver: "org.apache.derby.jdbc.AutoloadedDriver",
          available: "true",
          parameters: {
            database: "database",
          },
        },
        {
          url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
          driver: "com.mysql.cj.jdbc.Driver",
          available: "true",
          parameters: {
            port: "3306",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
          driver: "com.mysql.jdbc.Driver",
          available: "true",
          parameters: {
            port: "3306",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          available: "true",
          driver: "org.elasticsearch.xpack.sql.jdbc.EsDriver",
        },
        {
          url: "jdbc:awsathena://{{hostName}}",
          driver: "com.simba.athena.jdbc.Driver",
          available: "true",
          parameters: {
            hostName: "localhost",
          },
        },
        {
          url: "jdbc:jtds:sqlserver://{{hostName}}:{{port}}/{{database}}",
          driver: "net.sourceforge.jtds.jdbc.Driver",
          available: "true",
          parameters: {
            port: "1433",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          url: "jdbc:clickhouse://{{hostName}}:{{port}}/{{database}}",
          driver: "ru.yandex.clickhouse.ClickHouseDriver",
          available: "true",
          parameters: {
            port: "8123",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          url: "jdbc:postgresql://{{hostName}}:{{port}}/{{database}}",
          driver: "org.postgresql.Driver",
          available: "true",
          parameters: {
            port: "5432",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          available: "true",
          driver: "com.helical.mongodb.MongoJdbcDriver",
        },
        {
          url: "jdbc:hive2://{{hostName}}:{{port}}/{{database}}",
          driver: "org.apache.hive.jdbc.HiveDriver",
          available: "true",
          parameters: {
            port: "10001",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          url: "jdbc:drill:{{hostName}}:{{port}}",
          driver: "org.apache.drill.jdbc.Driver",
          available: "true",
          parameters: {
            port: "31010",
            hostName: "drillbit=localhost",
          },
        },
        {
          url: "jdbc:informix-sqli://{{hostName}}:{{port}}/{{database}}:delimident=y",
          driver: "com.informix.jdbc.IfxDriver",
          available: "true",
          parameters: {
            port: "1526",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          url: "jdbc:db2://{{hostName}}:{{port}}/{{database}}",
          driver: "com.ibm.db2.jcc.DB2Driver",
          available: "true",
          parameters: {
            port: "50000",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          url: "jdbc:mariadb://{{hostName}}:{{port}}/{{database}}",
          driver: "org.mariadb.jdbc.Driver",
          available: "true",
          parameters: {
            port: "3306",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          url: "jdbc:presto://{{hostName}}:{{port}}",
          driver: "com.facebook.presto.jdbc.PrestoDriver",
          available: "true",
          parameters: {
            port: "8090",
            hostName: "localhost",
          },
        },
        {
          url: "jdbc:databricks://{{hostName}}:{{port}};{{database}}",
          driver: "com.databricks.client.jdbc.Driver",
          available: "true",
          parameters: {
            port: "443",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          available: "true",
          driver: "org.elasticsearch.xpack.sql.jdbc.EsDriver",
        },
        {
          url: "jdbc:postgresql://{{hostName}}:{{port}}/{{database}}",
          driver: "org.postgresql.Driver",
          available: "true",
          parameters: {
            port: "5432",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          url: "jdbc:derby://{{hostName}}:{{port}}/{{database}}",
          driver: "org.apache.derby.jdbc.ClientDriver",
          available: "true",
          parameters: {
            port: "1527",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          url: "jdbc:sqlite:{{database}}",
          driver: "org.sqlite.JDBC",
          available: "true",
          parameters: {
            database: "database",
          },
        },
      ],
      dataSourceTypes: [
        {
          type: "global.jdbc",
          name: "Managed DataSource",
          classifier: "global",
          categoryName: "advanced",
          categoryType: "advanced",
        },
        {
          type: "sql.jdbc",
          name: "Plain Jdbc DataSource",
          classifier: "efwd",
          categoryName: "advanced",
          categoryType: "advanced",
        },
        {
          type: "sql.jdbc.groovy",
          name: "Groovy Plain Jdbc DataSource",
          classifier: "efwd",
          categoryName: "advanced",
          categoryType: "advanced",
        },
        {
          type: "sql.jdbc.groovy.managed",
          name: "Groovy Managed Jdbc DataSource",
          classifier: "efwd",
          categoryName: "advanced",
          categoryType: "advanced",
        },
      ],
      dataSources: [
        {
          driver: "org.elasticsearch.xpack.sql.jdbc.EsDriver",
          databaseDialect: "",
          name: "Elasticsearch",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
        },
        {
          driver: "org.postgresql.Driver",
          databaseDialect: "postgresql",
          name: "Postgresql",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:postgresql://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "5432",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          name: "Dremio",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          driver: "net.sourceforge.jtds.jdbc.Driver",
          databaseDialect: "sqlserver",
          name: "Microsoft Sqlserver(sourceforge)",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:jtds:sqlserver://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "1433",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          name: "Microsoft Sqlserver",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          driver: "org.apache.derby.jdbc.ClientDriver",
          databaseDialect: "derby",
          name: "Derby",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:derby://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "1527",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          driver: "com.ibm.db2.jcc.DB2Driver",
          databaseDialect: "db2",
          name: "IBM Db2",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:db2://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "50000",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          name: "Teradata",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          driver: "com.informix.jdbc.IfxDriver",
          databaseDialect: "informix",
          name: "Informix",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:informix-sqli://{{hostName}}:{{port}}/{{database}}:delimident=y",
          parameters: {
            port: "1526",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          driver: "org.apache.drill.jdbc.Driver",
          databaseDialect: "drill",
          enabledTypes: false,
          name: "Apache Drill",
          categoryName: "Big Data",
          categoryType: "big_data",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:drill:{{hostName}}:{{port}}",
          parameters: {
            port: "31010",
            hostName: "drillbit=localhost",
          },
        },
        {
          name: "Oracle",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          driver: "ru.yandex.clickhouse.ClickHouseDriver",
          databaseDialect: "clickhouse",
          name: "Clickhouse",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:clickhouse://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "8123",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          driver: "com.simba.athena.jdbc.Driver",
          databaseDialect: "athena",
          name: "Athena",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:awsathena://{{hostName}}",
          parameters: {
            hostName: "localhost",
          },
        },
        {
          driver: "com.databricks.client.jdbc.Driver",
          databaseDialect: "databricks",
          name: "Databricks Client",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:databricks://{{hostName}}:{{port}};{{database}}",
          parameters: {
            port: "443",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          name: "Amazon Redshift",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          driver: "com.helical.mongodb.MongoJdbcDriver",
          databaseDialect: "himongo",
          name: "Helical Mongodb",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
        },
        {
          driver: "org.sqlite.JDBC",
          databaseDialect: "sqlite",
          name: "Sqlite",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:sqlite:{{database}}",
          parameters: {
            database: "database",
          },
        },
        {
          driver: "dynamicSwitch",
          databaseDialect: "",
          name: "DynamicSwitch",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
        },
        {
          name: "Amazon Dynamodb",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          driver: "com.facebook.presto.jdbc.PrestoDriver",
          databaseDialect: "presto",
          name: "Presto",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:presto://{{hostName}}:{{port}}",
          parameters: {
            port: "8090",
            hostName: "localhost",
          },
        },
        {
          driver: "org.apache.derby.jdbc.AutoloadedDriver",
          databaseDialect: "derby",
          name: "Derby",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:derby:{{database}}",
          parameters: {
            database: "database",
          },
        },
        {
          driver: "com.mysql.cj.jdbc.Driver",
          databaseDialect: "mysql",
          name: "Mysql Cj",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "3306",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          name: "Ξ Add Driver Ξ",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          driver: "org.mariadb.jdbc.Driver",
          databaseDialect: "mysql",
          name: "Mariadb",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:mariadb://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "3306",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          driver: "org.apache.hive.jdbc.HiveDriver",
          databaseDialect: "spark",
          name: "Hive",
          categoryName: "Big Data",
          categoryType: "big_data",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:hive2://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "10001",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          name: "Access",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          driver: "com.mysql.jdbc.Driver",
          databaseDialect: "mysql",
          name: "Mysql",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "3306",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          name: "Google Bigquery",
          categoryType: "supported",
          categoryName: "Supported",
        },
      ],
    },
  },
  getGetListDS: {
    dataSources: [
      {
        permissionLevel: 5,
        driver: null,
        name: "Groovy 1",
        classifier: "efwd",
        type: "sql.jdbc.groovy.managed",
        data: {
          dir: "Gagan",
          driverName: null,
          type: "sql.jdbc.groovy.managed",
          id: 1,
          userName: null,
          password: null,
          condition:
            'import groovy.sql.Sql;\n      import net.sf.json.JSONObject;\n      import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n      public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        if (userName.equals("hiadmin")) {\n          responseJson.put("globalId", 1);\n        }\n      \n        if (userName.equals("hiuser")) {\n          responseJson.put("globalId", 3);\n        }\n      \n        if (userName.equals("test")) {\n          responseJson.put("globalId", 4);\n        }\n      \n        responseJson.put("type", "global.jdbc");\n      \n        //throw new RuntimeException("This is a test exception" +responseJson);\n        return responseJson;\n      }',
          jdbcUrl: null,
        },
        dataSourceType: "",
      },
      {
        permissionLevel: 5,
        driver: "org.apache.derby.jdbc.AutoloadedDriver",
        name: "samplegroovy",
        classifier: "efwd",
        type: "sql.jdbc.groovy",
        data: {
          dir: "1somen",
          driverName: "org.apache.derby.jdbc.AutoloadedDriver",
          type: "sql.jdbc.groovy",
          id: 301,
          userName: "hiuser",
          password: "hiuser",
          condition:
            'import net.sf.json.JSONObject;\n    import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n    public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n      if(userName=="hiuser"){\n            responseJson.put("url", "jdbc:derby:/home/helical/Performance/hi/db/hiee");\n         responseJson.put("driver", "org.apache.derby.jdbc.AutoloadedDriver");\n      }\n       \n        return responseJson;\n    }',
          jdbcUrl:
            "jdbc:derby:/home/helical/Performance/hi/db/SampleTravelData",
        },
        dataSourceType: "",
      },
      {
        data: {
          id: "1",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.apache.derby.jdbc.AutoloadedDriver",
        name: "SampleTravelDataDerby",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
      {
        data: {
          id: "1000",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.apache.derby.jdbc.AutoloadedDriver",
        name: "hiee",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
      {
        data: {
          id: "1001",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.postgresql.Driver",
        name: "booking",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
      {
        data: {
          id: "1101",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.apache.derby.jdbc.AutoloadedDriver",
        name: "derby2",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
      {
        data: {
          id: "1201",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.sqlite.JDBC",
        name: "SampleTravelData",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
      {
        data: {
          id: "1302",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.sqlite.JDBC",
        name: "Sqlite",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
    ],
  },
  getMetaDataTables: {
    status: 1,
    response: {
      classifier: "db.generic",
      name: "HIUSER",
      dataSource: {
        sync: false,
        id: "1",
        connectionDatabaseId: "32d54648-5680-4d63-a014-38ce1412b13c",
        catSchemaPredicted: false,
        catalog: "",
        schema: "HIUSER",
        type: "dynamicDataSource",
        baseType: "global.jdbc",
      },
      uniqueId: "Metadata_duplicate",
      tables: {
        dimdate: {
          id: "4ac5d9f68b58bd7c0d179146e46795be",
          alias: "dimdate",
          columns: {
            dim_id: {
              alias: "dim_id",
              fullyQualifiedColumn: "dimdate.dim_id",
              columnId: "26580d9f-f17e-4f69-9b95-2005885b4e47",
              defaultFunction: "db.generic.aggregate.sum",
              type: {
                "java.lang.Integer": "numeric",
              },
            },
            fiscal_year: {
              alias: "fiscal_year",
              fullyQualifiedColumn: "dimdate.fiscal_year",
              columnId: "264ce539-9742-40c6-9fa9-877ec2376075",
              defaultFunction: "db.generic.groupBy.group",
              type: {
                "java.sql.Date": "date",
              },
            },
            modified_date: {
              alias: "modified_date",
              fullyQualifiedColumn: "dimdate.modified_date",
              columnId: "a9eed807-40e0-4b8a-a6df-cb73fa4ac89f",
              defaultFunction: "db.generic.groupBy.group",
              type: {
                "java.sql.Timestamp": "dateTime",
              },
            },
            date_key: {
              alias: "date_key",
              fullyQualifiedColumn: "dimdate.date_key",
              columnId: "4e530387-a8ac-43a0-b1c2-8ad5273e7076",
              defaultFunction: "db.generic.groupBy.group",
              type: {
                "java.lang.String": "text",
              },
            },
            day_number: {
              alias: "day_number",
              fullyQualifiedColumn: "dimdate.day_number",
              columnId: "6f3c5985-1679-429d-b3cd-58299695c563",
              defaultFunction: "db.generic.groupBy.group",
              type: {
                "java.lang.String": "text",
              },
            },
            fiscal_month_name: {
              alias: "fiscal_month_name",
              fullyQualifiedColumn: "dimdate.fiscal_month_name",
              columnId: "446248b2-fac5-4127-b9d1-a0537da5f884",
              defaultFunction: "db.generic.groupBy.group",
              type: {
                "java.lang.String": "text",
              },
            },
            fiscal_month_label: {
              alias: "fiscal_month_label",
              fullyQualifiedColumn: "dimdate.fiscal_month_label",
              columnId: "30f5a138-bb48-43a7-bcaf-61b4375a2b66",
              defaultFunction: "db.generic.groupBy.group",
              type: {
                "java.lang.String": "text",
              },
            },
            created_date: {
              alias: "created_date",
              fullyQualifiedColumn: "dimdate.created_date",
              columnId: "4bb4acf4-d846-46eb-a6fd-e4ad29c8f7d3",
              defaultFunction: "db.generic.groupBy.group",
              type: {
                "java.lang.String": "text",
              },
            },
            created_time: {
              alias: "created_time",
              fullyQualifiedColumn: "dimdate.created_time",
              columnId: "ea5c1769-1d26-4715-9cda-7df52625ac5e",
              defaultFunction: "db.generic.groupBy.group",
              type: {
                "java.lang.String": "text",
              },
            },
            rating: {
              alias: "rating",
              fullyQualifiedColumn: "dimdate.rating",
              columnId: "c1a7f367-4c1e-4241-9c50-3640c0e3fdfc",
              defaultFunction: "db.generic.groupBy.group",
              type: {
                "java.lang.String": "text",
              },
            },
            modified_date_1: {
              alias: "modified_date_1",
              duplicate: true,
              originalName: "modified_date",
              fullyQualifiedColumn: "dimdate.modified_date_1",
              columnId: "0070dec1-2871-4881-a21e-357dd3b84f7d",
              defaultFunction: "db.generic.groupBy.group",
              type: {
                "java.sql.Timestamp": "dateTime",
              },
            },
          },
          name: "dimdate",
        },
        employee_details: {
          id: "4e1fd245f4d13b77be423a43f01d80b2",
          alias: "employee_details",
          columns: {
            employee_id: {
              alias: "employee_id",
              fullyQualifiedColumn: "employee_details.employee_id",
              columnId: "36fff8a1-a089-4d5a-b17e-d6c7792924de",
              defaultFunction: "db.generic.aggregate.sum",
              type: {
                "java.lang.Integer": "numeric",
              },
            },
            employee_name: {
              alias: "employee_name",
              fullyQualifiedColumn: "employee_details.employee_name",
              columnId: "1bebce58-a73c-40a5-a7df-8b7c4ae9dc2e",
              defaultFunction: "db.generic.groupBy.group",
              type: {
                "java.lang.String": "text",
              },
            },
            age: {
              alias: "age",
              fullyQualifiedColumn: "employee_details.age",
              columnId: "5d9fbf4e-fcd7-4b38-a173-ee1bd32cb9ab",
              defaultFunction: "db.generic.aggregate.sum",
              type: {
                "java.lang.Integer": "numeric",
              },
            },
            address: {
              alias: "address",
              fullyQualifiedColumn: "employee_details.address",
              columnId: "819f727b-bc8a-4c84-8c80-93bf760cb306",
              defaultFunction: "db.generic.groupBy.group",
              type: {
                "java.lang.String": "text",
              },
            },
            address_1: {
              alias: "address_1",
              duplicate: true,
              originalName: "address",
              fullyQualifiedColumn: "employee_details.address_1",
              columnId: "cb8edb08-6d75-4760-95e6-80897b9f1beb",
              defaultFunction: "db.generic.groupBy.group",
              type: {
                "java.lang.String": "text",
              },
            },
          },
          name: "employee_details",
        },
      },
      sets: [["employee_details"], ["dimdate"]],
      joins: [],
      metadataName: "Metadata_duplicate",
      metadataDir: "sibtain",
    },
  },
  mockdataFetchSchemaFetchCatalog: {
    status: 1,
    response: {
      classifier: "db.workflow",
      metadata: {
        catalogs: [
          {
            name: "Null",
            schemas: [
              {
                name: "SQLJ",
              },
              {
                name: "SYSFUN",
              },
              {
                name: "SYSCAT",
              },
              {
                name: "HIUSER",
              },
              {
                name: "SYSCS_DIAG",
              },
              {
                name: "SYSCS_UTIL",
              },
              {
                name: "SYSIBM",
              },
              {
                name: "APP",
              },
              {
                name: "NULLID",
              },
              {
                name: "SYSPROC",
              },
              {
                name: "SYS",
              },
              {
                name: "SYSSTAT",
              },
            ],
          },
        ],
      },
    },
    position: "0",
    maxSize: "1",
    totalPage: 1,
    resultPage: 1,
  },
  mockdataFetchTables: {
    status: 1,
    response: {
      classifier: "db.workflow",
      metadata: {
        catalogs: [
          {
            name: "Null",
            schemas: [
              {
                name: "HIUSER",
                tables: [
                  {
                    id: "be534112989b616b194bc59c2fb25a42",
                    name: "geo_cordinates",
                  },
                  {
                    id: "9645c648a1c0dbeec1287aaf1e996db3",
                    name: "meeting_details",
                  },
                  {
                    id: "4e1fd245f4d13b77be423a43f01d80b2",
                    name: "employee_details",
                  },
                  { id: "4ac5d9f68b58bd7c0d179146e46795be", name: "dimdate" },
                  {
                    id: "8a28627d07d04ef096d9935f12e0c7e9",
                    name: "travel_details",
                  },
                ],
              },
            ],
          },
        ],
        dataSource: {
          id: "1",
          type: "dynamicDataSource",
          baseType: "global.jdbc",
          catSchemaPredicted: false,
          sync: false,
          catalog: "",
          schema: "HIUSER",
        },
        name: "HIUSER",
      },
    },
    position: "0",
    maxSize: "1",
    totalPage: 1,
    resultPage: 1,
  },
};
