export const mockData5822 = {
  getStaticDSList: {
    status: 1,
    response: {
      driversList: [
        {
          driver: "dynamicSwitch",
          showInDatasource: "false",
          available: "true",
          parameters: [],
        },
        {
          url: "jdbc:derby:{{database}}",
          driver: "org.apache.derby.jdbc.AutoloadedDriver",
          available: "true",
          parameters: { database: "database" },
        },
        {
          url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
          driver: "com.mysql.cj.jdbc.Driver",
          available: "true",
          parameters: {
            port: "3306",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
          driver: "com.mysql.jdbc.Driver",
          available: "true",
          parameters: {
            port: "3306",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          available: "true",
          driver: "org.elasticsearch.xpack.sql.jdbc.EsDriver",
        },
        {
          url: "jdbc:awsathena://{{hostName}}",
          driver: "com.simba.athena.jdbc.Driver",
          available: "true",
          parameters: { hostName: "localhost" },
        },
        {
          url: "jdbc:jtds:sqlserver://{{hostName}}:{{port}}/{{database}}",
          driver: "net.sourceforge.jtds.jdbc.Driver",
          available: "true",
          parameters: {
            port: "1433",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          url: "jdbc:clickhouse://{{hostName}}:{{port}}/{{database}}",
          driver: "ru.yandex.clickhouse.ClickHouseDriver",
          available: "true",
          parameters: {
            port: "8123",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          url: "jdbc:postgresql://{{hostName}}:{{port}}/{{database}}",
          driver: "org.postgresql.Driver",
          available: "true",
          parameters: {
            port: "5432",
            hostName: "localhost",
            database: "database",
          },
        },
        { available: "true", driver: "com.helical.mongodb.MongoJdbcDriver" },
        {
          url: "jdbc:hive2://{{hostName}}:{{port}}/{{database}}",
          driver: "org.apache.hive.jdbc.HiveDriver",
          available: "true",
          parameters: {
            port: "10001",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          url: "jdbc:drill:{{hostName}}:{{port}}",
          driver: "org.apache.drill.jdbc.Driver",
          available: "true",
          parameters: { port: "31010", hostName: "drillbit=localhost" },
        },
        {
          url: "jdbc:informix-sqli://{{hostName}}:{{port}}/{{database}}:delimident=y",
          driver: "com.informix.jdbc.IfxDriver",
          available: "true",
          parameters: {
            port: "1526",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          url: "jdbc:db2://{{hostName}}:{{port}}/{{database}}",
          driver: "com.ibm.db2.jcc.DB2Driver",
          available: "true",
          parameters: {
            port: "50000",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          url: "jdbc:mariadb://{{hostName}}:{{port}}/{{database}}",
          driver: "org.mariadb.jdbc.Driver",
          available: "true",
          parameters: {
            port: "3306",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          url: "jdbc:presto://{{hostName}}:{{port}}",
          driver: "com.facebook.presto.jdbc.PrestoDriver",
          available: "true",
          parameters: { port: "8090", hostName: "localhost" },
        },
        {
          url: "jdbc:databricks://{{hostName}}:{{port}};{{database}}",
          driver: "com.databricks.client.jdbc.Driver",
          available: "true",
          parameters: {
            port: "443",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          available: "true",
          driver: "org.elasticsearch.xpack.sql.jdbc.EsDriver",
        },
        {
          url: "jdbc:postgresql://{{hostName}}:{{port}}/{{database}}",
          driver: "org.postgresql.Driver",
          available: "true",
          parameters: {
            port: "5432",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          url: "jdbc:derby://{{hostName}}:{{port}}/{{database}}",
          driver: "org.apache.derby.jdbc.ClientDriver",
          available: "true",
          parameters: {
            port: "1527",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          url: "jdbc:sqlite:{{database}}",
          driver: "org.sqlite.JDBC",
          available: "true",
          parameters: { database: "database" },
        },
      ],
      dataSourceTypes: [
        {
          type: "global.jdbc",
          name: "Managed DataSource",
          classifier: "global",
          categoryName: "advanced",
          categoryType: "advanced",
        },
        {
          type: "sql.jdbc",
          name: "Plain Jdbc DataSource",
          classifier: "efwd",
          categoryName: "advanced",
          categoryType: "advanced",
        },
        {
          type: "sql.jdbc.groovy",
          name: "Groovy Plain Jdbc DataSource",
          classifier: "efwd",
          categoryName: "advanced",
          categoryType: "advanced",
        },
        {
          type: "sql.jdbc.groovy.managed",
          name: "Groovy Managed Jdbc DataSource",
          classifier: "efwd",
          categoryName: "advanced",
          categoryType: "advanced",
        },
      ],
      dataSources: [
        {
          driver: "org.elasticsearch.xpack.sql.jdbc.EsDriver",
          databaseDialect: "",
          name: "Elasticsearch",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
        },
        {
          driver: "org.postgresql.Driver",
          databaseDialect: "postgresql",
          name: "Postgresql",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:postgresql://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "5432",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          name: "Dremio",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          driver: "net.sourceforge.jtds.jdbc.Driver",
          databaseDialect: "sqlserver",
          name: "Microsoft Sqlserver(sourceforge)",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:jtds:sqlserver://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "1433",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          name: "Microsoft Sqlserver",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          driver: "org.apache.derby.jdbc.ClientDriver",
          databaseDialect: "derby",
          name: "Derby",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:derby://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "1527",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          driver: "com.ibm.db2.jcc.DB2Driver",
          databaseDialect: "db2",
          name: "IBM Db2",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:db2://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "50000",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          name: "Teradata",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          driver: "com.informix.jdbc.IfxDriver",
          databaseDialect: "informix",
          name: "Informix",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:informix-sqli://{{hostName}}:{{port}}/{{database}}:delimident=y",
          parameters: {
            port: "1526",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          driver: "org.apache.drill.jdbc.Driver",
          databaseDialect: "drill",
          enabledTypes: false,
          name: "Apache Drill",
          categoryName: "Big Data",
          categoryType: "big_data",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:drill:{{hostName}}:{{port}}",
          parameters: { port: "31010", hostName: "drillbit=localhost" },
        },
        {
          name: "Oracle",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          driver: "ru.yandex.clickhouse.ClickHouseDriver",
          databaseDialect: "clickhouse",
          name: "Clickhouse",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:clickhouse://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "8123",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          driver: "com.simba.athena.jdbc.Driver",
          databaseDialect: "athena",
          name: "Athena",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:awsathena://{{hostName}}",
          parameters: { hostName: "localhost" },
        },
        {
          driver: "com.databricks.client.jdbc.Driver",
          databaseDialect: "databricks",
          name: "Databricks Client",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:databricks://{{hostName}}:{{port}};{{database}}",
          parameters: {
            port: "443",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          name: "Amazon Redshift",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          driver: "com.helical.mongodb.MongoJdbcDriver",
          databaseDialect: "himongo",
          name: "Helical Mongodb",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
        },
        {
          driver: "org.sqlite.JDBC",
          databaseDialect: "sqlite",
          name: "Sqlite",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:sqlite:{{database}}",
          parameters: { database: "database" },
        },
        {
          driver: "dynamicSwitch",
          databaseDialect: "",
          name: "DynamicSwitch",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
        },
        {
          name: "Amazon Dynamodb",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          driver: "com.facebook.presto.jdbc.PrestoDriver",
          databaseDialect: "presto",
          name: "Presto",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:presto://{{hostName}}:{{port}}",
          parameters: { port: "8090", hostName: "localhost" },
        },
        {
          driver: "org.apache.derby.jdbc.AutoloadedDriver",
          databaseDialect: "derby",
          name: "Derby",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:derby:{{database}}",
          parameters: { database: "database" },
        },
        {
          driver: "com.mysql.cj.jdbc.Driver",
          databaseDialect: "mysql",
          name: "Mysql Cj",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "3306",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          name: "Ξ Add Driver Ξ",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          driver: "org.mariadb.jdbc.Driver",
          databaseDialect: "mysql",
          name: "Mariadb",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:mariadb://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "3306",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          driver: "org.apache.hive.jdbc.HiveDriver",
          databaseDialect: "spark",
          name: "Hive",
          categoryName: "Big Data",
          categoryType: "big_data",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:hive2://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "10001",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          name: "Access",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          driver: "com.mysql.jdbc.Driver",
          databaseDialect: "mysql",
          name: "Mysql",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "3306",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          name: "Google Bigquery",
          categoryType: "supported",
          categoryName: "Supported",
        },
      ],
    },
  },
  getGetListDS: {
    dataSources: [
      {
        permissionLevel: 5,
        driver: null,
        name: "Groovy 1",
        classifier: "efwd",
        type: "sql.jdbc.groovy.managed",
        data: {
          dir: "Gagan",
          driverName: null,
          type: "sql.jdbc.groovy.managed",
          id: 1,
          userName: null,
          password: null,
          condition:
            'import groovy.sql.Sql;\n      import net.sf.json.JSONObject;\n      import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n      public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        if (userName.equals("hiadmin")) {\n          responseJson.put("globalId", 1);\n        }\n      \n        if (userName.equals("hiuser")) {\n          responseJson.put("globalId", 3);\n        }\n      \n        if (userName.equals("test")) {\n          responseJson.put("globalId", 4);\n        }\n      \n        responseJson.put("type", "global.jdbc");\n      \n        //throw new RuntimeException("This is a test exception" +responseJson);\n        return responseJson;\n      }',
          jdbcUrl: null,
        },
        dataSourceType: "",
      },
      {
        data: { id: "1", type: "dynamicDataSource" },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.apache.derby.jdbc.AutoloadedDriver",
        name: "SampleTravelDataDerby",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
      {
        data: { id: "1000", type: "dynamicDataSource" },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.apache.derby.jdbc.AutoloadedDriver",
        name: "hiee",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
      {
        data: { id: "1001", type: "dynamicDataSource" },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.postgresql.Driver",
        name: "booking",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
      {
        data: { id: "1101", type: "dynamicDataSource" },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.apache.derby.jdbc.AutoloadedDriver",
        name: "derby2",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
      {
        data: { id: "1201", type: "dynamicDataSource" },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.sqlite.JDBC",
        name: "SampleTravelData",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
      {
        data: { id: "1302", type: "dynamicDataSource" },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.sqlite.JDBC",
        name: "Sqlite",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
    ],
  },
  getMetaDataTables: {
    status: 1,
    response: {
      classifier: "db.generic",
      name: "HIUSER",
      dataSource: {
        sync: false,
        id: "1",
        connectionDatabaseId: "96d14ec1-643a-43e6-913c-5ee6dc9e2c4f",
        catSchemaPredicted: false,
        catalog: "",
        schema: "HIUSER",
        type: "dynamicDataSource",
        baseType: "global.jdbc",
      },
      uniqueId: "view_5822",
      tables: {
        employee_details: {
          id: "4e1fd245f4d13b77be423a43f01d80b2",
          alias: "employee_details",
          columns: {
            employee_id: {
              alias: "employee_id",
              fullyQualifiedColumn: "employee_details.employee_id",
              columnId: "c3467f5a-113c-4499-9618-8785df127187",
              defaultFunction: "db.generic.aggregate.sum",
              type: { "java.lang.Integer": "numeric" },
            },
            employee_name: {
              alias: "employee_name",
              fullyQualifiedColumn: "employee_details.employee_name",
              columnId: "b8a4bb14-4e14-4278-8f94-47217c631c41",
              defaultFunction: "db.generic.groupBy.group",
              type: { "java.lang.String": "text" },
            },
            age: {
              alias: "age",
              fullyQualifiedColumn: "employee_details.age",
              columnId: "70f9e392-9fed-4ce3-bbaa-c9c408fcee0d",
              defaultFunction: "db.generic.aggregate.sum",
              type: { "java.lang.Integer": "numeric" },
            },
            address: {
              alias: "address",
              fullyQualifiedColumn: "employee_details.address",
              columnId: "700500e9-c1dc-46cd-86e7-cda8f8e3abaa",
              defaultFunction: "db.generic.groupBy.group",
              type: { "java.lang.String": "text" },
            },
          },
          name: "employee_details",
        },
        "View 2": {
          type: "view",
          id: "0af43341-dc5c-4ea7-afad-7a3b3d15505f",
          alias: "View 2",
          columns: {
            dim_id: {
              alias: "dim_id",
              fullyQualifiedColumn: "View 2.dim_id",
              columnId: "5f33b51c-e97d-48df-b61e-99b67a0b9199",
              defaultFunction: "db.generic.aggregate.sum",
              type: { "java.lang.Float": "numeric" },
            },
            fiscal_year: {
              alias: "fiscal_year",
              fullyQualifiedColumn: "View 2.fiscal_year",
              columnId: "8f3d1cc1-866d-4be2-9a0f-50741735cffe",
              defaultFunction: "db.generic.groupBy.group",
              type: { "java.sql.Date": "date" },
            },
            modified_date: {
              alias: "modified_date",
              fullyQualifiedColumn: "View 2.modified_date",
              columnId: "3e71a4d1-ce2b-4c2c-95b3-93d44769f5e4",
              defaultFunction: "db.generic.groupBy.group",
              type: { "java.sql.Timestamp": "dateTime" },
            },
            date_key: {
              alias: "date_key",
              fullyQualifiedColumn: "View 2.date_key",
              columnId: "6676938c-167c-4e55-84ac-cc5cd1d24573",
              defaultFunction: "db.generic.groupBy.group",
              type: { "java.lang.String": "text" },
            },
            day_number: {
              alias: "day_number",
              fullyQualifiedColumn: "View 2.day_number",
              columnId: "8dfe6e67-3f2c-4902-9b25-98651e443654",
              defaultFunction: "db.generic.groupBy.group",
              type: { "java.lang.String": "text" },
            },
            fiscal_month_name: {
              alias: "fiscal_month_name",
              fullyQualifiedColumn: "View 2.fiscal_month_name",
              columnId: "28aae191-1584-4adb-9ea1-afd75078826b",
              defaultFunction: "db.generic.groupBy.group",
              type: { "java.lang.String": "text" },
            },
            fiscal_month_label: {
              alias: "fiscal_month_label",
              fullyQualifiedColumn: "View 2.fiscal_month_label",
              columnId: "c7f23d90-3080-4b20-ab32-697dab33d2ab",
              defaultFunction: "db.generic.groupBy.group",
              type: { "java.lang.String": "text" },
            },
            created_date: {
              alias: "created_date",
              fullyQualifiedColumn: "View 2.created_date",
              columnId: "11f21118-9449-4af2-9acd-7567b1f3b35d",
              defaultFunction: "db.generic.groupBy.group",
              type: { "java.lang.String": "text" },
            },
            created_time: {
              alias: "created_time",
              fullyQualifiedColumn: "View 2.created_time",
              columnId: "8fb944ce-c76a-48ac-8f50-e418e3621651",
              defaultFunction: "db.generic.groupBy.group",
              type: { "java.lang.String": "text" },
            },
            rating: {
              alias: "rating",
              fullyQualifiedColumn: "View 2.rating",
              columnId: "5ff7d935-de52-44ba-a107-01ce5788cf9d",
              defaultFunction: "db.generic.groupBy.group",
              type: { "java.lang.String": "text" },
            },
          },
          name: "View 2",
        },
      },
      sets: [["employee_details"], ["View 2"]],
      joins: [],
      crossJoins: [],
      metadataName: "view-5822",
      metadataDir: "Sibtain",
    },
  },
  mockdataFetchSchemaFetchCatalog: {
    status: 1,
    response: {
      classifier: "db.workflow",
      metadata: {
        catalogs: [
          {
            name: "Null",
            schemas: [
              { name: "SQLJ" },
              { name: "SYSFUN" },
              { name: "SYSCAT" },
              { name: "HIUSER" },
              { name: "SYSCS_DIAG" },
              { name: "SYSCS_UTIL" },
              { name: "SYSIBM" },
              { name: "APP" },
              { name: "NULLID" },
              { name: "SYSPROC" },
              { name: "SYS" },
              { name: "SYSSTAT" },
            ],
          },
        ],
      },
    },
    position: "0",
    maxSize: "1",
    totalPage: 1,
    resultPage: 1,
  },
  mockdataFetchTables: {
    status: 1,
    response: {
      classifier: "db.workflow",
      metadata: {
        catalogs: [
          {
            name: "Null",
            schemas: [
              {
                name: "HIUSER",
                tables: [
                  {
                    id: "be534112989b616b194bc59c2fb25a42",
                    name: "geo_cordinates",
                  },
                  {
                    id: "9645c648a1c0dbeec1287aaf1e996db3",
                    name: "meeting_details",
                  },
                  {
                    id: "4e1fd245f4d13b77be423a43f01d80b2",
                    name: "employee_details",
                  },
                  { id: "4ac5d9f68b58bd7c0d179146e46795be", name: "dimdate" },
                  {
                    id: "8a28627d07d04ef096d9935f12e0c7e9",
                    name: "travel_details",
                  },
                ],
              },
            ],
          },
        ],
        dataSource: {
          id: "1",
          type: "dynamicDataSource",
          baseType: "global.jdbc",
          catSchemaPredicted: false,
          sync: false,
          catalog: "",
          schema: "HIUSER",
        },
        name: "HIUSER",
      },
    },
    position: "0",
    maxSize: "1",
    totalPage: 1,
    resultPage: 1,
  },
};
