export const mock_data = {
  itemsData: [
    {
      key: "show",
      label: "Show",
      value: true,
      elementType: "Switch",
      groupId: "title",
    },
    {
      key: "value",
      label: "Text",
      placeHolder: "Enter title",
      value: "",
      elementType: "Input",
      groupId: "title",
    },
    {
      key: "padding",
      label: "Padding",
      value: 0,
      elementType: "InputNumber",
      groupId: "title",
    },
    {
      key: "fontSize",
      label: "Font Size",
      tooltip: "Font Size in px",
      value: 32,
      elementType: "InputNumber",
      groupId: "title",
    },
    {
      key: "fontColor",
      label: "Font Color",
      value: {
        a: 1,
        b: 0,
        g: 0,
        r: 0,
      },
      elementType: "ColorPicker",
      groupId: "title",
    },
    {
      key: "alignment",
      label: "Alignment",
      value: "center",
      elementType: "Select",
      groupId: "title",
      values: [
        {
          key: "left",
          label: "Left",
        },
        {
          key: "right",
          label: "Right",
        },
        {
          key: "center",
          label: "Center",
        },
      ],
    },
    {
      key: "position",
      label: "Position",
      value: "top",
      elementType: "Select",
      groupId: "title",
      values: [
        {
          key: "top",
          label: "Top",
        },
        {
          key: "bottom",
          label: "Bottom",
        },
      ],
    },
    {
      key: "show",
      label: "Show",
      value: false,
      elementType: "Switch",
      groupId: "subTitle",
    },
    {
      key: "value",
      label: "Text",
      placeHolder: "Enter sub title",
      value: "",
      elementType: "Input",
      groupId: "subTitle",
    },
    {
      key: "padding",
      label: "Padding",
      value: 0,
      elementType: "InputNumber",
      groupId: "subTitle",
    },
    {
      key: "fontSize",
      label: "Font Size",
      tooltip: "Font Size in px",
      value: 24,
      elementType: "InputNumber",
      groupId: "subTitle",
    },
    {
      key: "fontColor",
      label: "Font Color",
      value: {
        a: 1,
        b: 0,
        g: 0,
        r: 0,
      },
      elementType: "ColorPicker",
      groupId: "subTitle",
    },
    {
      key: "alignment",
      label: "Alignment",
      value: "center",
      elementType: "Select",
      groupId: "subTitle",
      values: [
        {
          key: "left",
          label: "Left",
        },
        {
          key: "right",
          label: "Right",
        },
        {
          key: "center",
          label: "Center",
        },
      ],
    },
    {
      key: "position",
      label: "Position",
      value: "top",
      elementType: "Select",
      groupId: "subTitle",
      values: [
        {
          key: "top",
          label: "Top",
        },
        {
          key: "bottom",
          label: "Bottom",
        },
      ],
    },
    {
      key: "isCacheEnabled",
      label: "Cache",
      value: false,
      elementType: "Switch",
      groupId: "cache",
    },
    {
      key: "interval",
      label: "Interval",
      value: "00:00:01",
      elementType: "TimePicker",
      defaultValue: "00:00:01",
      showNow: false,
      groupId: "cache",
      tooltip:
        "The report will be refreshed after predefined interval(HH:MM:SS).",
    },
    {
      key: "field",
      label: "Field",
      value: "",
      elementType: "Select",
      groupId: "format",
      values: [
        {
          key: "ee78559a-c99c-40d0-886d-18346527d26f",
          label: "sum_dim_id",
        },
        {
          key: "59eb7057-2c94-4594-812d-9e4353ec1278",
          label: "modified_date",
        },
      ],
    },
    {
      key: "apply",
      label: "Apply",
      tooltip: "Apply On",
      value: [],
      elementType: "Select",
      groupId: "format",
      multiSelect: true,
      values: [
        {
          key: "axis",
          label: "Axis",
        },
        {
          key: "pane",
          label: "Pane",
        },
        {
          key: "tooltip",
          label: "Tooltip",
        },
        {
          key: "label",
          label: "Label",
        },
        {
          key: "actions",
          label: "Actions",
        },
      ],
    },
    {
      key: "formatDatatype",
      label: "Data Type",
      tooltip: "Data Type",
      value: "",
      elementType: "Select",
      groupId: "format",
      disabled: true,
      values: [
        {
          key: "numeric",
          label: "Number",
        },
        {
          key: "date",
          label: "Date",
        },
        {
          key: "time",
          label: "Time",
        },
        {
          key: "dateTime",
          label: "DateTime",
        },
      ],
    },
    {
      key: "formatColorField",
      label: "Field",
      value: "ee78559a-c99c-40d0-886d-18346527d26f",
      elementType: "Select",
      groupId: "color",
      values: [
        {
          key: "ee78559a-c99c-40d0-886d-18346527d26f",
          label: "sum_dim_id",
        },
        {
          key: "59eb7057-2c94-4594-812d-9e4353ec1278",
          label: "modified_date",
        },
      ],
    },
    {
      key: "formatColorStyle",
      label: "Format Style",
      value: "fieldValue",
      elementType: "Select",
      groupId: "color",
      values: [
        {
          key: "gradient",
          label: "Gradient",
        },
        {
          key: "fieldValue",
          label: "Field Value",
        },
      ],
    },
    {
      key: "barType",
      label: "Type",
      value: "stacked",
      elementType: "Select",
      groupId: "bar",
      values: [
        {
          key: "stacked",
          label: "Stacked",
        },
        {
          key: "grouped",
          label: "Grouped",
        },
        {
          key: "percentage",
          label: "Percentage",
        },
      ],
    },
    {
      key: "showRadial",
      label: "Show Radial",
      value: false,
      elementType: "Switch",
      groupId: "radial",
    },
    {
      key: "legendPosition",
      label: "Position",
      value: "right",
      elementType: "Select",
      groupId: "legend",
      values: [
        {
          key: "top",
          label: "Top",
        },
        {
          key: "right",
          label: "Right",
        },
        {
          key: "left",
          label: "Left",
        },
        {
          key: "bottom",
          label: "Bottom",
        },
        {
          key: "none",
          label: "None",
        },
      ],
    },
    {
      key: "applyRangeOn",
      label: "Apply On",
      value: "",
      elementType: "Select",
      groupId: "axisRange",
      values: [
        {
          key: "ee78559a-c99c-40d0-886d-18346527d26f",
          label: "sum_dim_id",
        },
        {
          key: "59eb7057-2c94-4594-812d-9e4353ec1278",
          label: "modified_date",
        },
      ],
    },
    {
      key: "defaultColor",
      label: "Default",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "showAll",
      label: "Show all",
      value: true,
      elementType: "Switch",
      groupId: "color",
    },
    {
      key: "1",
      label: "1",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "2",
      label: "2",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "3",
      label: "3",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "4",
      label: "4",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "5",
      label: "5",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "6",
      label: "6",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "7",
      label: "7",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "8",
      label: "8",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "9",
      label: "9",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "10",
      label: "10",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "11",
      label: "11",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "12",
      label: "12",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "13",
      label: "13",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "14",
      label: "14",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "15",
      label: "15",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "16",
      label: "16",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "17",
      label: "17",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "18",
      label: "18",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "19",
      label: "19",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "20",
      label: "20",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "21",
      label: "21",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "22",
      label: "22",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "23",
      label: "23",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "24",
      label: "24",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "25",
      label: "25",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "26",
      label: "26",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "27",
      label: "27",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "28",
      label: "28",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "29",
      label: "29",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "30",
      label: "30",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "31",
      label: "31",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "32",
      label: "32",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "33",
      label: "33",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "34",
      label: "34",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "35",
      label: "35",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "36",
      label: "36",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "37",
      label: "37",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "38",
      label: "38",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "39",
      label: "39",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "40",
      label: "40",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "41",
      label: "41",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "42",
      label: "42",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "43",
      label: "43",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "44",
      label: "44",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "45",
      label: "45",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "46",
      label: "46",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "47",
      label: "47",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "48",
      label: "48",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "49",
      label: "49",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "50",
      label: "50",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "51",
      label: "51",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "52",
      label: "52",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "53",
      label: "53",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "54",
      label: "54",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "55",
      label: "55",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "56",
      label: "56",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "57",
      label: "57",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "58",
      label: "58",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "59",
      label: "59",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "60",
      label: "60",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "61",
      label: "61",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "62",
      label: "62",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "63",
      label: "63",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "64",
      label: "64",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "65",
      label: "65",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "66",
      label: "66",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "67",
      label: "67",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "68",
      label: "68",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "69",
      label: "69",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "70",
      label: "70",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "71",
      label: "71",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "72",
      label: "72",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "73",
      label: "73",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "74",
      label: "74",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "75",
      label: "75",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
    {
      key: "76",
      label: "76",
      value: {
        r: 84,
        g: 108,
        b: 230,
        a: 1,
      },
      elementType: "ColorPicker",
      groupId: "color",
    },
  ],
  groupKey: "cache",
  initialReport: {
    id: "d9795f95-4c7b-4543-8c44-51efd314de9a",
    mode: "create",
    active: true,
    metadata: null,
    metadataLoading: false,
    hreportLoading: false,
    functions: {},
    databaseFunctions: {},
    fields: [],
    filters: [],
    defaultValueDisplayMap: {},
    editingField: null,
    marksList: [
      {
        value: "_all_",
        id: "a266ca26-77b5-4af0-bd12-43bc387ce0e9",
        subVizType: "",
        color: {
          fields: [],
        },
        size: {
          fields: [],
        },
        label: {
          fields: [],
        },
        tooltip: {
          fields: [],
        },
        shape: {
          fields: [],
        },
        detail: {
          fields: [],
        },
      },
    ],
    activeMark: "a266ca26-77b5-4af0-bd12-43bc387ce0e9",
    activeTool: "1",
    scripts: [
      {
        id: "pre-execution",
        value: "",
        title: "Pre Execution",
      },
      {
        id: "pre-fetch",
        value: "",
        title: "Pre Fetch",
      },
      {
        id: "post-fetch",
        value: "",
        title: "Post Fetch",
      },
      {
        id: "post-execution",
        value: "",
        title: "Post Execution",
      },
    ],
    selectedScript: "pre-execution",
    styles: "",
    sqlString: "",
    options: {
      limitBy: 1000,
      sample: "sample",
      prependTableNameToAlias: false,
    },
    interactiveMode: false,
    drillDown: false,
    drillThrough: false,
    drillDownList: [],
    currentDrillDown: "",
    drillThroughList: [],
    toolbarConfig: {
      selectable: false,
    },
    selectedType: "",
    reportData: {},
    customStyles: "",
    customScripts: [],
    analytics: [
      {
        value: false,
        key: "subTotals",
        label: "Row Sub Totals",
      },
    ],
    properties: {
      title: {
        show: false,
        value: "",
        padding: 0,
        fontSize: 32,
        fontColor: {
          a: 1,
          b: 0,
          g: 0,
          r: 0,
        },
        alignment: "center",
        position: "top",
      },
      subTitle: {
        show: false,
        value: "",
        padding: 0,
        fontSize: 24,
        fontColor: {
          a: 1,
          b: 0,
          g: 0,
          r: 0,
        },
        alignment: "center",
        position: "top",
      },
      format: {
        formatFields: [],
        formatDatatype: "",
        activeFieldId: "",
      },
      axisRange: {
        fields: [],
        activeDatatype: "",
        activeId: "",
      },
      cache: {
        isCacheEnabled: false,
        interval: "00:00:01",
      },
      bar: {
        barType: "stacked",
      },
      radial: {
        showRadial: false,
      },
      legend: {
        legendPosition: "right",
      },
      formatColor: {
        defaultColor: {
          r: 84,
          g: 108,
          b: 230,
          a: 1,
        },
        showAll: false,
        dataColors: [],
        formatColorStyle: "",
        formatColorField: "",
        minimum: {
          r: 183,
          g: 192,
          b: 232,
          a: 1,
        },
        maximum: {
          r: 84,
          g: 108,
          b: 230,
          a: 1,
        },
      },
    },
    reportInfo: {
      location: "",
      uuid: "",
      reportName: "Untitled 1",
    },
    cellMenuData: null,
    showHiddenColumns: false,
    showHiddenRows: false,
  },

  expectedResult: {
    isCacheEnabled: false,
    interval: "00:00:01",
  },
};
