#The properties are used for the sql query data types mapping
java.lang.String=text
java.math.BigDecimal=numeric
java.lang.Boolean=boolean
java.lang.Byte=numeric
java.lang.Short=numeric
java.lang.Integer=numeric
java.lang.Long=numeric
java.lang.Float=numeric
java.lang.Double=numeric
java.sql.Date=date
java.sql.Time=time
java.sql.Timestamp=dateTime
#For any other unknown datatypes
java.lang.Object=other
java.sql.Struct=other
java.sql.Array=other
java.sql.SQLXML=other
java.sql.RowId=other
java.sql.Blob=other
uuid=other
## DuckDB DataTypes
TINYINT=numeric
SMALLINT=numeric
INTEGER=numeric
BIGINT=numeric
HUGEINT=numeric
UTINYINT=numeric
USMALLINT=numeric
UINTEGER=numeric
UBIGINT=numeric
UHUGEINT=numeric
TIMESTAMP_MS=dateTime
TIMESTAMP=dateTime
TIMESTAMP_NS=dateTime
TIMESTAMP_S=dateTime
TIMESTAMPTZ=dateTime
JSON=other
STRUCT=other
VARCHAR=text
DATE=date
UUID=other