# suppress inspection "UnusedProperty" for whole file
#The following jdbc driver classes mapping with url is used to provide default url in case of
#data source/connection creation using the UI. The default values are configured for well known
databases.
#hive
org.apache.hive.jdbc.HiveDriver=jdbc:hive2://{{hostName}}:{{port}}/{{database}},10001

#Apache Drill
org.apache.drill.jdbc.Driver=jdbc:drill:{{hostName}}:{{port}},31010

#Dremio
#jdbc:dremio:direct=<DREMIO_COORDINATOR>:31010[;schema=<OPTIONAL_SCHMEMA>]
#com.dremio.jdbc.Driver=jdbc:dremio:direct={{hostName}}:{{port}};schema={{database}},31010
com.dremio.jdbc.Driver=jdbc:dremio:{{hostName}}:{{port}};schema={{database}},31010

#MongoDB - handled by the native NoSQL MongoDB loader
mongoDb=mongodb://{{hostName}}:{{port}}/{{database}}

#HelicalMongoDriver,add this for himongodriver to view in datasource section
#com.helical.mongodb.MongoJdbcDriver=mongodb+srv://{{hostName}}:{{port}}/{{database}},27017
#Oracle
oracle.jdbc.OracleDriver=jdbc:oracle:thin:@{{hostName}}:{{port}}:{{database}},1521
type.service.oracle.jdbc.OracleDriver=jdbc:oracle:thin:@{{hostName}}:{{port}}/{{database}},1521

#For more such pattern use type.patternname.drivername=template
#type.tns.oracle.jdbc.OracleDriver=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST={{hostName}})(PORT={{port}})))

#cData
#cdata.jdbc.mongodb.MongoDBDriver=dbc:sqlserver://{{hostName}}:{{port}};DatabaseName={{database}},27017

#Mysql
com.mysql.jdbc.Driver=jdbc:mysql://{{hostName}}:{{port}}/{{database}},3306

#MysqlNew
com.mysql.cj.jdbc.Driver=jdbc:mysql://{{hostName}}:{{port}}/{{database}},3306

#SqlServer
com.microsoft.sqlserver.jdbc.SQLServerDriver=jdbc:sqlserver://{{hostName}}:{{port}};DatabaseName={{database}},1433
#jtds
net.sourceforge.jtds.jdbc.Driver=jdbc:jtds:sqlserver://{{hostName}}:{{port}}/{{database}},1433

#Postgres
org.postgresql.Driver = jdbc:postgresql://{{hostName}}:{{port}}/{{database}},5432


#DB2
com.ibm.db2.jcc.DB2Driver=jdbc:db2://{{hostName}}:{{port}}/{{database}},50000

#MsAccess
net.ucanaccess.jdbc.UcanaccessDriver=jdbc:ucanaccess:{{database}},

#Sqlite
org.sqlite.JDBC=jdbc:sqlite:{{database}},


#Sybase
com.sybase.jdbc4.jdbc.SybDriver=jdbc:sybase:Tds:{{hostName}}:{{port}}/{{database}},5000
