# suppress inspection "UnusedProperty" for whole file
#The following jdbc driver classes mapping with url is used to provide default url in case of
#data source/connection creation using the UI. The default values are configured for well known
#databases.
#hive
org.apache.hive.jdbc.HiveDriver=jdbc:hive2://{{hostName}}:{{port}}/{{database}},10001

#Apache Drill
org.apache.drill.jdbc.Driver=jdbc:drill:{{hostName}}:{{port}},31010

#Dremio
#jdbc:dremio:direct=<DREMIO_COORDINATOR>:31010[;schema=<OPTIONAL_SCHMEMA>]
#com.dremio.jdbc.Driver=jdbc:dremio:direct={{hostName}}:{{port}},31010
com.dremio.jdbc.Driver=jdbc:dremio:{{hostName}}:{{port}};schema={{database}},31010


#MongoDB
mongoDb=mongodb://{{hostName}}:{{port}}/{{database}}

#HelicalMongoDriver,add this for himongodriver to view in datasource section
#com.helical.mongodb.MongoJdbcDriver=mongodb+srv://{{hostName}}:{{port}}/{{database}},27017
#Oracle
oracle.jdbc.OracleDriver=jdbc:oracle:thin:@{{hostName}}:{{port}}:{{database}},1521
type.service.oracle.jdbc.OracleDriver=jdbc:oracle:thin:@{{hostName}}:{{port}}/{{database}},1521

#For more such pattern use type.patternname.drivername=template
#type.tns.oracle.jdbc.OracleDriver=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST={{hostName}})(PORT={{port}})))

#cData
#cdata.jdbc.mongodb.MongoDBDriver=dbc:sqlserver://{{hostName}}:{{port}};DatabaseName={{database}},27017

#Mysql
com.mysql.jdbc.Driver=jdbc:mysql://{{hostName}}:{{port}}/{{database}},3306

#MysqlNew
com.mysql.cj.jdbc.Driver=jdbc:mysql://{{hostName}}:{{port}}/{{database}},3306

#SqlServer
com.microsoft.sqlserver.jdbc.SQLServerDriver=jdbc:sqlserver://{{hostName}}:{{port}};DatabaseName={{database}},1433
#jtds
net.sourceforge.jtds.jdbc.Driver=jdbc:jtds:sqlserver://{{hostName}}:{{port}}/{{database}},1433


#Postgres
org.postgresql.Driver = jdbc:postgresql://{{hostName}}:{{port}}/{{database}},5432


#DB2
com.ibm.db2.jcc.DB2Driver=jdbc:db2://{{hostName}}:{{port}}/{{database}},50000


#MsAccess
net.ucanaccess.jdbc.UcanaccessDriver=jdbc:ucanaccess:{{database}},

#Sqlite
org.sqlite.JDBC=jdbc:sqlite:{{database}},


#Sybase
com.sybase.jdbc4.jdbc.SybDriver=jdbc:sybase:Tds:{{hostName}}:{{port}}/{{database}},5000
com.sybase.jdbc2.jdbc.SybDriver=jdbc:sybase:Tds:{{hostName}}:{{port}}/{{database}},5000

#MariaDb
org.mariadb.jdbc.Driver=jdbc:mariadb://{{hostName}}:{{port}}/{{database}},3306


#Ingres
com.ingres.jdbc.IngresDriver=jdbc:ingres://{{hostName}}:{{port}}/{{database}};,II7


#Informix
com.informix.jdbc.IfxDriver=jdbc:informix-sqli://{{hostName}}:{{port}}/{{database}}:delimident=y,1526


#Presto
com.facebook.presto.jdbc.PrestoDriver=jdbc:presto://{{hostName}}:{{port}},8090


#Teradata
com.teradata.jdbc.TeraDriver=jdbc:teradata://{{hostName}}/{{database}},

#Derby
org.apache.derby.jdbc.AutoloadedDriver=jdbc:derby:{{database}},

#Derby_17
org.apache.derby.iapi.jdbc.AutoloadedDriver=jdbc:derby:{{database}},


#Hive
#

#FireBird
org.firebirdsql.jdbc.FBDriver=jdbc:firebirdsql://{{hostName}}:{{port}}/{{database}},3051 

#Hsqldb
org.hsqldb.jdbcDriver=jdbc:hsqldb:hsql://{{hostName}}:{{port}}/{{database}},9001

#redshift
com.amazon.redshift.jdbc.Driver=jdbc:redshift://{{hostName}}:{{port}}/{{database}},5439

#clickhouse
ru.yandex.clickhouse.ClickHouseDriver=jdbc:clickhouse://{{hostName}}:{{port}}/{{database}},8123

#vertica
com.vertica.jdbc.Driver=jdbc:vertica://{{hostName}}:{{port}}/{{database}},5433

#Derby Client
org.apache.derby.jdbc.ClientDriver=jdbc:derby://{{hostName}}:{{port}}/{{database}},1527

#Athena
com.simba.athena.jdbc.Driver=jdbc:awsathena://{{hostName}},
com.simba.athena.jdbc42.Driver=jdbc:awsathena://{{hostName}}

#Databricks
com.databricks.client.jdbc.Driver=jdbc:databricks://{{hostName}}:{{port}};{{database}},443

#snowflake
net.snowflake.client.jdbc.SnowflakeDriver=jdbc:snowflake://{{hostName}}
com.snowflake.client.jdbc.SnowflakeDriver=jdbc:snowflake://{{hostName}}

#elastic
org.elasticsearch.xpack.sql.jdbc.EsDriver=jdbc:es://{{hostName}}

#trino
io.trino.jdbc.TrinoDriver=jdbc:trino://{{hostName}}:{{port}}/{{database}},8889

#http-driver
com.helical.HttpDriver=jdbc:{{hostName}}

#himongo
com.helical.mongodb.MongoJdbcDriver=mongodb://{{hostName}}:{{port}}/{{database}},27017

#flatfile
com.helical.FlatFileDriver=jdbc:flatfile:{{hostName}}