#The properties are used for the sql query data types mapping
java.lang.String=db.generic.groupBy.group
java.math.BigDecimal=db.generic.aggregate.sum
java.lang.Boolean=db.generic.groupBy.group
java.lang.Byte=db.generic.aggregate.sum
java.lang.Short=db.generic.aggregate.sum
java.lang.Integer=db.generic.aggregate.sum
java.lang.Long=db.generic.aggregate.sum
java.lang.Float=db.generic.aggregate.sum
java.lang.Double=db.generic.aggregate.sum
java.sql.Date=db.generic.groupBy.group
java.sql.Time=db.generic.groupBy.group
java.sql.Timestamp=db.generic.groupBy.group

## Duckdb Specific
TINYINT=db.generic.aggregate.sum
SMALLINT=db.generic.aggregate.sum
INTEGER=db.generic.aggregate.sum
BIGINT=db.generic.aggregate.sum
HUGEINT=db.generic.aggregate.sum
UTINYINT=db.generic.aggregate.sum
USMALLINT=db.generic.aggregate.sum
UINTEGER=db.generic.aggregate.sum
UBIGINT=db.generic.aggregate.sum
UHUGEINT=db.generic.aggregate.sum
TIMESTAMP_MS=db.generic.groupBy.group
TIMESTAMP=db.generic.groupBy.group
TIMESTAMP_NS=db.generic.groupBy.group
TIMESTAMP_S=db.generic.groupBy.group
TIMESTAMPTZ=db.generic.groupBy.group
