
#Oracle
oracle.jdbc.OracleDriver=SELECT 1 FROM DUAL
oracle.jdbc.driver.OracleDriver=SELECT 1 FROM DUAL

#Mysql
com.mysql.jdbc.Driver=SELECT 1
com.mysql.cj.jdbc.Driver=SELECT 1

#SqlServer
com.microsoft.sqlserver.jdbc.SQLServerDriver=SELECT 1
#com.microsoft.sqlserver.jdbc.SQLServerDriver=SELECT 1
net.sourceforge.jtds.jdbc.Driver=SELECT 1

#Postgres
org.postgresql.Driver=SELECT 1
com.helical.mongodb.MongoJdbcDriver=SELECT 1

#DB2
#alternately we may use db2390, db2400 inplace of db2 
com.ibm.db2.jcc.DB2Driver=SELECT 1
com.ibm.db2.jdbc.app.DB2Driver=SELECT 1

#Uptycs
org.uptycs.UptycsDriver=SELECT 1

#Ms Access
net.ucanaccess.jdbc.UcanaccessDriver=SELECT 1

#Sqlite
org.sqlite.JDBC=SELECT 1

#Apache Drill
org.apache.drill.jdbc.Driver=SELECT 1

#Dremio
com.dremio.jdbc.Driver=SELECT 1


#Sybase 
com.sybase.jdbc4.jdbc.SybDriver=SELECT 1
com.sybase.jdbc2.jdbc.SybDriver=SELECT 1
#net.sourceforge.jtds.jdbc.Driver=SELECT 1
sybase.jdbc.sqlanywhere.IDriver=SELECT 1

#Mariadb
org.mariadb.jdbc.Driver=SELECT 1

#Ingres
com.ingres.jdbc.IngresDriver=SELECT 1

#Informix
com.informix.jdbc.IfxDriver=SELECT 1

#Presto
com.facebook.presto.jdbc.PrestoDriver=SELECT 1

#Teradata
com.teradata.jdbc.TeraDriver=SELECT 1


#Derby
org.apache.derby.jdbc.AutoloadedDriver=SELECT 1 FROM SYSIBM.SYSDUMMY1
org.apache.derby.jdbc.EmbeddedDriver=SELECT 1 FROM SYSIBM.SYSDUMMY1

#Hive
org.apache.hadoop.hive.jdbc.HiveDriver=SELECT 1
org.apache.hive.jdbc.HiveDriver=SELECT 1

#Mongo
mongodb.jdbc.MongoDriver=SELECT 1

#redshift
com.amazon.redshift.jdbc.Driver=SELECT 1

#BigQuery
com.simba.googlebigquery.jdbc42.Driver=SELECT 1

#AmazonDynamoDB
cdata.jdbc.amazondynamodb.AmazonDynamoDBDriver=SELECT 1

com.ibm.as400.access.AS400JDBCDriver=SELECT 1
COM.ibm.db2os390.sqlj.jdbc.DB2SQLJDriver=SELECT 1

com.sap.dbtech.jdbc.DriverSapDB=SELECT 1
org.hsqldb.jdbcDriver=SELECT 1
com.progress.sql.jdbc.JdbcProgressDriver=SELECT 1
com.mckoi.JDBCDriver=SELECT 1
interbase.interclient.Driver=SELECT 1
com.pointbase.jdbc.jdbcUniversalDriver=SELECT 1
com.frontbase.jdbc.FBJDriver=SELECT 1
org.firebirdsql.jdbc.FBDriver=SELECT 1
org.h2.Driver=SELECT 1
com.mimer.jdbc.Driver=SELECT 1
org.apache.calcite.jdbc.Driver=SELECT 1


#clickhouse
ru.yandex.clickhouse.ClickHouseDriver=SELECT 1

#vertica
com.vertica.jdbc.Driver=SELECT 1

#cdata
cdata.jdbc.mongodb.MongoDBDriver=SELECT 1

#derby client
org.apache.derby.jdbc.ClientDriver=SELECT 1

#Athena
com.simba.athena.jdbc.Driver=SELECT 1
com.simba.athena.jdbc42.Driver=SELECT 1

#databricks
com.databricks.client.jdbc.Driver=SELECT 1

#snowflake
net.snowflake.client.jdbc.SnowflakeDriver=SELECT 1


#elasticsearch
org.elasticsearch.xpack.sql.jdbc.EsDriver=SELECT 1

#trino
io.trino.jdbc.TrinoDriver=SELECT 1


#duckdb
org.duckdb.DuckDBDriver=SELECT 1

#sap
com.sap.db.jdbc.Driver=SELECT 1

#firebirdDB
org.firebirdsql.jdbc.FBDriver=SELECT 1

#yugabyte
com.yugabyte.Driver=SELECT 1

#HttpDriver
com.helical.HttpDriver=SELECT 1

#himongo
com.helical.mongodb.MongoJdbcDriver=SELECT 1

#FlatFile
com.helical.FlatFileDriver=SELECT 1