net.sf.jasperreports.export.xls.exclude.origin.keep.first.band.1=pageHeader
net.sf.jasperreports.export.xls.exclude.origin.band.1=title
net.sf.jasperreports.export.xls.exclude.origin.band.2=pageFooter
net.sf.jasperreports.export.xls.exclude.origin.keep.first.band.2=columnHeader
net.sf.jasperreports.export.xls.exclude.origin.keep.first.band.3=columnHeader
net.sf.jasperreports.export.xls.remove.empty.space.between.rows=true
net.sf.jasperreports.export.xls.remove.empty.space.between.columns=true
net.sf.jasperreports.export.xlsx.exclude.origin.keep.first.band.1=pageHeader
net.sf.jasperreports.export.xlsx.exclude.origin.band.1=title
net.sf.jasperreports.export.xlsx.exclude.origin.band.2=pageFooter
net.sf.jasperreports.export.xlsx.exclude.origin.keep.first.band.2=columnHeader
net.sf.jasperreports.export.xlsx.exclude.origin.keep.first.band.3=columnHeader
net.sf.jasperreports.export.xlsx.remove.empty.space.between.rows=true
net.sf.jasperreports.export.xlsx.remove.empty.space.between.columns=true

#font properties , accepts comma separated values
fontDirectories=/usr/local/share/fonts,/usr/share/fonts,c:\\Windows\\Fonts

#jasper chrome properties
net.sf.jasperreports.chrome.executable.path=${CHROME_EXECUTABLE_LOCATION}
net.sf.jasperreports.chrome.enabled=true
net.sf.jasperreports.chrome.page.isolate=true
net.sf.jasperreports.chrome.argument.remote-allow-origins=*
net.sf.jasperreports.chrome.argument.no-sandbox=true
net.sf.jasperreports.chrome.page.timeout=10000
net.sf.jasperreports.chrome.argument.disable-blink-features=CSSAnimations,CSSTransitions,WebAnimations
net.sf.jasperreports.chrome.headless=true
net.sf.jasperreports.chrome.disable-gpu=true

## image resolution properties
net.sf.jasperreports.image.dpi=300

replace.strategy.blank=net.sf.jasperreports.