### OSM properties

##Configure the token if required. As of now osm is free so token is set to free.
#osm.token=free

#Configure the theme of the osm chart.
#osm.style=light
# There should be minimum 2 tiles configured when enabled OSM tiles.
#osm.tileUrls.normal=https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png
#osm.tileUrls.light=https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png
#osm.tileUrls.dark=https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png



### mapbox properties  configuration
## Helical Insight uses four type of maps the default is set to mapbox
## To configure you can change token which can be obtained from mapbox and style
## To enable mapbox related properties, enable the below settings.

mapbox.token=token_value
#dark or light or normal or blank
mapbox.style=light

### End of mapbox configuration.

#-------------------------------------------------#

### amapv2 properties  configuration

#amapv2.token=token_value
#amapv2.style=light #dark or light or normal or blank

### End of amapv2  configuration.

#-------------------------------------------------#

### amapv1 properties  configuration

#amapv1.token=token_value
#amapv1.style=light #dark or light or normal or blank

### End of amapv1  configuration.

#-------------------------------------------------#
### amap properties  configuration

#amap.token=token_value
#amap.style=light #dark or light or normal or blank

### End of amap  configuration.

#-------------------------------------------------#
### map properties  configuration

#map.token=token_value
#map.style=light #dark or light or normal or blank

### End of map  configuration.