#releaseNote.property
#read this file from jsp.
hi.heading=What's New?
hi.a_li=Java 25 LTS upgrade for better performance and compatibility.
hi.b_li=Support of table, crosstab and charts components in canned report. 
hi.c_li=Report properties can be configured for better visualization and export in canned report. 
hi.d_li=Report module has support of Open Street Map.
hi.e_li=KPI visualization in the Report module.
hi.f_li=Workflow API support, reporting enhancements (marks, properties, map visualizations, usability), and designer enhancements (tab, HTML, dropdown). <a href="https://www.helicalinsight.com/walkthrough-of-helical-insight-6-2/" target="_blank">Click Here </a>to Know more

