################################################################
# Security Rule Definitions(For Adhoc Reports for Columns, this will not work for tables)
#
# default - this level of security is as good as no-security
#
# sql-detect - this rule will use the sqlpattern property to detect sql and throws error incase if sql is detected
#
# How to use security rules
#   to find the path in the json it should begin with $ sign which represents the root of the json documents, the starting element
#   followed by dot(.) and key e.g "$.location"
#   incase of nested json document the jsonpath needs to be constructed as "$.metadataFileJson.connectionDetails.connectionType"
#   incase of json array`s the json path needs to be constructed as below
#   $.columns[*]
#   incase if you want to access an array element then define the rule as follows
#   $.columns[*].column
#   incase if you are unsure the location of the key then the jsonpath can be constructed as
#   $..columns
#   incase if you want to filter out specific column then jsonpath will be defined as follows
#   $.columns[?(@['custom'])] - this will check only for columns
#   incase of strict
################################################################

$.@name=sql-detect