
#Oracle
oracle.jdbc.OracleDriver=org.hibernate.dialect.OracleDialect

#Uptycs
org.uptycs.UptycsDriver=org.hibernate.dialect.PostgreSQLDialect

#Mysql
com.mysql.jdbc.Driver=org.hibernate.dialect.MySQLDialect
com.mysql.cj.jdbc.Driver=org.hibernate.dialect.MySQLDialect

#SqlServer
com.microsoft.sqlserver.jdbc.SQLServerDriver=org.hibernate.dialect.SQLServerDialect
net.sourceforge.jtds.jdbc.Driver=org.hibernate.dialect.SQLServerDialect


#PostgreSQL
org.postgresql.Driver=org.hibernate.dialect.PostgreSQLDialect
com.helical.mongodb.MongoJdbcDriver=org.hibernate.dialect.PostgreSQLDialect

#DB2 
com.ibm.db2.jcc.DB2Driver=org.hibernate.dialect.DB2Dialect
com.ibm.db2.jdbc.app.DB2Driver=org.hibernate.dialect.DB2Dialect
com.ibm.as400.access.AS400JDBCDriver=org.hibernate.dialect.DB2400Dialect
COM.ibm.db2os390.sqlj.jdbc.DB2SQLJDriver=org.hibernate.community.dialect.DB2390Dialect

#MsAccess
net.ucanaccess.jdbc.UcanaccessDriver=org.hibernate.dialect.SQLServerDialect


#Sqlite
org.sqlite.JDBC=org.hibernate.community.dialect.SQLiteDialect

#Apache Drill
org.apache.drill.jdbc.Driver=com.helicalinsight.adhoc.genericsql.AapacheDrillSqlDialect

#Dremio
com.dremio.jdbc.Driver=com.helicalinsight.adhoc.genericsql.DremioSqlDialect


#Sybase
com.sybase.jdbc4.jdbc.SybDriver=org.hibernate.dialect.SybaseDialect
com.sybase.jdbc3.jdbc.SybDriver=org.hibernate.dialect.SybaseDialect
com.sybase.jdbc2.jdbc.SybDriver=org.hibernate.dialect.SybaseDialect
sybase.jdbc.sqlanywhere.IDriver=org.hibernate.community.dialect.SybaseAnywhereDialect


#Mariadb
org.mariadb.jdbc.Driver=org.hibernate.community.dialect.MariaDBLegacyDialect

#Ingres
com.ingres.jdbc.IngresDriver=org.hibernate.community.dialect.IngresDialect

#Informix
com.informix.jdbc.IfxDriver=org.hibernate.community.dialect.InformixDialect


#Presto
com.facebook.presto.jdbc.PrestoDriver=org.hibernate.dialect.PostgreSQLDialect

#Teradata
com.teradata.jdbc.TeraDriver=com.helicalinsight.adhoc.genericsql.TeradataHIDialect


#Derby
org.apache.derby.jdbc.EmbeddedDriver=org.hibernate.dialect.DerbyDialect
org.apache.derby.jdbc.AutoloadedDriver=org.hibernate.dialect.DerbyDialect
org.apache.derby.iapi.jdbc.AutoloadedDriver=org.hibernate.dialect.DerbyDialect
org.apache.derby.iapi.jdbc.InternalDriver=org.hibernate.dialect.DerbyDialect

#Derby Client
org.apache.derby.jdbc.ClientDriver=org.hibernate.dialect.DerbyDialect

#Hive
org.apache.hive.jdbc.HiveDriver=com.helicalinsight.adhoc.genericsql.AapacheDrillSqlDialect
org.apache.hadoop.hive.jdbc.HiveDriver=com.helicalinsight.adhoc.genericsql.AapacheDrillSqlDialect

#Cdata
cdata.jdbc.mongodb.MongoDBDriver=org.hibernate.dialect.SQLServerDialect

#redshift
com.amazon.redshift.jdbc.Driver=com.helicalinsight.adhoc.RedshiftDialect

#BigQuery
com.simba.googlebigquery.jdbc42.Driver=org.hibernate.dialect.MySQLDialect

#AmazonDynamoDB
cdata.jdbc.amazondynamodb.AmazonDynamoDBDriver=org.hibernate.dialect.PostgreSQLDialect


com.sap.dbtech.jdbc.DriverSapDB=org.hibernate.community.dialect.SAPDBDialect
org.hsqldb.jdbcDriver=org.hibernate.dialect.HSQLDialect
com.progress.sql.jdbc.JdbcProgressDriver=org.hibernate.dialect.ProgressDialect
com.mckoi.JDBCDriver=org.hibernate.dialect.MckoiDialect
interbase.interclient.Driver=org.hibernate.dialect.InterbaseDialect
com.pointbase.jdbc.jdbcUniversalDriver=org.hibernate.dialect.PointbaseDialect
com.frontbase.jdbc.FBJDriver=org.hibernate.dialect.FrontbaseDialect
org.firebirdsql.jdbc.FBDriver=org.hibernate.community.dialect.FirebirdDialect
org.h2.Driver=org.hibernate.dialect.H2Dialect
com.mimer.jdbc.Driver=org.hibernate.community.dialect.MimerSQLDialect
org.apache.calcite.jdbc.Driver=com.helicalinsight.adhoc.genericsql.CalciteHibernateDialect
com.amazon.redshift.jdbc.Driver=org.hibernate.dialect.PostgreSQLDialect

#clickhouse
ru.yandex.clickhouse.ClickHouseDriver=org.hibernate.dialect.MySQLDialect

#vertica
com.vertica.jdbc.Driver=org.hibernate.dialect.PostgreSQLDialect
															  
#Athena
com.simba.athena.jdbc.Driver=org.hibernate.dialect.PostgreSQLDialect
com.simba.athena.jdbc42.Driver=org.hibernate.dialect.PostgreSQLDialect

#Databricks
com.databricks.client.jdbc.Driver=org.hibernate.dialect.MySQLDialect

# Snowflake
net.snowflake.client.jdbc.SnowflakeDriver=org.hibernate.dialect.DerbyDialect

#elasticsearch
org.elasticsearch.xpack.sql.jdbc.EsDriver=org.hibernate.dialect.PostgreSQLDialect

#trino
io.trino.jdbc.TrinoDriver=org.hibernate.dialect.PostgreSQLDialect

#duckdb
org.duckdb.DuckDBDriver=org.hibernate.dialect.PostgreSQLDialect

# sap
com.sap.db.jdbc.Driver=org.hibernate.dialect.HANADialect

#Firebird
org.firebirdsql.jdbc.FBDriver=org.hibernate.community.dialect.FirebirdDialect

#yugabyte 
com.yugabyte.Driver=org.hibernate.dialect.PostgreSQLDialect

com.helical.HttpDriver=org.hibernate.dialect.PostgreSQLDialect

com.helical.mongodb.MongoJdbcDriver=org.hibernate.dialect.MySQLDialect
com.helical.FlatFileDriver=org.hibernate.dialect.PostgreSQLDialect