package com.helical.mongodb;

import com.mongodb.MongoClient;
import com.mongodb.client.MongoCollection;
import org.bson.Document;

import javax.sql.rowset.CachedRowSet;
import javax.sql.rowset.RowSetMetaDataImpl;
import javax.sql.rowset.RowSetProvider;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.SQLFeatureNotSupportedException;
import java.sql.SQLWarning;
import java.sql.Statement;
import java.sql.Types;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

public class MongoStatement implements Statement {

    private final MongoConnection connection;

    private boolean closed;
    private int queryTimeout;
    private int fetchSize;

    public MongoStatement(MongoConnection connection) {
        this.connection = connection;
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        checkClosed();

        if (sql == null || sql.trim().isEmpty()) {
            throw new SQLException("SQL query cannot be empty");
        }

        String normalized = sql.trim();

        // Temporary diagnostic: capture the exact SQL generated by Helical Insight.
        System.out.println("[MongoJdbcDriver] SQL received: " + normalized);

        // Helical Insight uses SELECT 1 as the default connection test.
        if (normalized.matches("(?i)SELECT\\s+1\\s*;?")) {
            return createConstantResultSet();
        }

        return executeMongoSelect(normalized);
    }

    private ResultSet executeMongoSelect(String sql)
            throws SQLException {

        // Normalize multiline SQL so keywords can be parsed consistently.
        String normalizedSql = sql.trim().replaceAll("\\s+", " ");
        String upperSql = normalizedSql.toUpperCase();

        System.out.println("[MongoJdbcDriver] Normalized SQL: " + normalizedSql);
        System.out.println("[MongoJdbcDriver] FROM index: " + upperSql.indexOf(" FROM "));

        if (!upperSql.startsWith("SELECT ")) {
            throw new SQLFeatureNotSupportedException(
                    "MongoDB JDBC driver currently supports SELECT queries only"
            );
        }

        int fromIndex = upperSql.indexOf(" FROM ");

        if (fromIndex < 0) {
            throw new SQLException(
                    "SELECT query must contain a FROM clause"
            );
        }

        String projectionPart =
            normalizedSql.substring(7, fromIndex).trim();

        String collectionPart =
            normalizedSql.substring(fromIndex + 6).trim();

        if (collectionPart.endsWith(";")) {
            collectionPart = collectionPart
                    .substring(0, collectionPart.length() - 1)
                    .trim();
        }

        String collectionName = collectionPart.split("\\s+")[0]
            .replace("\"", "")
            .replace("`", "");

        if (collectionName.contains(".")) {
            collectionName = collectionName.substring(collectionName.lastIndexOf('.') + 1);
        }

        // Helical Insight may qualify the collection as "database"."collection".
        // MongoDB expects only the collection name here.
        if (collectionName.contains(".")) {
            collectionName =
                    collectionName.substring(
                            collectionName.lastIndexOf('.') + 1
                    );
        }

        if (collectionName.isEmpty()) {
            throw new SQLException(
                    "MongoDB collection name is missing"
            );
        }

        MongoClient client =
                connection.getMongoClient();

        MongoCollection<Document> collection =
                client.getDatabase(connection.getDatabaseName())
                        .getCollection(collectionName);

        List<Document> documents =
            collection.find().into(new ArrayList<>());

        System.out.println("[MongoJdbcDriver] Collection: " + collectionName);
        System.out.println("[MongoJdbcDriver] Documents found: " + documents.size());

        List<String> columns =
                determineColumns(
                    projectionPart,
                    documents
                );

        System.out.println("[MongoJdbcDriver] Columns: " + columns);

        return createResultSet(
                columns,
                documents,
                projectionPart
        );
    }

    private List<String> determineColumns(
            String projectionPart,
            List<Document> documents) {

        List<String> columns = new ArrayList<>();

        if ("*".equals(projectionPart)) {

            Set<String> uniqueColumns =
                    new LinkedHashSet<>();

            for (Document document : documents) {
                uniqueColumns.addAll(document.keySet());
            }

            columns.addAll(uniqueColumns);

        } else {

            String[] requestedColumns =
                    projectionPart.split(",");

            for (String column : requestedColumns) {

                String name = column.trim();

                // Keep the output column name used by Helical Insight.
                String upperName = name.toUpperCase();

                int asIndex = upperName.indexOf(" AS ");

                if (asIndex >= 0) {
                    name = name.substring(asIndex + 4).trim();
                }

                name = name
                        .replace("\"", "")
                        .replace("`", "");

                columns.add(name);
            }
        }

        return columns;
    }

    private ResultSet createResultSet(
            List<String> columns,
            List<Document> documents,
            String projectionPart)
            throws SQLException {

        CachedRowSet rowSet =
                RowSetProvider.newFactory()
                        .createCachedRowSet();

        RowSetMetaDataImpl metadata =
                new RowSetMetaDataImpl();

        metadata.setColumnCount(columns.size());

        for (int i = 0; i < columns.size(); i++) {

            String columnName = columns.get(i);

            metadata.setColumnName(i + 1, columnName);
            metadata.setColumnLabel(i + 1, columnName);

            metadata.setColumnType(
                    i + 1,
                    determineColumnType(columnName, documents)
            );

            metadata.setNullable(
                    i + 1,
                    ResultSetMetaData.columnNullable
            );
        }

        rowSet.setMetaData(metadata);

        // Detect the GROUP BY fields from the SQL generated by Helical Insight.
        String upperProjection = projectionPart.toUpperCase();

        boolean hasAggregate =
                upperProjection.contains("SUM(");

        if (hasAggregate) {

            List<String> groupColumns =
                    extractGroupColumns(projectionPart);

            Map<String, List<Document>> groups =
                    new LinkedHashMap<>();

            for (Document document : documents) {

                StringBuilder groupKey =
                        new StringBuilder();

                for (String groupColumn : groupColumns) {
                    groupKey
                            .append(String.valueOf(
                                    document.get(groupColumn)))
                            .append("|");
                }

                groups.computeIfAbsent(
                        groupKey.toString(),
                        key -> new ArrayList<>()
                ).add(document);
            }

            for (List<Document> groupDocuments : groups.values()) {

                Document firstDocument =
                        groupDocuments.get(0);

                rowSet.moveToInsertRow();

                for (int i = 0; i < columns.size(); i++) {

                    String columnName = columns.get(i);

                    Object value =
                            calculateAggregate(
                                    columnName,
                                    projectionPart,
                                    groupDocuments
                            );

                    if (value == null) {
                        value = firstDocument.get(columnName);
                    }

                    rowSet.updateObject(
                            i + 1,
                            convertMongoValue(value)
                    );
                }

                rowSet.insertRow();
                rowSet.moveToCurrentRow();
            }

        } else {

            // Normal SELECT: return one row for each MongoDB document.
            for (Document document : documents) {

                rowSet.moveToInsertRow();

                for (int i = 0; i < columns.size(); i++) {

                    String columnName = columns.get(i);

                    Object value =
                            document.get(columnName);

                    rowSet.updateObject(
                            i + 1,
                            convertMongoValue(value)
                    );
                }

                rowSet.insertRow();
                rowSet.moveToCurrentRow();
            }
        }

        rowSet.beforeFirst();

        return rowSet;
    }

    private List<String> extractGroupColumns(String projectionPart) {

        List<String> groupColumns =
                new ArrayList<>();

        // The GROUP BY clause is outside projectionPart, so this
        // method currently handles the known Helical Insight query
        // through the projection aliases.
        String[] expressions =
                projectionPart.split(",");

        for (String expression : expressions) {

            String name = expression.trim();

            String upperName = name.toUpperCase();

            int asIndex = upperName.indexOf(" AS ");

            if (asIndex >= 0) {
                name = name.substring(0, asIndex).trim();
            }

            // Aggregate expressions are not group fields.
            if (name.toUpperCase().contains("SUM(")) {
                continue;
            }

            name = name
                    .replace("\"", "")
                    .replace("`", "");

            if (name.contains(".")) {
                name = name.substring(name.lastIndexOf('.') + 1);
            }

            if (!name.isEmpty()) {
                groupColumns.add(name);
            }
        }

        return groupColumns;
    }

    private Object calculateAggregate(
            String columnName,
            String projectionPart,
            List<Document> documents) {

        String upperProjection = projectionPart.toUpperCase();

        // Currently supports SUM(field) AS alias.
        if (!upperProjection.contains("SUM(")) {
            return null;
        }

        String[] expressions = projectionPart.split(",");

        for (String expression : expressions) {

            String upperExpression = expression.toUpperCase();

            if (!upperExpression.contains("SUM(")) {
                continue;
            }

            int sumStart = upperExpression.indexOf("SUM(") + 4;
            int sumEnd = upperExpression.indexOf(")", sumStart);

            if (sumEnd < 0) {
                continue;
            }

            String alias = null;

            int asIndex = upperExpression.indexOf(" AS ");

            if (asIndex >= 0) {
                alias = expression
                        .substring(asIndex + 4)
                        .trim()
                        .replace("\"", "")
                        .replace("`", "");
            }

            if (alias == null ||
                    !alias.equalsIgnoreCase(columnName)) {
                continue;
            }

            String field = expression
                    .substring(sumStart, sumEnd)
                    .trim()
                    .replace("\"", "")
                    .replace("`", "");

            // Remove database and collection qualifiers.
            if (field.contains(".")) {
                field = field.substring(field.lastIndexOf('.') + 1);
            }

            double sum = 0;

            for (Document document : documents) {
                Object value = document.get(field);

                if (value instanceof Number) {
                    sum += ((Number) value).doubleValue();
                }
            }

            return sum;
        }

        return null;
    }

    private Object convertMongoValue(Object value) {

        if (value == null) {
            return null;
        }

        if (value instanceof org.bson.types.ObjectId) {
            return value.toString();
        }

        if (value instanceof Document) {
            return ((Document) value).toJson();
        }

        return value;
    }

    private int determineColumnType(
            String columnName,
            List<Document> documents) {

        for (Document document : documents) {

            Object value =
                    document.get(columnName);

            if (value == null) {
                continue;
            }

            if (value instanceof Integer) {
                return Types.INTEGER;
            }

            if (value instanceof Long) {
                return Types.BIGINT;
            }

            if (value instanceof Double ||
                    value instanceof Float) {
                return Types.DOUBLE;
            }

            if (value instanceof Boolean) {
                return Types.BOOLEAN;
            }

            if (value instanceof java.util.Date) {
                return Types.TIMESTAMP;
            }

            return Types.VARCHAR;
        }

        return Types.VARCHAR;
    }

    private ResultSet createConstantResultSet()
            throws SQLException {

        CachedRowSet rowSet =
                RowSetProvider.newFactory()
                        .createCachedRowSet();

        RowSetMetaDataImpl metadata =
                new RowSetMetaDataImpl();

        metadata.setColumnCount(1);
        metadata.setColumnName(1, "1");
        metadata.setColumnLabel(1, "1");
        metadata.setColumnType(1, Types.INTEGER);
        metadata.setNullable(
                1,
                ResultSetMetaData.columnNoNulls
        );

        rowSet.setMetaData(metadata);

        rowSet.moveToInsertRow();
        rowSet.updateInt(1, 1);
        rowSet.insertRow();
        rowSet.moveToCurrentRow();

        rowSet.beforeFirst();

        return rowSet;
    }

    private void checkClosed() throws SQLException {

        if (closed) {
            throw new SQLException(
                    "Statement is closed"
            );
        }

        if (connection.isClosed()) {
            throw new SQLException(
                    "Connection is closed"
            );
        }
    }

    private SQLFeatureNotSupportedException unsupported() {
        return new SQLFeatureNotSupportedException(
                "This JDBC operation is not supported by the MongoDB driver"
        );
    }

    @Override
    public Connection getConnection() {
        return connection;
    }

    @Override
    public void close() {
        closed = true;
    }

    @Override
    public boolean isClosed() {
        return closed;
    }

    @Override
    public int getQueryTimeout() {
        return queryTimeout;
    }

    @Override
    public void setQueryTimeout(int seconds) {
        queryTimeout = seconds;
    }

    @Override
    public void setFetchSize(int rows) {
        fetchSize = rows;
    }

    @Override
    public int getFetchSize() {
        return fetchSize;
    }

    @Override
    public int getFetchDirection() {
        return ResultSet.FETCH_FORWARD;
    }

    @Override
    public void setFetchDirection(int direction) throws SQLException {
        if (direction != ResultSet.FETCH_FORWARD) {
            throw unsupported();
        }
    }

    @Override
    public int getResultSetHoldability() {
        return ResultSet.CLOSE_CURSORS_AT_COMMIT;
    }

    @Override
    public int getResultSetType() {
        return ResultSet.TYPE_FORWARD_ONLY;
    }

    @Override
    public int getResultSetConcurrency() {
        return ResultSet.CONCUR_READ_ONLY;
    }

    @Override
    public boolean execute(String sql)
            throws SQLException {
        executeQuery(sql);
        return true;
    }

    @Override
    public boolean execute(
            String sql,
            int autoGeneratedKeys)
            throws SQLException {
        executeQuery(sql);
        return true;
    }

    @Override
    public boolean execute(
            String sql,
            int[] columnIndexes)
            throws SQLException {
        executeQuery(sql);
        return true;
    }

    @Override
    public boolean execute(
            String sql,
            String[] columnNames)
            throws SQLException {
        executeQuery(sql);
        return true;
    }

    @Override
    public ResultSet getResultSet()
            throws SQLException {
        throw unsupported();
    }

    @Override
    public int getMaxRows() {
        return 0;
    }

    @Override
    public int getUpdateCount() {
        return -1;
    }

    @Override
    public void setMaxRows(int max) {
    }

    @Override
    public void cancel() {
    }

    @Override
    public SQLWarning getWarnings() {
        return null;
    }

    @Override
    public void clearWarnings() {
    }

    @Override
    public int executeUpdate(String sql)
            throws SQLException {
        throw unsupported();
    }

    @Override
    public int executeUpdate(
            String sql,
            int autoGeneratedKeys)
            throws SQLException {
        throw unsupported();
    }

    @Override
    public int executeUpdate(
            String sql,
            int[] columnIndexes)
            throws SQLException {
        throw unsupported();
    }

    @Override
    public int executeUpdate(
            String sql,
            String[] columnNames)
            throws SQLException {
        throw unsupported();
    }

    @Override
    public long executeLargeUpdate(String sql)
            throws SQLException {
        throw unsupported();
    }

    @Override
    public long executeLargeUpdate(
            String sql,
            int autoGeneratedKeys)
            throws SQLException {
        throw unsupported();
    }

    @Override
    public long executeLargeUpdate(
            String sql,
            int[] columnIndexes)
            throws SQLException {
        throw unsupported();
    }

    @Override
    public long executeLargeUpdate(
            String sql,
            String[] columnNames)
            throws SQLException {
        throw unsupported();
    }

    @Override
    public void addBatch(String sql)
            throws SQLException {
        throw unsupported();
    }

    @Override
    public void clearBatch() {
    }

    @Override
    public int[] executeBatch()
            throws SQLException {
        throw unsupported();
    }

    @Override
    public long[] executeLargeBatch()
            throws SQLException {
        throw unsupported();
    }

    @Override
    public void setCursorName(String name)
            throws SQLException {
        throw unsupported();
    }

    @Override
    public void setEscapeProcessing(boolean enable) {
    }

    @Override
    public int getMaxFieldSize() {
        return 0;
    }

    @Override
    public void setMaxFieldSize(int max) {
    }

    @Override
    public boolean getMoreResults() {
        return false;
    }

    @Override
    public boolean getMoreResults(int current) {
        return false;
    }

    @Override
    public ResultSet getGeneratedKeys()
            throws SQLException {
        throw unsupported();
    }

    @Override
    public void setPoolable(boolean poolable) {
    }

    @Override
    public boolean isPoolable() {
        return false;
    }

    @Override
    public void closeOnCompletion() {
    }

    @Override
    public boolean isCloseOnCompletion() {
        return false;
    }

    @Override
    public long getLargeMaxRows() {
        return 0;
    }

    @Override
    public void setLargeMaxRows(long max) {
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) {
        return iface.isInstance(this);
    }

    @Override
    public <T> T unwrap(Class<T> iface)
            throws SQLException {

        if (iface.isInstance(this)) {
            return iface.cast(this);
        }

        throw new SQLException(
                "Not a wrapper for " + iface.getName()
        );
    }
}
