export const itemAddedDesignerState = {
  filterCounter: 0,
  parameterDrawerStatus: false,
  designerSettings: [
    {
      key: "parameters",
      values: {
        enable: true,
        orientation: "right",
        enableApplyButton: true,
      },
    },
  ],
  previewMode: false,
  designerMode: "create",
  dashboardVariables: {},
  dashboardUUID: "",
  variables: [],
  components: {},
  dashboardConfig: {
    id: "dashboard",
  },
  css: "",
  script: "",
  printOptions: {
    templateId: "Dashboard",
    title: "Dashboard",
  },
  componentSettings: {},
  toggleIframes: false,
  gridItemsData: [
    {
      id: "item-0u1vF",
      compType: "image",
      isGrouped: false,
      isSaved: false,
      initialPosition: {
        x: 0,
        y: 0,
        w: 2,
        h: 2,
        i: "item-0u1vF",
        static: false,
      },
      gridItemConfig: [
        {
          key: "header",
          values: {
            enable: false,
            title: "",
            placeholder: "Edit/Add your header content here",
            link: "",
            backgroundColor: {
              r: 24,
              g: 144,
              b: 255,
              a: 100,
            },
            position: "left",
          },
        },
        {
          key: "shadow",
          values: {
            enable: false,
            xOffset: 1,
            yOffset: 1,
            blur: 1,
            spread: 1,
            color: {
              r: 24,
              g: 144,
              b: 255,
              a: 100,
            },
          },
        },
        {
          key: "background",
          values: {
            enable: false,
            backgroundColor: {
              r: 255,
              g: 255,
              b: 255,
              a: 100,
            },
            image: "",
          },
        },
        {
          key: "border",
          values: {
            enable: false,
            borderWidth: 1,
            borderStyle: "solid",
            color: {
              r: 24,
              g: 144,
              b: 255,
              a: 100,
            },
          },
        },
        {
          key: "html",
          values: {
            enable: false,
            value: "",
          },
        },
        {
          key: "css",
          values: {
            enable: false,
            value: "",
          },
        },
        {
          key: "javascript",
          values: {
            enable: false,
            value: "",
          },
        },
        {
          key: "edit",
          values: {
            enable: true,
            url: "",
            opacity: 50,
          },
        },
      ],
    },
  ],
  layout: [
    {
      w: 2,
      h: 2,
      x: 0,
      y: 0,
      i: "item-0u1vF",
      moved: false,
      static: false,
    },
  ],
  dashboardDrawerStatus: false,
  gridItemDrawerStatus: false,
  currentGroupId: "",
  groupId: "edit",
  gridItemId: "item-0u1vF",
  drawerPositions: ["right", "bottom", "left", "top"],
  currentDrawerPosition: 0,
  gridSettings: [
    {
      key: "breakpoints",
      values: [
        {
          key: "lg",
          name: "Large Screens",
          value: 1200,
          tooltip: "Large Screens(lg)",
        },
        {
          key: "md",
          name: "Medium Screens",
          value: 996,
          tooltip: "Medium Screens(md)",
        },
        {
          key: "sm",
          name: "Small Screens",
          value: 768,
          tooltip: "Small Screens(sm)",
        },
        {
          key: "xs",
          name: "Extra Small Screens",
          value: 480,
          tooltip: "Extra Small Screens(xs)",
        },
        {
          key: "xxs",
          name: "Extra Extra Small Screens",
          value: 240,
          tooltip: "Extra Extra Small Screens(xxs)",
        },
      ],
    },
    {
      key: "columns",
      values: [
        {
          key: "lg",
          name: "Large Screens",
          value: 12,
          tooltip: "Large Screens(lg)",
        },
        {
          key: "md",
          name: "Medium Screens",
          value: 12,
          tooltip: "Medium Screens(md)",
        },
        {
          key: "sm",
          name: "Small Screens",
          value: 6,
          tooltip: "Small Screens(sm)",
        },
        {
          key: "xs",
          name: "Extra Small Screens",
          value: 4,
          tooltip: "Extra Small Screens(xs)",
        },
        {
          key: "xxs",
          name: "Extra Extra Small Screens",
          value: 2,
          tooltip: "Extra Extra Small Screens(xxs)",
        },
      ],
    },
    {
      key: "grid",
      values: {
        autoSize: true,
        compactType: null,
        rowHeight: 100,
        isDroppable: false,
        preventCollision: true,
        measureBeforeMount: false,
        isDraggable: true,
        isResizable: true,
      },
    },
    {
      key: "header",
      values: {
        enable: false,
        title: "",
        placeholder: "Edit/Add your header content here",
        link: "",
        backgroundColor: {
          r: 255,
          g: 255,
          b: 255,
          a: 100,
        },
        position: "left",
      },
    },
    {
      key: "shadow",
      values: {
        enable: false,
        xOffset: 0,
        yOffset: 0,
        blur: 0,
        spread: 0,
        color: {
          r: 255,
          g: 255,
          b: 255,
          a: 100,
        },
      },
    },
    {
      key: "background",
      values: {
        enable: false,
        backgroundColor: {
          r: 255,
          g: 255,
          b: 255,
          a: 100,
        },
        image: "",
      },
    },
    {
      key: "border",
      values: {
        enable: false,
        borderWidth: 1,
        borderStyle: "solid",
        color: {
          r: 255,
          g: 255,
          b: 255,
          a: 100,
        },
      },
    },
    {
      key: "html",
      values: {
        enable: false,
        value: "",
      },
    },
    {
      key: "css",
      values: {
        enable: false,
        value: "",
      },
    },
    {
      key: "javascript",
      values: {
        enable: false,
        value: "",
      },
    },
  ],
  filterItemsData: [],
  maximizedGridItem: {},
  maximizingStatus: false,
  gridIndex: 0,
  isLoading: false,
  reportId: "",
  applyDashboardFilters: null,
  isSaving: false,
  expandDesignerDrawers: false,
  hasUnsavedData: true,
  itemAddedStatus: 1662010105946,
};
export const itemSavedDesignerState = {
  filterCounter: 0,
  parameterDrawerStatus: false,
  designerSettings: [
    {
      key: "parameters",
      values: {
        enable: true,
        orientation: "right",
        enableApplyButton: true,
      },
    },
  ],
  previewMode: false,
  designerMode: "create",
  dashboardVariables: {},
  dashboardUUID: "",
  variables: [],
  components: {},
  dashboardConfig: {
    id: "dashboard",
  },
  css: "",
  script: "",
  printOptions: {
    templateId: "Dashboard",
    title: "Dashboard",
  },
  componentSettings: {},
  toggleIframes: false,
  gridItemsData: [
    {
      id: "item-0u1vF",
      compType: "image",
      isGrouped: false,
      isSaved: true,
      initialPosition: {
        x: 0,
        y: 0,
        w: 2,
        h: 2,
        i: "item-0u1vF",
        static: false,
      },
      gridItemConfig: [
        {
          key: "header",
          values: {
            enable: false,
            title: "",
            placeholder: "Edit/Add your header content here",
            link: "",
            backgroundColor: {
              r: 24,
              g: 144,
              b: 255,
              a: 100,
            },
            position: "left",
          },
        },
        {
          key: "shadow",
          values: {
            enable: false,
            xOffset: 1,
            yOffset: 1,
            blur: 1,
            spread: 1,
            color: {
              r: 24,
              g: 144,
              b: 255,
              a: 100,
            },
          },
        },
        {
          key: "background",
          values: {
            enable: false,
            backgroundColor: {
              r: 255,
              g: 255,
              b: 255,
              a: 100,
            },
            image: "",
          },
        },
        {
          key: "border",
          values: {
            enable: false,
            borderWidth: 1,
            borderStyle: "solid",
            color: {
              r: 24,
              g: 144,
              b: 255,
              a: 100,
            },
          },
        },
        {
          key: "html",
          values: {
            enable: false,
            value: "",
          },
        },
        {
          key: "css",
          values: {
            enable: false,
            value: "",
          },
        },
        {
          key: "javascript",
          values: {
            enable: false,
            value: "",
          },
        },
        {
          key: "edit",
          values: {
            enable: true,
            url: "",
            opacity: 50,
          },
        },
      ],
    },
  ],
  layout: [
    {
      w: 2,
      h: 2,
      x: 0,
      y: 0,
      i: "item-0u1vF",
      moved: false,
      static: false,
    },
  ],
  dashboardDrawerStatus: false,
  gridItemDrawerStatus: false,
  currentGroupId: "",
  groupId: "edit",
  gridItemId: "item-0u1vF",
  drawerPositions: ["right", "bottom", "left", "top"],
  currentDrawerPosition: 0,
  gridSettings: [
    {
      key: "breakpoints",
      values: [
        {
          key: "lg",
          name: "Large Screens",
          value: 1200,
          tooltip: "Large Screens(lg)",
        },
        {
          key: "md",
          name: "Medium Screens",
          value: 996,
          tooltip: "Medium Screens(md)",
        },
        {
          key: "sm",
          name: "Small Screens",
          value: 768,
          tooltip: "Small Screens(sm)",
        },
        {
          key: "xs",
          name: "Extra Small Screens",
          value: 480,
          tooltip: "Extra Small Screens(xs)",
        },
        {
          key: "xxs",
          name: "Extra Extra Small Screens",
          value: 240,
          tooltip: "Extra Extra Small Screens(xxs)",
        },
      ],
    },
    {
      key: "columns",
      values: [
        {
          key: "lg",
          name: "Large Screens",
          value: 12,
          tooltip: "Large Screens(lg)",
        },
        {
          key: "md",
          name: "Medium Screens",
          value: 12,
          tooltip: "Medium Screens(md)",
        },
        {
          key: "sm",
          name: "Small Screens",
          value: 6,
          tooltip: "Small Screens(sm)",
        },
        {
          key: "xs",
          name: "Extra Small Screens",
          value: 4,
          tooltip: "Extra Small Screens(xs)",
        },
        {
          key: "xxs",
          name: "Extra Extra Small Screens",
          value: 2,
          tooltip: "Extra Extra Small Screens(xxs)",
        },
      ],
    },
    {
      key: "grid",
      values: {
        autoSize: true,
        compactType: null,
        rowHeight: 100,
        isDroppable: false,
        preventCollision: true,
        measureBeforeMount: false,
        isDraggable: true,
        isResizable: true,
      },
    },
    {
      key: "header",
      values: {
        enable: false,
        title: "",
        placeholder: "Edit/Add your header content here",
        link: "",
        backgroundColor: {
          r: 255,
          g: 255,
          b: 255,
          a: 100,
        },
        position: "left",
      },
    },
    {
      key: "shadow",
      values: {
        enable: false,
        xOffset: 0,
        yOffset: 0,
        blur: 0,
        spread: 0,
        color: {
          r: 255,
          g: 255,
          b: 255,
          a: 100,
        },
      },
    },
    {
      key: "background",
      values: {
        enable: false,
        backgroundColor: {
          r: 255,
          g: 255,
          b: 255,
          a: 100,
        },
        image: "",
      },
    },
    {
      key: "border",
      values: {
        enable: false,
        borderWidth: 1,
        borderStyle: "solid",
        color: {
          r: 255,
          g: 255,
          b: 255,
          a: 100,
        },
      },
    },
    {
      key: "html",
      values: {
        enable: false,
        value: "",
      },
    },
    {
      key: "css",
      values: {
        enable: false,
        value: "",
      },
    },
    {
      key: "javascript",
      values: {
        enable: false,
        value: "",
      },
    },
  ],
  filterItemsData: [],
  maximizedGridItem: {},
  maximizingStatus: false,
  gridIndex: 0,
  isLoading: false,
  reportId: "",
  applyDashboardFilters: null,
  isSaving: false,
  expandDesignerDrawers: false,
  hasUnsavedData: true,
  itemAddedStatus: 1662010105946,
};

export const beforeAddingFilter = {
  filterCounter: 1,
  parameterDrawerStatus: true,
  designerSettings: [
    {
      key: "parameters",
      values: {
        enable: true,
        orientation: "right",
        enableApplyButton: true,
      },
    },
  ],
  previewMode: false,
  designerMode: "create",
  dashboardVariables: {},
  dashboardUUID: "",
  variables: [],
  components: {},
  dashboardConfig: {
    id: "dashboard",
  },
  css: "",
  script: "",
  printOptions: {
    templateId: "Dashboard",
    title: "Dashboard",
  },
  componentSettings: {},
  toggleIframes: false,
  gridItemsData: [
    {
      id: "item-niOMd",
      compType: "dashboard-designer-component",
      isGrouped: false,
      isSaved: false,
      initialPosition: {
        x: 0,
        y: 0,
        w: 2,
        h: 2,
        i: "item-niOMd",
        static: false,
      },
      gridItemConfig: [
        {
          key: "header",
          values: {
            enable: true,
            title: "hreportWith2Filters",
            placeholder: "Edit/Add your header content here",
            link: "",
            backgroundColor: {
              r: 24,
              g: 144,
              b: 255,
              a: 100,
            },
            position: "left",
          },
        },
        {
          key: "shadow",
          values: {
            enable: false,
            xOffset: 1,
            yOffset: 1,
            blur: 1,
            spread: 1,
            color: {
              r: 24,
              g: 144,
              b: 255,
              a: 100,
            },
          },
        },
        {
          key: "background",
          values: {
            enable: false,
            backgroundColor: {
              r: 255,
              g: 255,
              b: 255,
              a: 100,
            },
            image: "",
          },
        },
        {
          key: "border",
          values: {
            enable: false,
            borderWidth: 1,
            borderStyle: "solid",
            color: {
              r: 24,
              g: 144,
              b: 255,
              a: 100,
            },
          },
        },
        {
          key: "html",
          values: {
            enable: false,
            value: "",
          },
        },
        {
          key: "css",
          values: {
            enable: false,
            value: "",
          },
        },
        {
          key: "javascript",
          values: {
            enable: false,
            value: "",
          },
        },
        {
          key: "griditemsettings",
          values: {
            export: false,
            edit: false,
            maximize: false,
          },
        },
      ],
      reportInfo: {
        file: {
          path: "sai_ganesh/hreportWith2Filters.hr",
          name: "hreportWith2Filters.hr",
          title: "hreportWith2Filters",
        },
        mode: "dashboard",
        filters: [],
        component: "hreport",
        extension: "hr",
      },
      filters: [
        {
          column: "travel_details.booking_platform",
          label: "booking_platform",
          dataType: "text",
          backendDataType: "java.lang.String",
          condition: "IS_ONE_OF",
          values: ["Makemytrip"],
          valuesMode: "custom",
          mode: "auto",
          orderBy: "",
          valuesRange: {},
          rangeValuesType: "",
          dateTimeToggle: false,
          rangeSelectionToggole: true,
          maxInput: "",
          minInput: "",
          valuesList: [],
          drillDownId: "",
          uid: "104e3760-ac86-4372-ba7b-0f69187d1753",
          configId: "be93b3c2-7d45-4cbb-9007-78bd691b5266",
          dataId: "8120f657-781a-4751-8e91-e144a9fd8734",
          mapping: {
            isEnabled: true,
            unique: true,
            isDefaultFunction: true,
            valueDisplayMap: [],
            valueAliasName: "random",
            orderBy: {
              display: "asc",
              value: "none",
            },
            valueDBFuntionInfo: {},
            valueColumn: {
              alias: "booking_platform",
              fullyQualifiedColumn: "travel_details.booking_platform",
              columnId: "27f17a28-3282-4a1b-9aaf-fdb706938c9e",
              defaultFunction: "none",
              type: {
                "java.lang.String": "text",
              },
            },
            displayColumn: {
              alias: "booking_platform",
              fullyQualifiedColumn: "travel_details.booking_platform",
              columnId: "27f17a28-3282-4a1b-9aaf-fdb706938c9e",
              defaultFunction: "none",
              type: {
                "java.lang.String": "text",
              },
            },
          },
          cascade: {
            isEnabled: false,
            filters: [],
            filtersCount: 0,
          },
          active: false,
          loading: false,
        },
        {
          column: "travel_details.mode_of_payment",
          label: "mode_of_payment",
          dataType: "text",
          backendDataType: "java.lang.String",
          condition: "IS_ONE_OF",
          values: ["Credit"],
          valuesMode: "custom",
          mode: "auto",
          orderBy: "",
          valuesRange: {},
          rangeValuesType: "",
          dateTimeToggle: false,
          rangeSelectionToggole: true,
          maxInput: "",
          minInput: "",
          valuesList: [],
          drillDownId: "",
          uid: "5c5a3eb6-60fa-4f00-80db-591c26c1eeb5",
          configId: "c0cc5501-e96a-44a9-a297-7b8c08702aef",
          dataId: "c117d2cc-908e-41ea-9265-6b74944dfd1c",
          mapping: {
            isEnabled: true,
            unique: true,
            isDefaultFunction: true,
            valueDisplayMap: [],
            valueAliasName: "random",
            orderBy: {
              display: "asc",
              value: "none",
            },
            valueDBFuntionInfo: {},
            valueColumn: {
              alias: "mode_of_payment",
              fullyQualifiedColumn: "travel_details.mode_of_payment",
              columnId: "b3044ece-20cc-4d60-bc0e-ae5ab1546184",
              defaultFunction: "none",
              type: {
                "java.lang.String": "text",
              },
            },
            displayColumn: {
              alias: "mode_of_payment",
              fullyQualifiedColumn: "travel_details.mode_of_payment",
              columnId: "b3044ece-20cc-4d60-bc0e-ae5ab1546184",
              defaultFunction: "none",
              type: {
                "java.lang.String": "text",
              },
            },
          },
          cascade: {
            isEnabled: false,
            filters: [],
            filtersCount: 0,
          },
          active: false,
          loading: false,
        },
      ],
      listeners: ["booking_platform", "mode_of_payment"],
      reportId: "2f9792ad-690c-4b25-9290-67ecb3aaa474",
      lastModified: 1662007943965,
    },
  ],
  layout: [
    {
      w: 2,
      h: 2,
      x: 4,
      y: 1,
      i: "item-niOMd",
      moved: false,
      static: false,
    },
  ],
  dashboardDrawerStatus: false,
  gridItemDrawerStatus: false,
  currentGroupId: "",
  groupId: "edit",
  gridItemId: "item-UQJ4Q",
  drawerPositions: ["right", "bottom", "left", "top"],
  currentDrawerPosition: 0,
  gridSettings: [
    {
      key: "breakpoints",
      values: [
        {
          key: "lg",
          name: "Large Screens",
          value: 1200,
          tooltip: "Large Screens(lg)",
        },
        {
          key: "md",
          name: "Medium Screens",
          value: 996,
          tooltip: "Medium Screens(md)",
        },
        {
          key: "sm",
          name: "Small Screens",
          value: 768,
          tooltip: "Small Screens(sm)",
        },
        {
          key: "xs",
          name: "Extra Small Screens",
          value: 480,
          tooltip: "Extra Small Screens(xs)",
        },
        {
          key: "xxs",
          name: "Extra Extra Small Screens",
          value: 240,
          tooltip: "Extra Extra Small Screens(xxs)",
        },
      ],
    },
    {
      key: "columns",
      values: [
        {
          key: "lg",
          name: "Large Screens",
          value: 12,
          tooltip: "Large Screens(lg)",
        },
        {
          key: "md",
          name: "Medium Screens",
          value: 12,
          tooltip: "Medium Screens(md)",
        },
        {
          key: "sm",
          name: "Small Screens",
          value: 6,
          tooltip: "Small Screens(sm)",
        },
        {
          key: "xs",
          name: "Extra Small Screens",
          value: 4,
          tooltip: "Extra Small Screens(xs)",
        },
        {
          key: "xxs",
          name: "Extra Extra Small Screens",
          value: 2,
          tooltip: "Extra Extra Small Screens(xxs)",
        },
      ],
    },
    {
      key: "grid",
      values: {
        autoSize: true,
        compactType: null,
        rowHeight: 100,
        isDroppable: false,
        preventCollision: true,
        measureBeforeMount: false,
        isDraggable: true,
        isResizable: true,
      },
    },
    {
      key: "header",
      values: {
        enable: false,
        title: "",
        placeholder: "Edit/Add your header content here",
        link: "",
        backgroundColor: {
          r: 255,
          g: 255,
          b: 255,
          a: 100,
        },
        position: "left",
      },
    },
    {
      key: "shadow",
      values: {
        enable: false,
        xOffset: 0,
        yOffset: 0,
        blur: 0,
        spread: 0,
        color: {
          r: 255,
          g: 255,
          b: 255,
          a: 100,
        },
      },
    },
    {
      key: "background",
      values: {
        enable: false,
        backgroundColor: {
          r: 255,
          g: 255,
          b: 255,
          a: 100,
        },
        image: "",
      },
    },
    {
      key: "border",
      values: {
        enable: false,
        borderWidth: 1,
        borderStyle: "solid",
        color: {
          r: 255,
          g: 255,
          b: 255,
          a: 100,
        },
      },
    },
    {
      key: "html",
      values: {
        enable: false,
        value: "",
      },
    },
    {
      key: "css",
      values: {
        enable: false,
        value: "",
      },
    },
    {
      key: "javascript",
      values: {
        enable: false,
        value: "",
      },
    },
  ],
  filterItemsData: [],
  maximizedGridItem: {},
  maximizingStatus: false,
  gridIndex: -3,
  isLoading: false,
  reportId: "",
  applyDashboardFilters: null,
  isSaving: false,
  expandDesignerDrawers: false,
  hasUnsavedData: true,
  itemAddedStatus: 1662014895879,
};

export const afterAddingFilter = {
  filterCounter: 2,
  parameterDrawerStatus: true,
  designerSettings: [
    {
      key: "parameters",
      values: {
        enable: true,
        orientation: "right",
        enableApplyButton: true,
      },
    },
  ],
  previewMode: false,
  designerMode: "create",
  dashboardVariables: {},
  dashboardUUID: "",
  variables: [],
  components: {},
  dashboardConfig: {
    id: "dashboard",
  },
  css: "",
  script: "",
  printOptions: {
    templateId: "Dashboard",
    title: "Dashboard",
  },
  componentSettings: {},
  toggleIframes: false,
  gridItemsData: [
    {
      id: "item-niOMd",
      compType: "dashboard-designer-component",
      isGrouped: false,
      isSaved: false,
      initialPosition: {
        x: 0,
        y: 0,
        w: 2,
        h: 2,
        i: "item-niOMd",
        static: false,
      },
      gridItemConfig: [
        {
          key: "header",
          values: {
            enable: true,
            title: "hreportWith2Filters",
            placeholder: "Edit/Add your header content here",
            link: "",
            backgroundColor: {
              r: 24,
              g: 144,
              b: 255,
              a: 100,
            },
            position: "left",
          },
        },
        {
          key: "shadow",
          values: {
            enable: false,
            xOffset: 1,
            yOffset: 1,
            blur: 1,
            spread: 1,
            color: {
              r: 24,
              g: 144,
              b: 255,
              a: 100,
            },
          },
        },
        {
          key: "background",
          values: {
            enable: false,
            backgroundColor: {
              r: 255,
              g: 255,
              b: 255,
              a: 100,
            },
            image: "",
          },
        },
        {
          key: "border",
          values: {
            enable: false,
            borderWidth: 1,
            borderStyle: "solid",
            color: {
              r: 24,
              g: 144,
              b: 255,
              a: 100,
            },
          },
        },
        {
          key: "html",
          values: {
            enable: false,
            value: "",
          },
        },
        {
          key: "css",
          values: {
            enable: false,
            value: "",
          },
        },
        {
          key: "javascript",
          values: {
            enable: false,
            value: "",
          },
        },
        {
          key: "griditemsettings",
          values: {
            export: false,
            edit: false,
            maximize: false,
          },
        },
      ],
      reportInfo: {
        file: {
          path: "sai_ganesh/hreportWith2Filters.hr",
          name: "hreportWith2Filters.hr",
          title: "hreportWith2Filters",
        },
        mode: "dashboard",
        filters: [],
        component: "hreport",
        extension: "hr",
      },
      filters: [
        {
          column: "travel_details.booking_platform",
          label: "booking_platform",
          dataType: "text",
          backendDataType: "java.lang.String",
          condition: "IS_ONE_OF",
          values: ["Makemytrip"],
          valuesMode: "custom",
          mode: "auto",
          orderBy: "",
          valuesRange: {},
          rangeValuesType: "",
          dateTimeToggle: false,
          rangeSelectionToggole: true,
          maxInput: "",
          minInput: "",
          valuesList: [],
          drillDownId: "",
          uid: "104e3760-ac86-4372-ba7b-0f69187d1753",
          configId: "be93b3c2-7d45-4cbb-9007-78bd691b5266",
          dataId: "8120f657-781a-4751-8e91-e144a9fd8734",
          mapping: {
            isEnabled: true,
            unique: true,
            isDefaultFunction: true,
            valueDisplayMap: [],
            valueAliasName: "random",
            orderBy: {
              display: "asc",
              value: "none",
            },
            valueDBFuntionInfo: {},
            valueColumn: {
              alias: "booking_platform",
              fullyQualifiedColumn: "travel_details.booking_platform",
              columnId: "27f17a28-3282-4a1b-9aaf-fdb706938c9e",
              defaultFunction: "none",
              type: {
                "java.lang.String": "text",
              },
            },
            displayColumn: {
              alias: "booking_platform",
              fullyQualifiedColumn: "travel_details.booking_platform",
              columnId: "27f17a28-3282-4a1b-9aaf-fdb706938c9e",
              defaultFunction: "none",
              type: {
                "java.lang.String": "text",
              },
            },
          },
          cascade: {
            isEnabled: false,
            filters: [],
            filtersCount: 0,
          },
          active: false,
          loading: false,
        },
        {
          column: "travel_details.mode_of_payment",
          label: "mode_of_payment",
          dataType: "text",
          backendDataType: "java.lang.String",
          condition: "IS_ONE_OF",
          values: ["Credit"],
          valuesMode: "custom",
          mode: "auto",
          orderBy: "",
          valuesRange: {},
          rangeValuesType: "",
          dateTimeToggle: false,
          rangeSelectionToggole: true,
          maxInput: "",
          minInput: "",
          valuesList: [],
          drillDownId: "",
          uid: "5c5a3eb6-60fa-4f00-80db-591c26c1eeb5",
          configId: "c0cc5501-e96a-44a9-a297-7b8c08702aef",
          dataId: "c117d2cc-908e-41ea-9265-6b74944dfd1c",
          mapping: {
            isEnabled: true,
            unique: true,
            isDefaultFunction: true,
            valueDisplayMap: [],
            valueAliasName: "random",
            orderBy: {
              display: "asc",
              value: "none",
            },
            valueDBFuntionInfo: {},
            valueColumn: {
              alias: "mode_of_payment",
              fullyQualifiedColumn: "travel_details.mode_of_payment",
              columnId: "b3044ece-20cc-4d60-bc0e-ae5ab1546184",
              defaultFunction: "none",
              type: {
                "java.lang.String": "text",
              },
            },
            displayColumn: {
              alias: "mode_of_payment",
              fullyQualifiedColumn: "travel_details.mode_of_payment",
              columnId: "b3044ece-20cc-4d60-bc0e-ae5ab1546184",
              defaultFunction: "none",
              type: {
                "java.lang.String": "text",
              },
            },
          },
          cascade: {
            isEnabled: false,
            filters: [],
            filtersCount: 0,
          },
          active: false,
          loading: false,
        },
      ],
      listeners: ["booking_platform", "mode_of_payment"],
      reportId: "2f9792ad-690c-4b25-9290-67ecb3aaa474",
      lastModified: 1662007943965,
    },
    {
      id: "item-vzeLA",
      compType: "filter",
      index: 1,
      key: "2",
      reportInfo: {
        file: {
          path: "sai_ganesh/hreportWith2Filters.hr",
          name: "hreportWith2Filters.hr",
          title: "hreportWith2Filters",
        },
        mode: "filter",
        filters: [],
        component: "hreport",
        extension: "hr",
      },
      parameter: {
        dashboardFilter: {
          columnName: "booking_platform",
          uid: "104e3760-ac86-4372-ba7b-0f69187d1753",
        },
      },
      filters: [
        {
          column: "travel_details.booking_platform",
          label: "booking_platform",
          dataType: "text",
          backendDataType: "java.lang.String",
          condition: "IS_ONE_OF",
          values: ["Makemytrip"],
          valuesMode: "custom",
          mode: "auto",
          orderBy: "",
          valuesRange: {},
          rangeValuesType: "",
          dateTimeToggle: false,
          rangeSelectionToggole: true,
          maxInput: "",
          minInput: "",
          valuesList: [],
          drillDownId: "",
          uid: "104e3760-ac86-4372-ba7b-0f69187d1753",
          configId: "be93b3c2-7d45-4cbb-9007-78bd691b5266",
          dataId: "8120f657-781a-4751-8e91-e144a9fd8734",
          mapping: {
            isEnabled: true,
            unique: true,
            isDefaultFunction: true,
            valueDisplayMap: [],
            valueAliasName: "random",
            orderBy: {
              display: "asc",
              value: "none",
            },
            valueDBFuntionInfo: {},
            valueColumn: {
              alias: "booking_platform",
              fullyQualifiedColumn: "travel_details.booking_platform",
              columnId: "27f17a28-3282-4a1b-9aaf-fdb706938c9e",
              defaultFunction: "none",
              type: {
                "java.lang.String": "text",
              },
            },
            displayColumn: {
              alias: "booking_platform",
              fullyQualifiedColumn: "travel_details.booking_platform",
              columnId: "27f17a28-3282-4a1b-9aaf-fdb706938c9e",
              defaultFunction: "none",
              type: {
                "java.lang.String": "text",
              },
            },
          },
          cascade: {
            isEnabled: false,
            filters: [],
            filtersCount: 0,
          },
          active: false,
          loading: false,
        },
        {
          column: "travel_details.mode_of_payment",
          label: "mode_of_payment",
          dataType: "text",
          backendDataType: "java.lang.String",
          condition: "IS_ONE_OF",
          values: ["Credit"],
          valuesMode: "custom",
          mode: "auto",
          orderBy: "",
          valuesRange: {},
          rangeValuesType: "",
          dateTimeToggle: false,
          rangeSelectionToggole: true,
          maxInput: "",
          minInput: "",
          valuesList: [],
          drillDownId: "",
          uid: "5c5a3eb6-60fa-4f00-80db-591c26c1eeb5",
          configId: "c0cc5501-e96a-44a9-a297-7b8c08702aef",
          dataId: "c117d2cc-908e-41ea-9265-6b74944dfd1c",
          mapping: {
            isEnabled: true,
            unique: true,
            isDefaultFunction: true,
            valueDisplayMap: [],
            valueAliasName: "random",
            orderBy: {
              display: "asc",
              value: "none",
            },
            valueDBFuntionInfo: {},
            valueColumn: {
              alias: "mode_of_payment",
              fullyQualifiedColumn: "travel_details.mode_of_payment",
              columnId: "b3044ece-20cc-4d60-bc0e-ae5ab1546184",
              defaultFunction: "none",
              type: {
                "java.lang.String": "text",
              },
            },
            displayColumn: {
              alias: "mode_of_payment",
              fullyQualifiedColumn: "travel_details.mode_of_payment",
              columnId: "b3044ece-20cc-4d60-bc0e-ae5ab1546184",
              defaultFunction: "none",
              type: {
                "java.lang.String": "text",
              },
            },
          },
          cascade: {
            isEnabled: false,
            filters: [],
            filtersCount: 0,
          },
          active: false,
          loading: false,
        },
      ],
      listeners: ["booking_platform", "mode_of_payment"],
      reportId: "e03dd4b6-71a7-4fb6-b64c-1b6134a1deae",
    },
  ],
  layout: [
    {
      w: 2,
      h: 2,
      x: 4,
      y: 1,
      i: "item-niOMd",
      moved: false,
      static: false,
    },
  ],
  dashboardDrawerStatus: false,
  gridItemDrawerStatus: false,
  currentGroupId: "",
  groupId: "edit",
  gridItemId: "item-UQJ4Q",
  drawerPositions: ["right", "bottom", "left", "top"],
  currentDrawerPosition: 0,
  gridSettings: [
    {
      key: "breakpoints",
      values: [
        {
          key: "lg",
          name: "Large Screens",
          value: 1200,
          tooltip: "Large Screens(lg)",
        },
        {
          key: "md",
          name: "Medium Screens",
          value: 996,
          tooltip: "Medium Screens(md)",
        },
        {
          key: "sm",
          name: "Small Screens",
          value: 768,
          tooltip: "Small Screens(sm)",
        },
        {
          key: "xs",
          name: "Extra Small Screens",
          value: 480,
          tooltip: "Extra Small Screens(xs)",
        },
        {
          key: "xxs",
          name: "Extra Extra Small Screens",
          value: 240,
          tooltip: "Extra Extra Small Screens(xxs)",
        },
      ],
    },
    {
      key: "columns",
      values: [
        {
          key: "lg",
          name: "Large Screens",
          value: 12,
          tooltip: "Large Screens(lg)",
        },
        {
          key: "md",
          name: "Medium Screens",
          value: 12,
          tooltip: "Medium Screens(md)",
        },
        {
          key: "sm",
          name: "Small Screens",
          value: 6,
          tooltip: "Small Screens(sm)",
        },
        {
          key: "xs",
          name: "Extra Small Screens",
          value: 4,
          tooltip: "Extra Small Screens(xs)",
        },
        {
          key: "xxs",
          name: "Extra Extra Small Screens",
          value: 2,
          tooltip: "Extra Extra Small Screens(xxs)",
        },
      ],
    },
    {
      key: "grid",
      values: {
        autoSize: true,
        compactType: null,
        rowHeight: 100,
        isDroppable: false,
        preventCollision: true,
        measureBeforeMount: false,
        isDraggable: true,
        isResizable: true,
      },
    },
    {
      key: "header",
      values: {
        enable: false,
        title: "",
        placeholder: "Edit/Add your header content here",
        link: "",
        backgroundColor: {
          r: 255,
          g: 255,
          b: 255,
          a: 100,
        },
        position: "left",
      },
    },
    {
      key: "shadow",
      values: {
        enable: false,
        xOffset: 0,
        yOffset: 0,
        blur: 0,
        spread: 0,
        color: {
          r: 255,
          g: 255,
          b: 255,
          a: 100,
        },
      },
    },
    {
      key: "background",
      values: {
        enable: false,
        backgroundColor: {
          r: 255,
          g: 255,
          b: 255,
          a: 100,
        },
        image: "",
      },
    },
    {
      key: "border",
      values: {
        enable: false,
        borderWidth: 1,
        borderStyle: "solid",
        color: {
          r: 255,
          g: 255,
          b: 255,
          a: 100,
        },
      },
    },
    {
      key: "html",
      values: {
        enable: false,
        value: "",
      },
    },
    {
      key: "css",
      values: {
        enable: false,
        value: "",
      },
    },
    {
      key: "javascript",
      values: {
        enable: false,
        value: "",
      },
    },
  ],
  filterItemsData: [],
  maximizedGridItem: {},
  maximizingStatus: false,
  gridIndex: -3,
  isLoading: false,
  reportId: "",
  applyDashboardFilters: null,
  isSaving: false,
  expandDesignerDrawers: false,
  hasUnsavedData: true,
  itemAddedStatus: 1662014895879,
};
