export const mock_data = {
     data_1 :{
        type: "metadata_field",
        field: {
          columnName: "destination_id",
          column: {
            alias: "destination_id",
            fullyQualifiedColumn: "travel_details.destination_id",
            id: "43083",
            defaultFunction: "db.generic.aggregate.sum",
            type: {
              "java.lang.Integer": "numeric",
            },
          },
          table: {
            id: "14467",
            alias: "travel_details",
            columns: {
              travel_id: {
                alias: "travel_id",
                fullyQualifiedColumn: "travel_details.travel_id",
                id: "43077",
                defaultFunction: "db.generic.aggregate.sum",
                type: {
                  "java.lang.Integer": "numeric",
                },
              },
              travel_date: {
                alias: "travel_date",
                fullyQualifiedColumn: "travel_details.travel_date",
                id: "43078",
                defaultFunction: "db.generic.groupBy.group",
                type: {
                  "java.lang.String": "text",
                },
              },
              travel_type: {
                alias: "travel_type",
                fullyQualifiedColumn: "travel_details.travel_type",
                id: "43079",
                defaultFunction: "db.generic.groupBy.group",
                type: {
                  "java.lang.String": "text",
                },
              },
              travel_medium: {
                alias: "travel_medium",
                fullyQualifiedColumn: "travel_details.travel_medium",
                id: "43080",
                defaultFunction: "db.generic.groupBy.group",
                type: {
                  "java.lang.String": "text",
                },
              },
              source_id: {
                alias: "source_id",
                fullyQualifiedColumn: "travel_details.source_id",
                id: "43081",
                defaultFunction: "db.generic.aggregate.sum",
                type: {
                  "java.lang.Integer": "numeric",
                },
              },
              source: {
                alias: "source",
                fullyQualifiedColumn: "travel_details.source",
                id: "43082",
                defaultFunction: "db.generic.groupBy.group",
                type: {
                  "java.lang.String": "text",
                },
              },
              destination_id: {
                alias: "destination_id",
                fullyQualifiedColumn: "travel_details.destination_id",
                id: "43083",
                defaultFunction: "db.generic.aggregate.sum",
                type: {
                  "java.lang.Integer": "numeric",
                },
              },
              destination: {
                alias: "destination",
                fullyQualifiedColumn: "travel_details.destination",
                id: "43084",
                defaultFunction: "db.generic.groupBy.group",
                type: {
                  "java.lang.String": "text",
                },
              },
              travel_cost: {
                alias: "travel_cost",
                fullyQualifiedColumn: "travel_details.travel_cost",
                id: "43085",
                defaultFunction: "db.generic.aggregate.sum",
                type: {
                  "java.lang.Integer": "numeric",
                },
              },
              mode_of_payment: {
                alias: "mode_of_payment",
                fullyQualifiedColumn: "travel_details.mode_of_payment",
                id: "43086",
                defaultFunction: "db.generic.groupBy.group",
                type: {
                  "java.lang.String": "text",
                },
              },
              booking_platform: {
                alias: "booking_platform",
                fullyQualifiedColumn: "travel_details.booking_platform",
                id: "43087",
                defaultFunction: "db.generic.groupBy.group",
                type: {
                  "java.lang.String": "text",
                },
              },
              travelled_by: {
                alias: "travelled_by",
                fullyQualifiedColumn: "travel_details.travelled_by",
                id: "43088",
                defaultFunction: "db.generic.aggregate.sum",
                type: {
                  "java.lang.Integer": "numeric",
                },
              },
            },
            name: "travel_details",
            cacheId: "21e1b86ae9680d0fc197ed543c3e37eb",
            key: "a92ed91c-0ba1-4656-90ab-047642f917d5",
          },
          type: {
            "java.lang.Integer": "numeric",
          },
          defaultFunction: "db.generic.aggregate.sum",
          key: "43083",
          columnId: "43083",
          alias: "destination_id",
          tableId: "14467",
          dataType: "numeric",
          tableName: "travel_details",
          tableAlias: "travel_details",
          dataSource: {
            databaseName: "",
            catalog: "",
            schema: "",
          },
        },
        markType: "color",
        mark: {
          value: "_all_",
          id: "3348bf79-f51a-40a7-8142-69416cdead28",
          subVizType: "",
          color: {
            fields: [],
          },
          size: {
            fields: [],
          },
          label: {
            fields: [],
          },
          tooltip: {
            fields: [],
          },
          shape: {
            fields: [],
          },
          detail: {
            fields: [],
          },
        },
        fields: [
          {
            column: "travel_details.booking_platform",
            columnID: "43087",
            label: "booking_platform",
            id: "e01007ab-183a-43cd-a7a9-6a0c6fa59971",
            type: {
              backendDataType: "java.lang.String",
              dataType: "text",
            },
            autogen_alias: "booking_platform",
            isNormalTable: true,
            tableAlias: "travel_details",
            groupBy: ["db.generic.groupBy.group"],
            orderByColumn: false,
            showOrderByColumn: false,
            addedAs: "column",
            floatingType: "discrete",
            functionsDefinition: "",
            applyBeforeAggregate: false,
            hiddenIncludeInResultSet: false,
            metaDataAlias: "booking_platform",
            databaseName: "",
          },
          {
            column: "travel_details.source_id",
            columnID: "43081",
            label: "sum_source_id",
            id: "bd2e2b56-ea2b-45a0-8dc9-1a8e707db2d2",
            type: {
              backendDataType: "java.lang.Integer",
              dataType: "numeric",
            },
            autogen_alias: "sum_source_id",
            isNormalTable: true,
            tableAlias: "travel_details",
            aggregate: ["db.generic.aggregate.sum"],
            orderByColumn: false,
            showOrderByColumn: false,
            addedAs: "row",
            floatingType: "",
            functionsDefinition: "",
            applyBeforeAggregate: false,
            hiddenIncludeInResultSet: false,
            metaDataAlias: "source_id",
            databaseName: "",
          },
        ],
      },
      expectedResult_1 :{
        payload: {
          addedAs: "color",
          column: {
            alias: "destination_id",
            defaultFunction: "db.generic.aggregate.sum",
            fullyQualifiedColumn: "travel_details.destination_id",
            id: "43083",
            type: { "java.lang.Integer": "numeric" },
          },
          mark: {
            color: { fields: [] },
            detail: { fields: [] },
            id: "3348bf79-f51a-40a7-8142-69416cdead28",
            label: { fields: [] },
            shape: { fields: [] },
            size: { fields: [] },
            subVizType: "",
            tooltip: { fields: [] },
            value: "_all_",
          },
          markType: "color",
          table: {
            alias: "travel_details",
            cacheId: "21e1b86ae9680d0fc197ed543c3e37eb",
            columns: {
              booking_platform: {
                alias: "booking_platform",
                defaultFunction: "db.generic.groupBy.group",
                fullyQualifiedColumn: "travel_details.booking_platform",
                id: "43087",
                type: { "java.lang.String": "text" },
              },
              destination: {
                alias: "destination",
                defaultFunction: "db.generic.groupBy.group",
                fullyQualifiedColumn: "travel_details.destination",
                id: "43084",
                type: { "java.lang.String": "text" },
              },
              destination_id: {
                alias: "destination_id",
                defaultFunction: "db.generic.aggregate.sum",
                fullyQualifiedColumn: "travel_details.destination_id",
                id: "43083",
                type: { "java.lang.Integer": "numeric" },
              },
              mode_of_payment: {
                alias: "mode_of_payment",
                defaultFunction: "db.generic.groupBy.group",
                fullyQualifiedColumn: "travel_details.mode_of_payment",
                id: "43086",
                type: { "java.lang.String": "text" },
              },
              source: {
                alias: "source",
                defaultFunction: "db.generic.groupBy.group",
                fullyQualifiedColumn: "travel_details.source",
                id: "43082",
                type: { "java.lang.String": "text" },
              },
              source_id: {
                alias: "source_id",
                defaultFunction: "db.generic.aggregate.sum",
                fullyQualifiedColumn: "travel_details.source_id",
                id: "43081",
                type: { "java.lang.Integer": "numeric" },
              },
              travel_cost: {
                alias: "travel_cost",
                defaultFunction: "db.generic.aggregate.sum",
                fullyQualifiedColumn: "travel_details.travel_cost",
                id: "43085",
                type: { "java.lang.Integer": "numeric" },
              },
              travel_date: {
                alias: "travel_date",
                defaultFunction: "db.generic.groupBy.group",
                fullyQualifiedColumn: "travel_details.travel_date",
                id: "43078",
                type: { "java.lang.String": "text" },
              },
              travel_id: {
                alias: "travel_id",
                defaultFunction: "db.generic.aggregate.sum",
                fullyQualifiedColumn: "travel_details.travel_id",
                id: "43077",
                type: { "java.lang.Integer": "numeric" },
              },
              travel_medium: {
                alias: "travel_medium",
                defaultFunction: "db.generic.groupBy.group",
                fullyQualifiedColumn: "travel_details.travel_medium",
                id: "43080",
                type: { "java.lang.String": "text" },
              },
              travel_type: {
                alias: "travel_type",
                defaultFunction: "db.generic.groupBy.group",
                fullyQualifiedColumn: "travel_details.travel_type",
                id: "43079",
                type: { "java.lang.String": "text" },
              },
              travelled_by: {
                alias: "travelled_by",
                defaultFunction: "db.generic.aggregate.sum",
                fullyQualifiedColumn: "travel_details.travelled_by",
                id: "43088",
                type: { "java.lang.Integer": "numeric" },
              },
            },
            id: "14467",
            key: "a92ed91c-0ba1-4656-90ab-047642f917d5",
            name: "travel_details",
          },
        },
        type: "ADD_FIELD_TO_CANVAS",
      },
      data_2: {
        type: "metadata_field",
        field: {
          columnName: "date_key",
          column: {
            alias: "date_key",
            fullyQualifiedColumn: "dimdate.date_key",
            id: "42952",
            defaultFunction: "db.generic.groupBy.group",
            type: {
              "java.lang.String": "text",
            },
          },
          table: {
            id: "14450",
            alias: "dimdate_1",
            columns: {
              dim_id: {
                alias: "dim_id",
                fullyQualifiedColumn: "dimdate.dim_id",
                id: "42949",
                defaultFunction: "db.generic.aggregate.sum",
                type: {
                  "java.lang.Integer": "numeric",
                },
              },
              fiscal_year: {
                alias: "fiscal_year",
                fullyQualifiedColumn: "dimdate.fiscal_year",
                id: "42950",
                defaultFunction: "db.generic.groupBy.group",
                type: {
                  "java.lang.String": "text",
                },
              },
              modified_date: {
                alias: "modified_date",
                fullyQualifiedColumn: "dimdate.modified_date",
                id: "42951",
                defaultFunction: "db.generic.groupBy.group",
                type: {
                  "java.lang.String": "text",
                },
              },
              date_key: {
                alias: "date_key",
                fullyQualifiedColumn: "dimdate.date_key",
                id: "42952",
                defaultFunction: "db.generic.groupBy.group",
                type: {
                  "java.lang.String": "text",
                },
              },
              day_number: {
                alias: "day_number",
                fullyQualifiedColumn: "dimdate.day_number",
                id: "42953",
                defaultFunction: "db.generic.groupBy.group",
                type: {
                  "java.lang.String": "text",
                },
              },
              fiscal_month_name: {
                alias: "fiscal_month_name",
                fullyQualifiedColumn: "dimdate.fiscal_month_name",
                id: "42954",
                defaultFunction: "db.generic.groupBy.group",
                type: {
                  "java.lang.String": "text",
                },
              },
              fiscal_month_label: {
                alias: "fiscal_month_label",
                fullyQualifiedColumn: "dimdate.fiscal_month_label",
                id: "42955",
                defaultFunction: "db.generic.groupBy.group",
                type: {
                  "java.lang.String": "text",
                },
              },
              created_date: {
                alias: "created_date",
                fullyQualifiedColumn: "dimdate.created_date",
                id: "42956",
                defaultFunction: "db.generic.groupBy.group",
                type: {
                  "java.lang.String": "text",
                },
              },
              created_time: {
                alias: "created_time",
                fullyQualifiedColumn: "dimdate.created_time",
                id: "42957",
                defaultFunction: "db.generic.groupBy.group",
                type: {
                  "java.lang.String": "text",
                },
              },
              rating: {
                alias: "rating",
                fullyQualifiedColumn: "dimdate.rating",
                id: "42958",
                defaultFunction: "db.generic.groupBy.group",
                type: {
                  "java.lang.String": "text",
                },
              },
            },
            name: "dimdate",
            cacheId: "d324e793296ff76020c708f1c8fbb704",
            key: "352e687f-0364-424e-9b90-fa34a6dd2301",
          },
          type: {
            "java.lang.String": "text",
          },
          defaultFunction: "db.generic.groupBy.group",
          key: "42952",
          columnId: "42952",
          alias: "date_key",
          tableId: "14450",
          dataType: "text",
          tableName: "dimdate",
          tableAlias: "dimdate_1",
          dataSource: {
            databaseName: "",
            catalog: "",
            schema: "",
            connectionDatabaseId: "13015",
          },
        },
        markType: "size",
        mark: {
          value: "_all_",
          id: "a1510e9e-ec5f-4390-bab7-f3a2686999c7",
          subVizType: "",
          color: {
            fields: [],
          },
          size: {
            fields: [],
          },
          label: {
            fields: [],
          },
          tooltip: {
            fields: [],
          },
          shape: {
            fields: [],
          },
          detail: {
            fields: [],
          },
        },
        fields: [
          {
            column: "dimdate.created_date",
            columnID: "42956",
            label: "created_date",
            id: "4defb070-3563-426f-91e8-f2ad0ae5677e",
            type: {
              backendDataType: "java.lang.String",
              dataType: "text",
            },
            autogen_alias: "created_date",
            isNormalTable: true,
            tableAlias: "dimdate_1",
            groupBy: ["db.generic.groupBy.group"],
            orderByColumn: false,
            showOrderByColumn: false,
            addedAs: "column",
            floatingType: "discrete",
            functionsDefinition: "",
            applyBeforeAggregate: false,
            hiddenIncludeInResultSet: false,
            metaDataAlias: "created_date",
            databaseName: "",
          },
          {
            column: "dimdate.dim_id",
            columnID: "42949",
            label: "sum_dim_id",
            id: "9614448c-9474-48a1-9708-a802cdad66be",
            type: {
              backendDataType: "java.lang.Integer",
              dataType: "numeric",
            },
            autogen_alias: "sum_dim_id",
            isNormalTable: true,
            tableAlias: "dimdate_1",
            aggregate: ["db.generic.aggregate.sum"],
            orderByColumn: false,
            showOrderByColumn: false,
            addedAs: "row",
            floatingType: "",
            functionsDefinition: "",
            applyBeforeAggregate: false,
            hiddenIncludeInResultSet: false,
            metaDataAlias: "dim_id",
            databaseName: "",
          },
        ],
      },
      expectedResult_2 : {
        payload: {
          addedAs: "size",
          column: {
            alias: "date_key",
            defaultFunction: "db.generic.groupBy.group",
            fullyQualifiedColumn: "dimdate.date_key",
            id: "42952",
            type: { "java.lang.String": "text" },
          },
          mark: {
            color: { fields: [] },
            detail: { fields: [] },
            id: "a1510e9e-ec5f-4390-bab7-f3a2686999c7",
            label: { fields: [] },
            shape: { fields: [] },
            size: { fields: [] },
            subVizType: "",
            tooltip: { fields: [] },
            value: "_all_",
          },
          markType: "size",
          table: {
            alias: "dimdate_1",
            cacheId: "d324e793296ff76020c708f1c8fbb704",
            columns: {
              created_date: {
                alias: "created_date",
                defaultFunction: "db.generic.groupBy.group",
                fullyQualifiedColumn: "dimdate.created_date",
                id: "42956",
                type: { "java.lang.String": "text" },
              },
              created_time: {
                alias: "created_time",
                defaultFunction: "db.generic.groupBy.group",
                fullyQualifiedColumn: "dimdate.created_time",
                id: "42957",
                type: { "java.lang.String": "text" },
              },
              date_key: {
                alias: "date_key",
                defaultFunction: "db.generic.groupBy.group",
                fullyQualifiedColumn: "dimdate.date_key",
                id: "42952",
                type: { "java.lang.String": "text" },
              },
              day_number: {
                alias: "day_number",
                defaultFunction: "db.generic.groupBy.group",
                fullyQualifiedColumn: "dimdate.day_number",
                id: "42953",
                type: { "java.lang.String": "text" },
              },
              dim_id: {
                alias: "dim_id",
                defaultFunction: "db.generic.aggregate.sum",
                fullyQualifiedColumn: "dimdate.dim_id",
                id: "42949",
                type: { "java.lang.Integer": "numeric" },
              },
              fiscal_month_label: {
                alias: "fiscal_month_label",
                defaultFunction: "db.generic.groupBy.group",
                fullyQualifiedColumn: "dimdate.fiscal_month_label",
                id: "42955",
                type: { "java.lang.String": "text" },
              },
              fiscal_month_name: {
                alias: "fiscal_month_name",
                defaultFunction: "db.generic.groupBy.group",
                fullyQualifiedColumn: "dimdate.fiscal_month_name",
                id: "42954",
                type: { "java.lang.String": "text" },
              },
              fiscal_year: {
                alias: "fiscal_year",
                defaultFunction: "db.generic.groupBy.group",
                fullyQualifiedColumn: "dimdate.fiscal_year",
                id: "42950",
                type: { "java.lang.String": "text" },
              },
              modified_date: {
                alias: "modified_date",
                defaultFunction: "db.generic.groupBy.group",
                fullyQualifiedColumn: "dimdate.modified_date",
                id: "42951",
                type: { "java.lang.String": "text" },
              },
              rating: {
                alias: "rating",
                defaultFunction: "db.generic.groupBy.group",
                fullyQualifiedColumn: "dimdate.rating",
                id: "42958",
                type: { "java.lang.String": "text" },
              },
            },
            id: "14450",
            key: "352e687f-0364-424e-9b90-fa34a6dd2301",
            name: "dimdate",
          },
        },
        type: "ADD_FIELD_TO_CANVAS",
      },
      data_3 : {
        type: "metadata_field",
        field: {
          columnName: "location_id",
          column: {
            alias: "location_id",
            fullyQualifiedColumn: "geo_cordinates.location_id",
            id: "42921",
            defaultFunction: "db.generic.aggregate.sum",
            type: {
              "java.lang.Integer": "numeric",
            },
          },
          table: {
            id: "14446",
            alias: "geo_cordinates",
            columns: {
              location_id: {
                alias: "location_id",
                fullyQualifiedColumn: "geo_cordinates.location_id",
                id: "42921",
                defaultFunction: "db.generic.aggregate.sum",
                type: {
                  "java.lang.Integer": "numeric",
                },
              },
              location: {
                alias: "location",
                fullyQualifiedColumn: "geo_cordinates.location",
                id: "42922",
                defaultFunction: "db.generic.groupBy.group",
                type: {
                  "java.lang.String": "text",
                },
              },
              latitude: {
                alias: "latitude",
                fullyQualifiedColumn: "geo_cordinates.latitude",
                id: "42923",
                defaultFunction: "db.generic.aggregate.sum",
                type: {
                  "java.lang.Float": "numeric",
                },
              },
              longitude: {
                alias: "longitude",
                fullyQualifiedColumn: "geo_cordinates.longitude",
                id: "42924",
                defaultFunction: "db.generic.aggregate.sum",
                type: {
                  "java.lang.Float": "numeric",
                },
              },
            },
            name: "geo_cordinates",
            cacheId: "f2ff93c37589ef57f40dcb15fda6d7ea",
            key: "0ee8d36f-0eb9-4bb6-b711-d45d64fe265e",
          },
          type: {
            "java.lang.Integer": "numeric",
          },
          defaultFunction: "db.generic.aggregate.sum",
          key: "42921",
          columnId: "42921",
          alias: "location_id",
          tableId: "14446",
          dataType: "numeric",
          tableName: "geo_cordinates",
          tableAlias: "geo_cordinates",
          dataSource: {
            databaseName: "",
            catalog: "",
            schema: "",
          },
        },
        markType: "color",
        mark: {
          value: "_all_",
          id: "51292fb1-ffb3-40d3-9bcf-d293e10f379e",
          subVizType: "",
          color: {
            fields: [],
          },
          size: {
            fields: [],
          },
          label: {
            fields: [],
          },
          tooltip: {
            fields: [],
          },
          shape: {
            fields: [],
          },
          detail: {
            fields: [],
          },
        },
        fields: [
          {
            column: "geo_cordinates.location_id",
            columnID: "42921",
            label: "sum_location_id",
            id: "88879cbb-ff1c-4ebe-942d-70ed141b0a63",
            type: {
              backendDataType: "java.lang.Integer",
              dataType: "numeric",
            },
            autogen_alias: "sum_location_id",
            isNormalTable: true,
            tableAlias: "geo_cordinates",
            aggregate: ["db.generic.aggregate.sum"],
            orderByColumn: false,
            showOrderByColumn: false,
            addedAs: "row",
            floatingType: "",
            functionsDefinition: "",
            applyBeforeAggregate: false,
            hiddenIncludeInResultSet: false,
            metaDataAlias: "location_id",
            databaseName: "",
          },
          {
            column: "geo_cordinates.location",
            columnID: "42922",
            label: "location",
            id: "cb016898-2799-4fb1-88b3-c5d1b0b126dd",
            type: {
              backendDataType: "java.lang.String",
              dataType: "text",
            },
            autogen_alias: "location",
            isNormalTable: true,
            tableAlias: "geo_cordinates",
            groupBy: ["db.generic.groupBy.group"],
            orderByColumn: false,
            showOrderByColumn: false,
            addedAs: "column",
            floatingType: "discrete",
            functionsDefinition: "",
            applyBeforeAggregate: false,
            hiddenIncludeInResultSet: false,
            metaDataAlias: "location",
            databaseName: "",
          },
        ],
      } ,
      expectedResult_3 : {
        payload: {
          addedAs: "color",
          column: {
            alias: "location_id",
            defaultFunction: "db.generic.aggregate.sum",
            fullyQualifiedColumn: "geo_cordinates.location_id",
            id: "42921",
            type: { "java.lang.Integer": "numeric" },
          },
          mark: {
            color: { fields: [] },
            detail: { fields: [] },
            id: "51292fb1-ffb3-40d3-9bcf-d293e10f379e",
            label: { fields: [] },
            shape: { fields: [] },
            size: { fields: [] },
            subVizType: "",
            tooltip: { fields: [] },
            value: "_all_",
          },
          markType: "color",
          table: {
            alias: "geo_cordinates",
            cacheId: "f2ff93c37589ef57f40dcb15fda6d7ea",
            columns: {
              latitude: {
                alias: "latitude",
                defaultFunction: "db.generic.aggregate.sum",
                fullyQualifiedColumn: "geo_cordinates.latitude",
                id: "42923",
                type: { "java.lang.Float": "numeric" },
              },
              location: {
                alias: "location",
                defaultFunction: "db.generic.groupBy.group",
                fullyQualifiedColumn: "geo_cordinates.location",
                id: "42922",
                type: { "java.lang.String": "text" },
              },
              location_id: {
                alias: "location_id",
                defaultFunction: "db.generic.aggregate.sum",
                fullyQualifiedColumn: "geo_cordinates.location_id",
                id: "42921",
                type: { "java.lang.Integer": "numeric" },
              },
              longitude: {
                alias: "longitude",
                defaultFunction: "db.generic.aggregate.sum",
                fullyQualifiedColumn: "geo_cordinates.longitude",
                id: "42924",
                type: { "java.lang.Float": "numeric" },
              },
            },
            id: "14446",
            key: "0ee8d36f-0eb9-4bb6-b711-d45d64fe265e",
            name: "geo_cordinates",
          },
        },
        type: "ADD_FIELD_TO_CANVAS",
      }
}