#Configure these properties based on your environment. 
#The following properties are used for login related db transactions.

#Remote server

user=${dbUser}
password=${dbPassword}
portNumber=${dbPort}
databaseName=${dbName}
serverName=${dbServer}

#Local Server

#user=postgres
#password=postgres
#portNumber=5433
#databaseName=hdi
#serverName=localhost
