# suppress inspection "UnusedProperty" for whole file
# Root logger option
name=PropertiesConfig
#property.filename = logs
appenders = console,file
appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

#Redirect log messages to a rolling log file
appender.file.type = RollingFile
appender.file.name = FileLogger
appender.file.fileName =${hiRepositoryPath}/System/Logs/helical-insight.log
appender.file.filePattern = ${hiRepositoryPath}/System/Logs/helical-insight-%i.log
appender.file.layout.type = PatternLayout
appender.file.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
appender.file.policies.type = Policies
appender.file.policies.size.type = SizeBasedTriggeringPolicy
appender.file.policies.size.size = 10MB
appender.file.strategy.type = DefaultRolloverStrategy
appender.file.strategy.max = 10

logger.hibernate.name=org.hibernate
logger.hibernate.level=OFF
logger.hibernatecache.name=org.hibernate.cache
logger.hibernatecache.level=OFF
logger.springframework.name=org.springframework
logger.springframework.level=OFF
logger.apachecommon.name=org.apache.commons
logger.apachecommon.level=OFF
logger.hiefw.name=com.helicalinsight.efw.framework.ApplicationWatcherUtils
logger.hiefw.level=OFF

rootLogger.level = error
rootLogger.appenderRefs = stdout,file
rootLogger.appenderRef.stdout.ref = STDOUT
rootLogger.appenderRef.file.ref = FileLogger