# suppress inspection "UnusedProperty" for whole file
png=image/png
jpeg=image/jpeg
jpg=image/jpeg
pdf=application/pdf
html=text/html
xls=application/excel
csv=application/octet-stream
docx=application/vnd.openxmlformats-officedocument.wordprocessingml.document
default-content-type=application/json
default-charset=UTF-8
xml=text/xml
rtf=application/rtf
odt=application/vnd.oasis.opendocument.text
ods=application/vnd.oasis.opendocument.spreadsheet
pptx=application/vnd.openxmlformats-officedocument.presentationml.presentation
txt=text/plain
xlsx=application/vnd.openxmlformats-officedocument.spreadsheetml.sheet