#The RHS value for the property is the key in adfs. 
# you can provide the custom  key in adfs
email=Email
role=Roles

#The RHS value for the profile can be comma separated values, 
#profile=Key1,Key2,Key3...
profile=Dept
organization=Organization