export const store = {
  getState: () => ({
    metadata: {
      present: {
        dataFetchedFor: {
          getDatasource: true,
          joins: false,
          viewSessionVariables: true,
          listDataSources: true,
          "kjv1-u454-5dic-7pjc-jm": false,
          "ar70-9nwn-yi0n-p744-3k": false,
        },
        loadingStatus: {
          getDatasource: true,
          listDataSources: true,
          "kjv1-u454-5dic-7pjc-jm": false,
          "ar70-9nwn-yi0n-p744-3k": false,
        },
        serviceErrorStatus: {},
        fetchedDSInfo: {},
        listDataSource: [],
        supportedDataSourceTypes: [
          {
            name: "Access",
            categoryType: "supported",
            categoryName: "Supported",
          },
          {
            name: "Amazon Dynamodb",
            categoryType: "supported",
            categoryName: "Supported",
          },
          {
            name: "Amazon Redshift",
            categoryType: "supported",
            categoryName: "Supported",
          },
          {
            name: "Dremio",
            categoryType: "supported",
            categoryName: "Supported",
          },
          {
            name: "Google Bigquery",
            categoryType: "supported",
            categoryName: "Supported",
          },
          {
            name: "IBM Db2",
            categoryType: "supported",
            categoryName: "Supported",
          },
          {
            name: "Informix",
            categoryType: "supported",
            categoryName: "Supported",
          },
          {
            name: "Microsoft Sqlserver",
            categoryType: "supported",
            categoryName: "Supported",
          },
          {
            name: "Mysql",
            categoryType: "supported",
            categoryName: "Supported",
          },
          {
            name: "Oracle",
            categoryType: "supported",
            categoryName: "Supported",
          },
          {
            name: "Presto",
            categoryType: "supported",
            categoryName: "Supported",
          },
          {
            name: "Teradata",
            categoryType: "supported",
            categoryName: "Supported",
          },
          {
            name: "Ξ Add Driver Ξ",
            categoryType: "supported",
            categoryName: "Supported",
          },
        ],
        allDataSourceTypes: [
          {
            name: "Access",
            categoryType: "supported",
            categoryName: "Supported",
          },
          {
            name: "Amazon Dynamodb",
            categoryType: "supported",
            categoryName: "Supported",
          },
          {
            name: "Amazon Redshift",
            categoryType: "supported",
            categoryName: "Supported",
          },
          {
            driver: "org.apache.drill.jdbc.Driver",
            databaseDialect: "drill",
            enabledTypes: false,
            name: "Apache Drill",
            categoryName: "Big Data",
            categoryType: "big_data",
            classifier: "global",
            imgUrl: "../images/data_sources/defaut_datasource.png",
            url: "jdbc:drill:{{hostName}}:{{port}}",
            parameters: {
              port: "31010",
              hostName: "drillbit=localhost",
            },
          },
          {
            driver: "com.simba.athena.jdbc.Driver",
            databaseDialect: "athena",
            name: "Athena",
            categoryName: "RDBMS",
            categoryType: "rdbms",
            type: "global.jdbc",
            dataSourceProvider: "tomcat",
            classifier: "global",
            imgUrl: "../images/data_sources/defaut_datasource.png",
            url: "jdbc:awsathena://{{hostName}}",
            parameters: {
              hostName: "localhost",
            },
          },
          {
            driver: "ru.yandex.clickhouse.ClickHouseDriver",
            databaseDialect: "clickhouse",
            name: "Clickhouse",
            categoryName: "RDBMS",
            categoryType: "rdbms",
            type: "global.jdbc",
            dataSourceProvider: "tomcat",
            classifier: "global",
            imgUrl: "../images/data_sources/defaut_datasource.png",
            url: "jdbc:clickhouse://{{hostName}}:{{port}}/{{database}}",
            parameters: {
              port: "8123",
              hostName: "localhost",
              database: "database",
            },
          },
          {
            driver: "com.databricks.client.jdbc.Driver",
            databaseDialect: "databricks",
            name: "Databricks Client",
            categoryName: "RDBMS",
            categoryType: "rdbms",
            type: "global.jdbc",
            dataSourceProvider: "tomcat",
            classifier: "global",
            imgUrl: "../images/data_sources/defaut_datasource.png",
            url: "jdbc:databricks://{{hostName}}:{{port}};{{database}}",
            parameters: {
              port: "443",
              hostName: "localhost",
              database: "database",
            },
          },
          {
            driver: "org.apache.derby.jdbc.ClientDriver",
            databaseDialect: "derby",
            name: "Derby",
            categoryName: "RDBMS",
            categoryType: "rdbms",
            type: "global.jdbc",
            dataSourceProvider: "tomcat",
            classifier: "global",
            imgUrl: "../images/data_sources/defaut_datasource.png",
            url: "jdbc:derby://{{hostName}}:{{port}}/{{database}}",
            parameters: {
              port: "1527",
              hostName: "localhost",
              database: "database",
            },
          },
          {
            driver: "org.apache.derby.jdbc.AutoloadedDriver",
            databaseDialect: "derby",
            name: "Derby",
            categoryName: "RDBMS",
            categoryType: "rdbms",
            type: "global.jdbc",
            dataSourceProvider: "tomcat",
            classifier: "global",
            imgUrl: "../images/data_sources/defaut_datasource.png",
            url: "jdbc:derby:{{database}}",
            parameters: {
              database: "database",
            },
          },
          {
            name: "Dremio",
            categoryType: "supported",
            categoryName: "Supported",
          },
          {
            driver: "dynamicSwitch",
            databaseDialect: "",
            name: "DynamicSwitch",
            categoryName: "RDBMS",
            categoryType: "rdbms",
            type: "global.jdbc",
            dataSourceProvider: "tomcat",
            classifier: "global",
            imgUrl: "../images/data_sources/defaut_datasource.png",
          },
          {
            name: "Google Bigquery",
            categoryType: "supported",
            categoryName: "Supported",
          },
          {
            driver: "com.helical.mongodb.MongoJdbcDriver",
            databaseDialect: "himongo",
            name: "Helical Mongodb",
            categoryName: "RDBMS",
            categoryType: "rdbms",
            type: "global.jdbc",
            dataSourceProvider: "tomcat",
            classifier: "global",
            imgUrl: "../images/data_sources/defaut_datasource.png",
          },
          {
            driver: "org.apache.hive.jdbc.HiveDriver",
            databaseDialect: "spark",
            name: "Hive",
            categoryName: "Big Data",
            categoryType: "big_data",
            classifier: "global",
            imgUrl: "../images/data_sources/defaut_datasource.png",
            url: "jdbc:hive2://{{hostName}}:{{port}}/{{database}}",
            parameters: {
              port: "10001",
              hostName: "localhost",
              database: "database",
            },
          },
          {
            name: "IBM Db2",
            categoryType: "supported",
            categoryName: "Supported",
          },
          {
            name: "Informix",
            categoryType: "supported",
            categoryName: "Supported",
          },
          {
            driver: "org.mariadb.jdbc.Driver",
            databaseDialect: "mysql",
            name: "Mariadb",
            categoryName: "RDBMS",
            categoryType: "rdbms",
            type: "global.jdbc",
            dataSourceProvider: "tomcat",
            classifier: "global",
            imgUrl: "../images/data_sources/defaut_datasource.png",
            url: "jdbc:mariadb://{{hostName}}:{{port}}/{{database}}",
            parameters: {
              port: "3306",
              hostName: "localhost",
              database: "database",
            },
          },
          {
            name: "Microsoft Sqlserver",
            categoryType: "supported",
            categoryName: "Supported",
          },
          {
            driver: "net.sourceforge.jtds.jdbc.Driver",
            databaseDialect: "sqlserver",
            name: "Microsoft Sqlserver(sourceforge)",
            categoryName: "RDBMS",
            categoryType: "rdbms",
            type: "global.jdbc",
            dataSourceProvider: "tomcat",
            classifier: "global",
            imgUrl: "../images/data_sources/defaut_datasource.png",
            url: "jdbc:jtds:sqlserver://{{hostName}}:{{port}}/{{database}}",
            parameters: {
              port: "1433",
              hostName: "localhost",
              database: "database",
            },
          },
          {
            name: "Mysql",
            categoryType: "supported",
            categoryName: "Supported",
          },
          {
            name: "Oracle",
            categoryType: "supported",
            categoryName: "Supported",
          },
          {
            driver: "org.postgresql.Driver",
            databaseDialect: "postgresql",
            name: "Postgresql",
            categoryName: "RDBMS",
            categoryType: "rdbms",
            type: "global.jdbc",
            dataSourceProvider: "tomcat",
            classifier: "global",
            imgUrl: "../images/data_sources/defaut_datasource.png",
            url: "jdbc:postgresql://{{hostName}}:{{port}}/{{database}}",
            parameters: {
              port: "5432",
              hostName: "localhost",
              database: "database",
            },
          },
          {
            name: "Presto",
            categoryType: "supported",
            categoryName: "Supported",
          },
          {
            driver: "org.sqlite.JDBC",
            databaseDialect: "sqlite",
            name: "Sqlite",
            categoryName: "RDBMS",
            categoryType: "rdbms",
            type: "global.jdbc",
            dataSourceProvider: "tomcat",
            classifier: "global",
            imgUrl: "../images/data_sources/defaut_datasource.png",
            url: "jdbc:sqlite:{{database}}",
            parameters: {
              database: "database",
            },
          },
          {
            name: "Teradata",
            categoryType: "supported",
            categoryName: "Supported",
          },
          {
            name: "Ξ Add Driver Ξ",
            categoryType: "supported",
            categoryName: "Supported",
          },
        ],
        metaDataSourceList: [
          {
            driver: "org.apache.drill.jdbc.Driver",
            databaseDialect: "drill",
            enabledTypes: false,
            name: "Apache Drill",
            categoryName: "Big Data",
            categoryType: "big_data",
            classifier: "global",
            imgUrl: "../images/data_sources/defaut_datasource.png",
            url: "jdbc:drill:{{hostName}}:{{port}}",
            parameters: {
              port: "31010",
              hostName: "drillbit=localhost",
            },
          },
          {
            driver: "com.simba.athena.jdbc.Driver",
            databaseDialect: "athena",
            name: "Athena",
            categoryName: "RDBMS",
            categoryType: "rdbms",
            type: "global.jdbc",
            dataSourceProvider: "tomcat",
            classifier: "global",
            imgUrl: "../images/data_sources/defaut_datasource.png",
            url: "jdbc:awsathena://{{hostName}}",
            parameters: {
              hostName: "localhost",
            },
          },
          {
            driver: "ru.yandex.clickhouse.ClickHouseDriver",
            databaseDialect: "clickhouse",
            name: "Clickhouse",
            categoryName: "RDBMS",
            categoryType: "rdbms",
            type: "global.jdbc",
            dataSourceProvider: "tomcat",
            classifier: "global",
            imgUrl: "../images/data_sources/defaut_datasource.png",
            url: "jdbc:clickhouse://{{hostName}}:{{port}}/{{database}}",
            parameters: {
              port: "8123",
              hostName: "localhost",
              database: "database",
            },
          },
          {
            driver: "com.databricks.client.jdbc.Driver",
            databaseDialect: "databricks",
            name: "Databricks Client",
            categoryName: "RDBMS",
            categoryType: "rdbms",
            type: "global.jdbc",
            dataSourceProvider: "tomcat",
            classifier: "global",
            imgUrl: "../images/data_sources/defaut_datasource.png",
            url: "jdbc:databricks://{{hostName}}:{{port}};{{database}}",
            parameters: {
              port: "443",
              hostName: "localhost",
              database: "database",
            },
          },
          {
            driver: "org.apache.derby.jdbc.ClientDriver",
            databaseDialect: "derby",
            name: "Derby",
            categoryName: "RDBMS",
            categoryType: "rdbms",
            type: "global.jdbc",
            dataSourceProvider: "tomcat",
            classifier: "global",
            imgUrl: "../images/data_sources/defaut_datasource.png",
            url: "jdbc:derby://{{hostName}}:{{port}}/{{database}}",
            parameters: {
              port: "1527",
              hostName: "localhost",
              database: "database",
            },
          },
          {
            driver: "org.apache.derby.jdbc.AutoloadedDriver",
            databaseDialect: "derby",
            name: "Derby",
            categoryName: "RDBMS",
            categoryType: "rdbms",
            type: "global.jdbc",
            dataSourceProvider: "tomcat",
            classifier: "global",
            imgUrl: "../images/data_sources/defaut_datasource.png",
            url: "jdbc:derby:{{database}}",
            parameters: {
              database: "database",
            },
          },
          {
            driver: "dynamicSwitch",
            databaseDialect: "",
            name: "DynamicSwitch",
            categoryName: "RDBMS",
            categoryType: "rdbms",
            type: "global.jdbc",
            dataSourceProvider: "tomcat",
            classifier: "global",
            imgUrl: "../images/data_sources/defaut_datasource.png",
          },
          {
            driver: "com.helical.mongodb.MongoJdbcDriver",
            databaseDialect: "himongo",
            name: "Helical Mongodb",
            categoryName: "RDBMS",
            categoryType: "rdbms",
            type: "global.jdbc",
            dataSourceProvider: "tomcat",
            classifier: "global",
            imgUrl: "../images/data_sources/defaut_datasource.png",
          },
          {
            driver: "org.apache.hive.jdbc.HiveDriver",
            databaseDialect: "spark",
            name: "Hive",
            categoryName: "Big Data",
            categoryType: "big_data",
            classifier: "global",
            imgUrl: "../images/data_sources/defaut_datasource.png",
            url: "jdbc:hive2://{{hostName}}:{{port}}/{{database}}",
            parameters: {
              port: "10001",
              hostName: "localhost",
              database: "database",
            },
          },
          {
            driver: "org.mariadb.jdbc.Driver",
            databaseDialect: "mysql",
            name: "Mariadb",
            categoryName: "RDBMS",
            categoryType: "rdbms",
            type: "global.jdbc",
            dataSourceProvider: "tomcat",
            classifier: "global",
            imgUrl: "../images/data_sources/defaut_datasource.png",
            url: "jdbc:mariadb://{{hostName}}:{{port}}/{{database}}",
            parameters: {
              port: "3306",
              hostName: "localhost",
              database: "database",
            },
          },
          {
            driver: "net.sourceforge.jtds.jdbc.Driver",
            databaseDialect: "sqlserver",
            name: "Microsoft Sqlserver(sourceforge)",
            categoryName: "RDBMS",
            categoryType: "rdbms",
            type: "global.jdbc",
            dataSourceProvider: "tomcat",
            classifier: "global",
            imgUrl: "../images/data_sources/defaut_datasource.png",
            url: "jdbc:jtds:sqlserver://{{hostName}}:{{port}}/{{database}}",
            parameters: {
              port: "1433",
              hostName: "localhost",
              database: "database",
            },
          },
          {
            driver: "org.postgresql.Driver",
            databaseDialect: "postgresql",
            name: "Postgresql",
            categoryName: "RDBMS",
            categoryType: "rdbms",
            type: "global.jdbc",
            dataSourceProvider: "tomcat",
            classifier: "global",
            imgUrl: "../images/data_sources/defaut_datasource.png",
            url: "jdbc:postgresql://{{hostName}}:{{port}}/{{database}}",
            parameters: {
              port: "5432",
              hostName: "localhost",
              database: "database",
            },
          },
          {
            driver: "org.sqlite.JDBC",
            databaseDialect: "sqlite",
            name: "Sqlite",
            categoryName: "RDBMS",
            categoryType: "rdbms",
            type: "global.jdbc",
            dataSourceProvider: "tomcat",
            classifier: "global",
            imgUrl: "../images/data_sources/defaut_datasource.png",
            url: "jdbc:sqlite:{{database}}",
            parameters: {
              database: "database",
            },
          },
        ],
        driversList: [
          {
            driver: "dynamicSwitch",
            showInDatasource: "false",
            available: "true",
            parameters: [],
          },
          {
            url: "jdbc:derby:{{database}}",
            driver: "org.apache.derby.jdbc.AutoloadedDriver",
            available: "true",
            parameters: {
              database: "database",
            },
          },
          {
            url: "jdbc:awsathena://{{hostName}}",
            driver: "com.simba.athena.jdbc.Driver",
            available: "true",
            parameters: {
              hostName: "localhost",
            },
          },
          {
            url: "jdbc:jtds:sqlserver://{{hostName}}:{{port}}/{{database}}",
            driver: "net.sourceforge.jtds.jdbc.Driver",
            available: "true",
            parameters: {
              port: "1433",
              hostName: "localhost",
              database: "database",
            },
          },
          {
            url: "jdbc:clickhouse://{{hostName}}:{{port}}/{{database}}",
            driver: "ru.yandex.clickhouse.ClickHouseDriver",
            available: "true",
            parameters: {
              port: "8123",
              hostName: "localhost",
              database: "database",
            },
          },
          {
            available: "true",
            driver: "com.helical.mongodb.MongoJdbcDriver",
          },
          {
            url: "jdbc:hive2://{{hostName}}:{{port}}/{{database}}",
            driver: "org.apache.hive.jdbc.HiveDriver",
            available: "true",
            parameters: {
              port: "10001",
              hostName: "localhost",
              database: "database",
            },
          },
          {
            url: "jdbc:drill:{{hostName}}:{{port}}",
            driver: "org.apache.drill.jdbc.Driver",
            available: "true",
            parameters: {
              port: "31010",
              hostName: "drillbit=localhost",
            },
          },
          {
            url: "jdbc:mariadb://{{hostName}}:{{port}}/{{database}}",
            driver: "org.mariadb.jdbc.Driver",
            available: "true",
            parameters: {
              port: "3306",
              hostName: "localhost",
              database: "database",
            },
          },
          {
            url: "jdbc:databricks://{{hostName}}:{{port}};{{database}}",
            driver: "com.databricks.client.jdbc.Driver",
            available: "true",
            parameters: {
              port: "443",
              hostName: "localhost",
              database: "database",
            },
          },
          {
            url: "jdbc:postgresql://{{hostName}}:{{port}}/{{database}}",
            driver: "org.postgresql.Driver",
            available: "true",
            parameters: {
              port: "5432",
              hostName: "localhost",
              database: "database",
            },
          },
          {
            url: "jdbc:derby://{{hostName}}:{{port}}/{{database}}",
            driver: "org.apache.derby.jdbc.ClientDriver",
            available: "true",
            parameters: {
              port: "1527",
              hostName: "localhost",
              database: "database",
            },
          },
          {
            url: "jdbc:sqlite:{{database}}",
            driver: "org.sqlite.JDBC",
            available: "true",
            parameters: {
              database: "database",
            },
          },
        ],
        allDataSources: [
          {
            data: {
              id: "1",
              type: "dynamicDataSource",
            },
            dataSourceProvider: "tomcat",
            type: "dynamicDataSource",
            permissionLevel: 5,
            driver: "org.apache.derby.jdbc.AutoloadedDriver",
            name: "SampleTravelDataDerby",
            classifier: "global",
            dataSourceType: "Managed DataSource",
          },
        ],
        dataSourceTypes: [
          {
            type: "sql.jdbc.groovy.managed",
            name: "Groovy Managed Jdbc DataSource",
            classifier: "efwd",
            categoryName: "advanced",
            categoryType: "advanced",
          },
          {
            type: "sql.jdbc.groovy",
            name: "Groovy Plain Jdbc DataSource",
            classifier: "efwd",
            categoryName: "advanced",
            categoryType: "advanced",
          },
          {
            type: "global.jdbc",
            name: "Managed DataSource",
            classifier: "global",
            categoryName: "advanced",
            categoryType: "advanced",
          },
          {
            type: "sql.jdbc",
            name: "Plain Jdbc DataSource",
            classifier: "efwd",
            categoryName: "advanced",
            categoryType: "advanced",
          },
        ],
        datasourceListToRender: [
          {
            name: "Derby",
            children: [
              {
                data: {
                  id: "1",
                  type: "dynamicDataSource",
                },
                dataSourceProvider: "tomcat",
                type: "dynamicDataSource",
                permissionLevel: 5,
                driver: "org.apache.derby.jdbc.AutoloadedDriver",
                name: "SampleTravelDataDerby",
                classifier: "global",
                dataSourceType: "Managed DataSource",
                category: "dataSource",
                children: [
                  {
                    name: "SQLJ",
                    children: [],
                    keyPath:
                      "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/n5pl-1wi4-6i1e-nf0j-y8",
                    key: "n5pl-1wi4-6i1e-nf0j-y8",
                    uuid: "n5pl-1wi4-6i1e-nf0j-y8",
                    data: {
                      id: "1",
                      type: "dynamicDataSource",
                    },
                    category: "schema",
                    datasourceName: "SampleTravelDataDerby",
                  },
                  {
                    name: "SYSFUN",
                    children: [],
                    keyPath:
                      "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/rns3-fsyc-rcmf-or1q-l1",
                    key: "rns3-fsyc-rcmf-or1q-l1",
                    uuid: "rns3-fsyc-rcmf-or1q-l1",
                    data: {
                      id: "1",
                      type: "dynamicDataSource",
                    },
                    category: "schema",
                    datasourceName: "SampleTravelDataDerby",
                  },
                  {
                    name: "SYSCAT",
                    children: [],
                    keyPath:
                      "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/fmj5-fvh4-30sm-zms6-9q",
                    key: "fmj5-fvh4-30sm-zms6-9q",
                    uuid: "fmj5-fvh4-30sm-zms6-9q",
                    data: {
                      id: "1",
                      type: "dynamicDataSource",
                    },
                    category: "schema",
                    datasourceName: "SampleTravelDataDerby",
                  },
                  {
                    name: "HIUSER",
                    children: [
                      {
                        id: "4ac5d9f68b58bd7c0d179146e46795be",
                        name: "dimdate",
                        data: {
                          id: "1",
                          type: "dynamicDataSource",
                        },
                        keyPath:
                          "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/ar70-9nwn-yi0n-p744-3k/9ztq-zs3b-f61h-k4rl-ub",
                        key: "9ztq-zs3b-f61h-k4rl-ub",
                        alias: "dimdate",
                        uuid: "9ztq-zs3b-f61h-k4rl-ub",
                        connId: "fb0f9",
                        dataSource: {
                          id: "1",
                          type: "dynamicDataSource",
                          baseType: "global.jdbc",
                          catSchemaPredicted: false,
                          sync: false,
                          catalog: "",
                          schema: "HIUSER",
                          connId: "fb0f9",
                          classifier: "db.workflow",
                          datasourceName: "SampleTravelDataDerby",
                          dsKeyPath:
                            "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/ar70-9nwn-yi0n-p744-3k",
                          driverType: "Derby",
                          database: "HIUSER",
                        },
                        dataSourceName: "SampleTravelDataDerby",
                        category: "table",
                        nameWithConnId: "dimdate_fb0f9",
                        database: "HIUSER",
                        schema: "HIUSER",
                        selected: true,
                      },
                      {
                        id: "4e1fd245f4d13b77be423a43f01d80b2",
                        name: "employee_details",
                        data: {
                          id: "1",
                          type: "dynamicDataSource",
                        },
                        keyPath:
                          "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/ar70-9nwn-yi0n-p744-3k/do9f-rzb8-lcfj-sy97-wu",
                        key: "do9f-rzb8-lcfj-sy97-wu",
                        alias: "employee_details",
                        uuid: "do9f-rzb8-lcfj-sy97-wu",
                        connId: "fb0f9",
                        dataSource: {
                          id: "1",
                          type: "dynamicDataSource",
                          baseType: "global.jdbc",
                          catSchemaPredicted: false,
                          sync: false,
                          catalog: "",
                          schema: "HIUSER",
                          connId: "fb0f9",
                          classifier: "db.workflow",
                          datasourceName: "SampleTravelDataDerby",
                          dsKeyPath:
                            "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/ar70-9nwn-yi0n-p744-3k",
                          driverType: "Derby",
                          database: "HIUSER",
                        },
                        dataSourceName: "SampleTravelDataDerby",
                        category: "table",
                        nameWithConnId: "employee_details_fb0f9",
                        database: "HIUSER",
                        schema: "HIUSER",
                        selected: true,
                      },
                      {
                        id: "be534112989b616b194bc59c2fb25a42",
                        name: "geo_cordinates",
                        data: {
                          id: "1",
                          type: "dynamicDataSource",
                        },
                        keyPath:
                          "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/ar70-9nwn-yi0n-p744-3k/cci8-nhcn-0u15-5uaq-lh",
                        key: "cci8-nhcn-0u15-5uaq-lh",
                        alias: "geo_cordinates",
                        uuid: "cci8-nhcn-0u15-5uaq-lh",
                        connId: "fb0f9",
                        dataSource: {
                          id: "1",
                          type: "dynamicDataSource",
                          baseType: "global.jdbc",
                          catSchemaPredicted: false,
                          sync: false,
                          catalog: "",
                          schema: "HIUSER",
                          connId: "fb0f9",
                          classifier: "db.workflow",
                          datasourceName: "SampleTravelDataDerby",
                          dsKeyPath:
                            "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/ar70-9nwn-yi0n-p744-3k",
                          driverType: "Derby",
                          database: "HIUSER",
                        },
                        dataSourceName: "SampleTravelDataDerby",
                        category: "table",
                        nameWithConnId: "geo_cordinates_fb0f9",
                        database: "HIUSER",
                        schema: "HIUSER",
                        selected: true,
                      },
                      {
                        id: "9645c648a1c0dbeec1287aaf1e996db3",
                        name: "meeting_details",
                        data: {
                          id: "1",
                          type: "dynamicDataSource",
                        },
                        keyPath:
                          "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/ar70-9nwn-yi0n-p744-3k/afnp-f5si-p2vk-kcqg-ez",
                        key: "afnp-f5si-p2vk-kcqg-ez",
                        alias: "meeting_details",
                        uuid: "afnp-f5si-p2vk-kcqg-ez",
                        connId: "fb0f9",
                        dataSource: {
                          id: "1",
                          type: "dynamicDataSource",
                          baseType: "global.jdbc",
                          catSchemaPredicted: false,
                          sync: false,
                          catalog: "",
                          schema: "HIUSER",
                          connId: "fb0f9",
                          classifier: "db.workflow",
                          datasourceName: "SampleTravelDataDerby",
                          dsKeyPath:
                            "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/ar70-9nwn-yi0n-p744-3k",
                          driverType: "Derby",
                          database: "HIUSER",
                        },
                        dataSourceName: "SampleTravelDataDerby",
                        category: "table",
                        nameWithConnId: "meeting_details_fb0f9",
                        database: "HIUSER",
                        schema: "HIUSER",
                        selected: true,
                      },
                      {
                        id: "8a28627d07d04ef096d9935f12e0c7e9",
                        name: "travel_details",
                        data: {
                          id: "1",
                          type: "dynamicDataSource",
                        },
                        keyPath:
                          "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/ar70-9nwn-yi0n-p744-3k/9rff-q9xb-t0dl-u3e6-pg",
                        key: "9rff-q9xb-t0dl-u3e6-pg",
                        alias: "travel_details",
                        uuid: "9rff-q9xb-t0dl-u3e6-pg",
                        connId: "fb0f9",
                        dataSource: {
                          id: "1",
                          type: "dynamicDataSource",
                          baseType: "global.jdbc",
                          catSchemaPredicted: false,
                          sync: false,
                          catalog: "",
                          schema: "HIUSER",
                          connId: "fb0f9",
                          classifier: "db.workflow",
                          datasourceName: "SampleTravelDataDerby",
                          dsKeyPath:
                            "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/ar70-9nwn-yi0n-p744-3k",
                          driverType: "Derby",
                          database: "HIUSER",
                        },
                        dataSourceName: "SampleTravelDataDerby",
                        category: "table",
                        nameWithConnId: "travel_details_fb0f9",
                        database: "HIUSER",
                        schema: "HIUSER",
                        selected: true,
                      },
                    ],
                    keyPath:
                      "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/ar70-9nwn-yi0n-p744-3k",
                    key: "ar70-9nwn-yi0n-p744-3k",
                    uuid: "ar70-9nwn-yi0n-p744-3k",
                    data: {
                      id: "1",
                      type: "dynamicDataSource",
                    },
                    category: "schema",
                    datasourceName: "SampleTravelDataDerby",
                    fetched: true,
                  },
                  {
                    name: "SYSCS_DIAG",
                    children: [],
                    keyPath:
                      "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/lj3z-nuk5-b4oe-vqiz-6h",
                    key: "lj3z-nuk5-b4oe-vqiz-6h",
                    uuid: "lj3z-nuk5-b4oe-vqiz-6h",
                    data: {
                      id: "1",
                      type: "dynamicDataSource",
                    },
                    category: "schema",
                    datasourceName: "SampleTravelDataDerby",
                  },
                  {
                    name: "SYSCS_UTIL",
                    children: [],
                    keyPath:
                      "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/33dm-j1my-rxvq-wpug-w2",
                    key: "33dm-j1my-rxvq-wpug-w2",
                    uuid: "33dm-j1my-rxvq-wpug-w2",
                    data: {
                      id: "1",
                      type: "dynamicDataSource",
                    },
                    category: "schema",
                    datasourceName: "SampleTravelDataDerby",
                  },
                  {
                    name: "SYSIBM",
                    children: [],
                    keyPath:
                      "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/kuqq-gkh7-yd96-i2y9-w5",
                    key: "kuqq-gkh7-yd96-i2y9-w5",
                    uuid: "kuqq-gkh7-yd96-i2y9-w5",
                    data: {
                      id: "1",
                      type: "dynamicDataSource",
                    },
                    category: "schema",
                    datasourceName: "SampleTravelDataDerby",
                  },
                  {
                    name: "APP",
                    children: [],
                    keyPath:
                      "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/zcba-1xbe-bkch-vpy3-ml",
                    key: "zcba-1xbe-bkch-vpy3-ml",
                    uuid: "zcba-1xbe-bkch-vpy3-ml",
                    data: {
                      id: "1",
                      type: "dynamicDataSource",
                    },
                    category: "schema",
                    datasourceName: "SampleTravelDataDerby",
                  },
                  {
                    name: "NULLID",
                    children: [],
                    keyPath:
                      "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/y0eq-oym0-blel-d96i-wr",
                    key: "y0eq-oym0-blel-d96i-wr",
                    uuid: "y0eq-oym0-blel-d96i-wr",
                    data: {
                      id: "1",
                      type: "dynamicDataSource",
                    },
                    category: "schema",
                    datasourceName: "SampleTravelDataDerby",
                  },
                  {
                    name: "SYSPROC",
                    children: [],
                    keyPath:
                      "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/bhpf-qdue-l14u-bwmp-zt",
                    key: "bhpf-qdue-l14u-bwmp-zt",
                    uuid: "bhpf-qdue-l14u-bwmp-zt",
                    data: {
                      id: "1",
                      type: "dynamicDataSource",
                    },
                    category: "schema",
                    datasourceName: "SampleTravelDataDerby",
                  },
                  {
                    name: "SYS",
                    children: [],
                    keyPath:
                      "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/oy35-qjqa-gzv6-6vrz-c5",
                    key: "oy35-qjqa-gzv6-6vrz-c5",
                    uuid: "oy35-qjqa-gzv6-6vrz-c5",
                    data: {
                      id: "1",
                      type: "dynamicDataSource",
                    },
                    category: "schema",
                    datasourceName: "SampleTravelDataDerby",
                  },
                  {
                    name: "SYSSTAT",
                    children: [],
                    keyPath:
                      "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/2hya-2mg3-vp55-3huy-cj",
                    key: "2hya-2mg3-vp55-3huy-cj",
                    uuid: "2hya-2mg3-vp55-3huy-cj",
                    data: {
                      id: "1",
                      type: "dynamicDataSource",
                    },
                    category: "schema",
                    datasourceName: "SampleTravelDataDerby",
                  },
                ],
                driverType: "Derby",
                keyPath: "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm",
                key: "kjv1-u454-5dic-7pjc-jm",
                uuid: "kjv1-u454-5dic-7pjc-jm",
                fetched: true,
              },
            ],
            key: "qy80-uioo-a9eo-0x1f-1h",
            uuid: "qy80-uioo-a9eo-0x1f-1h",
            keyPath: "qy80-uioo-a9eo-0x1f-1h",
            category: "dsGroup",
            imgUrl: "images/data_sources/defaut_datasource.png",
          },
        ],
        workFlow: {
          dataList: [
            {
              fetchSchemas: true,
              fetchCatalogs: true,
              working: true,
              connData: {
                id: "1",
                type: "dynamicDataSource",
              },
              connId: "1",
              dsUUID: "kjv1-u454-5dic-7pjc-jm",
              classifier: "db.workflow",
              metadata: {
                catalogs: [
                  {
                    name: "Null",
                    schemas: [
                      {
                        name: "SQLJ",
                      },
                      {
                        name: "SYSFUN",
                      },
                      {
                        name: "SYSCAT",
                      },
                      {
                        name: "HIUSER",
                      },
                      {
                        name: "SYSCS_DIAG",
                      },
                      {
                        name: "SYSCS_UTIL",
                      },
                      {
                        name: "SYSIBM",
                      },
                      {
                        name: "APP",
                      },
                      {
                        name: "NULLID",
                      },
                      {
                        name: "SYSPROC",
                      },
                      {
                        name: "SYS",
                      },
                      {
                        name: "SYSSTAT",
                      },
                    ],
                  },
                ],
              },
            },
            {
              classifier: "db.workflow",
              metadata: {
                catalogs: [
                  {
                    name: "Null",
                    schemas: [
                      {
                        name: "HIUSER",
                        tables: [
                          {
                            id: "be534112989b616b194bc59c2fb25a42",
                            name: "geo_cordinates",
                          },
                          {
                            id: "9645c648a1c0dbeec1287aaf1e996db3",
                            name: "meeting_details",
                          },
                          {
                            id: "4e1fd245f4d13b77be423a43f01d80b2",
                            name: "employee_details",
                          },
                          {
                            id: "4ac5d9f68b58bd7c0d179146e46795be",
                            name: "dimdate",
                          },
                          {
                            id: "8a28627d07d04ef096d9935f12e0c7e9",
                            name: "travel_details",
                          },
                        ],
                      },
                    ],
                  },
                ],
                dataSource: {
                  id: "1",
                  type: "dynamicDataSource",
                  baseType: "global.jdbc",
                  catSchemaPredicted: false,
                  sync: false,
                  catalog: "",
                  schema: "HIUSER",
                  connId: "fb0f9",
                  classifier: "db.workflow",
                  datasourceName: "SampleTravelDataDerby",
                  dsKeyPath:
                    "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/ar70-9nwn-yi0n-p744-3k",
                  driverType: "Derby",
                  database: "HIUSER",
                },
                name: "HIUSER",
              },
            },
          ],
        },
        dataSource: [
          {
            id: "1",
            type: "dynamicDataSource",
            baseType: "global.jdbc",
            catSchemaPredicted: false,
            sync: false,
            catalog: "",
            schema: "HIUSER",
            connId: "fb0f9",
            classifier: "db.workflow",
            datasourceName: "SampleTravelDataDerby",
            dsKeyPath:
              "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/ar70-9nwn-yi0n-p744-3k",
            driverType: "Derby",
            database: "HIUSER",
          },
        ],
        tables: {
          dimdate: {
            id: "4ac5d9f68b58bd7c0d179146e46795be",
            name: "dimdate",
            data: {
              id: "1",
              type: "dynamicDataSource",
            },
            keyPath:
              "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/ar70-9nwn-yi0n-p744-3k/9ztq-zs3b-f61h-k4rl-ub",
            key: "9ztq-zs3b-f61h-k4rl-ub",
            alias: "dimdate",
            uuid: "9ztq-zs3b-f61h-k4rl-ub",
            connId: "fb0f9",
            dataSource: {
              id: "1",
              type: "dynamicDataSource",
              baseType: "global.jdbc",
              catSchemaPredicted: false,
              sync: false,
              catalog: "",
              schema: "HIUSER",
              connId: "fb0f9",
              classifier: "db.workflow",
              datasourceName: "SampleTravelDataDerby",
              dsKeyPath:
                "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/ar70-9nwn-yi0n-p744-3k",
              driverType: "Derby",
              database: "HIUSER",
            },
            dataSourceName: "SampleTravelDataDerby",
            category: "table",
            nameWithConnId: "dimdate_fb0f9",
            database: "HIUSER",
            schema: "HIUSER",
            selected: true,
            keyName: "dimdate",
          },
          employee_details: {
            id: "4e1fd245f4d13b77be423a43f01d80b2",
            name: "employee_details",
            data: {
              id: "1",
              type: "dynamicDataSource",
            },
            keyPath:
              "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/ar70-9nwn-yi0n-p744-3k/do9f-rzb8-lcfj-sy97-wu",
            key: "do9f-rzb8-lcfj-sy97-wu",
            alias: "employee_details",
            uuid: "do9f-rzb8-lcfj-sy97-wu",
            connId: "fb0f9",
            dataSource: {
              id: "1",
              type: "dynamicDataSource",
              baseType: "global.jdbc",
              catSchemaPredicted: false,
              sync: false,
              catalog: "",
              schema: "HIUSER",
              connId: "fb0f9",
              classifier: "db.workflow",
              datasourceName: "SampleTravelDataDerby",
              dsKeyPath:
                "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/ar70-9nwn-yi0n-p744-3k",
              driverType: "Derby",
              database: "HIUSER",
            },
            dataSourceName: "SampleTravelDataDerby",
            category: "table",
            nameWithConnId: "employee_details_fb0f9",
            database: "HIUSER",
            schema: "HIUSER",
            selected: true,
            keyName: "employee_details",
          },
          geo_cordinates: {
            id: "be534112989b616b194bc59c2fb25a42",
            name: "geo_cordinates",
            data: {
              id: "1",
              type: "dynamicDataSource",
            },
            keyPath:
              "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/ar70-9nwn-yi0n-p744-3k/cci8-nhcn-0u15-5uaq-lh",
            key: "cci8-nhcn-0u15-5uaq-lh",
            alias: "geo_cordinates",
            uuid: "cci8-nhcn-0u15-5uaq-lh",
            connId: "fb0f9",
            dataSource: {
              id: "1",
              type: "dynamicDataSource",
              baseType: "global.jdbc",
              catSchemaPredicted: false,
              sync: false,
              catalog: "",
              schema: "HIUSER",
              connId: "fb0f9",
              classifier: "db.workflow",
              datasourceName: "SampleTravelDataDerby",
              dsKeyPath:
                "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/ar70-9nwn-yi0n-p744-3k",
              driverType: "Derby",
              database: "HIUSER",
            },
            dataSourceName: "SampleTravelDataDerby",
            category: "table",
            nameWithConnId: "geo_cordinates_fb0f9",
            database: "HIUSER",
            schema: "HIUSER",
            selected: true,
            keyName: "geo_cordinates",
          },
          meeting_details: {
            id: "9645c648a1c0dbeec1287aaf1e996db3",
            name: "meeting_details",
            data: {
              id: "1",
              type: "dynamicDataSource",
            },
            keyPath:
              "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/ar70-9nwn-yi0n-p744-3k/afnp-f5si-p2vk-kcqg-ez",
            key: "afnp-f5si-p2vk-kcqg-ez",
            alias: "meeting_details",
            uuid: "afnp-f5si-p2vk-kcqg-ez",
            connId: "fb0f9",
            dataSource: {
              id: "1",
              type: "dynamicDataSource",
              baseType: "global.jdbc",
              catSchemaPredicted: false,
              sync: false,
              catalog: "",
              schema: "HIUSER",
              connId: "fb0f9",
              classifier: "db.workflow",
              datasourceName: "SampleTravelDataDerby",
              dsKeyPath:
                "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/ar70-9nwn-yi0n-p744-3k",
              driverType: "Derby",
              database: "HIUSER",
            },
            dataSourceName: "SampleTravelDataDerby",
            category: "table",
            nameWithConnId: "meeting_details_fb0f9",
            database: "HIUSER",
            schema: "HIUSER",
            selected: true,
            keyName: "meeting_details",
          },
          travel_details: {
            id: "8a28627d07d04ef096d9935f12e0c7e9",
            name: "travel_details",
            data: {
              id: "1",
              type: "dynamicDataSource",
            },
            keyPath:
              "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/ar70-9nwn-yi0n-p744-3k/9rff-q9xb-t0dl-u3e6-pg",
            key: "9rff-q9xb-t0dl-u3e6-pg",
            alias: "travel_details",
            uuid: "9rff-q9xb-t0dl-u3e6-pg",
            connId: "fb0f9",
            dataSource: {
              id: "1",
              type: "dynamicDataSource",
              baseType: "global.jdbc",
              catSchemaPredicted: false,
              sync: false,
              catalog: "",
              schema: "HIUSER",
              connId: "fb0f9",
              classifier: "db.workflow",
              datasourceName: "SampleTravelDataDerby",
              dsKeyPath:
                "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/ar70-9nwn-yi0n-p744-3k",
              driverType: "Derby",
              database: "HIUSER",
            },
            dataSourceName: "SampleTravelDataDerby",
            category: "table",
            nameWithConnId: "travel_details_fb0f9",
            database: "HIUSER",
            schema: "HIUSER",
            selected: true,
            keyName: "travel_details",
          },
          "View 1": {
            name: "View 1",
            alias: "View 1",
            columns: {
              dim_id: {
                alias: "dim_id",
                id: "eb2f01da-0ea1-4074-adbf-6b52444ea768",
                columnId: "eb2f01da-0ea1-4074-adbf-6b52444ea768",
                type: {
                  "java.lang.Float": "numeric",
                },
              },
              fiscal_year: {
                alias: "fiscal_year",
                id: "25c0f6ee-f021-47e6-9d1c-03a49eb8369a",
                columnId: "25c0f6ee-f021-47e6-9d1c-03a49eb8369a",
                type: {
                  "java.sql.Date": "date",
                },
              },
              modified_date: {
                alias: "modified_date",
                id: "c5ef1f4a-8ddb-48f2-94f6-39cb10e63baa",
                columnId: "c5ef1f4a-8ddb-48f2-94f6-39cb10e63baa",
                type: {
                  "java.sql.Timestamp": "dateTime",
                },
              },
              date_key: {
                alias: "date_key",
                id: "a40088df-346f-4a94-8640-e8f3b972da84",
                columnId: "a40088df-346f-4a94-8640-e8f3b972da84",
                type: {
                  "java.lang.String": "text",
                },
              },
              day_number: {
                alias: "day_number",
                id: "6f5b9ae9-65f0-420a-8ffe-22caffa4c5be",
                columnId: "6f5b9ae9-65f0-420a-8ffe-22caffa4c5be",
                type: {
                  "java.lang.String": "text",
                },
              },
              fiscal_month_name: {
                alias: "fiscal_month_name",
                id: "b597e2df-0d6a-439b-b1bc-ad44ec10e73f",
                columnId: "b597e2df-0d6a-439b-b1bc-ad44ec10e73f",
                type: {
                  "java.lang.String": "text",
                },
              },
              fiscal_month_label: {
                alias: "fiscal_month_label",
                id: "a9dd32bf-5040-457d-ba4b-5f5a970d9e7a",
                columnId: "a9dd32bf-5040-457d-ba4b-5f5a970d9e7a",
                type: {
                  "java.lang.String": "text",
                },
              },
              created_date: {
                alias: "created_date",
                id: "c4deccde-96e2-416d-9a0e-cb3ead05d0c0",
                columnId: "c4deccde-96e2-416d-9a0e-cb3ead05d0c0",
                type: {
                  "java.lang.String": "text",
                },
              },
              created_time: {
                alias: "created_time",
                id: "84fc9d54-7be6-4b5a-be9a-55822749cdbe",
                columnId: "84fc9d54-7be6-4b5a-be9a-55822749cdbe",
                type: {
                  "java.lang.String": "text",
                },
              },
              rating: {
                alias: "rating",
                id: "0edbd0bc-addb-4fbf-a5c2-b29834b56fbc",
                columnId: "0edbd0bc-addb-4fbf-a5c2-b29834b56fbc",
                type: {
                  "java.lang.String": "text",
                },
              },
            },
            key: "n4dc-qajz-us3k-003s-j7",
            uuid: "n4dc-qajz-us3k-003s-j7",
            query: 'select * from "dimdate"',
            queryType: "conditionIf",
            labels: [
              {
                name: "dim_id",
                type: "numeric",
                checked: true,
              },
              {
                name: "fiscal_year",
                type: "date",
                checked: true,
              },
              {
                name: "modified_date",
                type: "dateTime",
                checked: true,
              },
              {
                name: "date_key",
                type: "text",
                checked: true,
              },
              {
                name: "day_number",
                type: "text",
                checked: true,
              },
              {
                name: "fiscal_month_name",
                type: "text",
                checked: true,
              },
              {
                name: "fiscal_month_label",
                type: "text",
                checked: true,
              },
              {
                name: "created_date",
                type: "text",
                checked: true,
              },
              {
                name: "created_time",
                type: "text",
                checked: true,
              },
              {
                name: "rating",
                type: "text",
                checked: true,
              },
            ],
            dataSource: {
              id: "1",
              type: "dynamicDataSource",
              baseType: "global.jdbc",
              catSchemaPredicted: false,
              sync: false,
              catalog: "",
              schema: "HIUSER",
              connId: "fb0f9",
              classifier: "db.workflow",
              datasourceName: "SampleTravelDataDerby",
              dsKeyPath:
                "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/ar70-9nwn-yi0n-p744-3k",
              driverType: "Derby",
              database: "HIUSER",
            },
            error: false,
            validate: true,
            processedQuery:
              'select * from (select * from "dimdate") foo fetch first 1 rows only',
            id: "86e51d92-b7e6-45f3-b772-6c54d1b8688b",
            type: "view",
            isModified: true,
            columnsFetched: true,
            keyName: "View 1",
            category: "view",
          },
        },
        views: [
          {
            name: "View 1",
            alias: "View 1",
            columns: {
              dim_id: {
                alias: "dim_id",
                id: "eb2f01da-0ea1-4074-adbf-6b52444ea768",
                columnId: "eb2f01da-0ea1-4074-adbf-6b52444ea768",
                type: {
                  "java.lang.Float": "numeric",
                },
              },
              fiscal_year: {
                alias: "fiscal_year",
                id: "25c0f6ee-f021-47e6-9d1c-03a49eb8369a",
                columnId: "25c0f6ee-f021-47e6-9d1c-03a49eb8369a",
                type: {
                  "java.sql.Date": "date",
                },
              },
              modified_date: {
                alias: "modified_date",
                id: "c5ef1f4a-8ddb-48f2-94f6-39cb10e63baa",
                columnId: "c5ef1f4a-8ddb-48f2-94f6-39cb10e63baa",
                type: {
                  "java.sql.Timestamp": "dateTime",
                },
              },
              date_key: {
                alias: "date_key",
                id: "a40088df-346f-4a94-8640-e8f3b972da84",
                columnId: "a40088df-346f-4a94-8640-e8f3b972da84",
                type: {
                  "java.lang.String": "text",
                },
              },
              day_number: {
                alias: "day_number",
                id: "6f5b9ae9-65f0-420a-8ffe-22caffa4c5be",
                columnId: "6f5b9ae9-65f0-420a-8ffe-22caffa4c5be",
                type: {
                  "java.lang.String": "text",
                },
              },
              fiscal_month_name: {
                alias: "fiscal_month_name",
                id: "b597e2df-0d6a-439b-b1bc-ad44ec10e73f",
                columnId: "b597e2df-0d6a-439b-b1bc-ad44ec10e73f",
                type: {
                  "java.lang.String": "text",
                },
              },
              fiscal_month_label: {
                alias: "fiscal_month_label",
                id: "a9dd32bf-5040-457d-ba4b-5f5a970d9e7a",
                columnId: "a9dd32bf-5040-457d-ba4b-5f5a970d9e7a",
                type: {
                  "java.lang.String": "text",
                },
              },
              created_date: {
                alias: "created_date",
                id: "c4deccde-96e2-416d-9a0e-cb3ead05d0c0",
                columnId: "c4deccde-96e2-416d-9a0e-cb3ead05d0c0",
                type: {
                  "java.lang.String": "text",
                },
              },
              created_time: {
                alias: "created_time",
                id: "84fc9d54-7be6-4b5a-be9a-55822749cdbe",
                columnId: "84fc9d54-7be6-4b5a-be9a-55822749cdbe",
                type: {
                  "java.lang.String": "text",
                },
              },
              rating: {
                alias: "rating",
                id: "0edbd0bc-addb-4fbf-a5c2-b29834b56fbc",
                columnId: "0edbd0bc-addb-4fbf-a5c2-b29834b56fbc",
                type: {
                  "java.lang.String": "text",
                },
              },
            },
            key: "n4dc-qajz-us3k-003s-j7",
            uuid: "n4dc-qajz-us3k-003s-j7",
            query: 'select * from "dimdate"',
            queryType: "conditionIf",
            labels: [
              {
                name: "dim_id",
                type: "numeric",
                checked: true,
              },
              {
                name: "fiscal_year",
                type: "date",
                checked: true,
              },
              {
                name: "modified_date",
                type: "dateTime",
                checked: true,
              },
              {
                name: "date_key",
                type: "text",
                checked: true,
              },
              {
                name: "day_number",
                type: "text",
                checked: true,
              },
              {
                name: "fiscal_month_name",
                type: "text",
                checked: true,
              },
              {
                name: "fiscal_month_label",
                type: "text",
                checked: true,
              },
              {
                name: "created_date",
                type: "text",
                checked: true,
              },
              {
                name: "created_time",
                type: "text",
                checked: true,
              },
              {
                name: "rating",
                type: "text",
                checked: true,
              },
            ],
            dataSource: {
              id: "1",
              type: "dynamicDataSource",
              baseType: "global.jdbc",
              catSchemaPredicted: false,
              sync: false,
              catalog: "",
              schema: "HIUSER",
              connId: "fb0f9",
              classifier: "db.workflow",
              datasourceName: "SampleTravelDataDerby",
              dsKeyPath:
                "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/ar70-9nwn-yi0n-p744-3k",
              driverType: "Derby",
              database: "HIUSER",
            },
            error: false,
            validate: true,
            processedQuery:
              'select * from (select * from "dimdate") foo fetch first 1 rows only',
            id: "86e51d92-b7e6-45f3-b772-6c54d1b8688b",
            type: "view",
            isModified: true,
          },
        ],
        activeView: null,
        categories: {
          "qy80-uioo-a9eo-0x1f-1h": {
            ds: {
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "org.apache.derby.jdbc.AutoloadedDriver",
              name: "SampleTravelDataDerby",
              classifier: "global",
              dataSourceType: "Managed DataSource",
            },
            category: {
              driver: "org.apache.derby.jdbc.AutoloadedDriver",
              databaseDialect: "derby",
              name: "Derby",
              categoryName: "RDBMS",
              categoryType: "rdbms",
              type: "global.jdbc",
              dataSourceProvider: "tomcat",
              classifier: "global",
              imgUrl: "../images/data_sources/defaut_datasource.png",
              url: "jdbc:derby:{{database}}",
              parameters: {
                database: "database",
              },
            },
          },
        },
        activeEditorTab: "views",
        dataSourcesAddedToMetadata: [
          {
            id: "1",
            type: "dynamicDataSource",
            baseType: "global.jdbc",
            catSchemaPredicted: false,
            sync: false,
            catalog: "",
            schema: "HIUSER",
            connId: "fb0f9",
            classifier: "db.workflow",
            datasourceName: "SampleTravelDataDerby",
            dsKeyPath:
              "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/ar70-9nwn-yi0n-p744-3k",
            driverType: "Derby",
            database: "HIUSER",
          },
        ],
        changeDSList: {},
        changedTables: [],
        changedColumns: [],
        removedTables: [],
        removedColumns: [],
        removedDataSources: [],
        duplicateColumnList: [],
        duplicateTableList: [],
        unsavedViews: [],
        saveDetails: false,
        savedTableIds: [],
        savedColumnIds: [],
        joins: [],
        mode: "create",
        allTablesKeys: [
          "cci8-nhcn-0u15-5uaq-lh",
          "afnp-f5si-p2vk-kcqg-ez",
          "do9f-rzb8-lcfj-sy97-wu",
          "9ztq-zs3b-f61h-k4rl-ub",
          "9rff-q9xb-t0dl-u3e6-pg",
        ],
        selectedTableKeys: [
          "9ztq-zs3b-f61h-k4rl-ub",
          "do9f-rzb8-lcfj-sy97-wu",
          "cci8-nhcn-0u15-5uaq-lh",
          "afnp-f5si-p2vk-kcqg-ez",
          "9rff-q9xb-t0dl-u3e6-pg",
        ],
        metadataName: "Metadata_1",
        activeDataSource: false,
        metadataToEdit: false,
        isSavingInProgress: false,
        editViewsTempData: {
          "n4dc-qajz-us3k-003s-j7": {
            name: "View 1",
            alias: "View 1",
            columns: {},
            key: "n4dc-qajz-us3k-003s-j7",
            uuid: "n4dc-qajz-us3k-003s-j7",
            query: "",
            queryType: "conditionIf",
            labels: [
              {
                name: "dim_id",
                type: "numeric",
                checked: true,
              },
              {
                name: "fiscal_year",
                type: "date",
                checked: true,
              },
              {
                name: "modified_date",
                type: "dateTime",
                checked: true,
              },
              {
                name: "date_key",
                type: "text",
                checked: true,
              },
              {
                name: "day_number",
                type: "text",
                checked: true,
              },
              {
                name: "fiscal_month_name",
                type: "text",
                checked: true,
              },
              {
                name: "fiscal_month_label",
                type: "text",
                checked: true,
              },
              {
                name: "created_date",
                type: "text",
                checked: true,
              },
              {
                name: "created_time",
                type: "text",
                checked: true,
              },
              {
                name: "rating",
                type: "text",
                checked: true,
              },
            ],
            dataSource: {
              id: "1",
              type: "dynamicDataSource",
              baseType: "global.jdbc",
              catSchemaPredicted: false,
              sync: false,
              catalog: "",
              schema: "HIUSER",
              connId: "fb0f9",
              classifier: "db.workflow",
              datasourceName: "SampleTravelDataDerby",
              dsKeyPath:
                "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/ar70-9nwn-yi0n-p744-3k",
              driverType: "Derby",
              database: "HIUSER",
            },
            error: false,
            validate: true,
            processedQuery:
              'select * from (select * from "dimdate") foo fetch first 1 rows only',
          },
        },
        inititalStateFromJest: false,
        timeStamp: 1658902117723,
        initialEditResponse: false,
        editorFullView: false,
        selectedTableOrColumnKey: {},
        expressionObj: [],
        securityConstants: {},
        edit: false,
        isAllowServiceCall: true,
        isValidatedTableShow: false,
        securityTableData: [],
        addOneMoreSecurity: false,
        viewSessionVariables: {
          hasStoredProcedure: {
            expressions: {
              user: [
                "${user}.id",
                "${user}.email",
                "${user}.enabled",
                "${user}.name",
                "${user}.isExternalUser",
              ],
              org: ["${org}.id", "${org}.name"],
              profile: ["${profile}.name", "${profile}.id", "${profile}.value"],
              role: ["${role}.id", "${role}.name"],
            },
            tooltip: "Stored procedure",
            placeHolder: "call  yourStoredProcedure('param1','param2',...)",
          },
          conditionIf: {
            expressions: {
              user: [
                "${user}.id",
                "${user}.email",
                "${user}.enabled",
                "${user}.name",
                "${user}.isExternalUser",
              ],
              org: ["${org}.id", "${org}.name"],
              profile: ["${profile}.name", "${profile}.id", "${profile}.value"],
              role: ["${role}.id", "${role}.name"],
            },
            tooltip: "Query",
            placeHolder: "select 1",
          },
          groovy: {
            expressions: {
              filter: [
                "${filter}.label",
                "${filter}.id",
                "${filter}.column",
                "${filter}.value",
                "${filter}.values",
                "${filter}.mode",
                "${filter}.condition",
                "${filter}.fullyQualifiedColumn",
              ],
              globalOptions: [
                'check("${filter}.label","value")',
                "hasFilters()",
                "addQuotes(string)",
                'getFilterArrayByLabels(["labelArray"])',
                'findFilterByLabel("label")',
                "findFilter([key:value,key:value])",
                'findFilter(\'{"key":"value"}\')',
                "formData",
                "filters",
                "sqlContext",
                "filters.size()",
              ],
            },
            tooltip: "Dynamic Query",
            placeHolder: "return 'select 1'",
          },
        },
        textEditingObj: {},
        selectedJoinNameData: {},
        filterbyData: [
          {
            value: "All",
            isChecked: true,
          },
          {
            value: "Table",
            isChecked: true,
          },
          {
            value: "Column",
            isChecked: true,
          },
          {
            value: "Global",
            isChecked: true,
          },
        ],
        isFirstRender: true,
        securityFormData: {},
      },
    },
  }),
};

export const tableRecord = {
  id: "be534112989b616b194bc59c2fb25a42",
  name: "geo_cordinates",
  data: {
    id: "1",
    type: "dynamicDataSource",
  },
  keyPath:
    "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/ar70-9nwn-yi0n-p744-3k/cci8-nhcn-0u15-5uaq-lh",
  key: "cci8-nhcn-0u15-5uaq-lh",
  alias: "geo_cordinates",
  uuid: "cci8-nhcn-0u15-5uaq-lh",
  connId: "fb0f9",
  dataSource: {
    id: "1",
    type: "dynamicDataSource",
    baseType: "global.jdbc",
    catSchemaPredicted: false,
    sync: false,
    catalog: "",
    schema: "HIUSER",
    connId: "fb0f9",
    classifier: "db.workflow",
    datasourceName: "SampleTravelDataDerby",
    dsKeyPath:
      "qy80-uioo-a9eo-0x1f-1h/kjv1-u454-5dic-7pjc-jm/ar70-9nwn-yi0n-p744-3k",
    driverType: "Derby",
    database: "HIUSER",
  },
  dataSourceName: "SampleTravelDataDerby",
  category: "table",
  nameWithConnId: "geo_cordinates_fb0f9",
  database: "HIUSER",
  schema: "HIUSER",
  selected: true,
};
