export const store5598 = {
  dataFetchedFor: {
    getDatasource: true,
    joins: false,
    viewSessionVariables: false,
    listDataSources: true,
    "km3q-4v77-0kqd-34lh-mt": false,
    "s9ur-4tvg-ewf6-1qbf-3l": false,
    "lbvz-hq13-9k5d-paid-bk": false,
  },
  loadingStatus: {
    getDatasource: true,
    listDataSources: true,
    "km3q-4v77-0kqd-34lh-mt": false,
    "s9ur-4tvg-ewf6-1qbf-3l": false,
    "lbvz-hq13-9k5d-paid-bk": false,
  },
  serviceErrorStatus: {},
  fetchedDSInfo: {},
  listDataSource: [],
  supportedDataSourceTypes: [
    {
      name: "Access",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      name: "Amazon Dynamodb",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      name: "Amazon Redshift",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      name: "Dremio",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      name: "Google Bigquery",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      name: "Microsoft Sqlserver",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      name: "Oracle",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      name: "Teradata",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      name: "Ξ Add Driver Ξ",
      categoryType: "supported",
      categoryName: "Supported",
    },
  ],
  allDataSourceTypes: [
    {
      name: "Access",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      name: "Amazon Dynamodb",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      name: "Amazon Redshift",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      driver: "org.apache.drill.jdbc.Driver",
      databaseDialect: "drill",
      enabledTypes: false,
      name: "Apache Drill",
      categoryName: "Big Data",
      categoryType: "big_data",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:drill:{{hostName}}:{{port}}",
      parameters: {
        port: "31010",
        hostName: "drillbit=localhost",
      },
    },
    {
      driver: "com.simba.athena.jdbc.Driver",
      databaseDialect: "athena",
      name: "Athena",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:awsathena://{{hostName}}",
      parameters: {
        hostName: "localhost",
      },
    },
    {
      driver: "ru.yandex.clickhouse.ClickHouseDriver",
      databaseDialect: "clickhouse",
      name: "Clickhouse",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:clickhouse://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "8123",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "com.databricks.client.jdbc.Driver",
      databaseDialect: "databricks",
      name: "Databricks Client",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:databricks://{{hostName}}:{{port}};{{database}}",
      parameters: {
        port: "443",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "org.apache.derby.jdbc.ClientDriver",
      databaseDialect: "derby",
      name: "Derby",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:derby://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "1527",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "org.apache.derby.jdbc.AutoloadedDriver",
      databaseDialect: "derby",
      name: "Derby",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:derby:{{database}}",
      parameters: {
        database: "database",
      },
    },
    {
      name: "Dremio",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      driver: "dynamicSwitch",
      databaseDialect: "",
      name: "DynamicSwitch",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
    },
    {
      driver: "org.elasticsearch.xpack.sql.jdbc.EsDriver",
      databaseDialect: "",
      name: "Elasticsearch",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
    },
    {
      name: "Google Bigquery",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      driver: "com.helical.mongodb.MongoJdbcDriver",
      databaseDialect: "himongo",
      name: "Helical Mongodb",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
    },
    {
      driver: "org.apache.hive.jdbc.HiveDriver",
      databaseDialect: "spark",
      name: "Hive",
      categoryName: "Big Data",
      categoryType: "big_data",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:hive2://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "10001",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "com.ibm.db2.jcc.DB2Driver",
      databaseDialect: "db2",
      name: "IBM Db2",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:db2://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "50000",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "com.informix.jdbc.IfxDriver",
      databaseDialect: "informix",
      name: "Informix",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:informix-sqli://{{hostName}}:{{port}}/{{database}}:delimident=y",
      parameters: {
        port: "1526",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "org.mariadb.jdbc.Driver",
      databaseDialect: "mysql",
      name: "Mariadb",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:mariadb://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "3306",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      name: "Microsoft Sqlserver",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      driver: "net.sourceforge.jtds.jdbc.Driver",
      databaseDialect: "sqlserver",
      name: "Microsoft Sqlserver(sourceforge)",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:jtds:sqlserver://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "1433",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "com.mysql.jdbc.Driver",
      databaseDialect: "mysql",
      name: "Mysql",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "3306",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "com.mysql.cj.jdbc.Driver",
      databaseDialect: "mysql",
      name: "Mysql Cj",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "3306",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      name: "Oracle",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      driver: "org.postgresql.Driver",
      databaseDialect: "postgresql",
      name: "Postgresql",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:postgresql://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "5432",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "com.facebook.presto.jdbc.PrestoDriver",
      databaseDialect: "presto",
      name: "Presto",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:presto://{{hostName}}:{{port}}",
      parameters: {
        port: "8090",
        hostName: "localhost",
      },
    },
    {
      driver: "org.sqlite.JDBC",
      databaseDialect: "sqlite",
      name: "Sqlite",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:sqlite:{{database}}",
      parameters: {
        database: "database",
      },
    },
    {
      name: "Teradata",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      name: "Ξ Add Driver Ξ",
      categoryType: "supported",
      categoryName: "Supported",
    },
  ],
  metaDataSourceList: [
    {
      driver: "org.apache.drill.jdbc.Driver",
      databaseDialect: "drill",
      enabledTypes: false,
      name: "Apache Drill",
      categoryName: "Big Data",
      categoryType: "big_data",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:drill:{{hostName}}:{{port}}",
      parameters: {
        port: "31010",
        hostName: "drillbit=localhost",
      },
    },
    {
      driver: "com.simba.athena.jdbc.Driver",
      databaseDialect: "athena",
      name: "Athena",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:awsathena://{{hostName}}",
      parameters: {
        hostName: "localhost",
      },
    },
    {
      driver: "ru.yandex.clickhouse.ClickHouseDriver",
      databaseDialect: "clickhouse",
      name: "Clickhouse",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:clickhouse://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "8123",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "com.databricks.client.jdbc.Driver",
      databaseDialect: "databricks",
      name: "Databricks Client",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:databricks://{{hostName}}:{{port}};{{database}}",
      parameters: {
        port: "443",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "org.apache.derby.jdbc.ClientDriver",
      databaseDialect: "derby",
      name: "Derby",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:derby://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "1527",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "org.apache.derby.jdbc.AutoloadedDriver",
      databaseDialect: "derby",
      name: "Derby",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:derby:{{database}}",
      parameters: {
        database: "database",
      },
    },
    {
      driver: "dynamicSwitch",
      databaseDialect: "",
      name: "DynamicSwitch",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
    },
    {
      driver: "org.elasticsearch.xpack.sql.jdbc.EsDriver",
      databaseDialect: "",
      name: "Elasticsearch",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
    },
    {
      driver: "com.helical.mongodb.MongoJdbcDriver",
      databaseDialect: "himongo",
      name: "Helical Mongodb",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
    },
    {
      driver: "org.apache.hive.jdbc.HiveDriver",
      databaseDialect: "spark",
      name: "Hive",
      categoryName: "Big Data",
      categoryType: "big_data",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:hive2://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "10001",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "com.ibm.db2.jcc.DB2Driver",
      databaseDialect: "db2",
      name: "IBM Db2",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:db2://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "50000",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "com.informix.jdbc.IfxDriver",
      databaseDialect: "informix",
      name: "Informix",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:informix-sqli://{{hostName}}:{{port}}/{{database}}:delimident=y",
      parameters: {
        port: "1526",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "org.mariadb.jdbc.Driver",
      databaseDialect: "mysql",
      name: "Mariadb",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:mariadb://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "3306",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "net.sourceforge.jtds.jdbc.Driver",
      databaseDialect: "sqlserver",
      name: "Microsoft Sqlserver(sourceforge)",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:jtds:sqlserver://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "1433",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "com.mysql.jdbc.Driver",
      databaseDialect: "mysql",
      name: "Mysql",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "3306",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "com.mysql.cj.jdbc.Driver",
      databaseDialect: "mysql",
      name: "Mysql Cj",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "3306",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "org.postgresql.Driver",
      databaseDialect: "postgresql",
      name: "Postgresql",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:postgresql://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "5432",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "com.facebook.presto.jdbc.PrestoDriver",
      databaseDialect: "presto",
      name: "Presto",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:presto://{{hostName}}:{{port}}",
      parameters: {
        port: "8090",
        hostName: "localhost",
      },
    },
    {
      driver: "org.sqlite.JDBC",
      databaseDialect: "sqlite",
      name: "Sqlite",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:sqlite:{{database}}",
      parameters: {
        database: "database",
      },
    },
  ],
  driversList: [
    {
      driver: "dynamicSwitch",
      showInDatasource: "false",
      available: "true",
      parameters: [],
    },
    {
      url: "jdbc:derby:{{database}}",
      driver: "org.apache.derby.jdbc.AutoloadedDriver",
      available: "true",
      parameters: {
        database: "database",
      },
    },
    {
      url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
      driver: "com.mysql.cj.jdbc.Driver",
      available: "true",
      parameters: {
        port: "3306",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
      driver: "com.mysql.jdbc.Driver",
      available: "true",
      parameters: {
        port: "3306",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      available: "true",
      driver: "org.elasticsearch.xpack.sql.jdbc.EsDriver",
    },
    {
      url: "jdbc:awsathena://{{hostName}}",
      driver: "com.simba.athena.jdbc.Driver",
      available: "true",
      parameters: {
        hostName: "localhost",
      },
    },
    {
      url: "jdbc:jtds:sqlserver://{{hostName}}:{{port}}/{{database}}",
      driver: "net.sourceforge.jtds.jdbc.Driver",
      available: "true",
      parameters: {
        port: "1433",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      url: "jdbc:clickhouse://{{hostName}}:{{port}}/{{database}}",
      driver: "ru.yandex.clickhouse.ClickHouseDriver",
      available: "true",
      parameters: {
        port: "8123",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      available: "true",
      driver: "com.helical.mongodb.MongoJdbcDriver",
    },
    {
      url: "jdbc:hive2://{{hostName}}:{{port}}/{{database}}",
      driver: "org.apache.hive.jdbc.HiveDriver",
      available: "true",
      parameters: {
        port: "10001",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      url: "jdbc:drill:{{hostName}}:{{port}}",
      driver: "org.apache.drill.jdbc.Driver",
      available: "true",
      parameters: {
        port: "31010",
        hostName: "drillbit=localhost",
      },
    },
    {
      url: "jdbc:informix-sqli://{{hostName}}:{{port}}/{{database}}:delimident=y",
      driver: "com.informix.jdbc.IfxDriver",
      available: "true",
      parameters: {
        port: "1526",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      url: "jdbc:db2://{{hostName}}:{{port}}/{{database}}",
      driver: "com.ibm.db2.jcc.DB2Driver",
      available: "true",
      parameters: {
        port: "50000",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      url: "jdbc:mariadb://{{hostName}}:{{port}}/{{database}}",
      driver: "org.mariadb.jdbc.Driver",
      available: "true",
      parameters: {
        port: "3306",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      url: "jdbc:presto://{{hostName}}:{{port}}",
      driver: "com.facebook.presto.jdbc.PrestoDriver",
      available: "true",
      parameters: {
        port: "8090",
        hostName: "localhost",
      },
    },
    {
      url: "jdbc:databricks://{{hostName}}:{{port}};{{database}}",
      driver: "com.databricks.client.jdbc.Driver",
      available: "true",
      parameters: {
        port: "443",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      available: "true",
      driver: "org.elasticsearch.xpack.sql.jdbc.EsDriver",
    },
    {
      url: "jdbc:postgresql://{{hostName}}:{{port}}/{{database}}",
      driver: "org.postgresql.Driver",
      available: "true",
      parameters: {
        port: "5432",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      url: "jdbc:derby://{{hostName}}:{{port}}/{{database}}",
      driver: "org.apache.derby.jdbc.ClientDriver",
      available: "true",
      parameters: {
        port: "1527",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      url: "jdbc:sqlite:{{database}}",
      driver: "org.sqlite.JDBC",
      available: "true",
      parameters: {
        database: "database",
      },
    },
  ],
  allDataSources: [
    {
      permissionLevel: 5,
      driver: "com.mysql.jdbc.Driver",
      data: {
        dir: "TestFold",
        driverName: "com.mysql.jdbc.Driver",
        type: "sql.jdbc.groovy",
        id: 1,
        userName: "hiuser",
        password: "hiuser",
        condition:
          'import net.sf.json.JSONObject;\n    import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n    public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        responseJson.put("driverName", "com.mysql.jdbc.Driver");\n        responseJson.put("jdbcUrl", "jdbc:mysql://127.0.0.1:3306/SampleTravelData");\n        responseJson.put("userName", "root");\n        responseJson.put("password", "root");\n        return responseJson;\n    }',
        jdbcUrl: "jdbc:mysql://127.0.0.1:3306/bugzilla",
      },
      name: "bugzill",
      classifier: "efwd",
      type: "sql.jdbc.groovy",
      dataSourceType: "Plain Groovy DataSource",
    },
    {
      permissionLevel: 5,
      driver: "org.postgresql.Driver",
      data: {
        dir: "Gagan",
        driverName: "org.postgresql.Driver",
        type: "sql.jdbc.groovy",
        id: 304,
        userName: "zlvkhftkogyvevhyxvalzgvu@psql-mock-database-cloud",
        password: "zlvkhftkogyvevhyxvalzgvu@psql-mock-database-cloud",
        condition:
          'import net.sf.json.JSONObject;\n    import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n    public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        responseJson.put("driver", "com.mysql.jdbc.Driver");\n        responseJson.put("url", "jdbc:mysql://localhost:3306/" + userName);\n        responseJson.put("user", "root");\n        responseJson.put("pass", "root");\n        return responseJson;\n    }',
        jdbcUrl:
          "jdbc:postgresql://psql-mock-database-cloud.postgres.database.azure.com:5432/booking1662345944710kenxhxumioueuzfj",
      },
      name: "booking",
      classifier: "efwd",
      type: "sql.jdbc.groovy",
      dataSourceType: "Plain Groovy DataSource",
    },
    {
      permissionLevel: 5,
      driver: "dynamicSwitch",
      data: {
        dir: "Gagan",
        driverName: null,
        type: "sql.jdbc.groovy.managed",
        id: 303,
        userName: null,
        password: null,
        condition:
          'import groovy.sql.Sql;\n      import net.sf.json.JSONObject;\n      import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n      public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        if (userName.equals("hiadmin")) {\n          responseJson.put("globalId", 1);\n        }\n      \n        if (userName.equals("hiuser")) {\n          responseJson.put("globalId", 3);\n        }\n      \n        if (userName.equals("test")) {\n          responseJson.put("globalId", 4);\n        }\n      \n        responseJson.put("type", "global.jdbc");\n      \n        //throw new RuntimeException("This is a test exception" +responseJson);\n        return responseJson;\n      }',
        jdbcUrl: null,
        driver: "dynamicSwitch",
      },
      name: "new conn",
      classifier: "efwd",
      type: "sql.jdbc.groovy.managed",
      dataSourceType: "Plain Groovy Managed DataSource",
    },
    {
      permissionLevel: 5,
      driver: "dynamicSwitch",
      data: {
        dir: "Gagan",
        driverName: null,
        type: "sql.jdbc.groovy.managed",
        id: 201,
        userName: null,
        password: null,
        condition:
          'import groovy.sql.Sql;\n      import net.sf.json.JSONObject;\n      import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n      public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        if (userName.equals("hiadmin")) {\n          responseJson.put("globalId", 1);\n        }\n      \n        if (userName.equals("hiuser")) {\n          responseJson.put("globalId", 3);\n        }\n      \n        if (userName.equals("test")) {\n          responseJson.put("globalId", 4);\n        }\n      \n        responseJson.put("type", "global.jdbc");\n      \n        //throw new RuntimeException("This is a test exception" +responseJson);\n        return responseJson;\n      }',
        jdbcUrl: null,
        driver: "dynamicSwitch",
      },
      name: "groovy man",
      classifier: "efwd",
      type: "sql.jdbc.groovy.managed",
      dataSourceType: "Plain Groovy Managed DataSource",
    },
    {
      permissionLevel: 5,
      driver: "dynamicSwitch",
      data: {
        dir: "Gagan",
        driverName: null,
        type: "sql.jdbc.groovy.managed",
        id: 401,
        userName: null,
        password: null,
        condition:
          'import groovy.sql.Sql;\n      import net.sf.json.JSONObject;\n      import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n      public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        if (userName.equals("hiadmin")) {\n          responseJson.put("globalId", 1);\n        }\n      \n        if (userName.equals("hiuser")) {\n          responseJson.put("globalId", 3);\n        }\n      \n        if (userName.equals("test")) {\n          responseJson.put("globalId", 4);\n        }\n      \n        responseJson.put("type", "global.jdbc");\n      \n        //throw new RuntimeException("This is a test exception" +responseJson);\n        return responseJson;\n      }',
        jdbcUrl: null,
        driver: "dynamicSwitch",
      },
      name: "new con1",
      classifier: "efwd",
      type: "sql.jdbc.groovy.managed",
      dataSourceType: "Plain Groovy Managed DataSource",
    },
    {
      data: {
        id: "1",
        type: "dynamicDataSource",
      },
      dataSourceProvider: "tomcat",
      type: "dynamicDataSource",
      permissionLevel: 5,
      driver: "org.apache.derby.jdbc.AutoloadedDriver",
      name: "SampleTravelDataDerby",
      classifier: "global",
      dataSourceType: "Managed DataSource",
    },
  ],
  dataSourceTypes: [
    {
      type: "sql.jdbc.groovy.managed",
      name: "Groovy Managed Jdbc DataSource",
      classifier: "efwd",
      categoryName: "advanced",
      categoryType: "advanced",
    },
    {
      type: "sql.jdbc.groovy",
      name: "Groovy Plain Jdbc DataSource",
      classifier: "efwd",
      categoryName: "advanced",
      categoryType: "advanced",
    },
    {
      type: "global.jdbc",
      name: "Managed DataSource",
      classifier: "global",
      categoryName: "advanced",
      categoryType: "advanced",
    },
    {
      type: "sql.jdbc",
      name: "Plain Jdbc DataSource",
      classifier: "efwd",
      categoryName: "advanced",
      categoryType: "advanced",
    },
  ],
  datasourceListToRender: [
    {
      name: "Derby",
      children: [
        {
          data: {
            id: "1",
            type: "dynamicDataSource",
          },
          dataSourceProvider: "tomcat",
          type: "dynamicDataSource",
          permissionLevel: 5,
          driver: "org.apache.derby.jdbc.AutoloadedDriver",
          name: "SampleTravelDataDerby",
          classifier: "global",
          dataSourceType: "Managed DataSource",
          category: "dataSource",
          children: [
            {
              name: "SQLJ",
              children: [],
              keyPath:
                "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/5yo4-81by-0f1k-tqic-zq",
              key: "5yo4-81by-0f1k-tqic-zq",
              uuid: "5yo4-81by-0f1k-tqic-zq",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
            },
            {
              name: "SYSFUN",
              children: [],
              keyPath:
                "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/qj4u-0sru-sixr-wei4-nk",
              key: "qj4u-0sru-sixr-wei4-nk",
              uuid: "qj4u-0sru-sixr-wei4-nk",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
            },
            {
              name: "SYSCAT",
              children: [],
              keyPath:
                "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/9jyu-713s-wf4f-hd1w-vu",
              key: "9jyu-713s-wf4f-hd1w-vu",
              uuid: "9jyu-713s-wf4f-hd1w-vu",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
            },
            {
              name: "HIUSER",
              children: [
                {
                  id: "4ac5d9f68b58bd7c0d179146e46795be",
                  name: "dimdate",
                  data: {
                    id: "1",
                    type: "dynamicDataSource",
                  },
                  keyPath:
                    "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/s9ur-4tvg-ewf6-1qbf-3l/lbvz-hq13-9k5d-paid-bk",
                  key: "lbvz-hq13-9k5d-paid-bk",
                  alias: "dimdate",
                  uuid: "lbvz-hq13-9k5d-paid-bk",
                  connId: "oh4uh",
                  dataSource: {
                    id: "1",
                    type: "dynamicDataSource",
                    baseType: "global.jdbc",
                    catSchemaPredicted: false,
                    sync: false,
                    catalog: "",
                    schema: "HIUSER",
                    connId: "oh4uh",
                    classifier: "db.workflow",
                    datasourceName: "SampleTravelDataDerby",
                    dsKeyPath:
                      "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/s9ur-4tvg-ewf6-1qbf-3l",
                    driverType: "Derby",
                    database: "HIUSER",
                  },
                  dataSourceName: "SampleTravelDataDerby",
                  category: "table",
                  nameWithConnId: "dimdate_oh4uh",
                  database: "HIUSER",
                  schema: "HIUSER",
                  selected: true,
                },
                {
                  id: "4e1fd245f4d13b77be423a43f01d80b2",
                  name: "employee_details",
                  data: {
                    id: "1",
                    type: "dynamicDataSource",
                  },
                  keyPath:
                    "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/s9ur-4tvg-ewf6-1qbf-3l/zp27-zcus-d9r5-lbh3-yn",
                  key: "zp27-zcus-d9r5-lbh3-yn",
                  alias: "employee_details",
                  uuid: "zp27-zcus-d9r5-lbh3-yn",
                  connId: "oh4uh",
                  dataSource: {
                    id: "1",
                    type: "dynamicDataSource",
                    baseType: "global.jdbc",
                    catSchemaPredicted: false,
                    sync: false,
                    catalog: "",
                    schema: "HIUSER",
                    connId: "oh4uh",
                    classifier: "db.workflow",
                    datasourceName: "SampleTravelDataDerby",
                    dsKeyPath:
                      "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/s9ur-4tvg-ewf6-1qbf-3l",
                    driverType: "Derby",
                    database: "HIUSER",
                  },
                  dataSourceName: "SampleTravelDataDerby",
                  category: "table",
                  nameWithConnId: "employee_details_oh4uh",
                  database: "HIUSER",
                  schema: "HIUSER",
                  selected: true,
                },
                {
                  id: "be534112989b616b194bc59c2fb25a42",
                  name: "geo_cordinates",
                  data: {
                    id: "1",
                    type: "dynamicDataSource",
                  },
                  keyPath:
                    "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/s9ur-4tvg-ewf6-1qbf-3l/e5hl-dvsc-boy3-6l9n-ga",
                  key: "e5hl-dvsc-boy3-6l9n-ga",
                  alias: "geo_cordinates",
                  uuid: "e5hl-dvsc-boy3-6l9n-ga",
                  connId: "oh4uh",
                  dataSource: {
                    id: "1",
                    type: "dynamicDataSource",
                    baseType: "global.jdbc",
                    catSchemaPredicted: false,
                    sync: false,
                    catalog: "",
                    schema: "HIUSER",
                    connId: "oh4uh",
                    classifier: "db.workflow",
                    datasourceName: "SampleTravelDataDerby",
                    dsKeyPath:
                      "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/s9ur-4tvg-ewf6-1qbf-3l",
                    driverType: "Derby",
                    database: "HIUSER",
                  },
                  dataSourceName: "SampleTravelDataDerby",
                  category: "table",
                  nameWithConnId: "geo_cordinates_oh4uh",
                  database: "HIUSER",
                  schema: "HIUSER",
                  selected: true,
                },
                {
                  id: "9645c648a1c0dbeec1287aaf1e996db3",
                  name: "meeting_details",
                  data: {
                    id: "1",
                    type: "dynamicDataSource",
                  },
                  keyPath:
                    "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/s9ur-4tvg-ewf6-1qbf-3l/v27h-ab6e-eq8q-0awr-66",
                  key: "v27h-ab6e-eq8q-0awr-66",
                  alias: "meeting_details",
                  uuid: "v27h-ab6e-eq8q-0awr-66",
                  connId: "oh4uh",
                  dataSource: {
                    id: "1",
                    type: "dynamicDataSource",
                    baseType: "global.jdbc",
                    catSchemaPredicted: false,
                    sync: false,
                    catalog: "",
                    schema: "HIUSER",
                    connId: "oh4uh",
                    classifier: "db.workflow",
                    datasourceName: "SampleTravelDataDerby",
                    dsKeyPath:
                      "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/s9ur-4tvg-ewf6-1qbf-3l",
                    driverType: "Derby",
                    database: "HIUSER",
                  },
                  dataSourceName: "SampleTravelDataDerby",
                  category: "table",
                  nameWithConnId: "meeting_details_oh4uh",
                  database: "HIUSER",
                  schema: "HIUSER",
                  selected: true,
                },
                {
                  id: "8a28627d07d04ef096d9935f12e0c7e9",
                  name: "travel_details",
                  data: {
                    id: "1",
                    type: "dynamicDataSource",
                  },
                  keyPath:
                    "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/s9ur-4tvg-ewf6-1qbf-3l/d1ko-ixts-n7x8-12v2-n7",
                  key: "d1ko-ixts-n7x8-12v2-n7",
                  alias: "travel_details",
                  uuid: "d1ko-ixts-n7x8-12v2-n7",
                  connId: "oh4uh",
                  dataSource: {
                    id: "1",
                    type: "dynamicDataSource",
                    baseType: "global.jdbc",
                    catSchemaPredicted: false,
                    sync: false,
                    catalog: "",
                    schema: "HIUSER",
                    connId: "oh4uh",
                    classifier: "db.workflow",
                    datasourceName: "SampleTravelDataDerby",
                    dsKeyPath:
                      "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/s9ur-4tvg-ewf6-1qbf-3l",
                    driverType: "Derby",
                    database: "HIUSER",
                  },
                  dataSourceName: "SampleTravelDataDerby",
                  category: "table",
                  nameWithConnId: "travel_details_oh4uh",
                  database: "HIUSER",
                  schema: "HIUSER",
                  selected: true,
                },
              ],
              keyPath:
                "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/s9ur-4tvg-ewf6-1qbf-3l",
              key: "s9ur-4tvg-ewf6-1qbf-3l",
              uuid: "s9ur-4tvg-ewf6-1qbf-3l",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
              fetched: true,
            },
            {
              name: "SYSCS_DIAG",
              children: [],
              keyPath:
                "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/bel1-a6xx-12kx-88q3-kf",
              key: "bel1-a6xx-12kx-88q3-kf",
              uuid: "bel1-a6xx-12kx-88q3-kf",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
            },
            {
              name: "SYSCS_UTIL",
              children: [],
              keyPath:
                "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/b6uz-q299-jsie-dugs-r6",
              key: "b6uz-q299-jsie-dugs-r6",
              uuid: "b6uz-q299-jsie-dugs-r6",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
            },
            {
              name: "SYSIBM",
              children: [],
              keyPath:
                "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/7jyo-6gy0-lifg-au1f-id",
              key: "7jyo-6gy0-lifg-au1f-id",
              uuid: "7jyo-6gy0-lifg-au1f-id",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
            },
            {
              name: "APP",
              children: [],
              keyPath:
                "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/qvdr-9bcu-jotf-tlhl-03",
              key: "qvdr-9bcu-jotf-tlhl-03",
              uuid: "qvdr-9bcu-jotf-tlhl-03",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
            },
            {
              name: "NULLID",
              children: [],
              keyPath:
                "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/ux59-x5fg-8o10-evne-h5",
              key: "ux59-x5fg-8o10-evne-h5",
              uuid: "ux59-x5fg-8o10-evne-h5",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
            },
            {
              name: "SYSPROC",
              children: [],
              keyPath:
                "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/akjr-igyr-gu9a-pny3-qg",
              key: "akjr-igyr-gu9a-pny3-qg",
              uuid: "akjr-igyr-gu9a-pny3-qg",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
            },
            {
              name: "SYS",
              children: [],
              keyPath:
                "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/o3vs-fpvd-4qhh-hf4a-kp",
              key: "o3vs-fpvd-4qhh-hf4a-kp",
              uuid: "o3vs-fpvd-4qhh-hf4a-kp",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
            },
            {
              name: "SYSSTAT",
              children: [],
              keyPath:
                "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/00wg-q7ms-6x6l-7f3m-vl",
              key: "00wg-q7ms-6x6l-7f3m-vl",
              uuid: "00wg-q7ms-6x6l-7f3m-vl",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
            },
          ],
          driverType: "Derby",
          keyPath: "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt",
          key: "km3q-4v77-0kqd-34lh-mt",
          uuid: "km3q-4v77-0kqd-34lh-mt",
          fetched: true,
        },
      ],
      key: "0imw-a30r-c3bl-w93g-7x",
      uuid: "0imw-a30r-c3bl-w93g-7x",
      keyPath: "0imw-a30r-c3bl-w93g-7x",
      category: "dsGroup",
      imgUrl: "images/data_sources/defaut_datasource.png",
    },
    {
      name: "DynamicSwitch",
      children: [
        {
          permissionLevel: 5,
          driver: "dynamicSwitch",
          data: {
            dir: "Gagan",
            driverName: null,
            type: "sql.jdbc.groovy.managed",
            id: 303,
            userName: null,
            password: null,
            condition:
              'import groovy.sql.Sql;\n      import net.sf.json.JSONObject;\n      import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n      public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        if (userName.equals("hiadmin")) {\n          responseJson.put("globalId", 1);\n        }\n      \n        if (userName.equals("hiuser")) {\n          responseJson.put("globalId", 3);\n        }\n      \n        if (userName.equals("test")) {\n          responseJson.put("globalId", 4);\n        }\n      \n        responseJson.put("type", "global.jdbc");\n      \n        //throw new RuntimeException("This is a test exception" +responseJson);\n        return responseJson;\n      }',
            jdbcUrl: null,
            driver: "dynamicSwitch",
          },
          name: "new conn",
          classifier: "efwd",
          type: "sql.jdbc.groovy.managed",
          dataSourceType: "Plain Groovy Managed DataSource",
          category: "dataSource",
          children: [],
          driverType: "DynamicSwitch",
          keyPath: "udnj-zujl-74jj-e4sv-7i/k3qz-hl9z-ct1r-9ufr-av",
          key: "k3qz-hl9z-ct1r-9ufr-av",
          uuid: "k3qz-hl9z-ct1r-9ufr-av",
        },
        {
          permissionLevel: 5,
          driver: "dynamicSwitch",
          data: {
            dir: "Gagan",
            driverName: null,
            type: "sql.jdbc.groovy.managed",
            id: 201,
            userName: null,
            password: null,
            condition:
              'import groovy.sql.Sql;\n      import net.sf.json.JSONObject;\n      import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n      public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        if (userName.equals("hiadmin")) {\n          responseJson.put("globalId", 1);\n        }\n      \n        if (userName.equals("hiuser")) {\n          responseJson.put("globalId", 3);\n        }\n      \n        if (userName.equals("test")) {\n          responseJson.put("globalId", 4);\n        }\n      \n        responseJson.put("type", "global.jdbc");\n      \n        //throw new RuntimeException("This is a test exception" +responseJson);\n        return responseJson;\n      }',
            jdbcUrl: null,
            driver: "dynamicSwitch",
          },
          name: "groovy man",
          classifier: "efwd",
          type: "sql.jdbc.groovy.managed",
          dataSourceType: "Plain Groovy Managed DataSource",
          category: "dataSource",
          children: [],
          driverType: "DynamicSwitch",
          keyPath: "udnj-zujl-74jj-e4sv-7i/0v5v-gdcy-lh2o-ttbm-vo",
          key: "0v5v-gdcy-lh2o-ttbm-vo",
          uuid: "0v5v-gdcy-lh2o-ttbm-vo",
        },
        {
          permissionLevel: 5,
          driver: "dynamicSwitch",
          data: {
            dir: "Gagan",
            driverName: null,
            type: "sql.jdbc.groovy.managed",
            id: 401,
            userName: null,
            password: null,
            condition:
              'import groovy.sql.Sql;\n      import net.sf.json.JSONObject;\n      import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n      public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        if (userName.equals("hiadmin")) {\n          responseJson.put("globalId", 1);\n        }\n      \n        if (userName.equals("hiuser")) {\n          responseJson.put("globalId", 3);\n        }\n      \n        if (userName.equals("test")) {\n          responseJson.put("globalId", 4);\n        }\n      \n        responseJson.put("type", "global.jdbc");\n      \n        //throw new RuntimeException("This is a test exception" +responseJson);\n        return responseJson;\n      }',
            jdbcUrl: null,
            driver: "dynamicSwitch",
          },
          name: "new con1",
          classifier: "efwd",
          type: "sql.jdbc.groovy.managed",
          dataSourceType: "Plain Groovy Managed DataSource",
          category: "dataSource",
          children: [],
          driverType: "DynamicSwitch",
          keyPath: "udnj-zujl-74jj-e4sv-7i/wolp-alcm-z8cg-8226-c0",
          key: "wolp-alcm-z8cg-8226-c0",
          uuid: "wolp-alcm-z8cg-8226-c0",
        },
      ],
      key: "udnj-zujl-74jj-e4sv-7i",
      uuid: "udnj-zujl-74jj-e4sv-7i",
      keyPath: "udnj-zujl-74jj-e4sv-7i",
      category: "dsGroup",
      imgUrl: "images/data_sources/defaut_datasource.png",
    },
    {
      name: "Mysql",
      children: [
        {
          permissionLevel: 5,
          driver: "com.mysql.jdbc.Driver",
          data: {
            dir: "TestFold",
            driverName: "com.mysql.jdbc.Driver",
            type: "sql.jdbc.groovy",
            id: 1,
            userName: "hiuser",
            password: "hiuser",
            condition:
              'import net.sf.json.JSONObject;\n    import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n    public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        responseJson.put("driverName", "com.mysql.jdbc.Driver");\n        responseJson.put("jdbcUrl", "jdbc:mysql://127.0.0.1:3306/SampleTravelData");\n        responseJson.put("userName", "root");\n        responseJson.put("password", "root");\n        return responseJson;\n    }',
            jdbcUrl: "jdbc:mysql://127.0.0.1:3306/bugzilla",
          },
          name: "bugzill",
          classifier: "efwd",
          type: "sql.jdbc.groovy",
          dataSourceType: "Plain Groovy DataSource",
          category: "dataSource",
          children: [],
          driverType: "Mysql",
          keyPath: "ajw5-a079-3fjd-ohry-ip/qux2-kkkb-wm2e-hrub-ef",
          key: "qux2-kkkb-wm2e-hrub-ef",
          uuid: "qux2-kkkb-wm2e-hrub-ef",
        },
      ],
      key: "ajw5-a079-3fjd-ohry-ip",
      uuid: "ajw5-a079-3fjd-ohry-ip",
      keyPath: "ajw5-a079-3fjd-ohry-ip",
      category: "dsGroup",
      imgUrl: "images/data_sources/defaut_datasource.png",
    },
    {
      name: "Postgresql",
      children: [
        {
          permissionLevel: 5,
          driver: "org.postgresql.Driver",
          data: {
            dir: "Gagan",
            driverName: "org.postgresql.Driver",
            type: "sql.jdbc.groovy",
            id: 304,
            userName: "zlvkhftkogyvevhyxvalzgvu@psql-mock-database-cloud",
            password: "zlvkhftkogyvevhyxvalzgvu@psql-mock-database-cloud",
            condition:
              'import net.sf.json.JSONObject;\n    import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n    public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        responseJson.put("driver", "com.mysql.jdbc.Driver");\n        responseJson.put("url", "jdbc:mysql://localhost:3306/" + userName);\n        responseJson.put("user", "root");\n        responseJson.put("pass", "root");\n        return responseJson;\n    }',
            jdbcUrl:
              "jdbc:postgresql://psql-mock-database-cloud.postgres.database.azure.com:5432/booking1662345944710kenxhxumioueuzfj",
          },
          name: "booking",
          classifier: "efwd",
          type: "sql.jdbc.groovy",
          dataSourceType: "Plain Groovy DataSource",
          category: "dataSource",
          children: [],
          driverType: "Postgresql",
          keyPath: "i91q-zfm0-8oq1-9920-68/zyko-l9zj-d28f-ttyw-i9",
          key: "zyko-l9zj-d28f-ttyw-i9",
          uuid: "zyko-l9zj-d28f-ttyw-i9",
        },
      ],
      key: "i91q-zfm0-8oq1-9920-68",
      uuid: "i91q-zfm0-8oq1-9920-68",
      keyPath: "i91q-zfm0-8oq1-9920-68",
      category: "dsGroup",
      imgUrl: "images/data_sources/defaut_datasource.png",
    },
  ],
  workFlow: {
    dataList: [
      {
        fetchSchemas: true,
        fetchCatalogs: true,
        working: true,
        connData: {
          id: "1",
          type: "dynamicDataSource",
        },
        connId: "1",
        dsUUID: "km3q-4v77-0kqd-34lh-mt",
        classifier: "db.workflow",
        metadata: {
          catalogs: [
            {
              name: "Null",
              schemas: [
                {
                  name: "SQLJ",
                },
                {
                  name: "SYSFUN",
                },
                {
                  name: "SYSCAT",
                },
                {
                  name: "HIUSER",
                },
                {
                  name: "SYSCS_DIAG",
                },
                {
                  name: "SYSCS_UTIL",
                },
                {
                  name: "SYSIBM",
                },
                {
                  name: "APP",
                },
                {
                  name: "NULLID",
                },
                {
                  name: "SYSPROC",
                },
                {
                  name: "SYS",
                },
                {
                  name: "SYSSTAT",
                },
              ],
            },
          ],
        },
      },
      {
        classifier: "db.workflow",
        metadata: {
          catalogs: [
            {
              name: "Null",
              schemas: [
                {
                  name: "HIUSER",
                  tables: [
                    {
                      id: "be534112989b616b194bc59c2fb25a42",
                      name: "geo_cordinates",
                    },
                    {
                      id: "9645c648a1c0dbeec1287aaf1e996db3",
                      name: "meeting_details",
                    },
                    {
                      id: "4e1fd245f4d13b77be423a43f01d80b2",
                      name: "employee_details",
                    },
                    {
                      id: "4ac5d9f68b58bd7c0d179146e46795be",
                      name: "dimdate",
                    },
                    {
                      id: "8a28627d07d04ef096d9935f12e0c7e9",
                      name: "travel_details",
                    },
                  ],
                },
              ],
            },
          ],
          dataSource: {
            id: "1",
            type: "dynamicDataSource",
            baseType: "global.jdbc",
            catSchemaPredicted: false,
            sync: false,
            catalog: "",
            schema: "HIUSER",
            connId: "oh4uh",
            classifier: "db.workflow",
            datasourceName: "SampleTravelDataDerby",
            dsKeyPath:
              "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/s9ur-4tvg-ewf6-1qbf-3l",
            driverType: "Derby",
            database: "HIUSER",
          },
          name: "HIUSER",
        },
      },
    ],
  },
  dataSource: [
    {
      id: "1",
      type: "dynamicDataSource",
      baseType: "global.jdbc",
      catSchemaPredicted: false,
      sync: false,
      catalog: "",
      schema: "HIUSER",
      connId: "oh4uh",
      classifier: "db.workflow",
      datasourceName: "SampleTravelDataDerby",
      dsKeyPath:
        "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/s9ur-4tvg-ewf6-1qbf-3l",
      driverType: "Derby",
      database: "HIUSER",
    },
  ],
  tables: {
    dimdate: {
      id: "4ac5d9f68b58bd7c0d179146e46795be",
      name: "dimdate",
      data: {
        id: "1",
        type: "dynamicDataSource",
      },
      keyPath:
        "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/s9ur-4tvg-ewf6-1qbf-3l/lbvz-hq13-9k5d-paid-bk",
      key: "lbvz-hq13-9k5d-paid-bk",
      alias: "dimdate",
      uuid: "lbvz-hq13-9k5d-paid-bk",
      connId: "oh4uh",
      dataSource: {
        id: "1",
        type: "dynamicDataSource",
        baseType: "global.jdbc",
        catSchemaPredicted: false,
        sync: false,
        catalog: "",
        schema: "HIUSER",
        connId: "oh4uh",
        classifier: "db.workflow",
        datasourceName: "SampleTravelDataDerby",
        dsKeyPath:
          "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/s9ur-4tvg-ewf6-1qbf-3l",
        driverType: "Derby",
        database: "HIUSER",
      },
      dataSourceName: "SampleTravelDataDerby",
      category: "table",
      nameWithConnId: "dimdate_oh4uh",
      database: "HIUSER",
      schema: "HIUSER",
      selected: true,
      keyName: "dimdate",
      columns: {
        dim_id: {
          alias: "dim_id",
          fullyQualifiedColumn: "dimdate.dim_id",
          defaultFunction: "db.generic.aggregate.sum",
          type: {
            "java.lang.Integer": "numeric",
          },
          category: "column",
          originalName: "dim_id",
          originalId: "90b72023-c5b7-40fa-b73b-1fff251e0dea",
          tableKey: "dimdate",
          connId: "oh4uh",
          duplicateIndex: 0,
          columnKey: "dim_id",
          _columnId: "90b72023-c5b7-40fa-b73b-1fff251e0dea",
          uuid: "j8i4-ymsp-vt5z-k5ub-qt",
        },
        fiscal_year: {
          alias: "fiscal_year",
          fullyQualifiedColumn: "dimdate.fiscal_year",
          defaultFunction: "db.generic.groupBy.group",
          type: {
            "java.sql.Date": "date",
          },
          category: "column",
          originalName: "fiscal_year",
          originalId: "590c67b3-bfc1-4bf0-8184-7319e68bb7bf",
          tableKey: "dimdate",
          connId: "oh4uh",
          duplicateIndex: 0,
          columnKey: "fiscal_year",
          _columnId: "590c67b3-bfc1-4bf0-8184-7319e68bb7bf",
          uuid: "m9g1-ov9r-ycxd-gfcg-1i",
        },
        modified_date: {
          alias: "modified_date",
          fullyQualifiedColumn: "dimdate.modified_date",
          defaultFunction: "db.generic.groupBy.group",
          type: {
            "java.sql.Timestamp": "dateTime",
          },
          category: "column",
          originalName: "modified_date",
          originalId: "7590975e-ad0c-4056-9a9c-0aaa47dc059a",
          tableKey: "dimdate",
          connId: "oh4uh",
          duplicateIndex: 0,
          columnKey: "modified_date",
          _columnId: "7590975e-ad0c-4056-9a9c-0aaa47dc059a",
          uuid: "n49u-r3yr-rwa1-hlry-el",
        },
        date_key: {
          alias: "date_key",
          fullyQualifiedColumn: "dimdate.date_key",
          defaultFunction: "db.generic.groupBy.group",
          type: {
            "java.lang.String": "text",
          },
          category: "column",
          originalName: "date_key",
          originalId: "a01be8d7-dfbc-41e0-b652-c5ffa2c1c798",
          tableKey: "dimdate",
          connId: "oh4uh",
          duplicateIndex: 0,
          columnKey: "date_key",
          _columnId: "a01be8d7-dfbc-41e0-b652-c5ffa2c1c798",
          uuid: "909j-kci0-aywo-pv4y-se",
        },
        day_number: {
          alias: "day_number",
          fullyQualifiedColumn: "dimdate.day_number",
          defaultFunction: "db.generic.groupBy.group",
          type: {
            "java.lang.String": "text",
          },
          category: "column",
          originalName: "day_number",
          originalId: "d90fa697-1639-4115-8f2f-a73568368fa7",
          tableKey: "dimdate",
          connId: "oh4uh",
          duplicateIndex: 0,
          columnKey: "day_number",
          _columnId: "d90fa697-1639-4115-8f2f-a73568368fa7",
          uuid: "evri-8nt6-j1ru-g4p5-sf",
        },
        fiscal_month_name: {
          alias: "fiscal_month_name",
          fullyQualifiedColumn: "dimdate.fiscal_month_name",
          defaultFunction: "db.generic.groupBy.group",
          type: {
            "java.lang.String": "text",
          },
          category: "column",
          originalName: "fiscal_month_name",
          originalId: "0407ae4d-b8c5-43f0-885b-7951d39773d1",
          tableKey: "dimdate",
          connId: "oh4uh",
          duplicateIndex: 0,
          columnKey: "fiscal_month_name",
          _columnId: "0407ae4d-b8c5-43f0-885b-7951d39773d1",
          uuid: "96wb-pu7b-pprw-c1wm-jp",
        },
        fiscal_month_label: {
          alias: "fiscal_month_label",
          fullyQualifiedColumn: "dimdate.fiscal_month_label",
          defaultFunction: "db.generic.groupBy.group",
          type: {
            "java.lang.String": "text",
          },
          category: "column",
          originalName: "fiscal_month_label",
          originalId: "c2a6855b-f91b-4b69-b720-73361fce1b5a",
          tableKey: "dimdate",
          connId: "oh4uh",
          duplicateIndex: 0,
          columnKey: "fiscal_month_label",
          _columnId: "c2a6855b-f91b-4b69-b720-73361fce1b5a",
          uuid: "zvjb-oubj-mkn6-v5us-mc",
        },
        created_date: {
          alias: "created_date",
          fullyQualifiedColumn: "dimdate.created_date",
          defaultFunction: "db.generic.groupBy.group",
          type: {
            "java.lang.String": "text",
          },
          category: "column",
          originalName: "created_date",
          originalId: "aafda9c2-d481-475b-bbad-9752ecedf02b",
          tableKey: "dimdate",
          connId: "oh4uh",
          duplicateIndex: 0,
          columnKey: "created_date",
          _columnId: "aafda9c2-d481-475b-bbad-9752ecedf02b",
          uuid: "zg73-dcn5-z8o5-8flg-qk",
        },
        created_time: {
          alias: "created_time",
          fullyQualifiedColumn: "dimdate.created_time",
          defaultFunction: "db.generic.groupBy.group",
          type: {
            "java.lang.String": "text",
          },
          category: "column",
          originalName: "created_time",
          originalId: "45f91e9e-7ecb-40f9-b0f8-db540c46a8b9",
          tableKey: "dimdate",
          connId: "oh4uh",
          duplicateIndex: 0,
          columnKey: "created_time",
          _columnId: "45f91e9e-7ecb-40f9-b0f8-db540c46a8b9",
          uuid: "ze5u-h315-lwac-2ygf-ga",
        },
        rating: {
          alias: "rating",
          fullyQualifiedColumn: "dimdate.rating",
          defaultFunction: "db.generic.groupBy.group",
          type: {
            "java.lang.String": "text",
          },
          category: "column",
          originalName: "rating",
          originalId: "5aeedfe5-e387-4334-a7d4-3d63594a6b97",
          tableKey: "dimdate",
          connId: "oh4uh",
          duplicateIndex: 0,
          columnKey: "rating",
          _columnId: "5aeedfe5-e387-4334-a7d4-3d63594a6b97",
          uuid: "csbl-4gr1-wlzg-ullt-6a",
        },
      },
      columnsFetched: true,
    },
    employee_details: {
      id: "4e1fd245f4d13b77be423a43f01d80b2",
      name: "employee_details",
      data: {
        id: "1",
        type: "dynamicDataSource",
      },
      keyPath:
        "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/s9ur-4tvg-ewf6-1qbf-3l/zp27-zcus-d9r5-lbh3-yn",
      key: "zp27-zcus-d9r5-lbh3-yn",
      alias: "employee_details",
      uuid: "zp27-zcus-d9r5-lbh3-yn",
      connId: "oh4uh",
      dataSource: {
        id: "1",
        type: "dynamicDataSource",
        baseType: "global.jdbc",
        catSchemaPredicted: false,
        sync: false,
        catalog: "",
        schema: "HIUSER",
        connId: "oh4uh",
        classifier: "db.workflow",
        datasourceName: "SampleTravelDataDerby",
        dsKeyPath:
          "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/s9ur-4tvg-ewf6-1qbf-3l",
        driverType: "Derby",
        database: "HIUSER",
      },
      dataSourceName: "SampleTravelDataDerby",
      category: "table",
      nameWithConnId: "employee_details_oh4uh",
      database: "HIUSER",
      schema: "HIUSER",
      selected: true,
      keyName: "employee_details",
    },
    geo_cordinates: {
      id: "be534112989b616b194bc59c2fb25a42",
      name: "geo_cordinates",
      data: {
        id: "1",
        type: "dynamicDataSource",
      },
      keyPath:
        "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/s9ur-4tvg-ewf6-1qbf-3l/e5hl-dvsc-boy3-6l9n-ga",
      key: "e5hl-dvsc-boy3-6l9n-ga",
      alias: "geo_cordinates",
      uuid: "e5hl-dvsc-boy3-6l9n-ga",
      connId: "oh4uh",
      dataSource: {
        id: "1",
        type: "dynamicDataSource",
        baseType: "global.jdbc",
        catSchemaPredicted: false,
        sync: false,
        catalog: "",
        schema: "HIUSER",
        connId: "oh4uh",
        classifier: "db.workflow",
        datasourceName: "SampleTravelDataDerby",
        dsKeyPath:
          "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/s9ur-4tvg-ewf6-1qbf-3l",
        driverType: "Derby",
        database: "HIUSER",
      },
      dataSourceName: "SampleTravelDataDerby",
      category: "table",
      nameWithConnId: "geo_cordinates_oh4uh",
      database: "HIUSER",
      schema: "HIUSER",
      selected: true,
      keyName: "geo_cordinates",
    },
    meeting_details: {
      id: "9645c648a1c0dbeec1287aaf1e996db3",
      name: "meeting_details",
      data: {
        id: "1",
        type: "dynamicDataSource",
      },
      keyPath:
        "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/s9ur-4tvg-ewf6-1qbf-3l/v27h-ab6e-eq8q-0awr-66",
      key: "v27h-ab6e-eq8q-0awr-66",
      alias: "meeting_details",
      uuid: "v27h-ab6e-eq8q-0awr-66",
      connId: "oh4uh",
      dataSource: {
        id: "1",
        type: "dynamicDataSource",
        baseType: "global.jdbc",
        catSchemaPredicted: false,
        sync: false,
        catalog: "",
        schema: "HIUSER",
        connId: "oh4uh",
        classifier: "db.workflow",
        datasourceName: "SampleTravelDataDerby",
        dsKeyPath:
          "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/s9ur-4tvg-ewf6-1qbf-3l",
        driverType: "Derby",
        database: "HIUSER",
      },
      dataSourceName: "SampleTravelDataDerby",
      category: "table",
      nameWithConnId: "meeting_details_oh4uh",
      database: "HIUSER",
      schema: "HIUSER",
      selected: true,
      keyName: "meeting_details",
    },
    travel_details: {
      id: "8a28627d07d04ef096d9935f12e0c7e9",
      name: "travel_details",
      data: {
        id: "1",
        type: "dynamicDataSource",
      },
      keyPath:
        "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/s9ur-4tvg-ewf6-1qbf-3l/d1ko-ixts-n7x8-12v2-n7",
      key: "d1ko-ixts-n7x8-12v2-n7",
      alias: "travel_details",
      uuid: "d1ko-ixts-n7x8-12v2-n7",
      connId: "oh4uh",
      dataSource: {
        id: "1",
        type: "dynamicDataSource",
        baseType: "global.jdbc",
        catSchemaPredicted: false,
        sync: false,
        catalog: "",
        schema: "HIUSER",
        connId: "oh4uh",
        classifier: "db.workflow",
        datasourceName: "SampleTravelDataDerby",
        dsKeyPath:
          "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/s9ur-4tvg-ewf6-1qbf-3l",
        driverType: "Derby",
        database: "HIUSER",
      },
      dataSourceName: "SampleTravelDataDerby",
      category: "table",
      nameWithConnId: "travel_details_oh4uh",
      database: "HIUSER",
      schema: "HIUSER",
      selected: true,
      keyName: "travel_details",
    },
  },
  views: [],
  activeView: false,
  categories: {
    "0imw-a30r-c3bl-w93g-7x": {
      ds: {
        data: {
          id: "1",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.apache.derby.jdbc.AutoloadedDriver",
        name: "SampleTravelDataDerby",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
      category: {
        driver: "org.apache.derby.jdbc.AutoloadedDriver",
        databaseDialect: "derby",
        name: "Derby",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:derby:{{database}}",
        parameters: {
          database: "database",
        },
      },
    },
    "udnj-zujl-74jj-e4sv-7i": {
      ds: {
        permissionLevel: 5,
        driver: "dynamicSwitch",
        data: {
          dir: "Gagan",
          driverName: null,
          type: "sql.jdbc.groovy.managed",
          id: 303,
          userName: null,
          password: null,
          condition:
            'import groovy.sql.Sql;\n      import net.sf.json.JSONObject;\n      import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n      public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        if (userName.equals("hiadmin")) {\n          responseJson.put("globalId", 1);\n        }\n      \n        if (userName.equals("hiuser")) {\n          responseJson.put("globalId", 3);\n        }\n      \n        if (userName.equals("test")) {\n          responseJson.put("globalId", 4);\n        }\n      \n        responseJson.put("type", "global.jdbc");\n      \n        //throw new RuntimeException("This is a test exception" +responseJson);\n        return responseJson;\n      }',
          jdbcUrl: null,
          driver: "dynamicSwitch",
        },
        name: "new conn",
        classifier: "efwd",
        type: "sql.jdbc.groovy.managed",
        dataSourceType: "Plain Groovy Managed DataSource",
      },
      category: {
        driver: "dynamicSwitch",
        databaseDialect: "",
        name: "DynamicSwitch",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
      },
    },
    "ajw5-a079-3fjd-ohry-ip": {
      ds: {
        permissionLevel: 5,
        driver: "com.mysql.jdbc.Driver",
        data: {
          dir: "TestFold",
          driverName: "com.mysql.jdbc.Driver",
          type: "sql.jdbc.groovy",
          id: 1,
          userName: "hiuser",
          password: "hiuser",
          condition:
            'import net.sf.json.JSONObject;\n    import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n    public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        responseJson.put("driverName", "com.mysql.jdbc.Driver");\n        responseJson.put("jdbcUrl", "jdbc:mysql://127.0.0.1:3306/SampleTravelData");\n        responseJson.put("userName", "root");\n        responseJson.put("password", "root");\n        return responseJson;\n    }',
          jdbcUrl: "jdbc:mysql://127.0.0.1:3306/bugzilla",
        },
        name: "bugzill",
        classifier: "efwd",
        type: "sql.jdbc.groovy",
        dataSourceType: "Plain Groovy DataSource",
      },
      category: {
        driver: "com.mysql.jdbc.Driver",
        databaseDialect: "mysql",
        name: "Mysql",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
        parameters: {
          port: "3306",
          hostName: "localhost",
          database: "database",
        },
      },
    },
    "i91q-zfm0-8oq1-9920-68": {
      ds: {
        permissionLevel: 5,
        driver: "org.postgresql.Driver",
        data: {
          dir: "Gagan",
          driverName: "org.postgresql.Driver",
          type: "sql.jdbc.groovy",
          id: 304,
          userName: "zlvkhftkogyvevhyxvalzgvu@psql-mock-database-cloud",
          password: "zlvkhftkogyvevhyxvalzgvu@psql-mock-database-cloud",
          condition:
            'import net.sf.json.JSONObject;\n    import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n    public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        responseJson.put("driver", "com.mysql.jdbc.Driver");\n        responseJson.put("url", "jdbc:mysql://localhost:3306/" + userName);\n        responseJson.put("user", "root");\n        responseJson.put("pass", "root");\n        return responseJson;\n    }',
          jdbcUrl:
            "jdbc:postgresql://psql-mock-database-cloud.postgres.database.azure.com:5432/booking1662345944710kenxhxumioueuzfj",
        },
        name: "booking",
        classifier: "efwd",
        type: "sql.jdbc.groovy",
        dataSourceType: "Plain Groovy DataSource",
      },
      category: {
        driver: "org.postgresql.Driver",
        databaseDialect: "postgresql",
        name: "Postgresql",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:postgresql://{{hostName}}:{{port}}/{{database}}",
        parameters: {
          port: "5432",
          hostName: "localhost",
          database: "database",
        },
      },
    },
  },
  activeEditorTab: "info",
  dataSourcesAddedToMetadata: [
    {
      id: "1",
      type: "dynamicDataSource",
      baseType: "global.jdbc",
      catSchemaPredicted: false,
      sync: false,
      catalog: "",
      schema: "HIUSER",
      connId: "oh4uh",
      classifier: "db.workflow",
      datasourceName: "SampleTravelDataDerby",
      dsKeyPath:
        "0imw-a30r-c3bl-w93g-7x/km3q-4v77-0kqd-34lh-mt/s9ur-4tvg-ewf6-1qbf-3l",
      driverType: "Derby",
      database: "HIUSER",
    },
  ],
  changeDSList: {},
  changedTables: [],
  changedColumns: [],
  removedTables: [],
  removedColumns: [],
  removedDataSources: [],
  duplicateColumnList: [],
  duplicateTableList: [],
  unsavedViews: [],
  saveDetails: false,
  savedTableIds: [],
  savedColumnIds: [],
  joins: [
    {
      type: "inner",
      operator: "=",
      left: {
        table: "dimdate",
        column: "dim_id",
        alias: false,
      },
      right: {
        table: "dimdate",
        column: "modified_date",
        alias: false,
      },
      key: "0gdd-aszh-kgq3-g0t2-dm",
      uuid: "0gdd-aszh-kgq3-g0t2-dm",
      action: "add",
      index: 1,
      leftColumn: "dimdate.dim_id",
      rightColumn: "dimdate.modified_date",
    },
  ],
  mode: "create",
  allTablesKeys: [
    "e5hl-dvsc-boy3-6l9n-ga",
    "v27h-ab6e-eq8q-0awr-66",
    "zp27-zcus-d9r5-lbh3-yn",
    "lbvz-hq13-9k5d-paid-bk",
    "d1ko-ixts-n7x8-12v2-n7",
  ],
  selectedTableKeys: [
    "lbvz-hq13-9k5d-paid-bk",
    "zp27-zcus-d9r5-lbh3-yn",
    "e5hl-dvsc-boy3-6l9n-ga",
    "v27h-ab6e-eq8q-0awr-66",
    "d1ko-ixts-n7x8-12v2-n7",
  ],
  metadataName: "Metadata_1",
  activeDataSource: false,
  metadataToEdit: false,
  isSavingInProgress: false,
  editViewsTempData: {},
  inititalStateFromJest: false,
  timeStamp: 1665495918128,
  initialEditResponse: false,
  editorFullView: false,
  selectedTableOrColumnKey: {},
  expressionObj: [],
  securityConstants: {},
  edit: false,
  isAllowServiceCall: true,
  isValidatedTableShow: false,
  securityTableData: [],
  addOneMoreSecurity: false,
  viewSessionVariables: false,
  textEditingObj: {},
  selectedJoinNameData: {},
  filterbyData: [
    {
      value: "All",
      isChecked: true,
    },
    {
      value: "Table",
      isChecked: true,
    },
    {
      value: "Column",
      isChecked: true,
    },
    {
      value: "Global",
      isChecked: true,
    },
  ],
  isFirstRender: true,
  securityFormData: {},
  accessType: "deny",
  entityNames: "",
  executionType: "conditionIf",
  expressionName: null,
  expressionType: "",
  isApplyDisabled: true,
  isInfoShow: true,
  securityKeysChecked: [],
  hasUnsavedData: true,
  getSecurityTableData: {
    tables: [],
    columns: [],
  },
  doResetFormData: false,
  tablesMergeType: "merge",
};

export const payload5598 = {
  type: "UPDATE_JOINS_DATA",
  payload: {
    data: [
      {
        type: "inner",
        operator: "=",
        left: {
          table: "dimdate",
          column: "fiscal_year",
          alias: false,
        },
        right: {
          table: "dimdate",
          column: "date_key",
          alias: false,
        },
        key: "81if-rup1-cgzx-m0wt-tk",
        uuid: "81if-rup1-cgzx-m0wt-tk",
        action: "noChange",
        index: 1,
        leftColumn: "dimdate.fiscal_year",
        rightColumn: "dimdate.date_key",
      },
      {
        id: "ca21d00c8c87263dedd812f8f74c05b5",
        type: "inner",
        operator: "=",
        left: {
          table: "geo_cordinates",
          column: "location_id",
        },
        right: {
          table: "dimdate",
          column: "dim_id",
        },
        uuid: "xsgs-fgv6-q8gp-2ik6-on",
        index: 2,
        action: "noChange",
      },
      {
        id: "af8f3186af3703a70a3d6e219faafb4e",
        type: "inner",
        operator: "=",
        left: {
          table: "employee_details",
          column: "employee_id",
        },
        right: {
          table: "meeting_details",
          column: "meeting_by",
        },
        uuid: "m960-5fy3-2gbi-nd1h-g9",
        index: 3,
        action: "noChange",
      },
      {
        id: "aab02b68e2c7febf125c50c8c5175037",
        type: "inner",
        operator: "=",
        left: {
          table: "employee_details",
          column: "employee_id",
        },
        right: {
          table: "travel_details",
          column: "travelled_by",
        },
        uuid: "52dh-nyue-qpwd-1v7y-ql",
        index: 4,
        action: "noChange",
      },
      {
        id: "daa3221b04c18670d4af25ac99f3ae76",
        type: "inner",
        operator: "=",
        left: {
          table: "geo_cordinates",
          column: "location_id",
        },
        right: {
          table: "travel_details",
          column: "destination_id",
        },
        uuid: "cii8-cntp-kaee-y3sr-bd",
        index: 5,
        action: "noChange",
      },
      {
        id: "cdeb5b19799c89335f23ed9b50cc5a22",
        type: "inner",
        operator: "=",
        left: {
          table: "geo_cordinates",
          column: "location_id",
        },
        right: {
          table: "travel_details",
          column: "source_id",
        },
        uuid: "fuhl-j1u5-g2c3-pup7-ef",
        index: 6,
        action: "noChange",
      },
    ],
    override: true,
  },
};

export const payload5598_2 = {
  type: "UPDATE_JOINS_DATA",
  payload: {
    data: [
      {
        type: "inner",
        operator: "=",
        left: {
          table: "dimdate",
          column: "fiscal_year",
          alias: false,
        },
        right: {
          table: "dimdate",
          column: "date_key",
          alias: false,
        },
        key: "81if-rup1-cgzx-m0wt-tk",
        uuid: "81if-rup1-cgzx-m0wt-tk",
        action: "add",
        index: 1,
        leftColumn: "dimdate.fiscal_year",
        rightColumn: "dimdate.date_key",
      },
      {
        id: "ca21d00c8c87263dedd812f8f74c05b5",
        type: "inner",
        operator: "=",
        left: {
          table: "geo_cordinates",
          column: "location_id",
        },
        right: {
          table: "dimdate",
          column: "dim_id",
        },
        uuid: "xsgs-fgv6-q8gp-2ik6-on",
        index: 2,
        action: "noChange",
      },
      {
        id: "af8f3186af3703a70a3d6e219faafb4e",
        type: "inner",
        operator: "=",
        left: {
          table: "employee_details",
          column: "employee_id",
        },
        right: {
          table: "meeting_details",
          column: "meeting_by",
        },
        uuid: "m960-5fy3-2gbi-nd1h-g9",
        index: 3,
        action: "noChange",
      },
      {
        id: "aab02b68e2c7febf125c50c8c5175037",
        type: "inner",
        operator: "=",
        left: {
          table: "employee_details",
          column: "employee_id",
        },
        right: {
          table: "travel_details",
          column: "travelled_by",
        },
        uuid: "52dh-nyue-qpwd-1v7y-ql",
        index: 4,
        action: "noChange",
      },
      {
        id: "daa3221b04c18670d4af25ac99f3ae76",
        type: "inner",
        operator: "=",
        left: {
          table: "geo_cordinates",
          column: "location_id",
        },
        right: {
          table: "travel_details",
          column: "destination_id",
        },
        uuid: "cii8-cntp-kaee-y3sr-bd",
        index: 5,
        action: "noChange",
      },
      {
        id: "cdeb5b19799c89335f23ed9b50cc5a22",
        type: "inner",
        operator: "=",
        left: {
          table: "geo_cordinates",
          column: "location_id",
        },
        right: {
          table: "travel_details",
          column: "source_id",
        },
        uuid: "fuhl-j1u5-g2c3-pup7-ef",
        index: 6,
        action: "noChange",
      },
    ],
    override: true,
  },
};

export const mergeJoinsData = {
  existingJoins: [
    {
      id: "2deb64c133e7802835cba022533d7e55_1681966891087",
      type: "inner",
      operator: "=",
      left: {
        table: "geo_cordinates",
        column: "location_id",
        tableId: "f2ff93c37589ef57f40dcb15fda6d7ea",
        dbId: "l0w0r",
      },
      right: {
        table: "dimdate",
        column: "dim_id",
        tableId: "d324e793296ff76020c708f1c8fbb704",
        dbId: "l0w0r",
      },
      uuid: "hb2q-an2h-hjzg-7k26-5d",
      index: 1,
      action: "noChange",
    },
  ],
  fetchedJoins: [
    {
      id: "2deb64c133e7802835cba022533d7e55_1681966891087",
      type: "inner",
      operator: "=",
      left: {
        table: "geo_cordinates",
        column: "location_id",
        tableId: "f2ff93c37589ef57f40dcb15fda6d7ea",
        dbId: "l0w0r",
      },
      right: {
        table: "dimdate",
        column: "dim_id",
        tableId: "d324e793296ff76020c708f1c8fbb704",
        dbId: "l0w0r",
      },
      uuid: "a24g-ad8z-k6xa-6fjt-m9",
    },
    {
      id: "e82a776d8dbb97cc4da8eba20faa158f_1681974579990",
      type: "inner",
      operator: "=",
      left: {
        table: "employee_details",
        column: "employee_id",
        tableId: "b161910cbebfd353351a6c0b46e6a02e",
        dbId: "l0w0r",
      },
      right: {
        table: "meeting_details",
        column: "meeting_by",
        tableId: "025fbfb381cb17d4519363c3585626fb",
        dbId: "l0w0r",
      },
      uuid: "uite-bsyu-985h-5rw3-aj",
    },
    {
      id: "28a7232594b3b5ce47f2f42ceee8cf9a_1681974579990",
      type: "inner",
      operator: "=",
      left: {
        table: "geo_cordinates",
        column: "location_id",
        tableId: "f2ff93c37589ef57f40dcb15fda6d7ea",
        dbId: "l0w0r",
      },
      right: {
        table: "travel_details",
        column: "destination_id",
        tableId: "21e1b86ae9680d0fc197ed543c3e37eb",
        dbId: "l0w0r",
      },
      uuid: "za4r-kq0u-vk3l-zn4t-xt",
    },
    {
      id: "0749a258652416b7d37d6174eac86ebf_1681974579990",
      type: "inner",
      operator: "=",
      left: {
        table: "geo_cordinates",
        column: "location_id",
        tableId: "f2ff93c37589ef57f40dcb15fda6d7ea",
        dbId: "l0w0r",
      },
      right: {
        table: "travel_details",
        column: "source_id",
        tableId: "21e1b86ae9680d0fc197ed543c3e37eb",
        dbId: "l0w0r",
      },
      uuid: "f5om-yxor-2y24-q3mc-qm",
    },
    {
      id: "de4e30a53d95393a955a15094bf82856_1681974579990",
      type: "inner",
      operator: "=",
      left: {
        table: "employee_details",
        column: "employee_id",
        tableId: "b161910cbebfd353351a6c0b46e6a02e",
        dbId: "l0w0r",
      },
      right: {
        table: "travel_details",
        column: "travelled_by",
        tableId: "21e1b86ae9680d0fc197ed543c3e37eb",
        dbId: "l0w0r",
      },
      uuid: "60n9-qv2c-f1yn-xebi-ha",
    },
  ],
  tables: {
    dimdate: {
      id: "d324e793296ff76020c708f1c8fbb704",
      name: "dimdate",
      alias: "dimdate",
      dataSource: {
        id: "1201",
        type: "dynamicDataSource",
        baseType: "global.jdbc",
        catSchemaPredicted: false,
        sync: false,
        catalog: "",
        schema: "",
        connId: "l0w0r",
        dbId: "l0w0r",
        classifier: "db.workflow",
        datasourceName: "SampleTravelData",
        dsKeyPath: "cy2s-n1s3-iq8b-nv3m-96/xodi-tab3-vuk8-n9z6-0t",
        driverType: "Sqlite",
        database: "SampleTravelData",
      },
      category: "table",
      connId: "l0w0r",
      oldDbId: "l0w0r",
      keyPath:
        "cy2s-n1s3-iq8b-nv3m-96/xodi-tab3-vuk8-n9z6-0t/wfwe-8w14-wxk4-wk1u-ca",
      uniqueKey: "d324e793296ff76020c708f1c8fbb704_l0w0r",
      selected: true,
      keyName: "dimdate",
    },
    employee_details: {
      id: "b161910cbebfd353351a6c0b46e6a02e",
      name: "employee_details",
      alias: "employee_details",
      dataSource: {
        id: "1201",
        type: "dynamicDataSource",
        baseType: "global.jdbc",
        catSchemaPredicted: false,
        sync: false,
        catalog: "",
        schema: "",
        connId: "l0w0r",
        dbId: "l0w0r",
        classifier: "db.workflow",
        datasourceName: "SampleTravelData",
        dsKeyPath: "cy2s-n1s3-iq8b-nv3m-96/xodi-tab3-vuk8-n9z6-0t",
        driverType: "Sqlite",
        database: "SampleTravelData",
      },
      category: "table",
      connId: "l0w0r",
      oldDbId: "l0w0r",
      keyPath:
        "cy2s-n1s3-iq8b-nv3m-96/xodi-tab3-vuk8-n9z6-0t/83g6-rbcv-91ji-3sqn-3h",
      uniqueKey: "b161910cbebfd353351a6c0b46e6a02e_l0w0r",
      selected: true,
      keyName: "employee_details",
    },
    geo_cordinates: {
      id: "f2ff93c37589ef57f40dcb15fda6d7ea",
      name: "geo_cordinates",
      alias: "geo_cordinates",
      dataSource: {
        id: "1201",
        type: "dynamicDataSource",
        baseType: "global.jdbc",
        catSchemaPredicted: false,
        sync: false,
        catalog: "",
        schema: "",
        connId: "l0w0r",
        dbId: "l0w0r",
        classifier: "db.workflow",
        datasourceName: "SampleTravelData",
        dsKeyPath: "cy2s-n1s3-iq8b-nv3m-96/xodi-tab3-vuk8-n9z6-0t",
        driverType: "Sqlite",
        database: "SampleTravelData",
      },
      category: "table",
      connId: "l0w0r",
      oldDbId: "l0w0r",
      keyPath:
        "cy2s-n1s3-iq8b-nv3m-96/xodi-tab3-vuk8-n9z6-0t/v6q1-ihs9-ob75-tjjm-20",
      uniqueKey: "f2ff93c37589ef57f40dcb15fda6d7ea_l0w0r",
      selected: true,
      keyName: "geo_cordinates",
    },
    meeting_details: {
      id: "025fbfb381cb17d4519363c3585626fb",
      name: "meeting_details",
      alias: "meeting_details",
      dataSource: {
        id: "1201",
        type: "dynamicDataSource",
        baseType: "global.jdbc",
        catSchemaPredicted: false,
        sync: false,
        catalog: "",
        schema: "",
        connId: "l0w0r",
        dbId: "l0w0r",
        classifier: "db.workflow",
        datasourceName: "SampleTravelData",
        dsKeyPath: "cy2s-n1s3-iq8b-nv3m-96/xodi-tab3-vuk8-n9z6-0t",
        driverType: "Sqlite",
        database: "SampleTravelData",
      },
      category: "table",
      connId: "l0w0r",
      oldDbId: "l0w0r",
      keyPath:
        "cy2s-n1s3-iq8b-nv3m-96/xodi-tab3-vuk8-n9z6-0t/jv26-mc5y-2was-64vi-0p",
      uniqueKey: "025fbfb381cb17d4519363c3585626fb_l0w0r",
      selected: true,
      keyName: "meeting_details",
    },
    travel_details: {
      id: "21e1b86ae9680d0fc197ed543c3e37eb",
      name: "travel_details",
      alias: "travel_details",
      dataSource: {
        id: "1201",
        type: "dynamicDataSource",
        baseType: "global.jdbc",
        catSchemaPredicted: false,
        sync: false,
        catalog: "",
        schema: "",
        connId: "l0w0r",
        dbId: "l0w0r",
        classifier: "db.workflow",
        datasourceName: "SampleTravelData",
        dsKeyPath: "cy2s-n1s3-iq8b-nv3m-96/xodi-tab3-vuk8-n9z6-0t",
        driverType: "Sqlite",
        database: "SampleTravelData",
      },
      category: "table",
      connId: "l0w0r",
      oldDbId: "l0w0r",
      keyPath:
        "cy2s-n1s3-iq8b-nv3m-96/xodi-tab3-vuk8-n9z6-0t/ryk4-f2sl-krhw-sl29-ry",
      uniqueKey: "21e1b86ae9680d0fc197ed543c3e37eb_l0w0r",
      selected: true,
      keyName: "travel_details",
    },
  },
  storeJoins: [
    {
      id: "2deb64c133e7802835cba022533d7e55_1681966891087",
      type: "inner",
      operator: "=",
      left: {
        table: "geo_cordinates",
        column: "location_id",
        tableId: "f2ff93c37589ef57f40dcb15fda6d7ea",
        dbId: "l0w0r",
        cacheTableid: "f2ff93c37589ef57f40dcb15fda6d7ea",
      },
      right: {
        table: "dimdate",
        column: "dim_id",
        tableId: "d324e793296ff76020c708f1c8fbb704",
        dbId: "l0w0r",
        cacheTableid: "d324e793296ff76020c708f1c8fbb704",
      },
      uuid: "hb2q-an2h-hjzg-7k26-5d",
      index: 1,
      action: "noChange",
    },
    {
      id: "e82a776d8dbb97cc4da8eba20faa158f_1681974579990",
      type: "inner",
      operator: "=",
      left: {
        table: "employee_details",
        column: "employee_id",
        tableId: "b161910cbebfd353351a6c0b46e6a02e",
        dbId: "l0w0r",
        cacheTableid: "b161910cbebfd353351a6c0b46e6a02e",
      },
      right: {
        table: "meeting_details",
        column: "meeting_by",
        tableId: "025fbfb381cb17d4519363c3585626fb",
        dbId: "l0w0r",
        cacheTableid: "025fbfb381cb17d4519363c3585626fb",
      },
      uuid: "uite-bsyu-985h-5rw3-aj",
    },
    {
      id: "28a7232594b3b5ce47f2f42ceee8cf9a_1681974579990",
      type: "inner",
      operator: "=",
      left: {
        table: "geo_cordinates",
        column: "location_id",
        tableId: "f2ff93c37589ef57f40dcb15fda6d7ea",
        dbId: "l0w0r",
        cacheTableid: "f2ff93c37589ef57f40dcb15fda6d7ea",
      },
      right: {
        table: "travel_details",
        column: "destination_id",
        tableId: "21e1b86ae9680d0fc197ed543c3e37eb",
        dbId: "l0w0r",
        cacheTableid: "21e1b86ae9680d0fc197ed543c3e37eb",
      },
      uuid: "za4r-kq0u-vk3l-zn4t-xt",
    },
    {
      id: "0749a258652416b7d37d6174eac86ebf_1681974579990",
      type: "inner",
      operator: "=",
      left: {
        table: "geo_cordinates",
        column: "location_id",
        tableId: "f2ff93c37589ef57f40dcb15fda6d7ea",
        dbId: "l0w0r",
        cacheTableid: "f2ff93c37589ef57f40dcb15fda6d7ea",
      },
      right: {
        table: "travel_details",
        column: "source_id",
        tableId: "21e1b86ae9680d0fc197ed543c3e37eb",
        dbId: "l0w0r",
        cacheTableid: "21e1b86ae9680d0fc197ed543c3e37eb",
      },
      uuid: "f5om-yxor-2y24-q3mc-qm",
    },
    {
      id: "de4e30a53d95393a955a15094bf82856_1681974579990",
      type: "inner",
      operator: "=",
      left: {
        table: "employee_details",
        column: "employee_id",
        tableId: "b161910cbebfd353351a6c0b46e6a02e",
        dbId: "l0w0r",
        cacheTableid: "b161910cbebfd353351a6c0b46e6a02e",
      },
      right: {
        table: "travel_details",
        column: "travelled_by",
        tableId: "21e1b86ae9680d0fc197ed543c3e37eb",
        dbId: "l0w0r",
        cacheTableid: "21e1b86ae9680d0fc197ed543c3e37eb",
      },
      uuid: "60n9-qv2c-f1yn-xebi-ha",
    },
  ],
};
