export const datasourceListToRender = [
  {
    name: "Derby",
    children: [
      {
        permissionLevel: 5,
        driver: "org.apache.derby.jdbc.AutoloadedDriver",
        name: "Plain Jdbc",
        classifier: "efwd",
        type: "sql.jdbc",
        data: {
          dir: "datasources",
          driverName: "org.apache.derby.jdbc.AutoloadedDriver",
          type: "sql.jdbc",
          id: 501,
          userName: "hiuser",
          password: "hiuser",
          jdbcUrl:
            "jdbc:derby:/home/helical/Performance/hi/db/SampleTravelData",
        },
        dataSourceType: "Plain Jdbc DataSource",
        category: "dataSource",
        children: [],
        driverType: "Derby",
        keyPath: "9ynj-7r7m-w0gs-21w5-mm/eead-rvkn-dl1e-qb1b-x8",
        key: "eead-rvkn-dl1e-qb1b-x8",
        uuid: "eead-rvkn-dl1e-qb1b-x8",
      },
      {
        permissionLevel: 5,
        driver: "org.apache.derby.jdbc.AutoloadedDriver",
        name: "5722",
        classifier: "efwd",
        type: "sql.jdbc",
        data: {
          dir: "sai_ganesh",
          driverName: "org.apache.derby.jdbc.AutoloadedDriver",
          type: "sql.jdbc",
          id: 701,
          userName: "hiuser",
          password: "hiuser",
          jdbcUrl:
            "jdbc:derby:/home/helical/Performance/hi/db/SampleTravelData",
        },
        dataSourceType: "Plain Jdbc DataSource",
        category: "dataSource",
        children: [],
        driverType: "Derby",
        keyPath: "9ynj-7r7m-w0gs-21w5-mm/qqt1-qznw-fkz9-n61l-hu",
        key: "qqt1-qznw-fkz9-n61l-hu",
        uuid: "qqt1-qznw-fkz9-n61l-hu",
      },
      {
        data: {
          id: "1",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.apache.derby.jdbc.AutoloadedDriver",
        name: "SampleTravelDataDerby",
        classifier: "global",
        dataSourceType: "Managed DataSource",
        category: "dataSource",
        children: [],
        driverType: "Derby",
        keyPath: "9ynj-7r7m-w0gs-21w5-mm/d6ql-02hy-7i8h-098r-w7",
        key: "d6ql-02hy-7i8h-098r-w7",
        uuid: "d6ql-02hy-7i8h-098r-w7",
      },
      {
        data: {
          id: "1000",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.apache.derby.jdbc.AutoloadedDriver",
        name: "hiee",
        classifier: "global",
        dataSourceType: "Managed DataSource",
        category: "dataSource",
        children: [],
        driverType: "Derby",
        keyPath: "9ynj-7r7m-w0gs-21w5-mm/p014-1z7m-2zi3-0jeh-9w",
        key: "p014-1z7m-2zi3-0jeh-9w",
        uuid: "p014-1z7m-2zi3-0jeh-9w",
      },
      {
        data: {
          id: "1101",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.apache.derby.jdbc.AutoloadedDriver",
        name: "derby2",
        classifier: "global",
        dataSourceType: "Managed DataSource",
        category: "dataSource",
        children: [],
        driverType: "Derby",
        keyPath: "9ynj-7r7m-w0gs-21w5-mm/hbkh-mecx-mdqb-gglh-34",
        key: "hbkh-mecx-mdqb-gglh-34",
        uuid: "hbkh-mecx-mdqb-gglh-34",
      },
      {
        data: {
          id: "1801",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.apache.derby.jdbc.AutoloadedDriver",
        name: "Dump",
        classifier: "global",
        dataSourceType: "Managed DataSource",
        category: "dataSource",
        children: [],
        driverType: "Derby",
        keyPath: "9ynj-7r7m-w0gs-21w5-mm/98nx-htgq-iy9i-6lyo-7l",
        key: "98nx-htgq-iy9i-6lyo-7l",
        uuid: "98nx-htgq-iy9i-6lyo-7l",
      },
      {
        data: {
          id: "2301",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.apache.derby.jdbc.AutoloadedDriver",
        name: "SampleTravelData",
        classifier: "global",
        dataSourceType: "Managed DataSource",
        category: "dataSource",
        children: [],
        driverType: "Derby",
        keyPath: "9ynj-7r7m-w0gs-21w5-mm/qzjh-lm9q-w5i5-s05d-2r",
        key: "qzjh-lm9q-w5i5-s05d-2r",
        uuid: "qzjh-lm9q-w5i5-s05d-2r",
      },
      {
        data: {
          id: "2601",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.apache.derby.jdbc.AutoloadedDriver",
        name: "AnotherDerby",
        classifier: "global",
        dataSourceType: "Managed DataSource",
        category: "dataSource",
        children: [],
        driverType: "Derby",
        keyPath: "9ynj-7r7m-w0gs-21w5-mm/g5wp-085u-bhk8-nw5z-9c",
        key: "g5wp-085u-bhk8-nw5z-9c",
        uuid: "g5wp-085u-bhk8-nw5z-9c",
      },
    ],
    key: "9ynj-7r7m-w0gs-21w5-mm",
    uuid: "9ynj-7r7m-w0gs-21w5-mm",
    keyPath: "9ynj-7r7m-w0gs-21w5-mm",
    category: "dsGroup",
    imgUrl: "images/data_sources/defaut_datasource.png",
  },
  {
    name: "DynamicSwitch",
    children: [
      {
        permissionLevel: 5,
        driver: "dynamicSwitch",
        name: "Groovy 1",
        classifier: "efwd",
        type: "sql.jdbc.groovy.managed",
        data: {
          dir: "Gagan",
          driverName: null,
          type: "sql.jdbc.groovy.managed",
          id: 1,
          userName: null,
          password: null,
          condition:
            'import groovy.sql.Sql;\n      import net.sf.json.JSONObject;\n      import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n      public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        if (userName.equals("hiadmin")) {\n          responseJson.put("globalId", 1001);\n        }\n      \n        if (userName.equals("hiuser")) {\n          responseJson.put("globalId", 3);\n        }\n      \n        if (userName.equals("test")) {\n          responseJson.put("globalId", 4);\n        }\n      \n        responseJson.put("type", "global.jdbc");\n      \n        //throw new RuntimeException("This is a test exception" +responseJson);\n        return responseJson;\n      }',
          jdbcUrl: null,
          driver: "dynamicSwitch",
        },
        dataSourceType: "",
        category: "dataSource",
        children: [],
        driverType: "DynamicSwitch",
        keyPath: "kamv-r7zj-npkb-glyd-t9/lxs7-rr52-s6n3-ewmt-hq",
        key: "lxs7-rr52-s6n3-ewmt-hq",
        uuid: "lxs7-rr52-s6n3-ewmt-hq",
      },
      {
        permissionLevel: 5,
        driver: "dynamicSwitch",
        name: "6148b",
        classifier: "efwd",
        type: "sql.jdbc.groovy.managed",
        data: {
          dir: "03_03",
          driverName: null,
          type: "sql.jdbc.groovy.managed",
          id: 801,
          userName: null,
          password: null,
          condition:
            'import groovy.sql.Sql;\n      import net.sf.json.JSONObject;\n      import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n      public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        if (userName.equals("hiadmin")) {\n          responseJson.put("globalId", 1);\n        }\n      \n        if (userName.equals("hiuser")) {\n          responseJson.put("globalId", 1001);\n        }\n      \n        if (userName.equals("test")) {\n          responseJson.put("globalId", 4);\n        }\n      \n        responseJson.put("type", "global.jdbc");\n      \n        //throw new RuntimeException("This is a test exception" +responseJson);\n        return responseJson;\n      }',
          jdbcUrl: null,
          driver: "dynamicSwitch",
        },
        dataSourceType: "",
        category: "dataSource",
        children: [],
        driverType: "DynamicSwitch",
        keyPath: "kamv-r7zj-npkb-glyd-t9/ziy6-xqo7-dmfn-juaz-1k",
        key: "ziy6-xqo7-dmfn-juaz-1k",
        uuid: "ziy6-xqo7-dmfn-juaz-1k",
      },
      {
        permissionLevel: 5,
        driver: "dynamicSwitch",
        name: "GroovyManaged",
        classifier: "efwd",
        type: "sql.jdbc.groovy.managed",
        data: {
          dir: "sai_ganesh",
          driverName: null,
          type: "sql.jdbc.groovy.managed",
          id: 601,
          userName: null,
          password: null,
          condition:
            'import groovy.sql.Sql;\n      import net.sf.json.JSONObject;\n      import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n      public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        if (userName.equals("hiadmin")) {\n          responseJson.put("globalId", 1);\n        }\n      \n        if (userName.equals("hiuser")) {\n          responseJson.put("globalId", 300);\n        }\n      \n        if (userName.equals("test")) {\n          responseJson.put("globalId", 4);\n        }\n      \n        responseJson.put("type", "global.jdbc");\n      \n        //throw new RuntimeException("This is a test exception" +responseJson);\n        return responseJson;\n      }',
          jdbcUrl: null,
          driver: "dynamicSwitch",
        },
        dataSourceType: "",
        category: "dataSource",
        children: [],
        driverType: "DynamicSwitch",
        keyPath: "kamv-r7zj-npkb-glyd-t9/snrz-n0ja-x9sg-g4yz-sy",
        key: "snrz-n0ja-x9sg-g4yz-sy",
        uuid: "snrz-n0ja-x9sg-g4yz-sy",
      },
    ],
    key: "kamv-r7zj-npkb-glyd-t9",
    uuid: "kamv-r7zj-npkb-glyd-t9",
    keyPath: "kamv-r7zj-npkb-glyd-t9",
    category: "dsGroup",
    imgUrl: "images/data_sources/defaut_datasource.png",
  },
  {
    name: "Elasticsearch",
    children: [
      {
        data: {
          id: "2701",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.elasticsearch.xpack.sql.jdbc.EsDriver",
        name: "test",
        classifier: "global",
        dataSourceType: "Managed DataSource",
        category: "dataSource",
        children: [],
        driverType: "Elasticsearch",
        keyPath: "c8iu-0yig-voxq-8ls5-7u/obkk-bcze-1m7t-sjbt-mt",
        key: "obkk-bcze-1m7t-sjbt-mt",
        uuid: "obkk-bcze-1m7t-sjbt-mt",
      },
    ],
    key: "c8iu-0yig-voxq-8ls5-7u",
    uuid: "c8iu-0yig-voxq-8ls5-7u",
    keyPath: "c8iu-0yig-voxq-8ls5-7u",
    category: "dsGroup",
    imgUrl: "images/data_sources/defaut_datasource.png",
  },
  {
    name: "Mysql",
    children: [
      {
        data: {
          id: "2402",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "com.mysql.jdbc.Driver",
        name: "mysql",
        classifier: "global",
        dataSourceType: "Managed DataSource",
        category: "dataSource",
        children: [],
        driverType: "Mysql",
        keyPath: "ycgx-xvh8-klri-vjse-sd/bt05-vk9k-d6g3-96mo-1i",
        key: "bt05-vk9k-d6g3-96mo-1i",
        uuid: "bt05-vk9k-d6g3-96mo-1i",
      },
    ],
    key: "ycgx-xvh8-klri-vjse-sd",
    uuid: "ycgx-xvh8-klri-vjse-sd",
    keyPath: "ycgx-xvh8-klri-vjse-sd",
    category: "dsGroup",
    imgUrl: "images/data_sources/defaut_datasource.png",
  },
  {
    name: "Oracle",
    children: [
      {
        data: {
          id: "2001",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "oracle.jdbc.OracleDriver",
        name: "Oracle_12",
        classifier: "global",
        dataSourceType: "Managed DataSource",
        category: "dataSource",
        children: [],
        driverType: "Oracle",
        keyPath: "ldeu-hpel-ywte-hzsi-1s/9q1n-ca6t-hkgx-csns-sa",
        key: "9q1n-ca6t-hkgx-csns-sa",
        uuid: "9q1n-ca6t-hkgx-csns-sa",
      },
    ],
    key: "ldeu-hpel-ywte-hzsi-1s",
    uuid: "ldeu-hpel-ywte-hzsi-1s",
    keyPath: "ldeu-hpel-ywte-hzsi-1s",
    category: "dsGroup",
    imgUrl: "images/data_sources/defaut_datasource.png",
  },
  {
    name: "Postgresql",
    children: [
      {
        data: {
          id: "1001",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.postgresql.Driver",
        name: "booking",
        classifier: "global",
        dataSourceType: "Managed DataSource",
        category: "dataSource",
        children: [],
        driverType: "Postgresql",
        keyPath: "x7ml-u173-9bno-cgp8-mb/vfvx-uoly-o7gm-j8ao-os",
        key: "vfvx-uoly-o7gm-j8ao-os",
        uuid: "vfvx-uoly-o7gm-j8ao-os",
      },
      {
        data: {
          id: "1401",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.postgresql.Driver",
        name: "booking",
        classifier: "global",
        dataSourceType: "Managed DataSource",
        category: "dataSource",
        children: [],
        driverType: "Postgresql",
        keyPath: "x7ml-u173-9bno-cgp8-mb/su9i-392c-ob10-owse-b1",
        key: "su9i-392c-ob10-owse-b1",
        uuid: "su9i-392c-ob10-owse-b1",
      },
      {
        data: {
          id: "2202",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.postgresql.Driver",
        name: "SampleTravelData",
        classifier: "global",
        dataSourceType: "Managed DataSource",
        category: "dataSource",
        children: [],
        driverType: "Postgresql",
        keyPath: "x7ml-u173-9bno-cgp8-mb/t0su-l7dx-4aoa-r8t9-s9",
        key: "t0su-l7dx-4aoa-r8t9-s9",
        uuid: "t0su-l7dx-4aoa-r8t9-s9",
      },
    ],
    key: "x7ml-u173-9bno-cgp8-mb",
    uuid: "x7ml-u173-9bno-cgp8-mb",
    keyPath: "x7ml-u173-9bno-cgp8-mb",
    category: "dsGroup",
    imgUrl: "images/data_sources/defaut_datasource.png",
  },
  {
    name: "Snowflake Client",
    children: [
      {
        data: {
          id: "1901",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "net.snowflake.client.jdbc.SnowflakeDriver",
        name: "SnowflakeDS",
        classifier: "global",
        dataSourceType: "Managed DataSource",
        category: "dataSource",
        children: [],
        driverType: "Snowflake Client",
        keyPath: "p562-cbay-rp7z-p8k2-zs/4n4a-cj9d-a4du-ug5e-k0",
        key: "4n4a-cj9d-a4du-ug5e-k0",
        uuid: "4n4a-cj9d-a4du-ug5e-k0",
      },
      {
        data: {
          id: "1902",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "net.snowflake.client.jdbc.SnowflakeDriver",
        name: "SnowFlakeDSWorking",
        classifier: "global",
        dataSourceType: "Managed DataSource",
        category: "dataSource",
        children: [],
        driverType: "Snowflake Client",
        keyPath: "p562-cbay-rp7z-p8k2-zs/mdip-3a61-8fx1-56fv-cj",
        key: "mdip-3a61-8fx1-56fv-cj",
        uuid: "mdip-3a61-8fx1-56fv-cj",
      },
      {
        data: {
          id: "2403",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "net.snowflake.client.jdbc.SnowflakeDriver",
        name: "testdata",
        classifier: "global",
        dataSourceType: "Managed DataSource",
        category: "dataSource",
        children: [],
        driverType: "Snowflake Client",
        keyPath: "p562-cbay-rp7z-p8k2-zs/c3p7-b0ku-0d3u-hg3t-yu",
        key: "c3p7-b0ku-0d3u-hg3t-yu",
        uuid: "c3p7-b0ku-0d3u-hg3t-yu",
      },
      {
        data: {
          id: "2501",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "net.snowflake.client.jdbc.SnowflakeDriver",
        name: "60045",
        classifier: "global",
        dataSourceType: "Managed DataSource",
        category: "dataSource",
        children: [],
        driverType: "Snowflake Client",
        keyPath: "p562-cbay-rp7z-p8k2-zs/06ys-rfby-4m00-s9d3-k5",
        key: "06ys-rfby-4m00-s9d3-k5",
        uuid: "06ys-rfby-4m00-s9d3-k5",
      },
    ],
    key: "p562-cbay-rp7z-p8k2-zs",
    uuid: "p562-cbay-rp7z-p8k2-zs",
    keyPath: "p562-cbay-rp7z-p8k2-zs",
    category: "dsGroup",
    imgUrl: "images/data_sources/defaut_datasource.png",
  },
  {
    name: "Sqlite",
    children: [
      {
        data: {
          id: "1201",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.sqlite.JDBC",
        name: "SampleTravelData",
        classifier: "global",
        dataSourceType: "Managed DataSource",
        category: "dataSource",
        children: [
          {
            id: "d324e793296ff76020c708f1c8fbb704",
            name: "dimdate",
            alias: "dimdate",
            dataSource: {
              id: "1201",
              type: "dynamicDataSource",
              baseType: "global.jdbc",
              catSchemaPredicted: false,
              sync: false,
              catalog: "",
              schema: "",
              connId: "vu3lh",
              dbId: "vu3lh",
              classifier: "db.workflow",
              datasourceName: "SampleTravelData",
              dsKeyPath: "4q8g-pso4-xcnp-au87-at/8hil-l7b4-empw-xbou-u0",
              driverType: "Sqlite",
              database: "SampleTravelData",
            },
            category: "table",
            connId: "vu3lh",
            keyPath:
              "4q8g-pso4-xcnp-au87-at/8hil-l7b4-empw-xbou-u0/webb-9n57-l75u-mwod-6o",
            uniqueKey: "d324e793296ff76020c708f1c8fbb704_vu3lh",
            selected: false,
          },
          {
            id: "b161910cbebfd353351a6c0b46e6a02e",
            name: "employee_details",
            alias: "employee_details",
            dataSource: {
              id: "1201",
              type: "dynamicDataSource",
              baseType: "global.jdbc",
              catSchemaPredicted: false,
              sync: false,
              catalog: "",
              schema: "",
              connId: "vu3lh",
              dbId: "vu3lh",
              classifier: "db.workflow",
              datasourceName: "SampleTravelData",
              dsKeyPath: "4q8g-pso4-xcnp-au87-at/8hil-l7b4-empw-xbou-u0",
              driverType: "Sqlite",
              database: "SampleTravelData",
            },
            category: "table",
            connId: "vu3lh",
            keyPath:
              "4q8g-pso4-xcnp-au87-at/8hil-l7b4-empw-xbou-u0/e4qh-k8ud-neh0-89ak-hu",
            uniqueKey: "b161910cbebfd353351a6c0b46e6a02e_vu3lh",
            selected: false,
          },
          {
            id: "f2ff93c37589ef57f40dcb15fda6d7ea",
            name: "geo_cordinates",
            alias: "geo_cordinates",
            dataSource: {
              id: "1201",
              type: "dynamicDataSource",
              baseType: "global.jdbc",
              catSchemaPredicted: false,
              sync: false,
              catalog: "",
              schema: "",
              connId: "vu3lh",
              dbId: "vu3lh",
              classifier: "db.workflow",
              datasourceName: "SampleTravelData",
              dsKeyPath: "4q8g-pso4-xcnp-au87-at/8hil-l7b4-empw-xbou-u0",
              driverType: "Sqlite",
              database: "SampleTravelData",
            },
            category: "table",
            connId: "vu3lh",
            keyPath:
              "4q8g-pso4-xcnp-au87-at/8hil-l7b4-empw-xbou-u0/3hpn-rdet-ds84-2ot9-so",
            uniqueKey: "f2ff93c37589ef57f40dcb15fda6d7ea_vu3lh",
            selected: false,
          },
          {
            id: "025fbfb381cb17d4519363c3585626fb",
            name: "meeting_details",
            alias: "meeting_details",
            dataSource: {
              id: "1201",
              type: "dynamicDataSource",
              baseType: "global.jdbc",
              catSchemaPredicted: false,
              sync: false,
              catalog: "",
              schema: "",
              connId: "vu3lh",
              dbId: "vu3lh",
              classifier: "db.workflow",
              datasourceName: "SampleTravelData",
              dsKeyPath: "4q8g-pso4-xcnp-au87-at/8hil-l7b4-empw-xbou-u0",
              driverType: "Sqlite",
              database: "SampleTravelData",
            },
            category: "table",
            connId: "vu3lh",
            keyPath:
              "4q8g-pso4-xcnp-au87-at/8hil-l7b4-empw-xbou-u0/6n7i-ribs-uwde-6xnx-bl",
            uniqueKey: "025fbfb381cb17d4519363c3585626fb_vu3lh",
            selected: false,
          },
          {
            id: "21e1b86ae9680d0fc197ed543c3e37eb",
            name: "travel_details",
            alias: "travel_details",
            dataSource: {
              id: "1201",
              type: "dynamicDataSource",
              baseType: "global.jdbc",
              catSchemaPredicted: false,
              sync: false,
              catalog: "",
              schema: "",
              connId: "vu3lh",
              dbId: "vu3lh",
              classifier: "db.workflow",
              datasourceName: "SampleTravelData",
              dsKeyPath: "4q8g-pso4-xcnp-au87-at/8hil-l7b4-empw-xbou-u0",
              driverType: "Sqlite",
              database: "SampleTravelData",
            },
            category: "table",
            connId: "vu3lh",
            keyPath:
              "4q8g-pso4-xcnp-au87-at/8hil-l7b4-empw-xbou-u0/8crc-1yf0-vgju-6byn-ou",
            uniqueKey: "21e1b86ae9680d0fc197ed543c3e37eb_vu3lh",
            selected: false,
          },
        ],
        driverType: "Sqlite",
        keyPath: "4q8g-pso4-xcnp-au87-at/8hil-l7b4-empw-xbou-u0",
        key: "8hil-l7b4-empw-xbou-u0",
        uuid: "8hil-l7b4-empw-xbou-u0",
        fetched: true,
      },
      {
        data: {
          id: "1302",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.sqlite.JDBC",
        name: "Sqlite",
        classifier: "global",
        dataSourceType: "Managed DataSource",
        category: "dataSource",
        children: [],
        driverType: "Sqlite",
        keyPath: "4q8g-pso4-xcnp-au87-at/v9ui-wlii-nzyb-hrq6-f3",
        key: "v9ui-wlii-nzyb-hrq6-f3",
        uuid: "v9ui-wlii-nzyb-hrq6-f3",
      },
    ],
    key: "4q8g-pso4-xcnp-au87-at",
    uuid: "4q8g-pso4-xcnp-au87-at",
    keyPath: "4q8g-pso4-xcnp-au87-at",
    category: "dsGroup",
    imgUrl: "images/data_sources/defaut_datasource.png",
  },
];

export const record = {
  id: "d324e793296ff76020c708f1c8fbb704",
  name: "dimdate",
  alias: "dimdate",
  dataSource: {
    id: "1201",
    type: "dynamicDataSource",
    baseType: "global.jdbc",
    catSchemaPredicted: false,
    sync: false,
    catalog: "",
    schema: "",
    connId: "vu3lh",
    dbId: "vu3lh",
    classifier: "db.workflow",
    datasourceName: "SampleTravelData",
    dsKeyPath: "4q8g-pso4-xcnp-au87-at/8hil-l7b4-empw-xbou-u0",
    driverType: "Sqlite",
    database: "SampleTravelData",
  },
  category: "table",
  connId: "vu3lh",
  keyPath:
    "4q8g-pso4-xcnp-au87-at/8hil-l7b4-empw-xbou-u0/webb-9n57-l75u-mwod-6o",
  uniqueKey: "d324e793296ff76020c708f1c8fbb704_vu3lh",
  selected: false,
};
