export const sampleViews = [
  {
    type: "view",
    id: "ba864e07-1f50-4fce-9d96-3fd95e7a66fb",
    alias: "Query View",
    columns: {
      meeting_id: {
        alias: "meeting_id",
        fullyQualifiedColumn: "Query View.meeting_id",
        columnId: "36d9ec98-b95a-4f17-a980-8ce8d417a3ed",
        defaultFunction: "db.generic.aggregate.sum",
        type: {
          "java.lang.Float": "numeric",
        },
      },
      meeting_date: {
        alias: "meeting_date",
        fullyQualifiedColumn: "Query View.meeting_date",
        columnId: "1c9f388f-d213-41db-9ab4-67adf0dafc96",
        defaultFunction: "db.generic.groupBy.group",
        type: {
          "java.sql.Timestamp": "dateTime",
        },
      },
      meeting_by: {
        alias: "meeting_by",
        fullyQualifiedColumn: "Query View.meeting_by",
        columnId: "1b481d2c-6207-4fb1-9199-d9a6f382b122",
        defaultFunction: "db.generic.aggregate.sum",
        type: {
          "java.lang.Float": "numeric",
        },
      },
      client_name: {
        alias: "client_name",
        fullyQualifiedColumn: "Query View.client_name",
        columnId: "0d98c949-22d6-46b6-bd43-4afd195f9647",
        defaultFunction: "db.generic.groupBy.group",
        type: {
          "java.lang.String": "text",
        },
      },
      meeting_purpose: {
        alias: "meeting_purpose",
        fullyQualifiedColumn: "Query View.meeting_purpose",
        columnId: "6c821dfb-a718-49cd-af37-d7fa72184a8f",
        defaultFunction: "db.generic.groupBy.group",
        type: {
          "java.lang.String": "text",
        },
      },
      meeting_impact: {
        alias: "meeting_impact",
        fullyQualifiedColumn: "Query View.meeting_impact",
        columnId: "0a571c67-d949-46c3-854f-8e7941ee3a6e",
        defaultFunction: "db.generic.groupBy.group",
        type: {
          "java.lang.String": "text",
        },
      },
      meet_cancellation_status: {
        alias: "meet_cancellation_status",
        fullyQualifiedColumn: "Query View.meet_cancellation_status",
        columnId: "3575e8d0-d322-491f-b81d-733928ec1689",
        defaultFunction: "db.generic.groupBy.group",
        type: {
          "java.lang.String": "text",
        },
      },
      cancellation_reason: {
        alias: "cancellation_reason",
        fullyQualifiedColumn: "Query View.cancellation_reason",
        columnId: "a14991e4-7c79-4748-ab9e-3699256f98ba",
        defaultFunction: "db.generic.groupBy.group",
        type: {
          "java.lang.String": "text",
        },
      },
    },
    name: "Query View",
  },
  {
    type: "view",
    id: "219f780b-5f47-40d2-b565-14f0d5a6a72c",
    alias: "Dynamic View",
    columns: {
      travel_id: {
        alias: "travel_id",
        fullyQualifiedColumn: "Dynamic View.travel_id",
        columnId: "4764edac-d030-4903-b402-62df8fc1b5c9",
        defaultFunction: "db.generic.aggregate.sum",
        type: {
          "java.lang.Float": "numeric",
        },
      },
      travel_date: {
        alias: "travel_date",
        fullyQualifiedColumn: "Dynamic View.travel_date",
        columnId: "84c99624-d5b3-465e-8704-c5e04835ef5a",
        defaultFunction: "db.generic.groupBy.group",
        type: {
          "java.sql.Timestamp": "dateTime",
        },
      },
      travel_type: {
        alias: "travel_type",
        fullyQualifiedColumn: "Dynamic View.travel_type",
        columnId: "0fd366d4-51b5-4d58-bd36-ff92806dd682",
        defaultFunction: "db.generic.groupBy.group",
        type: {
          "java.lang.String": "text",
        },
      },
      travel_medium: {
        alias: "travel_medium",
        fullyQualifiedColumn: "Dynamic View.travel_medium",
        columnId: "825978f3-ac0b-4e5e-89ae-5ab5abbf438e",
        defaultFunction: "db.generic.groupBy.group",
        type: {
          "java.lang.String": "text",
        },
      },
      source_id: {
        alias: "source_id",
        fullyQualifiedColumn: "Dynamic View.source_id",
        columnId: "b1eb6840-5e13-4abe-a26b-42c33021dc10",
        defaultFunction: "db.generic.aggregate.sum",
        type: {
          "java.lang.Float": "numeric",
        },
      },
      source: {
        alias: "source",
        fullyQualifiedColumn: "Dynamic View.source",
        columnId: "6ec1fb57-e371-4644-be96-3462334bcbba",
        defaultFunction: "db.generic.groupBy.group",
        type: {
          "java.lang.String": "text",
        },
      },
      destination_id: {
        alias: "destination_id",
        fullyQualifiedColumn: "Dynamic View.destination_id",
        columnId: "acd15d71-ef78-4921-ae6a-0851b658ea9f",
        defaultFunction: "db.generic.aggregate.sum",
        type: {
          "java.lang.Float": "numeric",
        },
      },
      destination: {
        alias: "destination",
        fullyQualifiedColumn: "Dynamic View.destination",
        columnId: "b179b247-0e1a-44f6-a2bc-0a47b3174d8c",
        defaultFunction: "db.generic.groupBy.group",
        type: {
          "java.lang.String": "text",
        },
      },
      travel_cost: {
        alias: "travel_cost",
        fullyQualifiedColumn: "Dynamic View.travel_cost",
        columnId: "38a554b2-4d9a-483e-a415-fad62e2b5e79",
        defaultFunction: "db.generic.aggregate.sum",
        type: {
          "java.lang.Float": "numeric",
        },
      },
      mode_of_payment: {
        alias: "mode_of_payment",
        fullyQualifiedColumn: "Dynamic View.mode_of_payment",
        columnId: "0ae4c113-5138-40fa-bca0-c4b980e1cd8d",
        defaultFunction: "db.generic.groupBy.group",
        type: {
          "java.lang.String": "text",
        },
      },
      booking_platform: {
        alias: "booking_platform",
        fullyQualifiedColumn: "Dynamic View.booking_platform",
        columnId: "e60e3808-85c8-467a-a22d-0fcedb7964e2",
        defaultFunction: "db.generic.groupBy.group",
        type: {
          "java.lang.String": "text",
        },
      },
      travelled_by: {
        alias: "travelled_by",
        fullyQualifiedColumn: "Dynamic View.travelled_by",
        columnId: "c7d003d4-c58f-4536-aa51-84c380f55862",
        defaultFunction: "db.generic.aggregate.sum",
        type: {
          "java.lang.Float": "numeric",
        },
      },
    },
    name: "Dynamic View",
  },
];

export const sampleTables = {
  dimdate: {
    id: "d324e793296ff76020c708f1c8fbb704",
    name: "dimdate",
    alias: "dimdate",
    dataSource: {
      id: "1201",
      type: "dynamicDataSource",
      baseType: "global.jdbc",
      catSchemaPredicted: false,
      sync: false,
      catalog: "",
      schema: "",
      connId: "wfr0m",
      dbId: "wfr0m",
      classifier: "db.workflow",
      datasourceName: "SampleTravelData",
      dsKeyPath: "eue5-as8v-7cv3-rj6g-46/byd9-zgdv-ken0-o26m-y9",
      driverType: "Sqlite",
      database: "SampleTravelData",
    },
    category: "table",
    connId: "wfr0m",
    keyPath:
      "eue5-as8v-7cv3-rj6g-46/byd9-zgdv-ken0-o26m-y9/zxrk-yocc-qwtj-p7ac-mu",
    uniqueKey: "d324e793296ff76020c708f1c8fbb704_wfr0m",
    selected: true,
    keyName: "dimdate",
  },
  employee_details: {
    id: "b161910cbebfd353351a6c0b46e6a02e",
    name: "employee_details",
    alias: "employee_details",
    dataSource: {
      id: "1201",
      type: "dynamicDataSource",
      baseType: "global.jdbc",
      catSchemaPredicted: false,
      sync: false,
      catalog: "",
      schema: "",
      connId: "wfr0m",
      dbId: "wfr0m",
      classifier: "db.workflow",
      datasourceName: "SampleTravelData",
      dsKeyPath: "eue5-as8v-7cv3-rj6g-46/byd9-zgdv-ken0-o26m-y9",
      driverType: "Sqlite",
      database: "SampleTravelData",
    },
    category: "table",
    connId: "wfr0m",
    keyPath:
      "eue5-as8v-7cv3-rj6g-46/byd9-zgdv-ken0-o26m-y9/rk36-09nm-3xm8-rc94-yp",
    uniqueKey: "b161910cbebfd353351a6c0b46e6a02e_wfr0m",
    selected: true,
    keyName: "employee_details",
  },
  geo_cordinates: {
    id: "f2ff93c37589ef57f40dcb15fda6d7ea",
    name: "geo_cordinates",
    alias: "geo_cordinates",
    dataSource: {
      id: "1201",
      type: "dynamicDataSource",
      baseType: "global.jdbc",
      catSchemaPredicted: false,
      sync: false,
      catalog: "",
      schema: "",
      connId: "wfr0m",
      dbId: "wfr0m",
      classifier: "db.workflow",
      datasourceName: "SampleTravelData",
      dsKeyPath: "eue5-as8v-7cv3-rj6g-46/byd9-zgdv-ken0-o26m-y9",
      driverType: "Sqlite",
      database: "SampleTravelData",
    },
    category: "table",
    connId: "wfr0m",
    keyPath:
      "eue5-as8v-7cv3-rj6g-46/byd9-zgdv-ken0-o26m-y9/2ixk-l366-hfl3-u1js-50",
    uniqueKey: "f2ff93c37589ef57f40dcb15fda6d7ea_wfr0m",
    selected: true,
    keyName: "geo_cordinates",
  },
  meeting_details: {
    id: "025fbfb381cb17d4519363c3585626fb",
    name: "meeting_details",
    alias: "meeting_details",
    dataSource: {
      id: "1201",
      type: "dynamicDataSource",
      baseType: "global.jdbc",
      catSchemaPredicted: false,
      sync: false,
      catalog: "",
      schema: "",
      connId: "wfr0m",
      dbId: "wfr0m",
      classifier: "db.workflow",
      datasourceName: "SampleTravelData",
      dsKeyPath: "eue5-as8v-7cv3-rj6g-46/byd9-zgdv-ken0-o26m-y9",
      driverType: "Sqlite",
      database: "SampleTravelData",
    },
    category: "table",
    connId: "wfr0m",
    keyPath:
      "eue5-as8v-7cv3-rj6g-46/byd9-zgdv-ken0-o26m-y9/mud7-45ws-0wk7-gozu-lt",
    uniqueKey: "025fbfb381cb17d4519363c3585626fb_wfr0m",
    selected: true,
    keyName: "meeting_details",
  },
  travel_details: {
    id: "21e1b86ae9680d0fc197ed543c3e37eb",
    name: "travel_details",
    alias: "travel_details",
    dataSource: {
      id: "1201",
      type: "dynamicDataSource",
      baseType: "global.jdbc",
      catSchemaPredicted: false,
      sync: false,
      catalog: "",
      schema: "",
      connId: "wfr0m",
      dbId: "wfr0m",
      classifier: "db.workflow",
      datasourceName: "SampleTravelData",
      dsKeyPath: "eue5-as8v-7cv3-rj6g-46/byd9-zgdv-ken0-o26m-y9",
      driverType: "Sqlite",
      database: "SampleTravelData",
    },
    category: "table",
    connId: "wfr0m",
    keyPath:
      "eue5-as8v-7cv3-rj6g-46/byd9-zgdv-ken0-o26m-y9/k1v0-vogz-a2ed-pflj-ek",
    uniqueKey: "21e1b86ae9680d0fc197ed543c3e37eb_wfr0m",
    selected: true,
    keyName: "travel_details",
  },
};

export const retireveViewLabelsForGroovyMan = {
  views: [
    {
      name: "View 1",
      alias: "View 1",
      columns: {
        dim_id: {
          alias: "dim_id",
          id: "64d0fe32-a3f0-4c2a-8820-7d73612ae19a",
          columnId: "64d0fe32-a3f0-4c2a-8820-7d73612ae19a",
          type: {
            "java.lang.Float": "numeric",
          },
          category: "column",
          parentCategory: "view",
          uuid: "0a9cafd1-0215-47eb-a3b2-85006d2f0a6b",
          tableKey: "View 1",
          columnKey: "dim_id",
          fullyQualifiedColumn: "View 1.dim_id",
        },
        fiscal_year: {
          alias: "fiscal_year",
          id: "47a4c7d8-0b18-47e1-a87b-d821f4fd2bf0",
          columnId: "47a4c7d8-0b18-47e1-a87b-d821f4fd2bf0",
          type: {
            "java.sql.Date": "date",
          },
          category: "column",
          parentCategory: "view",
          uuid: "99567923-73d9-4a02-a383-3eb3661b1111",
          tableKey: "View 1",
          columnKey: "fiscal_year",
          fullyQualifiedColumn: "View 1.fiscal_year",
        },
        modified_date: {
          alias: "modified_date",
          id: "51213ef1-51b7-4073-bf68-4c90f826f12d",
          columnId: "51213ef1-51b7-4073-bf68-4c90f826f12d",
          type: {
            "java.sql.Timestamp": "dateTime",
          },
          category: "column",
          parentCategory: "view",
          uuid: "e21b3d1a-1202-4b84-80e0-0c335c87494a",
          tableKey: "View 1",
          columnKey: "modified_date",
          fullyQualifiedColumn: "View 1.modified_date",
        },
        date_key: {
          alias: "date_key",
          id: "c4fcb01e-4be2-4ded-9fe8-538c6b21884b",
          columnId: "c4fcb01e-4be2-4ded-9fe8-538c6b21884b",
          type: {
            "java.lang.String": "text",
          },
          category: "column",
          parentCategory: "view",
          uuid: "b2449e2d-c790-439d-aae0-518f9e17387d",
          tableKey: "View 1",
          columnKey: "date_key",
          fullyQualifiedColumn: "View 1.date_key",
        },
        day_number: {
          alias: "day_number",
          id: "fbe3b24d-fe6f-4479-a3c2-76a77b4d21ef",
          columnId: "fbe3b24d-fe6f-4479-a3c2-76a77b4d21ef",
          type: {
            "java.lang.String": "text",
          },
          category: "column",
          parentCategory: "view",
          uuid: "c4d28912-e84c-4b69-a70c-9b6d0ae457c8",
          tableKey: "View 1",
          columnKey: "day_number",
          fullyQualifiedColumn: "View 1.day_number",
        },
        fiscal_month_name: {
          alias: "fiscal_month_name",
          id: "da9fde5c-9cbe-476f-930a-5a4347be622b",
          columnId: "da9fde5c-9cbe-476f-930a-5a4347be622b",
          type: {
            "java.lang.String": "text",
          },
          category: "column",
          parentCategory: "view",
          uuid: "fc8618f2-1484-4d5d-91e4-7a5b5c14dda4",
          tableKey: "View 1",
          columnKey: "fiscal_month_name",
          fullyQualifiedColumn: "View 1.fiscal_month_name",
        },
        fiscal_month_label: {
          alias: "fiscal_month_label",
          id: "e4bdd321-b442-49bd-bd39-e9bf27cf2175",
          columnId: "e4bdd321-b442-49bd-bd39-e9bf27cf2175",
          type: {
            "java.lang.String": "text",
          },
          category: "column",
          parentCategory: "view",
          uuid: "b882fd13-91de-41cb-bb0f-51246280beff",
          tableKey: "View 1",
          columnKey: "fiscal_month_label",
          fullyQualifiedColumn: "View 1.fiscal_month_label",
        },
        created_date: {
          alias: "created_date",
          id: "25f4168f-d670-40a9-9dfa-8b28dc2add3a",
          columnId: "25f4168f-d670-40a9-9dfa-8b28dc2add3a",
          type: {
            "java.lang.String": "text",
          },
          category: "column",
          parentCategory: "view",
          uuid: "b105739d-ae26-4656-85b1-7328bc24454d",
          tableKey: "View 1",
          columnKey: "created_date",
          fullyQualifiedColumn: "View 1.created_date",
        },
        created_time: {
          alias: "created_time",
          id: "55e11b10-1d9f-489c-ad6e-038a0b32c07c",
          columnId: "55e11b10-1d9f-489c-ad6e-038a0b32c07c",
          type: {
            "java.lang.String": "text",
          },
          category: "column",
          parentCategory: "view",
          uuid: "2b21e976-3ee5-47b4-86c4-77a5a0757320",
          tableKey: "View 1",
          columnKey: "created_time",
          fullyQualifiedColumn: "View 1.created_time",
        },
        rating: {
          alias: "rating",
          id: "4f8ea93a-50f4-45a3-ad77-e042e10145d2",
          columnId: "4f8ea93a-50f4-45a3-ad77-e042e10145d2",
          type: {
            "java.lang.String": "text",
          },
          category: "column",
          parentCategory: "view",
          uuid: "88673e22-5475-409b-9b71-1329fcc0c51d",
          tableKey: "View 1",
          columnKey: "rating",
          fullyQualifiedColumn: "View 1.rating",
        },
      },
      key: "sru4-9g7w-4tgk-b2ez-ix",
      uuid: "sru4-9g7w-4tgk-b2ez-ix",
      query: 'select * from "dimdate"',
      queryType: "conditionIf",
      labels: [
        {
          name: "dim_id",
          type: "numeric",
          checked: true,
        },
        {
          name: "fiscal_year",
          type: "date",
          checked: true,
        },
        {
          name: "modified_date",
          type: "dateTime",
          checked: true,
        },
        {
          name: "date_key",
          type: "text",
          checked: true,
        },
        {
          name: "day_number",
          type: "text",
          checked: true,
        },
        {
          name: "fiscal_month_name",
          type: "text",
          checked: true,
        },
        {
          name: "fiscal_month_label",
          type: "text",
          checked: true,
        },
        {
          name: "created_date",
          type: "text",
          checked: true,
        },
        {
          name: "created_time",
          type: "text",
          checked: true,
        },
        {
          name: "rating",
          type: "text",
          checked: true,
        },
      ],
      dataSource: {
        id: "202",
        type: "sql.jdbc.groovy.managed",
        baseType: "global.jdbc",
        catSchemaPredicted: false,
        sync: false,
        catalog: "",
        schema: "HIUSER",
        dir: "Gagan",
        connId: "wvr0u",
        classifier: "db.workflow",
        datasourceName: "groovy man",
        dsKeyPath:
          "w33j-tly1-t8pm-73no-xj/t90f-22fh-3ulj-zbgd-bf/j1mo-4lgd-kmga-6rfy-o7",
        driverType: "DynamicSwitch",
        database: "HIUSER",
      },
      error: false,
      validate: true,
      processedQuery:
        'select * from (select * from "dimdate") foo fetch first 1 rows only',
      id: "8fa9be8c-ffe0-467e-b3e7-8389f323d293",
      type: "view",
      isModified: true,
    },
  ],
  activeView: "sru4-9g7w-4tgk-b2ez-ix",
  dataSourcesAddedToMetadata: [
    {
      id: "202",
      type: "sql.jdbc.groovy.managed",
      baseType: "global.jdbc",
      catSchemaPredicted: false,
      sync: false,
      catalog: "",
      schema: "HIUSER",
      dir: "Gagan",
      connId: "wvr0u",
      classifier: "db.workflow",
      datasourceName: "groovy man",
      dsKeyPath:
        "w33j-tly1-t8pm-73no-xj/t90f-22fh-3ulj-zbgd-bf/j1mo-4lgd-kmga-6rfy-o7",
      driverType: "DynamicSwitch",
      database: "HIUSER",
    },
  ],
  editViewsTempData: false,
};

export const retireveViewLabelsForDerby = {
  views: [
    {
      name: "View 1",
      alias: "View 1",
      columns: {
        dim_id: {
          alias: "dim_id",
          id: "64d0fe32-a3f0-4c2a-8820-7d73612ae19a",
          columnId: "64d0fe32-a3f0-4c2a-8820-7d73612ae19a",
          type: {
            "java.lang.Float": "numeric",
          },
          category: "column",
          parentCategory: "view",
          uuid: "0a9cafd1-0215-47eb-a3b2-85006d2f0a6b",
          tableKey: "View 1",
          columnKey: "dim_id",
          fullyQualifiedColumn: "View 1.dim_id",
        },
        fiscal_year: {
          alias: "fiscal_year",
          id: "47a4c7d8-0b18-47e1-a87b-d821f4fd2bf0",
          columnId: "47a4c7d8-0b18-47e1-a87b-d821f4fd2bf0",
          type: {
            "java.sql.Date": "date",
          },
          category: "column",
          parentCategory: "view",
          uuid: "99567923-73d9-4a02-a383-3eb3661b1111",
          tableKey: "View 1",
          columnKey: "fiscal_year",
          fullyQualifiedColumn: "View 1.fiscal_year",
        },
        modified_date: {
          alias: "modified_date",
          id: "51213ef1-51b7-4073-bf68-4c90f826f12d",
          columnId: "51213ef1-51b7-4073-bf68-4c90f826f12d",
          type: {
            "java.sql.Timestamp": "dateTime",
          },
          category: "column",
          parentCategory: "view",
          uuid: "e21b3d1a-1202-4b84-80e0-0c335c87494a",
          tableKey: "View 1",
          columnKey: "modified_date",
          fullyQualifiedColumn: "View 1.modified_date",
        },
        date_key: {
          alias: "date_key",
          id: "c4fcb01e-4be2-4ded-9fe8-538c6b21884b",
          columnId: "c4fcb01e-4be2-4ded-9fe8-538c6b21884b",
          type: {
            "java.lang.String": "text",
          },
          category: "column",
          parentCategory: "view",
          uuid: "b2449e2d-c790-439d-aae0-518f9e17387d",
          tableKey: "View 1",
          columnKey: "date_key",
          fullyQualifiedColumn: "View 1.date_key",
        },
        day_number: {
          alias: "day_number",
          id: "fbe3b24d-fe6f-4479-a3c2-76a77b4d21ef",
          columnId: "fbe3b24d-fe6f-4479-a3c2-76a77b4d21ef",
          type: {
            "java.lang.String": "text",
          },
          category: "column",
          parentCategory: "view",
          uuid: "c4d28912-e84c-4b69-a70c-9b6d0ae457c8",
          tableKey: "View 1",
          columnKey: "day_number",
          fullyQualifiedColumn: "View 1.day_number",
        },
        fiscal_month_name: {
          alias: "fiscal_month_name",
          id: "da9fde5c-9cbe-476f-930a-5a4347be622b",
          columnId: "da9fde5c-9cbe-476f-930a-5a4347be622b",
          type: {
            "java.lang.String": "text",
          },
          category: "column",
          parentCategory: "view",
          uuid: "fc8618f2-1484-4d5d-91e4-7a5b5c14dda4",
          tableKey: "View 1",
          columnKey: "fiscal_month_name",
          fullyQualifiedColumn: "View 1.fiscal_month_name",
        },
        fiscal_month_label: {
          alias: "fiscal_month_label",
          id: "e4bdd321-b442-49bd-bd39-e9bf27cf2175",
          columnId: "e4bdd321-b442-49bd-bd39-e9bf27cf2175",
          type: {
            "java.lang.String": "text",
          },
          category: "column",
          parentCategory: "view",
          uuid: "b882fd13-91de-41cb-bb0f-51246280beff",
          tableKey: "View 1",
          columnKey: "fiscal_month_label",
          fullyQualifiedColumn: "View 1.fiscal_month_label",
        },
        created_date: {
          alias: "created_date",
          id: "25f4168f-d670-40a9-9dfa-8b28dc2add3a",
          columnId: "25f4168f-d670-40a9-9dfa-8b28dc2add3a",
          type: {
            "java.lang.String": "text",
          },
          category: "column",
          parentCategory: "view",
          uuid: "b105739d-ae26-4656-85b1-7328bc24454d",
          tableKey: "View 1",
          columnKey: "created_date",
          fullyQualifiedColumn: "View 1.created_date",
        },
        created_time: {
          alias: "created_time",
          id: "55e11b10-1d9f-489c-ad6e-038a0b32c07c",
          columnId: "55e11b10-1d9f-489c-ad6e-038a0b32c07c",
          type: {
            "java.lang.String": "text",
          },
          category: "column",
          parentCategory: "view",
          uuid: "2b21e976-3ee5-47b4-86c4-77a5a0757320",
          tableKey: "View 1",
          columnKey: "created_time",
          fullyQualifiedColumn: "View 1.created_time",
        },
        rating: {
          alias: "rating",
          id: "4f8ea93a-50f4-45a3-ad77-e042e10145d2",
          columnId: "4f8ea93a-50f4-45a3-ad77-e042e10145d2",
          type: {
            "java.lang.String": "text",
          },
          category: "column",
          parentCategory: "view",
          uuid: "88673e22-5475-409b-9b71-1329fcc0c51d",
          tableKey: "View 1",
          columnKey: "rating",
          fullyQualifiedColumn: "View 1.rating",
        },
      },
      key: "sru4-9g7w-4tgk-b2ez-ix",
      uuid: "sru4-9g7w-4tgk-b2ez-ix",
      query: 'select * from "dimdate"',
      queryType: "conditionIf",
      labels: [
        {
          name: "dim_id",
          type: "numeric",
          checked: true,
        },
        {
          name: "fiscal_year",
          type: "date",
          checked: true,
        },
        {
          name: "modified_date",
          type: "dateTime",
          checked: true,
        },
        {
          name: "date_key",
          type: "text",
          checked: true,
        },
        {
          name: "day_number",
          type: "text",
          checked: true,
        },
        {
          name: "fiscal_month_name",
          type: "text",
          checked: true,
        },
        {
          name: "fiscal_month_label",
          type: "text",
          checked: true,
        },
        {
          name: "created_date",
          type: "text",
          checked: true,
        },
        {
          name: "created_time",
          type: "text",
          checked: true,
        },
        {
          name: "rating",
          type: "text",
          checked: true,
        },
      ],
      dataSource: {
        id: "202",
        type: "sql.jdbc.groovy.managed",
        baseType: "global.jdbc",
        catSchemaPredicted: false,
        sync: false,
        catalog: "",
        schema: "HIUSER",
        dir: "Gagan",
        connId: "wvr0u",
        classifier: "db.workflow",
        datasourceName: "groovy man",
        dsKeyPath:
          "w33j-tly1-t8pm-73no-xj/t90f-22fh-3ulj-zbgd-bf/j1mo-4lgd-kmga-6rfy-o7",
        driverType: "DynamicSwitch",
        database: "HIUSER",
      },
      error: false,
      validate: true,
      processedQuery:
        'select * from (select * from "dimdate") foo fetch first 1 rows only',
      id: "8fa9be8c-ffe0-467e-b3e7-8389f323d293",
      type: "view",
      isModified: true,
    },
  ],
  activeView: "sru4-9g7w-4tgk-b2ez-ix",
  dataSourcesAddedToMetadata: [
    {
      id: "202",
      type: "sql.jdbc.groovy.managed",
      baseType: "global.jdbc",
      catSchemaPredicted: false,
      sync: false,
      catalog: "",
      schema: "HIUSER",
      connId: "wvr0u",
      classifier: "db.workflow",
      datasourceName: "groovy man",
      dsKeyPath:
        "w33j-tly1-t8pm-73no-xj/t90f-22fh-3ulj-zbgd-bf/j1mo-4lgd-kmga-6rfy-o7",
      driverType: "DynamicSwitch",
      database: "HIUSER",
    },
  ],
  editViewsTempData: false,
};
