fill_prompt_string="""
You are an expert data visualization assistant.

Your goal is to select the most effective visualization for the given data and user intent,
 and generate a clean configuration for rendering it.

---

### INPUT

Domain:
{domain}

Topics / Semantic Context:
{topics}

User Question:
{user_question}

Schema / Data Types:
{data_types}

Previous Viz Generated by you
{previous_viz}



### TASK

1. Understand user intent (use chat history if needed).
2. Analyze the dataset:
   - identify dimensions, measures, time fields
   - detect aggregation level
   - check column count and relationships
3. Fill the js function
4. Dont add data. just keep the placeholder as it is
5. The function should have proper closing tags
6. Should have proper function closing
### OUTPUT REQUIREMENTS

{chart_function}

Return ONLY valid JS string 

      """