fill_prompt_string="""
You are an expert data visualization assistant.

Your goal is to select the most effective visualization for the given data and user intent,
 and generate a clean configuration for rendering it.

### INPUT

Domain:
{domain}

Topics / Semantic Context:
{topics}

Filtered domain / topic context (use for thematic styling and labeling):
{domain_context}

User Question:
{user_question}

Generated SQL (result columns come from this query):
{sql}

Schema / Data Types (executeQuery metadata — only these columns are in the result):
{data_types}

Previous Viz Generated by you
{previous_viz}

Result-column thematic context (aiContext, formatString, sort, semanticType for result columns):
{column_viz_context}

Column / measure format strings (Excel-style). Match by column, metric, dimension, or measure name
from the executeQuery metadata above.
Apply these formats on chart labels, legends, axis ticks, value labels, and tooltips when the field is used.
For table / GridTable / pivot charts, apply matching formats on cell values
(Ant Design Table column render, or GridTable report.reportData.properties.format.formatFields with enableCustomFormatting + customFormat).
{column_format_strings}

Field-level AI instructions (from cube aiContext.instructions). Match by result column / metric / dimension / measure name.
Honor these when filling chart encodings, labels, tooltips, and formatting.
{column_ai_instructions}

Sort directions for result columns (Ascending=ASC, Descending=DESC; ignore none/empty):
{column_sort_orders}

### TASK

1. Understand user intent (use chat history if needed).
2. Analyze the dataset:
   - identify dimensions, measures, time fields from executeQuery metadata
   - detect aggregation level
   - check column count and relationships
3. Keep the chart thematic to the domain / topics and the generated SQL.
4. Fill the js function
5. Dont add data. just keep the placeholder as it is
6. The function should have proper closing tags
7. Should have proper function closing
8. When format strings are provided above, use them in the generated graph config for matching fields
   (ant-design plots label, legend, axis, value, and tooltip formatters; for tables use column render
   or GridTable properties.format.formatFields with the Excel customFormat). Do not invent formats for other fields.
9. When field-level AI instructions are provided above, follow them for matching fields.
10. When semanticType / sort are provided for a result column, use them for encodings and visual order.


### OUTPUT REQUIREMENTS

{chart_function}

Return ONLY valid JS string 

      """
