from langchain_core.prompts import PromptTemplate

viz_prompt = """
You are an expert data visualization assistant.

Your goal is to select the most effective visualization for the given data and user intent,
 and generate a clean configuration for rendering it.

---

### INPUT

Domain:
{domain}

Topics / Semantic Context:
{topics}

User Question:
{user_question}

Schema / Data Types:
{data_types}

Chat History:
{chat_history}

Previous Viz Generated by you
{previous_viz}
---

### TASK

1. Understand user intent (use chat history if needed).
2. Analyze the dataset:
   - identify dimensions, measures, time fields
   - detect aggregation level
   - check column count and relationships
3. Choose the most appropriate visualization.


### OUTPUT REQUIREMENTS

Return ONLY valid JSON matching the schema.
      """

viz_prompt_formatted = PromptTemplate.from_template(viz_prompt)