package com.helicalinsight.adhoc.services.nosql;

import com.google.gson.Gson;
import com.google.gson.JsonObject;
import com.google.gson.JsonSyntaxException;
import com.helicalinsight.adhoc.services.DrillCsvDataSourceCreator;
import com.helicalinsight.datasource.GsonUtility;
import com.helicalinsight.datasource.nosql.NoSQLLoader;
import com.helicalinsight.efw.exceptions.EfwServiceException;
import com.helicalinsight.efw.utility.JsonUtils;
import com.mongodb.ConnectionString;
import com.mongodb.MongoClientSettings;
import com.mongodb.MongoCredential;
import com.mongodb.MongoException;
import com.mongodb.MongoSecurityException;
import com.mongodb.MongoTimeoutException;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoDatabase;
import org.apache.commons.lang3.StringUtils;
import org.bson.Document;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import java.util.concurrent.TimeUnit;

/**
 * {@code MongoNoSQLLoader} is the active, non-deprecated implementation of {@link NoSQLLoader} for MongoDB.
 * <p>
 * It is registered under the Spring bean name {@code "com.helicalinsight.nosql.mongo"}. This is the exact
 * {@code subType}/{@code driverName} value that the built-in "Mongodb" data source tile already sends (see
 * {@code hi-repository/System/Admin/Static/DataSourcesList.groovy}), and it is looked up dynamically via
 * {@code NoSqlUtils.getNoSqlImplementation(subType)} -&gt; {@code NoSqlDataSourceProperties.getSubType(formData)}.
 * This class replaces the previous, deprecated {@code MongoDrillLoader} which registered under the same bean
 * name but only produced a stub/best-effort Drill registration with no real connectivity verification.
 * <p>
 * Responsibilities:
 * <ul>
 *     <li>{@link #testConnection(JsonObject)} performs a real connectivity check against MongoDB using the
 *     official MongoDB Java driver (no Drill/Spark middleware is required for this step).</li>
 *     <li>{@link #loadToMiddleWare(JsonObject)} optionally registers the connection as an Apache Drill
 *     "mongo" storage plugin (the same mechanism already used by Helical Insight for other non-JDBC-native
 *     sources such as CSV, see {@link DrillCsvDataSourceCreator}), so the connection becomes queryable via
 *     SQL through Drill's JDBC driver just like any other configured data source. If Drill middleware is not
 *     enabled, this step is skipped gracefully and the connection is still saved successfully.</li>
 * </ul>
 *
 * @author Helical Insight
 */
@Component("com.helicalinsight.nosql.mongo")
@Scope("prototype")
public class MongoNoSQLLoader extends NoSQLLoader {

    private static final Logger logger = LoggerFactory.getLogger(MongoNoSQLLoader.class);

    /**
     * Tests connectivity to a MongoDB instance/cluster using the connection details supplied by the user
     * in the "Create/Edit Data Source" form.
     * <p>
     * Expected fields on {@code formData} (mirroring the fields already used by other NoSQL connections):
     * <ul>
     *     <li>{@code jdbcUrl} - a MongoDB connection string, e.g. {@code mongodb://host:port/database} or
     *     {@code mongodb+srv://host/database}. This is normally auto generated by the UI from the
     *     {@code databaseDrivers.properties} template for MongoDB.</li>
     *     <li>{@code database} / {@code databaseName} - the database to run the connectivity check against.
     *     Falls back to the database embedded in {@code jdbcUrl}, and finally to {@code admin}.</li>
     *     <li>{@code userName} / {@code password} - optional credentials.</li>
     *     <li>{@code authMechanism} - optional SASL/auth mechanism (e.g. SCRAM-SHA-1, SCRAM-SHA-256, PLAIN).</li>
     *     <li>{@code timeOut} - optional connect timeout in milliseconds.</li>
     *     <li>{@code maxWait} - optional server selection timeout in milliseconds.</li>
     * </ul>
     *
     * @param formData the connection form data.
     * @return {@code true} if the connection (and a MongoDB {@code ping} command) succeeded.
     */
    @Override
    public boolean testConnection(JsonObject formData) {
        try (MongoClient mongoClient = MongoConnectionSettingsBuilder.buildClient(formData)) {
            String database = MongoConnectionSettingsBuilder.resolveDatabase(formData);
            MongoDatabase mongoDatabase = mongoClient.getDatabase(database);
            Document pingResult = mongoDatabase.runCommand(new Document("ping", 1));
            logger.info("MongoDB connection test succeeded for database '{}'.", database);
            return pingResult != null;
        } catch (MongoSecurityException e) {
            logger.error("MongoDB authentication failed.", e);
            throw new EfwServiceException(
                    "MongoDB authentication failed. Please verify the username, password and auth database.", e);
        } catch (MongoTimeoutException e) {
            logger.error("MongoDB connection timed out.", e);
            throw new EfwServiceException(
                    "Could not connect to MongoDB. Please verify the host, port and that the server is reachable.",
                    e);
        } catch (MongoException e) {
            logger.error("MongoDB connection test failed.", e);
            throw new EfwServiceException("Unable to connect to MongoDB: " + e.getMessage(), e);
        } catch (IllegalArgumentException e) {
            logger.error("Invalid MongoDB connection configuration.", e);
            throw new EfwServiceException("Invalid MongoDB connection configuration: " + e.getMessage(), e);
        }
    }

    /**
     * Registers the MongoDB connection as a queryable data source.
     * <p>
     * When the Apache Drill middleware is enabled (see {@code hi-repository/System/Admin/drillConfig.xml}),
     * the connection is registered as a Drill "mongo" storage plugin, exactly like the existing CSV/JSON
     * NoSQL sources, which makes it immediately queryable through SQL via Drill's JDBC driver.
     * <p>
     * When Drill middleware is not enabled, this step is skipped and only a warning is logged - the
     * MongoDB connection itself is still created/saved successfully so this never blocks the basic
     * "configure a MongoDB connection" use case.
     *
     * @param formData the connection form data.
     * @return {@code true} once the operation completes (registration errors are surfaced as exceptions).
     */
    @Override
    public boolean loadToMiddleWare(JsonObject formData) {
        if (!isDrillMiddlewareEnabled()) {
            logger.warn("Apache Drill middleware is not enabled. The MongoDB connection '{}' has been saved, "
                            + "but will not be queryable through ad-hoc/SQL reports until Drill middleware is "
                            + "enabled (System > Admin > Drill Configuration) and the connection is saved again.",
                    GsonUtility.optString(formData, "name"));
            return true;
        }

        registerAsDrillStorage(formData);
        return true;
    }

    private boolean isDrillMiddlewareEnabled() {
        try {
            JsonObject drillConfig = JsonUtils.newGetXmlAsJson(JsonUtils.getDrillConfigPath());
            return drillConfig.has("enabled") && drillConfig.get("enabled").getAsBoolean();
        } catch (Exception e) {
            logger.warn("Could not read the Drill configuration to check whether middleware registration "
                    + "is required. Skipping middleware registration for this MongoDB connection.", e);
            return false;
        }
    }

    private void registerAsDrillStorage(JsonObject formData) {
        String storageName = sanitizeStorageName(GsonUtility.optString(formData, "name"));
        String theId = GsonUtility.optString(formData, "theId");
        if (StringUtils.isEmpty(storageName) || StringUtils.isEmpty(theId)) {
            throw new EfwServiceException(
                    "The connection name and id are required to register the MongoDB connection with Drill.");
        }

        String drillConnectionString = MongoConnectionSettingsBuilder.buildDrillConnectionString(formData);

        JsonObject config = new JsonObject();
        config.addProperty("type", "mongo");
        config.addProperty("connection", drillConnectionString);
        config.addProperty("enabled", true);

        JsonObject storageJson = new JsonObject();
        String qualifiedStorageName = storageName + "_" + theId;
        storageJson.addProperty("name", qualifiedStorageName);
        storageJson.add("config", config);

        String drillStorageUrl = DrillCsvDataSourceCreator.getUrlOfDrill();
        String resourceUrl = drillStorageUrl + "/storage/" + qualifiedStorageName + ".json";

        String result = DrillCsvDataSourceCreator.drillRestApiCall(resourceUrl, "POST", storageJson.toString());
        if (result == null) {
            throw new EfwServiceException(
                    "There was a problem registering the MongoDB connection as a Drill storage plugin. "
                            + "Please verify that the Drill middleware is up and reachable.");
        }
        try {
            new Gson().fromJson(result, JsonObject.class);
        } catch (JsonSyntaxException e) {
            throw new EfwServiceException(
                    "Unexpected response received from Drill while registering the MongoDB connection: " + result,
                    e);
        }
    }

    private static String sanitizeStorageName(String name) {
        if (StringUtils.isEmpty(name)) {
            return name;
        }
        return name.trim().replaceAll("\\s+", "_");
    }

    /**
     * Helper responsible for turning the generic connection form data into MongoDB driver level
     * connection settings. Kept as a private static nested utility to avoid the need for a shared
     * public class, since it is only needed by {@link MongoNoSQLLoader}.
     */
    private static final class MongoConnectionSettingsBuilder {

        private MongoConnectionSettingsBuilder() {
        }

        private static MongoClient buildClient(JsonObject formData) {
            MongoClientSettings settings = buildSettings(formData);
            return MongoClients.create(settings);
        }

        private static MongoClientSettings buildSettings(JsonObject formData) {
            String rawConnectionString = normalizedConnectionString(formData);
            ConnectionString connectionString;
            try {
                connectionString = new ConnectionString(rawConnectionString);
            } catch (IllegalArgumentException e) {
                throw new IllegalArgumentException(
                        "The MongoDB connection URL is not valid. Please use the format "
                                + "mongodb://host:port/database.", e);
            }

            int connectTimeout = GsonUtility.optInt(formData, "timeOut");
            int serverSelectionTimeout = GsonUtility.optInt(formData, "maxWait");
            boolean sslEnabled = GsonUtility.optBoolean(formData, "ssl");

            MongoClientSettings.Builder settingsBuilder = MongoClientSettings.builder()
                    .applyConnectionString(connectionString)
                    .applyToSocketSettings(builder -> {
                        if (connectTimeout > 0) {
                            builder.connectTimeout(connectTimeout, TimeUnit.MILLISECONDS);
                        }
                    })
                    .applyToClusterSettings(builder -> {
                        if (serverSelectionTimeout > 0) {
                            builder.serverSelectionTimeout(serverSelectionTimeout, TimeUnit.MILLISECONDS);
                        }
                    });

            if (sslEnabled) {
                settingsBuilder.applyToSslSettings(builder -> builder.enabled(true).invalidHostNameAllowed(true));
            }

            MongoCredential credential = buildCredential(formData, connectionString);
            if (credential != null) {
                settingsBuilder.credential(credential);
            }

            return settingsBuilder.build();
        }

        private static MongoCredential buildCredential(JsonObject formData, ConnectionString connectionString) {
            if (connectionString.getCredential() != null) {
                // Credentials were already supplied as part of the connection string (e.g. mongodb://user:pass@host).
                return null;
            }

            String username = GsonUtility.optString(formData, "userName");
            String password = GsonUtility.optString(formData, "password");
            if (StringUtils.isEmpty(username) || StringUtils.isEmpty(password)) {
                return null;
            }

            String authDatabase = GsonUtility.optString(formData, "authDatabase");
            if (StringUtils.isEmpty(authDatabase)) {
                authDatabase = resolveDatabase(formData);
            }
            String authMechanism = GsonUtility.optString(formData, "authMechanism");
            char[] passwordChars = password.toCharArray();

            if (StringUtils.isEmpty(authMechanism)) {
                return MongoCredential.createCredential(username, authDatabase, passwordChars);
            }

            switch (authMechanism.trim().toUpperCase()) {
                case "SCRAM-SHA-1":
                case "SCRAMSHA1":
                    return MongoCredential.createScramSha1Credential(username, authDatabase, passwordChars);
                case "SCRAM-SHA-256":
                case "SCRAMSHA256":
                    return MongoCredential.createScramSha256Credential(username, authDatabase, passwordChars);
                case "PLAIN":
                    return MongoCredential.createPlainCredential(username, authDatabase, passwordChars);
                case "GSSAPI":
                    return MongoCredential.createGSSAPICredential(username);
                case "MONGODB-X509":
                case "MONGODBX509":
                    return MongoCredential.createMongoX509Credential(username);
                default:
                    return MongoCredential.createCredential(username, authDatabase, passwordChars);
            }
        }

        private static String resolveDatabase(JsonObject formData) {
            String database = GsonUtility.optString(formData, "database");
            if (StringUtils.isEmpty(database)) {
                database = GsonUtility.optString(formData, "databaseName");
            }
            if (StringUtils.isEmpty(database)) {
                try {
                    ConnectionString connectionString = new ConnectionString(normalizedConnectionString(formData));
                    database = connectionString.getDatabase();
                } catch (IllegalArgumentException ignored) {
                    // fall through to the default below
                }
            }
            return StringUtils.isEmpty(database) ? "admin" : database;
        }

        private static String normalizedConnectionString(JsonObject formData) {
            String jdbcUrl = GsonUtility.optString(formData, "jdbcUrl");
            if (StringUtils.isEmpty(jdbcUrl)) {
                jdbcUrl = GsonUtility.optString(formData, "url");
            }
            if (StringUtils.isEmpty(jdbcUrl)) {
                throw new IllegalArgumentException(
                        "A MongoDB connection URL (jdbcUrl) is required, e.g. mongodb://host:port/database.");
            }
            // Some parts of the UI/config prefix connection URLs with "jdbc:" (as is done for regular JDBC
            // drivers). MongoDB connection strings never use that prefix, so it is stripped if present.
            return jdbcUrl.startsWith("jdbc:") ? jdbcUrl.substring("jdbc:".length()) : jdbcUrl;
        }

        private static String buildDrillConnectionString(JsonObject formData) {
            String connectionString = normalizedConnectionString(formData);
            String username = GsonUtility.optString(formData, "userName");
            String password = GsonUtility.optString(formData, "password");

            ConnectionString parsed;
            try {
                parsed = new ConnectionString(connectionString);
            } catch (IllegalArgumentException e) {
                throw new EfwServiceException("The MongoDB connection URL is not valid: " + connectionString, e);
            }

            if (StringUtils.isNotEmpty(username) && StringUtils.isNotEmpty(password)
                    && parsed.getCredential() == null) {
                String hosts = String.join(",", parsed.getHosts());
                String database = resolveDatabase(formData);
                return "mongodb://" + username + ":" + password + "@" + hosts + "/" + database
                        + "?authMechanism=SCRAM-SHA-1";
            }
            return connectionString;
        }
    }
}
