const dataSourceDataMock = {
  data: {
    status: 1,
    response: {
      driversList: [
        {
          driver: "com.helicalinsight.avro",
          available: "true",
          fileUpload: true,
          parameter: { "@type": "avro", "@extensions": ".avro" },
        },
        {
          driver: "com.helicalinsight.csv",
          available: "true",
          fileUpload: true,
          parameter: {
            "@delimiter": ",",
            "@extensions": ".csv",
            "@extractHeader": "true",
            "@type": "text",
          },
        },
        {
          driver: "com.helicalinsight.csvh",
          available: "true",
          fileUpload: true,
          parameter: {
            "@delimiter": ",",
            "@extensions": ".csvh",
            "@extractHeader": "true",
            "@type": "text",
          },
        },
        {
          driver: "com.helicalinsight.excel",
          available: "true",
          fileUpload: true,
          parameter: { "@type": "excel", "@extensions": ".excel" },
        },
        {
          driver: "com.helicalinsight.json",
          available: "true",
          fileUpload: true,
          parameter: { "@extensions": ".json", "@type": "json" },
        },
        {
          driver: "com.helicalinsight.ltsv",
          available: "true",
          fileUpload: true,
          parameter: { "@extensions": ".ltsv", "@type": "ltsv" },
        },
        {
          driver: "com.helicalinsight.parquet",
          available: "true",
          fileUpload: true,
          parameter: { "@type": "parquet", "@extensions": ".parquet" },
        },
        {
          driver: "com.helicalinsight.pcap",
          available: "true",
          fileUpload: true,
          parameter: { "@extensions": ".pcap", "@type": "pcap" },
        },
        {
          driver: "com.helicalinsight.pcapng",
          available: "true",
          fileUpload: true,
          parameter: { "@extensions": ".pcapng", "@type": "pcapng" },
        },
        {
          driver: "com.helicalinsight.psv",
          available: "true",
          fileUpload: true,
          parameter: {
            "@delimiter": "|",
            "@extensions": ".psv",
            "@extractHeader": "true",
            "@type": "text",
          },
        },
        {
          driver: "com.helicalinsight.sequencefile",
          available: "true",
          fileUpload: true,
          parameter: {
            "@extensions": ".sequencefile",
            "@type": "sequencefile",
          },
        },
        {
          driver: "com.helicalinsight.shp",
          available: "true",
          fileUpload: true,
          parameter: { "@type": "shp", "@extensions": ".shp" },
        },
        {
          driver: "com.helicalinsight.syslog",
          available: "true",
          fileUpload: true,
          parameter: { "@extensions": ".syslog", "@type": "syslog" },
        },
        {
          driver: "com.helicalinsight.tsv",
          available: "true",
          fileUpload: true,
          parameter: {
            "@delimiter": " ",
            "@extensions": ".tsv",
            "@extractHeader": "true",
            "@type": "text",
          },
        },
        {
          driver: "com.helicalinsight.nosql.mongo",
          available: "true",
          url: "mongodb://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "27017",
            hostName: "localhost",
            database: "database",
            collection: "collection",
            sslPort: "3345",
          },
        },
        {
          driver: "dynamicSwitch",
          showInDatasource: "false",
          available: "true",
          parameters: [],
        },
        {
          url: "jdbc:derby:{{database}}",
          driver: "org.apache.derby.jdbc.AutoloadedDriver",
          available: "true",
          parameters: { database: "database" },
        },
        {
          url: "jdbc:sqlserver://{{hostName}}:{{port}};DatabaseName={{database}}",
          driver: "com.microsoft.sqlserver.jdbc.SQLServerDriver",
          available: "true",
          parameters: {
            port: "1433",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
          driver: "com.mysql.cj.jdbc.Driver",
          available: "true",
          parameters: {
            port: "3306",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
          driver: "com.mysql.jdbc.Driver",
          available: "true",
          parameters: {
            port: "3306",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          url: "jdbc:jtds:sqlserver://{{hostName}}:{{port}}/{{database}}",
          driver: "net.sourceforge.jtds.jdbc.Driver",
          available: "true",
          parameters: {
            port: "1433",
            hostName: "localhost",
            database: "database",
          },
        },
        { available: "true", driver: "com.helical.mongodb.MongoJdbcDriver" },
        {
          url: "jdbc:hive2://{{hostName}}:{{port}}/{{database}}",
          driver: "org.apache.hive.jdbc.HiveDriver",
          available: "true",
          parameters: {
            port: "10001",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          url: "jdbc:drill:{{hostName}}:{{port}}",
          driver: "org.apache.drill.jdbc.Driver",
          available: "true",
          parameters: { port: "31010", hostName: "drillbit=localhost" },
        },
        {
          available: "true",
          driver: "oadd.org.apache.commons.dbcp2.PoolingDriver",
        },
        {
          url: "jdbc:informix-sqli://{{hostName}}:{{port}}/{{database}}:delimident=y",
          driver: "com.informix.jdbc.IfxDriver",
          available: "true",
          parameters: {
            port: "1526",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          url: "jdbc:db2://{{hostName}}:{{port}}/{{database}}",
          driver: "com.ibm.db2.jcc.DB2Driver",
          available: "true",
          parameters: {
            port: "50000",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          url: "jdbc:mariadb://{{hostName}}:{{port}}/{{database}}",
          driver: "org.mariadb.jdbc.Driver",
          available: "true",
          parameters: {
            port: "3306",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          url: "jdbc:presto://{{hostName}}:{{port}}",
          driver: "com.facebook.presto.jdbc.PrestoDriver",
          available: "true",
          parameters: { port: "8090", hostName: "localhost" },
        },
        {
          url: "jdbc:sqlite:{{database}}",
          driver: "org.sqlite.JDBC",
          available: "true",
          parameters: { database: "database" },
        },
      ],
      dataSourceTypes: [
        {
          type: "global.jdbc",
          name: "Managed DataSource",
          classifier: "global",
          categoryName: "advanced",
          categoryType: "advanced",
        },
        {
          type: "sql.jdbc",
          name: "Plain Jdbc DataSource",
          classifier: "efwd",
          categoryName: "advanced",
          categoryType: "advanced",
        },
        {
          type: "sql.jdbc.groovy",
          name: "Groovy Plain Jdbc DataSource",
          classifier: "efwd",
          categoryName: "advanced",
          categoryType: "advanced",
        },
        {
          type: "sql.jdbc.groovy.managed",
          name: "Groovy Managed Jdbc DataSource",
          classifier: "efwd",
          categoryName: "advanced",
          categoryType: "advanced",
        },
      ],
      dataSources: [
        {
          driver: "org.apache.drill.jdbc.Driver",
          databaseDialect: "drill",
          enabledTypes: true,
          name: "Apache Drill",
          categoryName: "Big Data",
          categoryType: "big_data",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:drill:{{hostName}}:{{port}}",
          parameters: { port: "31010", hostName: "drillbit=localhost" },
        },
        {
          driver: "com.helicalinsight.shp",
          databaseDialect: "",
          name: "Shp",
          categoryName: "Flat Files",
          categoryType: "flat_files",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          fileUpload: true,
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
        },
        {
          name: "Dremio",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          driver: "net.sourceforge.jtds.jdbc.Driver",
          databaseDialect: "sqlserver",
          name: "Microsoft Sqlserver(sourceforge)",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:jtds:sqlserver://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "1433",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          driver: "com.helicalinsight.tsv",
          databaseDialect: "",
          name: "Tsv",
          categoryName: "Flat Files",
          categoryType: "flat_files",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          fileUpload: true,
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
        },
        {
          categoryName: "No SQL & Big Data",
          categoryType: "nosql_bigdata",
          classifier: "global",
          dataSourceProvider: "noSql",
          driver: "com.helicalinsight.nosql.mongo",
          name: "Mongodb",
          parameters: {
            collection: "collection",
            database: "database",
            hostName: "localhost",
            port: "27017",
            sslPort: "3345",
          },
          type: "global.jdbc",
          url: "mongodb://{{hostName}}:{{port}}/{{database}}",
        },
        {
          driver: "com.helicalinsight.parquet",
          databaseDialect: "",
          name: "Parquet",
          categoryName: "Flat Files",
          categoryType: "flat_files",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          fileUpload: true,
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
        },
        {
          driver: "com.helicalinsight.pcapng",
          databaseDialect: "",
          name: "Pcapng",
          categoryName: "Flat Files",
          categoryType: "flat_files",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          fileUpload: true,
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
        },
        {
          driver: "com.helicalinsight.psv",
          databaseDialect: "",
          name: "Psv",
          categoryName: "Flat Files",
          categoryType: "flat_files",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          fileUpload: true,
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
        },
        {
          driver: "com.ibm.db2.jcc.DB2Driver",
          databaseDialect: "db2",
          name: "IBM Db2",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:db2://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "50000",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          name: "Teradata",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          driver: "com.helicalinsight.avro",
          databaseDialect: "",
          name: "Avro",
          categoryName: "Flat Files",
          categoryType: "flat_files",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          fileUpload: true,
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
        },
        {
          driver: "com.helicalinsight.csvh",
          databaseDialect: "",
          name: "Csvh",
          categoryName: "Flat Files",
          categoryType: "flat_files",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          fileUpload: true,
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
        },
        {
          driver: "com.helicalinsight.ltsv",
          databaseDialect: "",
          name: "Ltsv",
          categoryName: "Flat Files",
          categoryType: "flat_files",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          fileUpload: true,
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
        },
        {
          driver: "com.helicalinsight.pcap",
          databaseDialect: "",
          name: "Pcap",
          categoryName: "Flat Files",
          categoryType: "flat_files",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          fileUpload: true,
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
        },
        {
          driver: "com.informix.jdbc.IfxDriver",
          databaseDialect: "informix",
          name: "Informix",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:informix-sqli://{{hostName}}:{{port}}/{{database}}:delimident=y",
          parameters: {
            port: "1526",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          name: "Oracle",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          driver: "com.helicalinsight.sequencefile",
          databaseDialect: "",
          name: "Sequencefile",
          categoryName: "Flat Files",
          categoryType: "flat_files",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          fileUpload: true,
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
        },
        {
          name: "Amazondynamodb",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          driver: "com.helicalinsight.syslog",
          databaseDialect: "",
          name: "Syslog",
          categoryName: "Flat Files",
          categoryType: "flat_files",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          fileUpload: true,
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
        },
        {
          name: "Postgresql",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          driver: "com.microsoft.sqlserver.jdbc.SQLServerDriver",
          databaseDialect: "sqlserver",
          name: "Microsoft Sqlserver",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:sqlserver://{{hostName}}:{{port}};DatabaseName={{database}}",
          parameters: {
            port: "1433",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          name: "Amazon Redshift",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          driver: "com.helicalinsight.json",
          databaseDialect: "",
          name: "Json",
          categoryName: "Flat Files",
          categoryType: "flat_files",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          fileUpload: true,
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
        },
        {
          driver: "com.helical.mongodb.MongoJdbcDriver",
          databaseDialect: "himongo",
          name: "Helical Mongodb",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
        },
        {
          driver: "com.helicalinsight.csv",
          databaseDialect: "",
          name: "Csv",
          categoryName: "Flat Files",
          categoryType: "flat_files",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          fileUpload: true,
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
        },
        {
          driver: "org.sqlite.JDBC",
          databaseDialect: "sqlite",
          name: "Sqlite",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:sqlite:{{database}}",
          parameters: { database: "database" },
        },
        {
          driver: "dynamicSwitch",
          databaseDialect: "",
          name: "DynamicSwitch",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
        },
        {
          driver: "com.facebook.presto.jdbc.PrestoDriver",
          databaseDialect: "presto",
          name: "Presto",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:presto://{{hostName}}:{{port}}",
          parameters: { port: "8090", hostName: "localhost" },
        },
        {
          driver: "org.apache.derby.jdbc.AutoloadedDriver",
          databaseDialect: "derby",
          name: "Derby",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:derby:{{database}}",
          parameters: { database: "database" },
        },
        {
          driver: "com.mysql.cj.jdbc.Driver",
          databaseDialect: "mysql",
          name: "Mysql Cj",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "3306",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          name: "Ξ Add Driver Ξ",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          driver: "org.mariadb.jdbc.Driver",
          databaseDialect: "mysql",
          name: "Mariadb",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:mariadb://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "3306",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          driver: "org.apache.hive.jdbc.HiveDriver",
          databaseDialect: "spark",
          name: "Hive",
          categoryName: "Big Data",
          categoryType: "big_data",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:hive2://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "10001",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          driver: "oadd.org.apache.commons.dbcp2.PoolingDriver",
          databaseDialect: "",
          name: "Oadd Commons Dbcp2",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
        },
        {
          driver: "com.helicalinsight.excel",
          databaseDialect: "",
          name: "Excel",
          categoryName: "Flat Files",
          categoryType: "flat_files",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          fileUpload: true,
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
        },
        {
          name: "Access",
          categoryType: "supported",
          categoryName: "Supported",
        },
        {
          driver: "com.mysql.jdbc.Driver",
          databaseDialect: "mysql",
          name: "Mysql",
          categoryName: "RDBMS",
          categoryType: "rdbms",
          type: "global.jdbc",
          dataSourceProvider: "tomcat",
          classifier: "global",
          imgUrl: "../images/data_sources/defaut_datasource.png",
          url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
          parameters: {
            port: "3306",
            hostName: "localhost",
            database: "database",
          },
        },
        {
          name: "Googlebigquery",
          categoryType: "supported",
          categoryName: "Supported",
        },
      ],
    },
  },
};

const reportsCountMock = {
  data: {
    status: 1,
    response: {
      reportsCount: 32,
      latestReports: [
        {
          dir: "1638771660756",
          file: "08965194-4b18-4f8c-a472-c24fa136ce9d.metadata",
          lastModified: 1639567304000,
          logicalPath: "//naresh 1",
          reportPath: "1638771660756/08965194-4b18-4f8c-a472-c24fa136ce9d.metadata",
          title: "test",
        },
        {
          dir: "1639026125991",
          file: "59ced249-8d96-4175-aa88-75a17b200b5c.metadata",
          lastModified: 1639026140000,
          logicalPath: "//gagan",
          reportPath: "1639026125991/59ced249-8d96-4175-aa88-75a17b200b5c.metadata",
          title: "std",
        },
        {
          dir: "1638771660756",
          file: "bd36dafc-9ee2-43dc-9bd2-ba9255e3b77e.metadata",
          lastModified: 1638960729000,
          logicalPath: "//naresh 1",
          reportPath: "1638771660756/bd36dafc-9ee2-43dc-9bd2-ba9255e3b77e.metadata",
          title: "Metadata_1",
        },
        {
          dir: "1638771660756",
          file: "9b99e60b-2146-46ed-9ec9-5d503e88929f.efw",
          lastModified: 1638857049000,
          logicalPath: "//naresh 1",
          reportPath: "1638771660756/9b99e60b-2146-46ed-9ec9-5d503e88929f.efw",
          title: "de",
        },
        {
          dir: "1638771660756",
          file: "9b99e60b-2146-46ed-9ec9-5d503e88929f.efwdd",
          lastModified: 1638857049000,
          logicalPath: "//naresh 1",
          reportPath: "1638771660756/9b99e60b-2146-46ed-9ec9-5d503e88929f.efwdd",
          title: "de",
        },
        {
          dir: "1463377807724/1593413909773",
          file: "ead71899-7382-41ec-a0f1-992bb1ecb9fa.hcr",
          lastModified: 1638771685000,
          logicalPath: "//HI Sample Reports/Sample Canned Report",
          reportPath: "1463377807724/1593413909773/ead71899-7382-41ec-a0f1-992bb1ecb9fa.hcr",
          title: "Detailed Travel Report By Client",
        },
        {
          dir: "1463377807724/1465647380854",
          file: "3a91fae9-6d4d-48fc-a718-83f38613198f.efwdd",
          lastModified: 1638771676000,
          logicalPath: "//HI Sample Reports/DashboardDesigner-Sample",
          reportPath: "1463377807724/1465647380854/3a91fae9-6d4d-48fc-a718-83f38613198f.efwdd",
          title: "Sample Designer Report",
        },
        {
          dir: "1638768386261/1638768400749",
          file: "b85b50e4-bca0-44e7-aee7-5e362926151a.efw",
          lastModified: 1638771520000,
          logicalPath: "//API Automation_postman/Dashboard Designer_postman",
          reportPath: "1638768386261/1638768400749/b85b50e4-bca0-44e7-aee7-5e362926151a.efw",
          title: "hiviewerdelete_Designer",
        },
        {
          dir: "1638768386261/1638768400749",
          file: "d2dd958f-3f13-4e10-8e97-674cfb4ff194.efw",
          lastModified: 1638771513000,
          logicalPath: "//API Automation_postman/Dashboard Designer_postman",
          reportPath: "1638768386261/1638768400749/d2dd958f-3f13-4e10-8e97-674cfb4ff194.efw",
          title: "hiviewerdelete_Designer_hiadmin",
        },
        {
          dir: "1638768386261/1638768400749",
          file: "d3064885-5426-4d98-a6d5-a5b6de06d5fa.efw",
          lastModified: 1638771507000,
          logicalPath: "//API Automation_postman/Dashboard Designer_postman",
          reportPath: "1638768386261/1638768400749/d3064885-5426-4d98-a6d5-a5b6de06d5fa.efw",
          title: "delete_Designer_hiadmin",
        },
        {
          dir: "1638768386261/1638768400749",
          file: "e91c3496-0b23-47b1-83f1-116b3dbe29fc.efw",
          lastModified: 1638771499000,
          logicalPath: "//API Automation_postman/Dashboard Designer_postman",
          reportPath: "1638768386261/1638768400749/e91c3496-0b23-47b1-83f1-116b3dbe29fc.efw",
          title: "delete_Designer_hiadmin",
        },
        {
          dir: "1638768386261/1638768400749",
          file: "d89a4948-92ed-47bb-a7e9-5f77ef5c48df.efw",
          lastModified: 1638771448000,
          logicalPath: "//API Automation_postman/Dashboard Designer_postman",
          reportPath: "1638768386261/1638768400749/d89a4948-92ed-47bb-a7e9-5f77ef5c48df.efw",
          title: "Save_Designer_hiadmin",
        },
        {
          dir: "1638768386261/1638768400749",
          file: "f8630085-f1dc-44ac-852d-61030507e34e.efw",
          lastModified: 1638769832000,
          logicalPath: "//API Automation_postman/Dashboard Designer_postman",
          reportPath: "1638768386261/1638768400749/f8630085-f1dc-44ac-852d-61030507e34e.efw",
          title: "Designer save",
        },
        {
          dir: "1638768386261/1638769330507",
          file: "5528549f-0bbd-4812-8a0a-579050235731.metadata",
          lastModified: 1638769468000,
          logicalPath: "//API Automation_postman/Metadata_postman",
          reportPath: "1638768386261/1638769330507/5528549f-0bbd-4812-8a0a-579050235731.metadata",
          title: "MD create after deleting Ds cache",
        },
        {
          dir: "1638766714259/1638766728769",
          file: "9fe22584-59cd-447d-9703-7f2f36a5926b.efw",
          lastModified: 1638767541000,
          logicalPath: "//API Automation_postman/Dashboard Designer_postman",
          reportPath: "1638766714259/1638766728769/9fe22584-59cd-447d-9703-7f2f36a5926b.efw",
          title: "Designer save",
        },
        {
          dir: "1638766714259/1638766733400",
          file: "ad377f79-4b43-4029-9cbd-bee4791aeb40.metadata",
          lastModified: 1638766979000,
          logicalPath: "//API Automation_postman/Metadata_postman",
          reportPath: "1638766714259/1638766733400/ad377f79-4b43-4029-9cbd-bee4791aeb40.metadata",
          title: "MD save",
        },
        {
          dir: "1638766714259/1638766733400",
          file: "36a3bfe2-6978-4dfd-bb7a-56131c4bb36b.metadata",
          lastModified: 1638766940000,
          logicalPath: "//API Automation_postman/Metadata_postman",
          reportPath: "1638766714259/1638766733400/36a3bfe2-6978-4dfd-bb7a-56131c4bb36b.metadata",
          title: "MD create after deleting Ds cache",
        },
        {
          dir: "1463377807724/1463377836985",
          file: "e9be6771-995b-40eb-a01c-304857a100a1.metadata",
          lastModified: 1638760355000,
          logicalPath: "//HI Sample Reports/Adhoc Metadata",
          reportPath: "1463377807724/1463377836985/e9be6771-995b-40eb-a01c-304857a100a1.metadata",
          title: "Sample Travel MD",
        },
        {
          dir: "1463377807724/1463377836985/1591703058466",
          file: "aa3d9571-5568-444e-9446-79ec1f53c78f.metadata",
          lastModified: 1638760355000,
          logicalPath: "//HI Sample Reports/Adhoc Metadata/Metadata View",
          reportPath:
            "1463377807724/1463377836985/1591703058466/aa3d9571-5568-444e-9446-79ec1f53c78f.metadata",
          title: "Sample View MD",
        },
        {
          dir: "1463377807724/1463377836985/1591703058466",
          file: "c32f4755-d2e3-48c0-a210-8540a6f76f84.efwdd",
          lastModified: 1623822414000,
          logicalPath: "//HI Sample Reports/Adhoc Metadata/Metadata View",
          reportPath:
            "1463377807724/1463377836985/1591703058466/c32f4755-d2e3-48c0-a210-8540a6f76f84.efwdd",
          title: "Sample Dynamic View Dashboard",
        },
        {
          dir: "1463377807724/1463377836985/1591703058466",
          file: "c32f4755-d2e3-48c0-a210-8540a6f76f84.efw",
          lastModified: 1593429776000,
          logicalPath: "//HI Sample Reports/Adhoc Metadata/Metadata View",
          reportPath:
            "1463377807724/1463377836985/1591703058466/c32f4755-d2e3-48c0-a210-8540a6f76f84.efw",
          title: "Sample Dynamic View Dashboard",
        },
        {
          dir: "1463377807724/1472805277364",
          file: "dabe0f49-2da0-48db-9772-6a51d2a5e322.efwdd",
          lastModified: 1568120233000,
          logicalPath: "//HI Sample Reports/Dashboard Designer-Drill Down",
          reportPath: "1463377807724/1472805277364/dabe0f49-2da0-48db-9772-6a51d2a5e322.efwdd",
          title: "Drill Down Dashboard",
        },
        {
          dir: "1463377807724/1472803056242",
          file: "a2b8a874-719f-46b0-b3ff-7402ffe5b484.efwdd",
          lastModified: 1568096523000,
          logicalPath: "//HI Sample Reports/DashboardDesigner-InterpanelCommunication",
          reportPath: "1463377807724/1472803056242/a2b8a874-719f-46b0-b3ff-7402ffe5b484.efwdd",
          title: "Interpanel Report",
        },
        {
          dir: "1463377807724/1473687108420",
          file: "7ae144b2-0361-4640-b985-b3d15da1f5b2.efwdd",
          lastModified: 1568096523000,
          logicalPath: "//HI Sample Reports/DashboardDesigner - Advanced Mode",
          reportPath: "1463377807724/1473687108420/7ae144b2-0361-4640-b985-b3d15da1f5b2.efwdd",
          title: "DashboardDesigner Advanced Mode Report",
        },
        {
          dir: "1463377807724/1463377836985/1472652134512",
          file: "Readme.efw",
          lastModified: 1522764118000,
          logicalPath: "//HI Sample Reports/Adhoc Metadata/Adhoc Metadata Security",
          reportPath: "1463377807724/1463377836985/1472652134512/Readme.efw",
          title: "README",
        },
        {
          dir: "1463377807724/1472805277364",
          file: "dabe0f49-2da0-48db-9772-6a51d2a5e322.efw",
          lastModified: 1522764118000,
          logicalPath: "//HI Sample Reports/Dashboard Designer-Drill Down",
          reportPath: "1463377807724/1472805277364/dabe0f49-2da0-48db-9772-6a51d2a5e322.efw",
          title: "Drill Down Report",
        },
        {
          dir: "1463377807724/1463377978248/Sample EFW Report",
          file: "sample_report.efw",
          lastModified: 1522764118000,
          logicalPath: "//HI Sample Reports/EFW Reports/Sample EFW Report",
          reportPath: "1463377807724/1463377978248/Sample EFW Report/sample_report.efw",
          title: "Sample EFW Report",
        },
        {
          dir: "1463377807724/1463377978248/Sample EFW Dashboard",
          file: "sample_dashboard.efw",
          lastModified: 1522764118000,
          logicalPath: "//HI Sample Reports/EFW Reports/Sample EFW Dashboard",
          reportPath: "1463377807724/1463377978248/Sample EFW Dashboard/sample_dashboard.efw",
          title: "Sample EFW Dashboard",
        },
        {
          dir: "1463377807724/1472803056242",
          file: "a2b8a874-719f-46b0-b3ff-7402ffe5b484.efw",
          lastModified: 1522764118000,
          logicalPath: "//HI Sample Reports/DashboardDesigner-InterpanelCommunication",
          reportPath: "1463377807724/1472803056242/a2b8a874-719f-46b0-b3ff-7402ffe5b484.efw",
          title: "Inter Panel Communication Sample",
        },
        {
          dir: "1463377807724/1473687108420",
          file: "7ae144b2-0361-4640-b985-b3d15da1f5b2.efw",
          lastModified: 1522764118000,
          logicalPath: "//HI Sample Reports/DashboardDesigner - Advanced Mode",
          reportPath: "1463377807724/1473687108420/7ae144b2-0361-4640-b985-b3d15da1f5b2.efw",
          title: "DashboardDesigner Advanced Mode Report",
        },
        {
          dir: "1463377807724/1465647380854",
          file: "3a91fae9-6d4d-48fc-a718-83f38613198f.efw",
          lastModified: 1522764118000,
          logicalPath: "//HI Sample Reports/DashboardDesigner-Sample",
          reportPath: "1463377807724/1465647380854/3a91fae9-6d4d-48fc-a718-83f38613198f.efw",
          title: "Sample Designer Report",
        },
        {
          dir: "1463377807724/1472831070841",
          file: "hwfExample.efw",
          lastModified: 1522764118000,
          logicalPath: "//HI Sample Reports/Helical Workflow - HWF - Sample",
          reportPath: "1463377807724/1472831070841/hwfExample.efw",
          title: "Helical Workflow Example",
        },
      ],
    },
  },
};

const testConnectionMock = {
  data: {
    status: 1,
    response: { message: "The connection test is successful." },
  },
};

const saveConnectionMock = {
  data: {
    status: 1,
    response: {
      message: "A new Tomcat data source is created successfully.",
      dataSourceId: 1603,
      data: {
        name: "Testing",
        id: "1603",
        type: "dynamicDataSource",
        driver: "org.apache.derby.jdbc.AutoloadedDriver",
        database: "/home/helical/Performance/hi/db/SampleTravelData",
        requestId: "",
      },
    },
  },
};

const editConnectionMock = {
  data: {
    status: 1,
    response: {
      "@baseType": "global.jdbc",
      "@id": "1",
      "@name": "SampleTravelDataDerby",
      "@type": "dynamicDataSource",
      dataSourcePoolId: "tomcat_1",
      dataSourceProvider: "tomcat",
      databaseDialect: [],
      databaseName: "/home/helical/Performance/hi/db/SampleTravelData",
      driverName: "org.apache.derby.jdbc.AutoloadedDriver",
      forceAlternateUsername: "false",
      initialSize: "1",
      jdbcInterceptors:
        "org.apache.tomcat.jdbc.pool.interceptor.ConnectionState; org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer; org.apache.tomcat.jdbc.pool.interceptor.ResetAbandonedTimer",
      jmxEnabled: "true",
      logAbandoned: "true",
      maxActive: "100",
      maxWait: "180000",
      minEvictableIdleTimeMillis: "30000",
      minIdle: "1",
      password: "hiuser",
      removeAbandoned: "true",
      removeAbandonedTimeout: "36000",
      testOnBorrow: "true",
      testOnReturn: "false",
      testWhileIdle: "false",
      timeBetweenEvictionRunsMillis: "30000",
      jdbcUrl: "jdbc:derby:/home/helical/Performance/hi/db/SampleTravelData",
      userName: "hiuser",
      validationInterval: "30000",
      validationQuery: "SELECT 1",
      visible: "true",
    },
  },
};

const updateDatasourceMock = {
  data: {
    status: 1,
    response: {
      message: "The data source is updated with the new details successfully.",
      dataSourceId: 1400,
      data: {
        name: "DerbyRetest",
        id: "1400",
        type: "dynamicDataSource",
        driver: "org.apache.derby.jdbc.AutoloadedDriver",
        database: "/home/helical/Performance/hi/db/SampleTravelData",
        requestId: "",
      },
    },
  },
};

const deleteDatasourceConnectionMock = {
  data: {
    status: 1,
    response: {
      message: " Could not delete metadata Datasource deleted successfully",
      data: { id: "1400" },
    },
  },
};

const deleteDatasourceConnectionSimpleMock = {
  data: {
    status: 1,
    response: {
      message: "The datasource 1603 have been deleted successfully",
      dataSourceId: 1603,
      data: { name: "", id: "1603", type: "dynamicDataSource" },
    },
  },
};

const errorMock = {
  data: {
    status: 0,
    response: {
      message: "Error: FormValidationException: The formData does not have logLevel information",
    },
  },
};

const dataSourceMocks = {
  dataSourceDataMock,
  reportsCountMock,
  testConnectionMock,
  saveConnectionMock,
  editConnectionMock,
  updateDatasourceMock,
  deleteDatasourceConnectionMock,
  deleteDatasourceConnectionSimpleMock,
  errorMock,
};

export default dataSourceMocks;
