package com.helicalinsight.admin.model;

import org.springframework.security.core.GrantedAuthority;

import java.util.Collection;
import java.util.List;

/**
 * this is sub class of spring framework user class, the main responsibility of
 * this class is store the details of logged in user in principal object, this
 * class properties or fields is the details which is to stored in springs
 * security principal object
 *
 * @author Muqtar Ahmed
 * @version 1.1
 * @since 1.0
 */
@SuppressWarnings("unused")
public class Principal extends org.springframework.security.core.userdetails.User {

    /**
     * this is static and final filed of serial version id automatically
     * generated by eclipse
     */

    private static final long serialVersionUID = 1L;

    /**
     * list of user profile to be stored in principal object
     */

    private List<Profile> profiles;

    /**
     * organization name to be store in principal object
     */

    private String org_name;

    /**
     * email address of user to be store in principal object
     */

    private String emailAddress;

    /**
     * user object which is to be store in principal object
     */

    private User loggedInUser;

    /**
     * Constructor with arguments
     *
     * @param username              accept user name
     * @param password              accept password
     * @param enabled               boolean check for user enabled or disabled
     * @param accountNonExpired     boolean value this will be true
     * @param credentialsNonExpired boolean value this will be true
     * @param accountNonLocked      boolean value this will be true
     * @param authorities           roles of the logged in users
     * @param profiles              list of user profiles
     * @param org_name              organization name of the user
     * @param loggedInUser          logged in user object
     */
    public Principal(String username, String password, boolean enabled, boolean accountNonExpired,
                     boolean credentialsNonExpired, boolean accountNonLocked, Collection<? extends
            GrantedAuthority> authorities, String emailAddress, List<Profile> profiles, String org_name,
                     User loggedInUser) {
        super(username, password, enabled, accountNonExpired, credentialsNonExpired, accountNonLocked, authorities);
        this.profiles = profiles;
        this.org_name = org_name;
        this.emailAddress = emailAddress;
        this.loggedInUser = loggedInUser;
    }
    
    /**
     * getter for email address
     *
     * @return email address
     */

    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * setter for email address
     *
     * @param emailAddress email address
     */

    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    /**
     * getter for list of profile object
     *
     * @return list of user profile
     */

    public List<Profile> getProfiles() {
        return profiles;
    }

    /**
     * setter for list of profile object
     *
     * @param profiles list of profile object
     */

    public void setProfiles(List<Profile> profiles) {
        this.profiles = profiles;
    }

    /**
     * getter for organization name
     *
     * @return organization name
     */

    public String getOrg_name() {
        return org_name;
    }

    /**
     * setter for organization name
     *
     * @param org_name organization name
     */

    public void setOrg_name(String org_name) {
        this.org_name = org_name;
    }

    /**
     * getter for logged in user object
     *
     * @return logged in user object
     */

    public User getLoggedInUser() {
        return loggedInUser;
    }

    /**
     * setter for logged in user object
     *
     * @param loggedInUser logged in user object
     */
    public void setLoggedInUser(User loggedInUser) {
        this.loggedInUser = loggedInUser;
    }

    /**
     *
     */
    @Override
    public String toString() {
        return "Principal [profiles=" + profiles + ", org_name=" + org_name + ", " +
                "emailAddress=" +
                emailAddress + ", loggedInUser=" + loggedInUser + "]";
    }
}
