package com.helicalinsight.admin.model;

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.helicalinsight.datasource.model.GlobalConnectionSecurity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.util.List;

/**
 * This is persistent class for role which maps it's properties with role table
 * and persist them to a database, this class's object or instance in stored in
 * role table as per rule this class should have the default constructor, as
 * well as getter and setter method's for it's properties Annotation Entity mark
 * this class as Entity Bean and annotation Table allows you to specify the
 * details of the table that will be used to persist the entity in the database.
 *
 * @author Muqtar Ahmed
 * @version 1.1
 * @since 1.0
 */
@Entity
@Table(name = "role")
public class Role implements Serializable {

    /**
     * this is static and final filed of serial version id automatically
     * generated by eclipse
     */

    private static final long serialVersionUID = 1L;

    /**
     * each entity bean have the primary key and annotate with Id generatedvalue
     * generate the automaticaly determined the most appropriate primary key
     * with strategy
     */

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /**
     * details of the column role name to which field's or properties is mapped and this property
     * should not be empty
     */

    @NotNull
    @Size(min = 1)
    private String role_name;

    /**
     * details of the column organization id to which field's or properties is
     * mapped
     */

    private Integer org_id;


    @ManyToOne
    @JoinColumn(name = "org_id", insertable = false, updatable = false)
    private Organization organization;
    
    @OneToMany(mappedBy = "roleId", cascade = CascadeType.REMOVE)
    @LazyCollection(LazyCollectionOption.TRUE)
    private List<HIResourceSecurityDB> hiResourceSecurityDBs;
    
    @OneToMany(mappedBy = "roleId", cascade = CascadeType.REMOVE)
    @LazyCollection(LazyCollectionOption.TRUE)
    private List<HIEfwdConnSecurity> hiEfwdConnSecurities;
    
    @OneToMany(mappedBy = "roleId", cascade = CascadeType.REMOVE)
    @LazyCollection(LazyCollectionOption.TRUE)
    private List<GlobalConnectionSecurity> globalConnectionSecurities;

    /**
     * default constructor
     */

    public Role() {
    }

    /**
     * over loaded constructor with two arguments role name and organization id
     *
     * @param roleName role name
     * @param org_id   organization id
     */

    public Role(String roleName, Integer org_id) {
        this.role_name = roleName;
        this.org_id = org_id;
    }

    /**
     * over loaded constructor with three arguments
     *
     * @param id       role Id
     * @param roleName role name
     * @param users    list of users
     */

    public Role(int id, String roleName, List<User> users) {
        super();
        this.id = id;
        this.role_name = roleName;
    }

    /**
     * getter method for id primary key for role table
     *
     * @return generated id
     */
    @JsonIgnore
    public int getId() {
        return id;
    }

    /**
     * setter method for id primary key for role table
     *
     * @param id generated id
     */
    @JsonProperty
    public void setId(int id) {
        this.id = id;
    }

    /**
     * getter method for role name
     *
     * @return role name
     */

    public String getRole_name() {
        return role_name;
    }

    /**
     * setter method for role name
     *
     * @param role_name role name
     */

    public void setRole_name(String role_name) {
        this.role_name = role_name;
    }




    public Integer getOrg_id() {
        return org_id;
    }

    /**
     * setter method for organization id
     *
     * @param org_id organization id
     */

    public void setOrg_id(Integer org_id) {
        this.org_id = org_id;
    }

    public Organization getOrganization() {
        return organization;
    }

    public void setOrganization(Organization organization) {
        this.organization = organization;
    }


}

