export const changeDsMockData = {
  record: {
    permissionLevel: 5,
    driver: null,
    name: "GroovyManaged",
    classifier: "efwd",
    type: "sql.jdbc.groovy.managed",
    baseType: "sql.jdbc.groovy.managed",
    data: {
      dir: "sai_ganesh",
      driverName: null,
      type: "sql.jdbc.groovy.managed",
      id: "601",
      userName: null,
      password: null,
      condition:
        'import groovy.sql.Sql;\n      import net.sf.json.JSONObject;\n      import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n      public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        if (userName.equals("hiadmin")) {\n          responseJson.put("globalId", 1);\n        }\n      \n        if (userName.equals("hiuser")) {\n          responseJson.put("globalId", 300);\n        }\n      \n        if (userName.equals("test")) {\n          responseJson.put("globalId", 4);\n        }\n      \n        responseJson.put("type", "global.jdbc");\n      \n        //throw new RuntimeException("This is a test exception" +responseJson);\n        return responseJson;\n      }',
      jdbcUrl: null,
    },
    dataSourceType: "",
    sNo: 3,
    connId: "601",
    dir: "sai_ganesh",
    key: "4zgs-knh3-a5p9-vxzb-fc",
    test: false,
  },
  allDataSourceTypes: [
    {
      name: "Access",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      name: "Amazon Dynamodb",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      name: "Amazon Redshift",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      driver: "org.apache.drill.jdbc.Driver",
      databaseDialect: "drill",
      enabledTypes: false,
      name: "Apache Drill",
      categoryName: "Big Data",
      categoryType: "big_data",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:drill:{{hostName}}:{{port}}",
      parameters: {
        port: "31010",
        hostName: "drillbit=localhost",
      },
    },
    {
      driver: "com.simba.athena.jdbc.Driver",
      databaseDialect: "athena",
      name: "Athena",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:awsathena://{{hostName}}",
      parameters: {
        hostName: "localhost",
      },
    },
    {
      driver: "ru.yandex.clickhouse.ClickHouseDriver",
      databaseDialect: "clickhouse",
      name: "Clickhouse",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:clickhouse://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "8123",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "com.databricks.client.jdbc.Driver",
      databaseDialect: "databricks",
      name: "Databricks Client",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:databricks://{{hostName}}:{{port}};{{database}}",
      parameters: {
        port: "443",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "org.apache.derby.jdbc.ClientDriver",
      databaseDialect: "derby",
      name: "Derby",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:derby://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "1527",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "org.apache.derby.jdbc.AutoloadedDriver",
      databaseDialect: "derby",
      name: "Derby",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:derby:{{database}}",
      parameters: {
        database: "database",
      },
    },
    {
      name: "Dremio",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      driver: "dynamicSwitch",
      databaseDialect: "",
      name: "DynamicSwitch",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
    },
    {
      driver: "org.elasticsearch.xpack.sql.jdbc.EsDriver",
      databaseDialect: "elasticsearchsql",
      name: "Elasticsearch",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:es://{{hostName}}",
      parameters: {
        hostName: "localhost",
      },
    },
    {
      name: "Google Bigquery",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      driver: "com.helical.mongodb.MongoJdbcDriver",
      databaseDialect: "himongo",
      name: "Helical Mongodb",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
    },
    {
      driver: "org.apache.hive.jdbc.HiveDriver",
      databaseDialect: "spark",
      name: "Hive",
      categoryName: "Big Data",
      categoryType: "big_data",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:hive2://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "10001",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "com.ibm.db2.jcc.DB2Driver",
      databaseDialect: "db2",
      name: "IBM Db2",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:db2://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "50000",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "com.informix.jdbc.IfxDriver",
      databaseDialect: "informix",
      name: "Informix",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:informix-sqli://{{hostName}}:{{port}}/{{database}}:delimident=y",
      parameters: {
        port: "1526",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "org.mariadb.jdbc.Driver",
      databaseDialect: "mysql",
      name: "Mariadb",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:mariadb://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "3306",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      name: "Microsoft Sqlserver",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      driver: "net.sourceforge.jtds.jdbc.Driver",
      databaseDialect: "sqlserver",
      name: "Microsoft Sqlserver(sourceforge)",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:jtds:sqlserver://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "1433",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "com.mysql.jdbc.Driver",
      databaseDialect: "mysql",
      name: "Mysql",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "3306",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "oracle.jdbc.OracleDriver",
      databaseDialect: "oracle",
      name: "Oracle",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:oracle:thin:@{{hostName}}:{{port}}:{{database}}",
      parameters: {
        port: "1521",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "org.postgresql.Driver",
      databaseDialect: "postgresql",
      name: "Postgresql",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:postgresql://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "5432",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "com.facebook.presto.jdbc.PrestoDriver",
      databaseDialect: "presto",
      name: "Presto",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:presto://{{hostName}}:{{port}}",
      parameters: {
        port: "8090",
        hostName: "localhost",
      },
    },
    {
      driver: "net.snowflake.client.jdbc.SnowflakeDriver",
      databaseDialect: "snowflake",
      name: "Snowflake Client",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:snowflake://{{hostName}}",
      parameters: {
        hostName: "localhost",
      },
    },
    {
      driver: "org.sqlite.JDBC",
      databaseDialect: "sqlite",
      name: "Sqlite",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:sqlite:{{database}}",
      parameters: {
        database: "database",
      },
    },
    {
      name: "Teradata",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      name: "Ξ Add Driver Ξ",
      categoryType: "supported",
      categoryName: "Supported",
    },
  ],
  dataSourceState: [
    {
      sync: false,
      id: "1",
      catSchemaPredicted: false,
      catalog: "",
      schema: "HIUSER",
      type: "dynamicDataSource",
      baseType: "global.jdbc",
      dbId: "14723",
      driver: {
        data: {
          id: "1",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.apache.derby.jdbc.AutoloadedDriver",
        name: "SampleTravelDataDerby",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
      datasourceName: "SampleTravelDataDerby",
      driverType: "Derby",
      connId: "14723",
      classifier: "db.generic",
      joinsFetched: true,
      oldDbId: "kguky",
      database: "HIUSER",
    },
    {
      sync: false,
      id: "1201",
      catSchemaPredicted: false,
      catalog: "",
      schema: "",
      type: "dynamicDataSource",
      baseType: "global.jdbc",
      dbId: "14724",
      driver: {
        data: {
          id: "1201",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.sqlite.JDBC",
        name: "SampleTravelData",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
      datasourceName: "SampleTravelData",
      driverType: "Sqlite",
      connId: "14724",
      classifier: "db.generic",
      joinsFetched: true,
      oldDbId: "d7n4k",
      isExistedDS: true,
    },
  ],
  activeDS: "14723",
  allDataSources: [
    {
      permissionLevel: 5,
      driver: "dynamicSwitch",
      name: "Groovy 1",
      classifier: "efwd",
      type: "sql.jdbc.groovy.managed",
      baseType: "sql.jdbc.groovy.managed",
      data: {
        dir: "Gagan",
        driverName: null,
        type: "sql.jdbc.groovy.managed",
        id: "1",
        userName: null,
        password: null,
        condition:
          'import groovy.sql.Sql;\n      import net.sf.json.JSONObject;\n      import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n      public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        if (userName.equals("hiadmin")) {\n          responseJson.put("globalId", 1001);\n        }\n      \n        if (userName.equals("hiuser")) {\n          responseJson.put("globalId", 3);\n        }\n      \n        if (userName.equals("test")) {\n          responseJson.put("globalId", 4);\n        }\n      \n        responseJson.put("type", "global.jdbc");\n      \n        //throw new RuntimeException("This is a test exception" +responseJson);\n        return responseJson;\n      }',
        jdbcUrl: null,
        driver: "dynamicSwitch",
      },
      dataSourceType: "",
    },
    {
      permissionLevel: 5,
      driver: "dynamicSwitch",
      name: "6148b",
      classifier: "efwd",
      type: "sql.jdbc.groovy.managed",
      baseType: "sql.jdbc.groovy.managed",
      data: {
        dir: "03_03",
        driverName: null,
        type: "sql.jdbc.groovy.managed",
        id: "801",
        userName: null,
        password: null,
        condition:
          'import groovy.sql.Sql;\n      import net.sf.json.JSONObject;\n      import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n      public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        if (userName.equals("hiadmin")) {\n          responseJson.put("globalId", 1);\n        }\n      \n        if (userName.equals("hiuser")) {\n          responseJson.put("globalId", 1001);\n        }\n      \n        if (userName.equals("test")) {\n          responseJson.put("globalId", 4);\n        }\n      \n        responseJson.put("type", "global.jdbc");\n      \n        //throw new RuntimeException("This is a test exception" +responseJson);\n        return responseJson;\n      }',
        jdbcUrl: null,
        driver: "dynamicSwitch",
      },
      dataSourceType: "",
    },
    {
      permissionLevel: 5,
      driver: "org.apache.derby.jdbc.AutoloadedDriver",
      name: "Plain Jdbc",
      classifier: "efwd",
      type: "sql.jdbc",
      baseType: "sql.jdbc",
      data: {
        dir: "datasources",
        driverName: "org.apache.derby.jdbc.AutoloadedDriver",
        type: "sql.jdbc",
        id: "501",
        userName: "hiuser",
        password: "hiuser",
        jdbcUrl: "jdbc:derby:/home/helical/Performance/hi/db/SampleTravelData",
      },
      dataSourceType: "Plain Jdbc DataSource",
    },
    {
      permissionLevel: 5,
      driver: "dynamicSwitch",
      name: "GroovyManaged",
      classifier: "efwd",
      type: "sql.jdbc.groovy.managed",
      baseType: "sql.jdbc.groovy.managed",
      data: {
        dir: "sai_ganesh",
        driverName: null,
        type: "sql.jdbc.groovy.managed",
        id: "601",
        userName: null,
        password: null,
        condition:
          'import groovy.sql.Sql;\n      import net.sf.json.JSONObject;\n      import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n      public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        if (userName.equals("hiadmin")) {\n          responseJson.put("globalId", 1);\n        }\n      \n        if (userName.equals("hiuser")) {\n          responseJson.put("globalId", 300);\n        }\n      \n        if (userName.equals("test")) {\n          responseJson.put("globalId", 4);\n        }\n      \n        responseJson.put("type", "global.jdbc");\n      \n        //throw new RuntimeException("This is a test exception" +responseJson);\n        return responseJson;\n      }',
        jdbcUrl: null,
        driver: "dynamicSwitch",
      },
      dataSourceType: "",
    },
    {
      permissionLevel: 5,
      driver: "org.apache.derby.jdbc.AutoloadedDriver",
      name: "5722",
      classifier: "efwd",
      type: "sql.jdbc",
      baseType: "sql.jdbc",
      data: {
        dir: "sai_ganesh",
        driverName: "org.apache.derby.jdbc.AutoloadedDriver",
        type: "sql.jdbc",
        id: "701",
        userName: "hiuser",
        password: "hiuser",
        jdbcUrl: "jdbc:derby:/home/helical/Performance/hi/db/SampleTravelData",
      },
      dataSourceType: "Plain Jdbc DataSource",
    },
    {
      data: {
        id: "1",
        type: "dynamicDataSource",
      },
      dataSourceProvider: "tomcat",
      type: "dynamicDataSource",
      permissionLevel: 5,
      driver: "org.apache.derby.jdbc.AutoloadedDriver",
      name: "SampleTravelDataDerby",
      classifier: "global",
      dataSourceType: "Managed DataSource",
    },
    {
      data: {
        id: "1000",
        type: "dynamicDataSource",
      },
      dataSourceProvider: "tomcat",
      type: "dynamicDataSource",
      permissionLevel: 5,
      driver: "org.apache.derby.jdbc.AutoloadedDriver",
      name: "hiee",
      classifier: "global",
      dataSourceType: "Managed DataSource",
    },
    {
      data: {
        id: "1001",
        type: "dynamicDataSource",
      },
      dataSourceProvider: "tomcat",
      type: "dynamicDataSource",
      permissionLevel: 5,
      driver: "org.postgresql.Driver",
      name: "booking",
      classifier: "global",
      dataSourceType: "Managed DataSource",
    },
    {
      data: {
        id: "1101",
        type: "dynamicDataSource",
      },
      dataSourceProvider: "tomcat",
      type: "dynamicDataSource",
      permissionLevel: 5,
      driver: "org.apache.derby.jdbc.AutoloadedDriver",
      name: "derby2",
      classifier: "global",
      dataSourceType: "Managed DataSource",
    },
    {
      data: {
        id: "1201",
        type: "dynamicDataSource",
      },
      dataSourceProvider: "tomcat",
      type: "dynamicDataSource",
      permissionLevel: 5,
      driver: "org.sqlite.JDBC",
      name: "SampleTravelData",
      classifier: "global",
      dataSourceType: "Managed DataSource",
    },
    {
      data: {
        id: "1302",
        type: "dynamicDataSource",
      },
      dataSourceProvider: "tomcat",
      type: "dynamicDataSource",
      permissionLevel: 5,
      driver: "org.sqlite.JDBC",
      name: "Sqlite",
      classifier: "global",
      dataSourceType: "Managed DataSource",
    },
    {
      data: {
        id: "1401",
        type: "dynamicDataSource",
      },
      dataSourceProvider: "tomcat",
      type: "dynamicDataSource",
      permissionLevel: 5,
      driver: "org.postgresql.Driver",
      name: "booking",
      classifier: "global",
      dataSourceType: "Managed DataSource",
    },
    {
      data: {
        id: "1801",
        type: "dynamicDataSource",
      },
      dataSourceProvider: "tomcat",
      type: "dynamicDataSource",
      permissionLevel: 5,
      driver: "org.apache.derby.jdbc.AutoloadedDriver",
      name: "Dump",
      classifier: "global",
      dataSourceType: "Managed DataSource",
    },
    {
      data: {
        id: "1901",
        type: "dynamicDataSource",
      },
      dataSourceProvider: "tomcat",
      type: "dynamicDataSource",
      permissionLevel: 5,
      driver: "net.snowflake.client.jdbc.SnowflakeDriver",
      name: "SnowflakeDS",
      classifier: "global",
      dataSourceType: "Managed DataSource",
    },
    {
      data: {
        id: "1902",
        type: "dynamicDataSource",
      },
      dataSourceProvider: "tomcat",
      type: "dynamicDataSource",
      permissionLevel: 5,
      driver: "net.snowflake.client.jdbc.SnowflakeDriver",
      name: "SnowFlakeDSWorking",
      classifier: "global",
      dataSourceType: "Managed DataSource",
    },
    {
      data: {
        id: "2001",
        type: "dynamicDataSource",
      },
      dataSourceProvider: "tomcat",
      type: "dynamicDataSource",
      permissionLevel: 5,
      driver: "oracle.jdbc.OracleDriver",
      name: "Oracle_12",
      classifier: "global",
      dataSourceType: "Managed DataSource",
    },
    {
      data: {
        id: "2101",
        type: "dynamicDataSource",
      },
      dataSourceProvider: "tomcat",
      type: "dynamicDataSource",
      permissionLevel: 5,
      driver: "com.snowflake.client.jdbc.SnowflakeDriver",
      name: "Edit",
      classifier: "global",
      dataSourceType: "Managed DataSource",
    },
    {
      data: {
        id: "2202",
        type: "dynamicDataSource",
      },
      dataSourceProvider: "tomcat",
      type: "dynamicDataSource",
      permissionLevel: 5,
      driver: "org.postgresql.Driver",
      name: "SampleTravelData",
      classifier: "global",
      dataSourceType: "Managed DataSource",
    },
    {
      data: {
        id: "2301",
        type: "dynamicDataSource",
      },
      dataSourceProvider: "tomcat",
      type: "dynamicDataSource",
      permissionLevel: 5,
      driver: "org.apache.derby.jdbc.AutoloadedDriver",
      name: "SampleTravelData",
      classifier: "global",
      dataSourceType: "Managed DataSource",
    },
    {
      data: {
        id: "2402",
        type: "dynamicDataSource",
      },
      dataSourceProvider: "tomcat",
      type: "dynamicDataSource",
      permissionLevel: 5,
      driver: "com.mysql.jdbc.Driver",
      name: "mysql",
      classifier: "global",
      dataSourceType: "Managed DataSource",
    },
    {
      data: {
        id: "2403",
        type: "dynamicDataSource",
      },
      dataSourceProvider: "tomcat",
      type: "dynamicDataSource",
      permissionLevel: 5,
      driver: "net.snowflake.client.jdbc.SnowflakeDriver",
      name: "testdata",
      classifier: "global",
      dataSourceType: "Managed DataSource",
    },
    {
      data: {
        id: "2501",
        type: "dynamicDataSource",
      },
      dataSourceProvider: "tomcat",
      type: "dynamicDataSource",
      permissionLevel: 5,
      driver: "net.snowflake.client.jdbc.SnowflakeDriver",
      name: "60045",
      classifier: "global",
      dataSourceType: "Managed DataSource",
    },
    {
      data: {
        id: "2601",
        type: "dynamicDataSource",
      },
      dataSourceProvider: "tomcat",
      type: "dynamicDataSource",
      permissionLevel: 5,
      driver: "org.apache.derby.jdbc.AutoloadedDriver",
      name: "AnotherDerby",
      classifier: "global",
      dataSourceType: "Managed DataSource",
    },
    {
      data: {
        id: "2701",
        type: "dynamicDataSource",
      },
      dataSourceProvider: "tomcat",
      type: "dynamicDataSource",
      permissionLevel: 5,
      driver: "org.elasticsearch.xpack.sql.jdbc.EsDriver",
      name: "test",
      classifier: "global",
      dataSourceType: "Managed DataSource",
    },
  ],
};

export const returnData = [
  {
    sync: false,
    id: "601",
    catSchemaPredicted: false,
    catalog: "",
    schema: "HIUSER",
    type: "sql.jdbc.groovy.managed",
    baseType: "sql.jdbc.groovy.managed",
    dbId: "14723",
    driver: {
      permissionLevel: 5,
      driver: "dynamicSwitch",
      name: "GroovyManaged",
      classifier: "efwd",
      type: "sql.jdbc.groovy.managed",
      baseType: "sql.jdbc.groovy.managed",
      data: {
        dir: "sai_ganesh",
        driverName: null,
        type: "sql.jdbc.groovy.managed",
        id: "601",
        userName: null,
        password: null,
        condition:
          'import groovy.sql.Sql;\n      import net.sf.json.JSONObject;\n      import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n      public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        if (userName.equals("hiadmin")) {\n          responseJson.put("globalId", 1);\n        }\n      \n        if (userName.equals("hiuser")) {\n          responseJson.put("globalId", 300);\n        }\n      \n        if (userName.equals("test")) {\n          responseJson.put("globalId", 4);\n        }\n      \n        responseJson.put("type", "global.jdbc");\n      \n        //throw new RuntimeException("This is a test exception" +responseJson);\n        return responseJson;\n      }',
        jdbcUrl: null,
        driver: "dynamicSwitch",
      },
      dataSourceType: "",
    },
    datasourceName: "GroovyManaged",
    driverType: "DynamicSwitch",
    connId: "14723",
    classifier: "efwd",
    joinsFetched: true,
    oldDbId: "kguky",
    database: "HIUSER",
    dir: "sai_ganesh",
    driverName: null,
    userName: null,
    password: null,
    condition:
      'import groovy.sql.Sql;\n      import net.sf.json.JSONObject;\n      import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n      public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        if (userName.equals("hiadmin")) {\n          responseJson.put("globalId", 1);\n        }\n      \n        if (userName.equals("hiuser")) {\n          responseJson.put("globalId", 300);\n        }\n      \n        if (userName.equals("test")) {\n          responseJson.put("globalId", 4);\n        }\n      \n        responseJson.put("type", "global.jdbc");\n      \n        //throw new RuntimeException("This is a test exception" +responseJson);\n        return responseJson;\n      }',
    jdbcUrl: null,
    name: "GroovyManaged",
    changed: true,
  },
  {
    sync: false,
    id: "1201",
    catSchemaPredicted: false,
    catalog: "",
    schema: "",
    type: "dynamicDataSource",
    baseType: "global.jdbc",
    dbId: "14724",
    driver: {
      data: {
        id: "1201",
        type: "dynamicDataSource",
      },
      dataSourceProvider: "tomcat",
      type: "dynamicDataSource",
      permissionLevel: 5,
      driver: "org.sqlite.JDBC",
      name: "SampleTravelData",
      classifier: "global",
      dataSourceType: "Managed DataSource",
    },
    datasourceName: "SampleTravelData",
    driverType: "Sqlite",
    connId: "14724",
    classifier: "db.generic",
    joinsFetched: true,
    oldDbId: "d7n4k",
    isExistedDS: true,
  },
];
