const dummy = [
  {
    path: "naresh",
    permissionLevel: "5",
    name: "naresh",
    lastModified: 1654596664682,
    type: "folder",
    options: {
      selectable: "true",
    },
    children: [
      {
        path: "naresh/hreport.hr",
        extension: "hr",
        permissionLevel: "5",
        name: "hreport.hr",
        description: "hreport.hr",
        lastModified: 1654601597459,
        type: "file",
        title: "hreport",
        options: {},
      },
      {
        path: "naresh/Metadata_1.metadata",
        extension: "metadata",
        permissionLevel: "5",
        name: "Metadata_1.metadata",
        description: "Metadata_1.metadata",
        lastModified: 1654596669366,
        type: "file",
        title: "Metadata_1",
        options: {},
      },
    ],
  },
  {
    path: "Gagan",
    permissionLevel: "5",
    name: "Gagan",
    lastModified: 1654588810594,
    type: "folder",
    options: {
      selectable: "true",
    },
    children: [
      {
        path: "Gagan/4812_first_saveAs.metadata",
        extension: "metadata",
        permissionLevel: "5",
        name: "4812_first_saveAs.metadata",
        description: "4812 first saveAs.metadata",
        lastModified: 1654606931147,
        type: "file",
        title: "4812 first saveAs",
        options: {},
      },
      {
        path: "Gagan/4812_first_saveAS.metadata",
        extension: "metadata",
        permissionLevel: "5",
        name: "4812_first_saveAS.metadata",
        description: "4812 first saveAS.metadata",
        lastModified: 1654606862615,
        type: "file",
        title: "4812 first saveAS",
        options: {},
      },
      {
        path: "Gagan/4812_first_save.metadata",
        extension: "metadata",
        permissionLevel: "5",
        name: "4812_first_save.metadata",
        description: "4812 first save.metadata",
        lastModified: 1654606832711,
        type: "file",
        title: "4812 first save",
        options: {},
      },
      {
        path: "Gagan/saveas.metadata",
        extension: "metadata",
        permissionLevel: "5",
        name: "saveas.metadata",
        description: "saveas.metadata",
        lastModified: 1654588995069,
        type: "file",
        title: "saveas",
        options: {},
      },
      {
        path: "Gagan/Metadata_1.metadata",
        extension: "metadata",
        permissionLevel: "5",
        name: "Metadata_1.metadata",
        description: "Metadata_1.metadata",
        lastModified: 1654588815441,
        type: "file",
        title: "Metadata_1",
        options: {},
      },
    ],
  },
];
export default dummy;
