export const mock_data = {
     result : {
        fetchSchemas: true,
        fetchCatalogs: true,
        working: true,
        connData: {
          id: "1000",
          type: "dynamicDataSource",
        },
        connId: "1000",
        dsUUID: "dbou-ter3-pxma-36r0-ee",
        classifier: "db.workflow",
        metadata: {
          catalogs: [
            {
              name: "Null",
              schemas: [
                {
                  name: "SQLJ",
                },
                {
                  name: "SYSFUN",
                },
                {
                  name: "SYSCAT",
                },
                {
                  name: "HIUSER",
                },
                {
                  name: "SYSCS_DIAG",
                },
                {
                  name: "SYSCS_UTIL",
                },
                {
                  name: "SYSIBM",
                },
                {
                  name: "APP",
                },
                {
                  name: "NULLID",
                },
                {
                  name: "SYSPROC",
                },
                {
                  name: "SYS",
                },
                {
                  name: "SYSSTAT",
                },
              ],
            },
          ],
        },
      },
       record : {
        data: {
          id: "1000",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.apache.derby.jdbc.AutoloadedDriver",
        name: "hiee",
        classifier: "global",
        dataSourceType: "Managed DataSource",
        category: "dataSource",
        children: [],
        driverType: "Derby",
        keyPath: "x5wk-lswd-km6k-g8kg-6r/dbou-ter3-pxma-36r0-ee",
        key: "dbou-ter3-pxma-36r0-ee",
        uuid: "dbou-ter3-pxma-36r0-ee",
      },
       datasourceListToRender : [
        {
          name: "Derby",
          children: [
            {
              permissionLevel: 5,
              driver: "org.apache.derby.jdbc.AutoloadedDriver",
              name: "Plain Jdbc",
              classifier: "efwd",
              type: "sql.jdbc",
              data: {
                dir: "datasources",
                driverName: "org.apache.derby.jdbc.AutoloadedDriver",
                type: "sql.jdbc",
                id: 501,
                userName: "hiuser",
                password: "hiuser",
                jdbcUrl:
                  "jdbc:derby:/home/helical/Performance/hi/db/SampleTravelData",
              },
              dataSourceType: "Plain Jdbc DataSource",
              category: "dataSource",
              children: [],
              driverType: "Derby",
              keyPath: "zdxf-u4mx-af1v-holx-t6/vw5j-v6fs-62nh-cj5u-7f",
              key: "vw5j-v6fs-62nh-cj5u-7f",
              uuid: "vw5j-v6fs-62nh-cj5u-7f",
            },
            {
              permissionLevel: 5,
              driver: "org.apache.derby.jdbc.AutoloadedDriver",
              name: "5722",
              classifier: "efwd",
              type: "sql.jdbc",
              data: {
                dir: "sai_ganesh",
                driverName: "org.apache.derby.jdbc.AutoloadedDriver",
                type: "sql.jdbc",
                id: 701,
                userName: "hiuser",
                password: "hiuser",
                jdbcUrl:
                  "jdbc:derby:/home/helical/Performance/hi/db/SampleTravelData",
              },
              dataSourceType: "Plain Jdbc DataSource",
              category: "dataSource",
              children: [],
              driverType: "Derby",
              keyPath: "zdxf-u4mx-af1v-holx-t6/cv16-tc77-omve-e450-08",
              key: "cv16-tc77-omve-e450-08",
              uuid: "cv16-tc77-omve-e450-08",
            },
            {
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "org.apache.derby.jdbc.AutoloadedDriver",
              name: "SampleTravelDataDerby",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Derby",
              keyPath: "zdxf-u4mx-af1v-holx-t6/15nf-917x-5hzm-5lxt-4x",
              key: "15nf-917x-5hzm-5lxt-4x",
              uuid: "15nf-917x-5hzm-5lxt-4x",
            },
            {
              data: {
                id: "1000",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "org.apache.derby.jdbc.AutoloadedDriver",
              name: "hiee",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [
                {
                  name: "SQLJ",
                  children: [],
                  keyPath:
                    "zdxf-u4mx-af1v-holx-t6/ww93-dfen-o6we-fnis-ul/a1i6-zpc4-86gg-ddu7-m2",
                  key: "a1i6-zpc4-86gg-ddu7-m2",
                  uuid: "a1i6-zpc4-86gg-ddu7-m2",
                  data: {
                    id: "1000",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "hiee",
                },
                {
                  name: "SYSFUN",
                  children: [],
                  keyPath:
                    "zdxf-u4mx-af1v-holx-t6/ww93-dfen-o6we-fnis-ul/l91d-tjyv-kzst-gn6r-8b",
                  key: "l91d-tjyv-kzst-gn6r-8b",
                  uuid: "l91d-tjyv-kzst-gn6r-8b",
                  data: {
                    id: "1000",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "hiee",
                },
                {
                  name: "SYSCAT",
                  children: [],
                  keyPath:
                    "zdxf-u4mx-af1v-holx-t6/ww93-dfen-o6we-fnis-ul/lcro-42r3-cy1e-1tkj-jy",
                  key: "lcro-42r3-cy1e-1tkj-jy",
                  uuid: "lcro-42r3-cy1e-1tkj-jy",
                  data: {
                    id: "1000",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "hiee",
                },
                {
                  name: "HIUSER",
                  children: [],
                  keyPath:
                    "zdxf-u4mx-af1v-holx-t6/ww93-dfen-o6we-fnis-ul/d4rp-t72i-toa1-wxlt-9z",
                  key: "d4rp-t72i-toa1-wxlt-9z",
                  uuid: "d4rp-t72i-toa1-wxlt-9z",
                  data: {
                    id: "1000",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "hiee",
                },
                {
                  name: "SYSCS_DIAG",
                  children: [],
                  keyPath:
                    "zdxf-u4mx-af1v-holx-t6/ww93-dfen-o6we-fnis-ul/n3w5-1ozt-rs6b-3ggs-c8",
                  key: "n3w5-1ozt-rs6b-3ggs-c8",
                  uuid: "n3w5-1ozt-rs6b-3ggs-c8",
                  data: {
                    id: "1000",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "hiee",
                },
                {
                  name: "SYSCS_UTIL",
                  children: [],
                  keyPath:
                    "zdxf-u4mx-af1v-holx-t6/ww93-dfen-o6we-fnis-ul/6vpj-m5vm-3fg8-wnye-aq",
                  key: "6vpj-m5vm-3fg8-wnye-aq",
                  uuid: "6vpj-m5vm-3fg8-wnye-aq",
                  data: {
                    id: "1000",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "hiee",
                },
                {
                  name: "SYSIBM",
                  children: [],
                  keyPath:
                    "zdxf-u4mx-af1v-holx-t6/ww93-dfen-o6we-fnis-ul/k03i-muf6-wdm1-r5p2-wj",
                  key: "k03i-muf6-wdm1-r5p2-wj",
                  uuid: "k03i-muf6-wdm1-r5p2-wj",
                  data: {
                    id: "1000",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "hiee",
                },
                {
                  name: "APP",
                  children: [],
                  keyPath:
                    "zdxf-u4mx-af1v-holx-t6/ww93-dfen-o6we-fnis-ul/ojdk-xfsp-74h6-15r5-fd",
                  key: "ojdk-xfsp-74h6-15r5-fd",
                  uuid: "ojdk-xfsp-74h6-15r5-fd",
                  data: {
                    id: "1000",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "hiee",
                },
                {
                  name: "NULLID",
                  children: [],
                  keyPath:
                    "zdxf-u4mx-af1v-holx-t6/ww93-dfen-o6we-fnis-ul/u0o4-uz9c-ls25-iwaw-py",
                  key: "u0o4-uz9c-ls25-iwaw-py",
                  uuid: "u0o4-uz9c-ls25-iwaw-py",
                  data: {
                    id: "1000",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "hiee",
                },
                {
                  name: "SYSPROC",
                  children: [],
                  keyPath:
                    "zdxf-u4mx-af1v-holx-t6/ww93-dfen-o6we-fnis-ul/7ac9-m63j-ab9a-kodb-rz",
                  key: "7ac9-m63j-ab9a-kodb-rz",
                  uuid: "7ac9-m63j-ab9a-kodb-rz",
                  data: {
                    id: "1000",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "hiee",
                },
                {
                  name: "SYS",
                  children: [],
                  keyPath:
                    "zdxf-u4mx-af1v-holx-t6/ww93-dfen-o6we-fnis-ul/hynn-rxge-3gzm-rsin-qe",
                  key: "hynn-rxge-3gzm-rsin-qe",
                  uuid: "hynn-rxge-3gzm-rsin-qe",
                  data: {
                    id: "1000",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "hiee",
                },
                {
                  name: "SYSSTAT",
                  children: [],
                  keyPath:
                    "zdxf-u4mx-af1v-holx-t6/ww93-dfen-o6we-fnis-ul/xlkx-b8he-1yr8-jzcu-b2",
                  key: "xlkx-b8he-1yr8-jzcu-b2",
                  uuid: "xlkx-b8he-1yr8-jzcu-b2",
                  data: {
                    id: "1000",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "hiee",
                },
              ],
              driverType: "Derby",
              keyPath: "zdxf-u4mx-af1v-holx-t6/ww93-dfen-o6we-fnis-ul",
              key: "ww93-dfen-o6we-fnis-ul",
              uuid: "ww93-dfen-o6we-fnis-ul",
              fetched: true,
            },
            {
              data: {
                id: "1101",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "org.apache.derby.jdbc.AutoloadedDriver",
              name: "derby2",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Derby",
              keyPath: "zdxf-u4mx-af1v-holx-t6/ypnb-d61u-ey8p-qcpz-mo",
              key: "ypnb-d61u-ey8p-qcpz-mo",
              uuid: "ypnb-d61u-ey8p-qcpz-mo",
            },
            {
              data: {
                id: "1801",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "org.apache.derby.jdbc.AutoloadedDriver",
              name: "Dump",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Derby",
              keyPath: "zdxf-u4mx-af1v-holx-t6/xnhn-01bu-rlmc-12jp-js",
              key: "xnhn-01bu-rlmc-12jp-js",
              uuid: "xnhn-01bu-rlmc-12jp-js",
            },
            {
              data: {
                id: "2301",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "org.apache.derby.jdbc.AutoloadedDriver",
              name: "SampleTravelData",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Derby",
              keyPath: "zdxf-u4mx-af1v-holx-t6/5jer-3kug-zt8r-uo68-dk",
              key: "5jer-3kug-zt8r-uo68-dk",
              uuid: "5jer-3kug-zt8r-uo68-dk",
            },
            {
              data: {
                id: "2601",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "org.apache.derby.jdbc.AutoloadedDriver",
              name: "AnotherDerby",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Derby",
              keyPath: "zdxf-u4mx-af1v-holx-t6/kib3-u4ol-uays-3m4b-sv",
              key: "kib3-u4ol-uays-3m4b-sv",
              uuid: "kib3-u4ol-uays-3m4b-sv",
            },
          ],
          key: "zdxf-u4mx-af1v-holx-t6",
          uuid: "zdxf-u4mx-af1v-holx-t6",
          keyPath: "zdxf-u4mx-af1v-holx-t6",
          category: "dsGroup",
          imgUrl: "images/data_sources/defaut_datasource.png",
        },
        {
          name: "DynamicSwitch",
          children: [
            {
              permissionLevel: 5,
              driver: "dynamicSwitch",
              name: "Groovy 1",
              classifier: "efwd",
              type: "sql.jdbc.groovy.managed",
              data: {
                dir: "Gagan",
                driverName: null,
                type: "sql.jdbc.groovy.managed",
                id: 1,
                userName: null,
                password: null,
                condition:
                  'import groovy.sql.Sql;\n      import net.sf.json.JSONObject;\n      import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n      public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        if (userName.equals("hiadmin")) {\n          responseJson.put("globalId", 1001);\n        }\n      \n        if (userName.equals("hiuser")) {\n          responseJson.put("globalId", 3);\n        }\n      \n        if (userName.equals("test")) {\n          responseJson.put("globalId", 4);\n        }\n      \n        responseJson.put("type", "global.jdbc");\n      \n        //throw new RuntimeException("This is a test exception" +responseJson);\n        return responseJson;\n      }',
                jdbcUrl: null,
                driver: "dynamicSwitch",
              },
              dataSourceType: "",
              category: "dataSource",
              children: [],
              driverType: "DynamicSwitch",
              keyPath: "m4ju-f1c7-b1fu-7ji5-no/lvf6-zp9c-tuxn-jd38-2a",
              key: "lvf6-zp9c-tuxn-jd38-2a",
              uuid: "lvf6-zp9c-tuxn-jd38-2a",
            },
            {
              permissionLevel: 5,
              driver: "dynamicSwitch",
              name: "6148b",
              classifier: "efwd",
              type: "sql.jdbc.groovy.managed",
              data: {
                dir: "03_03",
                driverName: null,
                type: "sql.jdbc.groovy.managed",
                id: 801,
                userName: null,
                password: null,
                condition:
                  'import groovy.sql.Sql;\n      import net.sf.json.JSONObject;\n      import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n      public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        if (userName.equals("hiadmin")) {\n          responseJson.put("globalId", 1);\n        }\n      \n        if (userName.equals("hiuser")) {\n          responseJson.put("globalId", 1001);\n        }\n      \n        if (userName.equals("test")) {\n          responseJson.put("globalId", 4);\n        }\n      \n        responseJson.put("type", "global.jdbc");\n      \n        //throw new RuntimeException("This is a test exception" +responseJson);\n        return responseJson;\n      }',
                jdbcUrl: null,
                driver: "dynamicSwitch",
              },
              dataSourceType: "",
              category: "dataSource",
              children: [],
              driverType: "DynamicSwitch",
              keyPath: "m4ju-f1c7-b1fu-7ji5-no/11hx-j57o-ajrc-qs8n-uv",
              key: "11hx-j57o-ajrc-qs8n-uv",
              uuid: "11hx-j57o-ajrc-qs8n-uv",
            },
            {
              permissionLevel: 5,
              driver: "dynamicSwitch",
              name: "GroovyManaged",
              classifier: "efwd",
              type: "sql.jdbc.groovy.managed",
              data: {
                dir: "sai_ganesh",
                driverName: null,
                type: "sql.jdbc.groovy.managed",
                id: 601,
                userName: null,
                password: null,
                condition:
                  'import groovy.sql.Sql;\n      import net.sf.json.JSONObject;\n      import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n      public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        if (userName.equals("hiadmin")) {\n          responseJson.put("globalId", 1);\n        }\n      \n        if (userName.equals("hiuser")) {\n          responseJson.put("globalId", 300);\n        }\n      \n        if (userName.equals("test")) {\n          responseJson.put("globalId", 4);\n        }\n      \n        responseJson.put("type", "global.jdbc");\n      \n        //throw new RuntimeException("This is a test exception" +responseJson);\n        return responseJson;\n      }',
                jdbcUrl: null,
                driver: "dynamicSwitch",
              },
              dataSourceType: "",
              category: "dataSource",
              children: [],
              driverType: "DynamicSwitch",
              keyPath: "m4ju-f1c7-b1fu-7ji5-no/zuoy-949h-3jds-yw9g-ou",
              key: "zuoy-949h-3jds-yw9g-ou",
              uuid: "zuoy-949h-3jds-yw9g-ou",
            },
          ],
          key: "m4ju-f1c7-b1fu-7ji5-no",
          uuid: "m4ju-f1c7-b1fu-7ji5-no",
          keyPath: "m4ju-f1c7-b1fu-7ji5-no",
          category: "dsGroup",
          imgUrl: "images/data_sources/defaut_datasource.png",
        },
        {
          name: "Elasticsearch",
          children: [
            {
              data: {
                id: "2701",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "org.elasticsearch.xpack.sql.jdbc.EsDriver",
              name: "test",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Elasticsearch",
              keyPath: "58z0-0k0w-9dd6-ruyq-h8/9fb9-v10l-tj2y-gn2q-d2",
              key: "9fb9-v10l-tj2y-gn2q-d2",
              uuid: "9fb9-v10l-tj2y-gn2q-d2",
            },
          ],
          key: "58z0-0k0w-9dd6-ruyq-h8",
          uuid: "58z0-0k0w-9dd6-ruyq-h8",
          keyPath: "58z0-0k0w-9dd6-ruyq-h8",
          category: "dsGroup",
          imgUrl: "images/data_sources/defaut_datasource.png",
        },
        {
          name: "Mysql",
          children: [
            {
              data: {
                id: "2402",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "com.mysql.jdbc.Driver",
              name: "mysql",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Mysql",
              keyPath: "gjnv-dm28-ynip-vtxz-ql/8g3w-uj2t-8u42-raj0-g0",
              key: "8g3w-uj2t-8u42-raj0-g0",
              uuid: "8g3w-uj2t-8u42-raj0-g0",
            },
          ],
          key: "gjnv-dm28-ynip-vtxz-ql",
          uuid: "gjnv-dm28-ynip-vtxz-ql",
          keyPath: "gjnv-dm28-ynip-vtxz-ql",
          category: "dsGroup",
          imgUrl: "images/data_sources/defaut_datasource.png",
        },
        {
          name: "Oracle",
          children: [
            {
              data: {
                id: "2001",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "oracle.jdbc.OracleDriver",
              name: "Oracle_12",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Oracle",
              keyPath: "ygft-b775-se2q-i7d9-lj/mb0t-saax-z05x-98sh-t6",
              key: "mb0t-saax-z05x-98sh-t6",
              uuid: "mb0t-saax-z05x-98sh-t6",
            },
          ],
          key: "ygft-b775-se2q-i7d9-lj",
          uuid: "ygft-b775-se2q-i7d9-lj",
          keyPath: "ygft-b775-se2q-i7d9-lj",
          category: "dsGroup",
          imgUrl: "images/data_sources/defaut_datasource.png",
        },
        {
          name: "Postgresql",
          children: [
            {
              data: {
                id: "1001",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "org.postgresql.Driver",
              name: "booking",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Postgresql",
              keyPath: "ivun-xfd0-mmuc-mxvh-hg/me5s-2he3-bkjr-3t05-27",
              key: "me5s-2he3-bkjr-3t05-27",
              uuid: "me5s-2he3-bkjr-3t05-27",
            },
            {
              data: {
                id: "1401",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "org.postgresql.Driver",
              name: "booking",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Postgresql",
              keyPath: "ivun-xfd0-mmuc-mxvh-hg/pqba-52pn-3hmn-uckq-al",
              key: "pqba-52pn-3hmn-uckq-al",
              uuid: "pqba-52pn-3hmn-uckq-al",
            },
            {
              data: {
                id: "2202",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "org.postgresql.Driver",
              name: "SampleTravelData",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Postgresql",
              keyPath: "ivun-xfd0-mmuc-mxvh-hg/w5kq-xeoj-lr9v-zdr4-la",
              key: "w5kq-xeoj-lr9v-zdr4-la",
              uuid: "w5kq-xeoj-lr9v-zdr4-la",
            },
          ],
          key: "ivun-xfd0-mmuc-mxvh-hg",
          uuid: "ivun-xfd0-mmuc-mxvh-hg",
          keyPath: "ivun-xfd0-mmuc-mxvh-hg",
          category: "dsGroup",
          imgUrl: "images/data_sources/defaut_datasource.png",
        },
        {
          name: "Snowflake Client",
          children: [
            {
              data: {
                id: "1901",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "net.snowflake.client.jdbc.SnowflakeDriver",
              name: "SnowflakeDS",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Snowflake Client",
              keyPath: "uxn6-emts-27y4-of2h-nh/yjgq-2b21-4wum-as4c-ce",
              key: "yjgq-2b21-4wum-as4c-ce",
              uuid: "yjgq-2b21-4wum-as4c-ce",
            },
            {
              data: {
                id: "1902",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "net.snowflake.client.jdbc.SnowflakeDriver",
              name: "SnowFlakeDSWorking",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Snowflake Client",
              keyPath: "uxn6-emts-27y4-of2h-nh/oajb-x5bd-nj7y-zcbn-0b",
              key: "oajb-x5bd-nj7y-zcbn-0b",
              uuid: "oajb-x5bd-nj7y-zcbn-0b",
            },
            {
              data: {
                id: "2403",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "net.snowflake.client.jdbc.SnowflakeDriver",
              name: "testdata",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Snowflake Client",
              keyPath: "uxn6-emts-27y4-of2h-nh/ktu3-lb89-j5p9-2nq2-8c",
              key: "ktu3-lb89-j5p9-2nq2-8c",
              uuid: "ktu3-lb89-j5p9-2nq2-8c",
            },
            {
              data: {
                id: "2501",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "net.snowflake.client.jdbc.SnowflakeDriver",
              name: "60045",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Snowflake Client",
              keyPath: "uxn6-emts-27y4-of2h-nh/siw2-a9ry-vj7r-m0vm-0f",
              key: "siw2-a9ry-vj7r-m0vm-0f",
              uuid: "siw2-a9ry-vj7r-m0vm-0f",
            },
          ],
          key: "uxn6-emts-27y4-of2h-nh",
          uuid: "uxn6-emts-27y4-of2h-nh",
          keyPath: "uxn6-emts-27y4-of2h-nh",
          category: "dsGroup",
          imgUrl: "images/data_sources/defaut_datasource.png",
        },
        {
          name: "Sqlite",
          children: [
            {
              data: {
                id: "1201",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "org.sqlite.JDBC",
              name: "SampleTravelData",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Sqlite",
              keyPath: "rqr0-173l-zjox-efct-yw/9gzv-o5kq-dz5q-l3wc-s6",
              key: "9gzv-o5kq-dz5q-l3wc-s6",
              uuid: "9gzv-o5kq-dz5q-l3wc-s6",
            },
            {
              data: {
                id: "1302",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "org.sqlite.JDBC",
              name: "Sqlite",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Sqlite",
              keyPath: "rqr0-173l-zjox-efct-yw/u70b-m61b-amjy-t0ol-y8",
              key: "u70b-m61b-amjy-t0ol-y8",
              uuid: "u70b-m61b-amjy-t0ol-y8",
            },
          ],
          key: "rqr0-173l-zjox-efct-yw",
          uuid: "rqr0-173l-zjox-efct-yw",
          keyPath: "rqr0-173l-zjox-efct-yw",
          category: "dsGroup",
          imgUrl: "images/data_sources/defaut_datasource.png",
        },
      ],
     
  
      
       expectedResult : [
        {
          name: "Derby",
          children: [
            {
              permissionLevel: 5,
              driver: "org.apache.derby.jdbc.AutoloadedDriver",
              name: "Plain Jdbc",
              classifier: "efwd",
              type: "sql.jdbc",
              data: {
                dir: "datasources",
                driverName: "org.apache.derby.jdbc.AutoloadedDriver",
                type: "sql.jdbc",
                id: 501,
                userName: "hiuser",
                password: "hiuser",
                jdbcUrl:
                  "jdbc:derby:/home/helical/Performance/hi/db/SampleTravelData",
              },
              dataSourceType: "Plain Jdbc DataSource",
              category: "dataSource",
              children: [],
              driverType: "Derby",
              keyPath: "zdxf-u4mx-af1v-holx-t6/vw5j-v6fs-62nh-cj5u-7f",
              key: "vw5j-v6fs-62nh-cj5u-7f",
              uuid: "vw5j-v6fs-62nh-cj5u-7f",
            },
            {
              permissionLevel: 5,
              driver: "org.apache.derby.jdbc.AutoloadedDriver",
              name: "5722",
              classifier: "efwd",
              type: "sql.jdbc",
              data: {
                dir: "sai_ganesh",
                driverName: "org.apache.derby.jdbc.AutoloadedDriver",
                type: "sql.jdbc",
                id: 701,
                userName: "hiuser",
                password: "hiuser",
                jdbcUrl:
                  "jdbc:derby:/home/helical/Performance/hi/db/SampleTravelData",
              },
              dataSourceType: "Plain Jdbc DataSource",
              category: "dataSource",
              children: [],
              driverType: "Derby",
              keyPath: "zdxf-u4mx-af1v-holx-t6/cv16-tc77-omve-e450-08",
              key: "cv16-tc77-omve-e450-08",
              uuid: "cv16-tc77-omve-e450-08",
            },
            {
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "org.apache.derby.jdbc.AutoloadedDriver",
              name: "SampleTravelDataDerby",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Derby",
              keyPath: "zdxf-u4mx-af1v-holx-t6/15nf-917x-5hzm-5lxt-4x",
              key: "15nf-917x-5hzm-5lxt-4x",
              uuid: "15nf-917x-5hzm-5lxt-4x",
            },
            {
              data: {
                id: "1000",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "org.apache.derby.jdbc.AutoloadedDriver",
              name: "hiee",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [
                {
                  name: "SQLJ",
                  children: [],
                  keyPath:
                    "zdxf-u4mx-af1v-holx-t6/ww93-dfen-o6we-fnis-ul/a1i6-zpc4-86gg-ddu7-m2",
                  key: "a1i6-zpc4-86gg-ddu7-m2",
                  uuid: "a1i6-zpc4-86gg-ddu7-m2",
                  data: {
                    id: "1000",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "hiee",
                },
                {
                  name: "SYSFUN",
                  children: [],
                  keyPath:
                    "zdxf-u4mx-af1v-holx-t6/ww93-dfen-o6we-fnis-ul/l91d-tjyv-kzst-gn6r-8b",
                  key: "l91d-tjyv-kzst-gn6r-8b",
                  uuid: "l91d-tjyv-kzst-gn6r-8b",
                  data: {
                    id: "1000",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "hiee",
                },
                {
                  name: "SYSCAT",
                  children: [],
                  keyPath:
                    "zdxf-u4mx-af1v-holx-t6/ww93-dfen-o6we-fnis-ul/lcro-42r3-cy1e-1tkj-jy",
                  key: "lcro-42r3-cy1e-1tkj-jy",
                  uuid: "lcro-42r3-cy1e-1tkj-jy",
                  data: {
                    id: "1000",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "hiee",
                },
                {
                  name: "HIUSER",
                  children: [],
                  keyPath:
                    "zdxf-u4mx-af1v-holx-t6/ww93-dfen-o6we-fnis-ul/d4rp-t72i-toa1-wxlt-9z",
                  key: "d4rp-t72i-toa1-wxlt-9z",
                  uuid: "d4rp-t72i-toa1-wxlt-9z",
                  data: {
                    id: "1000",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "hiee",
                },
                {
                  name: "SYSCS_DIAG",
                  children: [],
                  keyPath:
                    "zdxf-u4mx-af1v-holx-t6/ww93-dfen-o6we-fnis-ul/n3w5-1ozt-rs6b-3ggs-c8",
                  key: "n3w5-1ozt-rs6b-3ggs-c8",
                  uuid: "n3w5-1ozt-rs6b-3ggs-c8",
                  data: {
                    id: "1000",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "hiee",
                },
                {
                  name: "SYSCS_UTIL",
                  children: [],
                  keyPath:
                    "zdxf-u4mx-af1v-holx-t6/ww93-dfen-o6we-fnis-ul/6vpj-m5vm-3fg8-wnye-aq",
                  key: "6vpj-m5vm-3fg8-wnye-aq",
                  uuid: "6vpj-m5vm-3fg8-wnye-aq",
                  data: {
                    id: "1000",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "hiee",
                },
                {
                  name: "SYSIBM",
                  children: [],
                  keyPath:
                    "zdxf-u4mx-af1v-holx-t6/ww93-dfen-o6we-fnis-ul/k03i-muf6-wdm1-r5p2-wj",
                  key: "k03i-muf6-wdm1-r5p2-wj",
                  uuid: "k03i-muf6-wdm1-r5p2-wj",
                  data: {
                    id: "1000",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "hiee",
                },
                {
                  name: "APP",
                  children: [],
                  keyPath:
                    "zdxf-u4mx-af1v-holx-t6/ww93-dfen-o6we-fnis-ul/ojdk-xfsp-74h6-15r5-fd",
                  key: "ojdk-xfsp-74h6-15r5-fd",
                  uuid: "ojdk-xfsp-74h6-15r5-fd",
                  data: {
                    id: "1000",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "hiee",
                },
                {
                  name: "NULLID",
                  children: [],
                  keyPath:
                    "zdxf-u4mx-af1v-holx-t6/ww93-dfen-o6we-fnis-ul/u0o4-uz9c-ls25-iwaw-py",
                  key: "u0o4-uz9c-ls25-iwaw-py",
                  uuid: "u0o4-uz9c-ls25-iwaw-py",
                  data: {
                    id: "1000",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "hiee",
                },
                {
                  name: "SYSPROC",
                  children: [],
                  keyPath:
                    "zdxf-u4mx-af1v-holx-t6/ww93-dfen-o6we-fnis-ul/7ac9-m63j-ab9a-kodb-rz",
                  key: "7ac9-m63j-ab9a-kodb-rz",
                  uuid: "7ac9-m63j-ab9a-kodb-rz",
                  data: {
                    id: "1000",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "hiee",
                },
                {
                  name: "SYS",
                  children: [],
                  keyPath:
                    "zdxf-u4mx-af1v-holx-t6/ww93-dfen-o6we-fnis-ul/hynn-rxge-3gzm-rsin-qe",
                  key: "hynn-rxge-3gzm-rsin-qe",
                  uuid: "hynn-rxge-3gzm-rsin-qe",
                  data: {
                    id: "1000",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "hiee",
                },
                {
                  name: "SYSSTAT",
                  children: [],
                  keyPath:
                    "zdxf-u4mx-af1v-holx-t6/ww93-dfen-o6we-fnis-ul/xlkx-b8he-1yr8-jzcu-b2",
                  key: "xlkx-b8he-1yr8-jzcu-b2",
                  uuid: "xlkx-b8he-1yr8-jzcu-b2",
                  data: {
                    id: "1000",
                    type: "dynamicDataSource",
                  },
                  category: "schema",
                  datasourceName: "hiee",
                },
              ],
              driverType: "Derby",
              keyPath: "zdxf-u4mx-af1v-holx-t6/ww93-dfen-o6we-fnis-ul",
              key: "ww93-dfen-o6we-fnis-ul",
              uuid: "ww93-dfen-o6we-fnis-ul",
              fetched: true,
            },
            {
              data: {
                id: "1101",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "org.apache.derby.jdbc.AutoloadedDriver",
              name: "derby2",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Derby",
              keyPath: "zdxf-u4mx-af1v-holx-t6/ypnb-d61u-ey8p-qcpz-mo",
              key: "ypnb-d61u-ey8p-qcpz-mo",
              uuid: "ypnb-d61u-ey8p-qcpz-mo",
            },
            {
              data: {
                id: "1801",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "org.apache.derby.jdbc.AutoloadedDriver",
              name: "Dump",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Derby",
              keyPath: "zdxf-u4mx-af1v-holx-t6/xnhn-01bu-rlmc-12jp-js",
              key: "xnhn-01bu-rlmc-12jp-js",
              uuid: "xnhn-01bu-rlmc-12jp-js",
            },
            {
              data: {
                id: "2301",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "org.apache.derby.jdbc.AutoloadedDriver",
              name: "SampleTravelData",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Derby",
              keyPath: "zdxf-u4mx-af1v-holx-t6/5jer-3kug-zt8r-uo68-dk",
              key: "5jer-3kug-zt8r-uo68-dk",
              uuid: "5jer-3kug-zt8r-uo68-dk",
            },
            {
              data: {
                id: "2601",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "org.apache.derby.jdbc.AutoloadedDriver",
              name: "AnotherDerby",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Derby",
              keyPath: "zdxf-u4mx-af1v-holx-t6/kib3-u4ol-uays-3m4b-sv",
              key: "kib3-u4ol-uays-3m4b-sv",
              uuid: "kib3-u4ol-uays-3m4b-sv",
            },
          ],
          key: "zdxf-u4mx-af1v-holx-t6",
          uuid: "zdxf-u4mx-af1v-holx-t6",
          keyPath: "zdxf-u4mx-af1v-holx-t6",
          category: "dsGroup",
          imgUrl: "images/data_sources/defaut_datasource.png",
        },
        {
          name: "DynamicSwitch",
          children: [
            {
              permissionLevel: 5,
              driver: "dynamicSwitch",
              name: "Groovy 1",
              classifier: "efwd",
              type: "sql.jdbc.groovy.managed",
              data: {
                dir: "Gagan",
                driverName: null,
                type: "sql.jdbc.groovy.managed",
                id: 1,
                userName: null,
                password: null,
                condition:
                  'import groovy.sql.Sql;\n      import net.sf.json.JSONObject;\n      import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n      public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        if (userName.equals("hiadmin")) {\n          responseJson.put("globalId", 1001);\n        }\n      \n        if (userName.equals("hiuser")) {\n          responseJson.put("globalId", 3);\n        }\n      \n        if (userName.equals("test")) {\n          responseJson.put("globalId", 4);\n        }\n      \n        responseJson.put("type", "global.jdbc");\n      \n        //throw new RuntimeException("This is a test exception" +responseJson);\n        return responseJson;\n      }',
                jdbcUrl: null,
                driver: "dynamicSwitch",
              },
              dataSourceType: "",
              category: "dataSource",
              children: [],
              driverType: "DynamicSwitch",
              keyPath: "m4ju-f1c7-b1fu-7ji5-no/lvf6-zp9c-tuxn-jd38-2a",
              key: "lvf6-zp9c-tuxn-jd38-2a",
              uuid: "lvf6-zp9c-tuxn-jd38-2a",
            },
            {
              permissionLevel: 5,
              driver: "dynamicSwitch",
              name: "6148b",
              classifier: "efwd",
              type: "sql.jdbc.groovy.managed",
              data: {
                dir: "03_03",
                driverName: null,
                type: "sql.jdbc.groovy.managed",
                id: 801,
                userName: null,
                password: null,
                condition:
                  'import groovy.sql.Sql;\n      import net.sf.json.JSONObject;\n      import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n      public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        if (userName.equals("hiadmin")) {\n          responseJson.put("globalId", 1);\n        }\n      \n        if (userName.equals("hiuser")) {\n          responseJson.put("globalId", 1001);\n        }\n      \n        if (userName.equals("test")) {\n          responseJson.put("globalId", 4);\n        }\n      \n        responseJson.put("type", "global.jdbc");\n      \n        //throw new RuntimeException("This is a test exception" +responseJson);\n        return responseJson;\n      }',
                jdbcUrl: null,
                driver: "dynamicSwitch",
              },
              dataSourceType: "",
              category: "dataSource",
              children: [],
              driverType: "DynamicSwitch",
              keyPath: "m4ju-f1c7-b1fu-7ji5-no/11hx-j57o-ajrc-qs8n-uv",
              key: "11hx-j57o-ajrc-qs8n-uv",
              uuid: "11hx-j57o-ajrc-qs8n-uv",
            },
            {
              permissionLevel: 5,
              driver: "dynamicSwitch",
              name: "GroovyManaged",
              classifier: "efwd",
              type: "sql.jdbc.groovy.managed",
              data: {
                dir: "sai_ganesh",
                driverName: null,
                type: "sql.jdbc.groovy.managed",
                id: 601,
                userName: null,
                password: null,
                condition:
                  'import groovy.sql.Sql;\n      import net.sf.json.JSONObject;\n      import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n      public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        if (userName.equals("hiadmin")) {\n          responseJson.put("globalId", 1);\n        }\n      \n        if (userName.equals("hiuser")) {\n          responseJson.put("globalId", 300);\n        }\n      \n        if (userName.equals("test")) {\n          responseJson.put("globalId", 4);\n        }\n      \n        responseJson.put("type", "global.jdbc");\n      \n        //throw new RuntimeException("This is a test exception" +responseJson);\n        return responseJson;\n      }',
                jdbcUrl: null,
                driver: "dynamicSwitch",
              },
              dataSourceType: "",
              category: "dataSource",
              children: [],
              driverType: "DynamicSwitch",
              keyPath: "m4ju-f1c7-b1fu-7ji5-no/zuoy-949h-3jds-yw9g-ou",
              key: "zuoy-949h-3jds-yw9g-ou",
              uuid: "zuoy-949h-3jds-yw9g-ou",
            },
          ],
          key: "m4ju-f1c7-b1fu-7ji5-no",
          uuid: "m4ju-f1c7-b1fu-7ji5-no",
          keyPath: "m4ju-f1c7-b1fu-7ji5-no",
          category: "dsGroup",
          imgUrl: "images/data_sources/defaut_datasource.png",
        },
        {
          name: "Elasticsearch",
          children: [
            {
              data: {
                id: "2701",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "org.elasticsearch.xpack.sql.jdbc.EsDriver",
              name: "test",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Elasticsearch",
              keyPath: "58z0-0k0w-9dd6-ruyq-h8/9fb9-v10l-tj2y-gn2q-d2",
              key: "9fb9-v10l-tj2y-gn2q-d2",
              uuid: "9fb9-v10l-tj2y-gn2q-d2",
            },
          ],
          key: "58z0-0k0w-9dd6-ruyq-h8",
          uuid: "58z0-0k0w-9dd6-ruyq-h8",
          keyPath: "58z0-0k0w-9dd6-ruyq-h8",
          category: "dsGroup",
          imgUrl: "images/data_sources/defaut_datasource.png",
        },
        {
          name: "Mysql",
          children: [
            {
              data: {
                id: "2402",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "com.mysql.jdbc.Driver",
              name: "mysql",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Mysql",
              keyPath: "gjnv-dm28-ynip-vtxz-ql/8g3w-uj2t-8u42-raj0-g0",
              key: "8g3w-uj2t-8u42-raj0-g0",
              uuid: "8g3w-uj2t-8u42-raj0-g0",
            },
          ],
          key: "gjnv-dm28-ynip-vtxz-ql",
          uuid: "gjnv-dm28-ynip-vtxz-ql",
          keyPath: "gjnv-dm28-ynip-vtxz-ql",
          category: "dsGroup",
          imgUrl: "images/data_sources/defaut_datasource.png",
        },
        {
          name: "Oracle",
          children: [
            {
              data: {
                id: "2001",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "oracle.jdbc.OracleDriver",
              name: "Oracle_12",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Oracle",
              keyPath: "ygft-b775-se2q-i7d9-lj/mb0t-saax-z05x-98sh-t6",
              key: "mb0t-saax-z05x-98sh-t6",
              uuid: "mb0t-saax-z05x-98sh-t6",
            },
          ],
          key: "ygft-b775-se2q-i7d9-lj",
          uuid: "ygft-b775-se2q-i7d9-lj",
          keyPath: "ygft-b775-se2q-i7d9-lj",
          category: "dsGroup",
          imgUrl: "images/data_sources/defaut_datasource.png",
        },
        {
          name: "Postgresql",
          children: [
            {
              data: {
                id: "1001",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "org.postgresql.Driver",
              name: "booking",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Postgresql",
              keyPath: "ivun-xfd0-mmuc-mxvh-hg/me5s-2he3-bkjr-3t05-27",
              key: "me5s-2he3-bkjr-3t05-27",
              uuid: "me5s-2he3-bkjr-3t05-27",
            },
            {
              data: {
                id: "1401",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "org.postgresql.Driver",
              name: "booking",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Postgresql",
              keyPath: "ivun-xfd0-mmuc-mxvh-hg/pqba-52pn-3hmn-uckq-al",
              key: "pqba-52pn-3hmn-uckq-al",
              uuid: "pqba-52pn-3hmn-uckq-al",
            },
            {
              data: {
                id: "2202",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "org.postgresql.Driver",
              name: "SampleTravelData",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Postgresql",
              keyPath: "ivun-xfd0-mmuc-mxvh-hg/w5kq-xeoj-lr9v-zdr4-la",
              key: "w5kq-xeoj-lr9v-zdr4-la",
              uuid: "w5kq-xeoj-lr9v-zdr4-la",
            },
          ],
          key: "ivun-xfd0-mmuc-mxvh-hg",
          uuid: "ivun-xfd0-mmuc-mxvh-hg",
          keyPath: "ivun-xfd0-mmuc-mxvh-hg",
          category: "dsGroup",
          imgUrl: "images/data_sources/defaut_datasource.png",
        },
        {
          name: "Snowflake Client",
          children: [
            {
              data: {
                id: "1901",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "net.snowflake.client.jdbc.SnowflakeDriver",
              name: "SnowflakeDS",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Snowflake Client",
              keyPath: "uxn6-emts-27y4-of2h-nh/yjgq-2b21-4wum-as4c-ce",
              key: "yjgq-2b21-4wum-as4c-ce",
              uuid: "yjgq-2b21-4wum-as4c-ce",
            },
            {
              data: {
                id: "1902",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "net.snowflake.client.jdbc.SnowflakeDriver",
              name: "SnowFlakeDSWorking",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Snowflake Client",
              keyPath: "uxn6-emts-27y4-of2h-nh/oajb-x5bd-nj7y-zcbn-0b",
              key: "oajb-x5bd-nj7y-zcbn-0b",
              uuid: "oajb-x5bd-nj7y-zcbn-0b",
            },
            {
              data: {
                id: "2403",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "net.snowflake.client.jdbc.SnowflakeDriver",
              name: "testdata",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Snowflake Client",
              keyPath: "uxn6-emts-27y4-of2h-nh/ktu3-lb89-j5p9-2nq2-8c",
              key: "ktu3-lb89-j5p9-2nq2-8c",
              uuid: "ktu3-lb89-j5p9-2nq2-8c",
            },
            {
              data: {
                id: "2501",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "net.snowflake.client.jdbc.SnowflakeDriver",
              name: "60045",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Snowflake Client",
              keyPath: "uxn6-emts-27y4-of2h-nh/siw2-a9ry-vj7r-m0vm-0f",
              key: "siw2-a9ry-vj7r-m0vm-0f",
              uuid: "siw2-a9ry-vj7r-m0vm-0f",
            },
          ],
          key: "uxn6-emts-27y4-of2h-nh",
          uuid: "uxn6-emts-27y4-of2h-nh",
          keyPath: "uxn6-emts-27y4-of2h-nh",
          category: "dsGroup",
          imgUrl: "images/data_sources/defaut_datasource.png",
        },
        {
          name: "Sqlite",
          children: [
            {
              data: {
                id: "1201",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "org.sqlite.JDBC",
              name: "SampleTravelData",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Sqlite",
              keyPath: "rqr0-173l-zjox-efct-yw/9gzv-o5kq-dz5q-l3wc-s6",
              key: "9gzv-o5kq-dz5q-l3wc-s6",
              uuid: "9gzv-o5kq-dz5q-l3wc-s6",
            },
            {
              data: {
                id: "1302",
                type: "dynamicDataSource",
              },
              dataSourceProvider: "tomcat",
              type: "dynamicDataSource",
              permissionLevel: 5,
              driver: "org.sqlite.JDBC",
              name: "Sqlite",
              classifier: "global",
              dataSourceType: "Managed DataSource",
              category: "dataSource",
              children: [],
              driverType: "Sqlite",
              keyPath: "rqr0-173l-zjox-efct-yw/u70b-m61b-amjy-t0ol-y8",
              key: "u70b-m61b-amjy-t0ol-y8",
              uuid: "u70b-m61b-amjy-t0ol-y8",
            },
          ],
          key: "rqr0-173l-zjox-efct-yw",
          uuid: "rqr0-173l-zjox-efct-yw",
          keyPath: "rqr0-173l-zjox-efct-yw",
          category: "dsGroup",
          imgUrl: "images/data_sources/defaut_datasource.png",
        },
      ]

}