import { checkInvalidJoins } from "../../../../../components/hi-metadata/utils/joins/utils";

describe("checkInvalidJoins", () => {
  test("should return invalid joins", () => {
    const joins = [
      {
        type: "inner",
        operator: "=",
        left: {
          table: "CACHE",
          column: "CONNECTION_ID",
          tableId: "9d0d7c2d929cc2f20de2c45f70b9640f",
          columnId: "3096a079-cb28-4c0c-90c3-5cced0f09ed0",
          dbId: "af1nv",
          isValid: true,
        },
        right: {
          table: "CACHE",
          column: "CONNECTION_ID",
          tableId: "9d0d7c2d929cc2f20de2c45f70b9640f",
          columnId: "3096a079-cb28-4c0c-90c3-5cced0f09ed0",
          dbId: "af1nv",
          isValid: true,
        },
        key: "s617-eq94-r5cf-8vds-cj",
        uuid: "s617-eq94-r5cf-8vds-cj",
        action: "add",
        index: 1,
        leftColumn: "CACHE.CONNECTION_ID",
        rightColumn: "CACHE.CONNECTION_ID",
      },
      {
        type: "inner",
        operator: "=",
        left: {
          table: "CACHE",
          column: "CACHE_ID",
          tableId: "9d0d7c2d929cc2f20de2c45f70b9640f",
          columnId: "e2ac4564-486f-4b05-a3c3-b3ad75b334d1",
          dbId: "af1nv",
          isValid: true,
        },
        right: {
          table: "CACHE",
          column: "CACHE_ID",
          tableId: "9d0d7c2d929cc2f20de2c45f70b9640f",
          columnId: "e2ac4564-486f-4b05-a3c3-b3ad75b334d1",
          dbId: "af1nv",
          isValid: true,
        },
        key: "pxey-uvah-ckjm-rych-td",
        uuid: "pxey-uvah-ckjm-rych-td",
        action: "add",
        index: 2,
        leftColumn: "CACHE.CACHE_ID",
        rightColumn: "CACHE.CACHE_ID",
      },
      {
        type: "left",
        operator: "=",
        left: {
          table: "CACHE",
          column: "CONNECTION_ID",
          tableId: "9d0d7c2d929cc2f20de2c45f70b9640f",
          columnId: "3096a079-cb28-4c0c-90c3-5cced0f09ed0",
          dbId: "af1nv",
          isValid: true,
        },
        right: {
          table: "CACHE",
          column: "CONNECTION_ID",
          tableId: "9d0d7c2d929cc2f20de2c45f70b9640f",
          columnId: "3096a079-cb28-4c0c-90c3-5cced0f09ed0",
          dbId: "af1nv",
          isValid: true,
        },
        key: "ccgx-3aix-qb11-dwkb-49",
        uuid: "ccgx-3aix-qb11-dwkb-49",
        action: "add",
        index: 3,
        leftColumn: "CACHE.CONNECTION_ID",
        rightColumn: "CACHE.CONNECTION_ID",
      },
      {
        type: "full",
        operator: "=",
        left: {
          table: "CACHE",
          column: "CACHE_ID",
          tableId: "9d0d7c2d929cc2f20de2c45f70b9640f",
          columnId: "e2ac4564-486f-4b05-a3c3-b3ad75b334d1",
          dbId: "af1nv",
          isValid: true,
        },
        right: {
          table: "CACHE",
          column: "CACHE_FILE_PATH",
          tableId: "9d0d7c2d929cc2f20de2c45f70b9640f",
          columnId: "4d8c3079-9e98-485f-8d91-6f334d4d8590",
          dbId: "af1nv",
          isValid: true,
        },
        key: "crmf-aj6f-jpwq-coqf-1o",
        uuid: "crmf-aj6f-jpwq-coqf-1o",
        action: "add",
        index: 4,
        leftColumn: "CACHE.CACHE_ID",
        rightColumn: "CACHE.CACHE_FILE_PATH",
      },
    ];
    const tables = {
      CACHE: {
        id: "9d0d7c2d929cc2f20de2c45f70b9640f",
        name: "CACHE",
        alias: "CACHE",
        dataSource: {
          id: "1000",
          type: "dynamicDataSource",
          baseType: "global.jdbc",
          catSchemaPredicted: false,
          sync: false,
          catalog: "",
          schema: "HIUSER",
          connId: "af1nv",
          dbId: "af1nv",
          classifier: "db.workflow",
          datasourceName: "hiee",
          dsKeyPath:
            "ug3t-hqng-xvjp-piwt-pv/ymuy-o245-nnwd-z1m9-lz/mg4n-jckw-bjnd-19ts-pa",
          driverType: "Derby",
          database: "HIUSER",
        },
        category: "table",
        connId: "af1nv",
        keyPath:
          "ug3t-hqng-xvjp-piwt-pv/ymuy-o245-nnwd-z1m9-lz/mg4n-jckw-bjnd-19ts-pa/n7zf-1axf-msb7-qoer-x5",
        uniqueKey: "9d0d7c2d929cc2f20de2c45f70b9640f_af1nv",
        schema: "HIUSER",
        selected: true,
        keyName: "CACHE",
        columns: {
          CACHE_ID: {
            alias: "CACHE_ID",
            fullyQualifiedColumn: "CACHE.CACHE_ID",
            id: "e2ac4564-486f-4b05-a3c3-b3ad75b334d1",
            defaultFunction: "db.generic.aggregate.sum",
            type: {
              "java.lang.Long": "numeric",
            },
            category: "column",
            uniqueKey: "e2ac4564-486f-4b05-a3c3-b3ad75b334d1_af1nv",
            name: "CACHE_ID",
            tableKey: "CACHE",
            connId: "af1nv",
            columnKey: "CACHE_ID",
            tableId: "9d0d7c2d929cc2f20de2c45f70b9640f",
          },
          CACHE_FILE_EXPIRY: {
            alias: "CACHE_FILE_EXPIRY",
            fullyQualifiedColumn: "CACHE.CACHE_FILE_EXPIRY",
            id: "a1deeb4d-f015-45f0-8e15-d4b33464d2c4",
            defaultFunction: "db.generic.groupBy.group",
            type: {
              "java.sql.Timestamp": "dateTime",
            },
            category: "column",
            uniqueKey: "a1deeb4d-f015-45f0-8e15-d4b33464d2c4_af1nv",
            name: "CACHE_FILE_EXPIRY",
            tableKey: "CACHE",
            connId: "af1nv",
            columnKey: "CACHE_FILE_EXPIRY",
            tableId: "9d0d7c2d929cc2f20de2c45f70b9640f",
          },
          CACHE_FILE_PATH: {
            alias: "CACHE_FILE_PATH",
            fullyQualifiedColumn: "CACHE.CACHE_FILE_PATH",
            id: "4d8c3079-9e98-485f-8d91-6f334d4d8590",
            defaultFunction: "db.generic.groupBy.group",
            type: {
              "java.lang.String": "text",
            },
            category: "column",
            uniqueKey: "4d8c3079-9e98-485f-8d91-6f334d4d8590_af1nv",
            name: "CACHE_FILE_PATH",
            tableKey: "CACHE",
            connId: "af1nv",
            columnKey: "CACHE_FILE_PATH",
            tableId: "9d0d7c2d929cc2f20de2c45f70b9640f",
          },
          CACHE_FILE_SIZE: {
            alias: "CACHE_FILE_SIZE",
            fullyQualifiedColumn: "CACHE.CACHE_FILE_SIZE",
            id: "8d62613f-0ddf-4b43-a27c-6d62bfca8997",
            defaultFunction: "db.generic.aggregate.sum",
            type: {
              "java.lang.Long": "numeric",
            },
            category: "column",
            uniqueKey: "8d62613f-0ddf-4b43-a27c-6d62bfca8997_af1nv",
            name: "CACHE_FILE_SIZE",
            tableKey: "CACHE",
            connId: "af1nv",
            columnKey: "CACHE_FILE_SIZE",
            tableId: "9d0d7c2d929cc2f20de2c45f70b9640f",
          },
          CACHE_FILE_TIME_STAMP: {
            alias: "CACHE_FILE_TIME_STAMP",
            fullyQualifiedColumn: "CACHE.CACHE_FILE_TIME_STAMP",
            id: "225b0b6b-3fe4-4165-a006-c29da12fd221",
            defaultFunction: "db.generic.groupBy.group",
            type: {
              "java.sql.Timestamp": "dateTime",
            },
            category: "column",
            uniqueKey: "225b0b6b-3fe4-4165-a006-c29da12fd221_af1nv",
            name: "CACHE_FILE_TIME_STAMP",
            tableKey: "CACHE",
            connId: "af1nv",
            columnKey: "CACHE_FILE_TIME_STAMP",
            tableId: "9d0d7c2d929cc2f20de2c45f70b9640f",
          },
          CONNECTION_FILE_PATH: {
            alias: "CONNECTION_FILE_PATH",
            fullyQualifiedColumn: "CACHE.CONNECTION_FILE_PATH",
            id: "ccc0fe63-5120-42bb-af60-608429291144",
            defaultFunction: "db.generic.groupBy.group",
            type: {
              "java.lang.String": "text",
            },
            category: "column",
            uniqueKey: "ccc0fe63-5120-42bb-af60-608429291144_af1nv",
            name: "CONNECTION_FILE_PATH",
            tableKey: "CACHE",
            connId: "af1nv",
            columnKey: "CONNECTION_FILE_PATH",
            tableId: "9d0d7c2d929cc2f20de2c45f70b9640f",
          },
          CONNECTION_TYPE: {
            alias: "CONNECTION_TYPE",
            fullyQualifiedColumn: "CACHE.CONNECTION_TYPE",
            id: "14a15cda-3245-4602-96c3-986fb822f2bd",
            defaultFunction: "db.generic.groupBy.group",
            type: {
              "java.lang.String": "text",
            },
            category: "column",
            uniqueKey: "14a15cda-3245-4602-96c3-986fb822f2bd_af1nv",
            name: "CONNECTION_TYPE",
            tableKey: "CACHE",
            connId: "af1nv",
            columnKey: "CONNECTION_TYPE",
            tableId: "9d0d7c2d929cc2f20de2c45f70b9640f",
          },
          MAP_ID: {
            alias: "MAP_ID",
            fullyQualifiedColumn: "CACHE.MAP_ID",
            id: "1b15b2a7-24b5-4e42-9e9d-ccee5ab748f1",
            defaultFunction: "db.generic.aggregate.sum",
            type: {
              "java.lang.Integer": "numeric",
            },
            category: "column",
            uniqueKey: "1b15b2a7-24b5-4e42-9e9d-ccee5ab748f1_af1nv",
            name: "MAP_ID",
            tableKey: "CACHE",
            connId: "af1nv",
            columnKey: "MAP_ID",
            tableId: "9d0d7c2d929cc2f20de2c45f70b9640f",
          },
          NO_OF_RECORDS: {
            alias: "NO_OF_RECORDS",
            fullyQualifiedColumn: "CACHE.NO_OF_RECORDS",
            id: "cfbbdc24-5a45-4fa8-b66c-4695200e12ee",
            defaultFunction: "db.generic.aggregate.sum",
            type: {
              "java.lang.Integer": "numeric",
            },
            category: "column",
            uniqueKey: "cfbbdc24-5a45-4fa8-b66c-4695200e12ee_af1nv",
            name: "NO_OF_RECORDS",
            tableKey: "CACHE",
            connId: "af1nv",
            columnKey: "NO_OF_RECORDS",
            tableId: "9d0d7c2d929cc2f20de2c45f70b9640f",
          },
          REPORT_PARAMETERS: {
            alias: "REPORT_PARAMETERS",
            fullyQualifiedColumn: "CACHE.REPORT_PARAMETERS",
            id: "791c2067-a5ed-41e1-86c6-18a2aa207761",
            defaultFunction: "db.generic.groupBy.group",
            type: {
              "java.lang.String": "text",
            },
            category: "column",
            uniqueKey: "791c2067-a5ed-41e1-86c6-18a2aa207761_af1nv",
            name: "REPORT_PARAMETERS",
            tableKey: "CACHE",
            connId: "af1nv",
            columnKey: "REPORT_PARAMETERS",
            tableId: "9d0d7c2d929cc2f20de2c45f70b9640f",
          },
          PRIORITY: {
            alias: "PRIORITY",
            fullyQualifiedColumn: "CACHE.PRIORITY",
            id: "d4190d56-6ccf-4819-85ca-4c22fdfcccda",
            defaultFunction: "db.generic.aggregate.sum",
            type: {
              "java.lang.Integer": "numeric",
            },
            category: "column",
            uniqueKey: "d4190d56-6ccf-4819-85ca-4c22fdfcccda_af1nv",
            name: "PRIORITY",
            tableKey: "CACHE",
            connId: "af1nv",
            columnKey: "PRIORITY",
            tableId: "9d0d7c2d929cc2f20de2c45f70b9640f",
          },
          QUERY: {
            alias: "QUERY",
            fullyQualifiedColumn: "CACHE.QUERY",
            id: "95219607-afa0-4c65-bb9b-d43516ba2dc1",
            defaultFunction: "db.generic.groupBy.group",
            type: {
              "java.lang.String": "text",
            },
            category: "column",
            uniqueKey: "95219607-afa0-4c65-bb9b-d43516ba2dc1_af1nv",
            name: "QUERY",
            tableKey: "CACHE",
            connId: "af1nv",
            columnKey: "QUERY",
            tableId: "9d0d7c2d929cc2f20de2c45f70b9640f",
          },
          STATUS: {
            alias: "STATUS",
            fullyQualifiedColumn: "CACHE.STATUS",
            id: "821fa757-ebe9-490a-be17-9488cae6b82a",
            defaultFunction: "db.generic.groupBy.group",
            type: {
              "java.lang.String": "text",
            },
            category: "column",
            uniqueKey: "821fa757-ebe9-490a-be17-9488cae6b82a_af1nv",
            name: "STATUS",
            tableKey: "CACHE",
            connId: "af1nv",
            columnKey: "STATUS",
            tableId: "9d0d7c2d929cc2f20de2c45f70b9640f",
          },
        },
        columnsFetched: true,
      },
    };

    const invalidJoins = checkInvalidJoins(joins, tables);
    let expectedResult = [
      {
        action: "add",
        index: 1,
        key: "s617-eq94-r5cf-8vds-cj",
        left: {
          column: "CONNECTION_ID",
          columnId: "3096a079-cb28-4c0c-90c3-5cced0f09ed0",
          dbId: "af1nv",
          isValid: true,
          table: "CACHE",
          tableId: "9d0d7c2d929cc2f20de2c45f70b9640f",
        },
        leftColumn: "CACHE.CONNECTION_ID",
        operator: "=",
        right: {
          column: "CONNECTION_ID",
          columnId: "3096a079-cb28-4c0c-90c3-5cced0f09ed0",
          dbId: "af1nv",
          isValid: true,
          table: "CACHE",
          tableId: "9d0d7c2d929cc2f20de2c45f70b9640f",
        },
        rightColumn: "CACHE.CONNECTION_ID",
        type: "inner",
        uuid: "s617-eq94-r5cf-8vds-cj",
      },
      {
        action: "add",
        index: 3,
        key: "ccgx-3aix-qb11-dwkb-49",
        left: {
          column: "CONNECTION_ID",
          columnId: "3096a079-cb28-4c0c-90c3-5cced0f09ed0",
          dbId: "af1nv",
          isValid: true,
          table: "CACHE",
          tableId: "9d0d7c2d929cc2f20de2c45f70b9640f",
        },
        leftColumn: "CACHE.CONNECTION_ID",
        operator: "=",
        right: {
          column: "CONNECTION_ID",
          columnId: "3096a079-cb28-4c0c-90c3-5cced0f09ed0",
          dbId: "af1nv",
          isValid: true,
          table: "CACHE",
          tableId: "9d0d7c2d929cc2f20de2c45f70b9640f",
        },
        rightColumn: "CACHE.CONNECTION_ID",
        type: "left",
        uuid: "ccgx-3aix-qb11-dwkb-49",
      },
    ];
    expect(invalidJoins).toEqual(expectedResult);
  });
});
