package com.helicalinsight.datasource;

import com.google.gson.Gson;
import com.google.gson.JsonObject;
import com.helicalinsight.datasource.managed.JdbcServiceImpl;
import com.helicalinsight.callback.CallBack;
import com.helicalinsight.datasource.managed.IJdbcService;
import com.helicalinsight.efw.ApplicationProperties;
import com.helicalinsight.efw.utility.JsonUtils;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import java.sql.ResultSet;

/**
 * EfwdService implements {@link IEfwdService}
 * Class is responsible to generate Sql Query and get result in the form of JsonObject and {@code java.sql.ResultSet} form.
 * Created by author on 17-Jan-15.
 * @author Rajasekhar
 */
@Component
@Scope("prototype")
public class EfwdService implements IEfwdService {
    private static final Logger logger = LoggerFactory.getLogger(EfwdService.class);

    @Autowired
    private EfwdQueryProcessor efwdQueryProcessor;

    @Autowired
    private EfwdServiceUtility efwdServiceUtility;

    @Autowired
    private IJdbcService jdbcService;
    private Integer limit;
    private String processedLimitQuery;
    /**
     * execute(@NotNull String httpRequestJson, String connectionDetails,
                              @NotNull String dataMapTagContent, @NotNull ApplicationProperties applicationProperties)
     * This method is responsible for execution of sql query and gets the result  in jsonObject form.
     * @param  httpRequestJson						request parameter json
     * @param  connectionDetails                    Driver connection details
     * @param  dataMapTagContent					content of the data map tag of efwd
     * @param  applicationProperties                instance which holds the application settings details
     * @return result of the SQL query as a JsonObject. 
     * 
     */
    @Nullable
    @Override
    public JsonObject execute(@NotNull String httpRequestJson, String connectionDetails,
                              @NotNull String dataMapTagContent, @NotNull ApplicationProperties applicationProperties) {

        QueryContext context = prepareQueryContext(httpRequestJson, connectionDetails, dataMapTagContent, applicationProperties);
        JsonObject result = this.jdbcService.execute(context.connectionsFilePath, context.connectionId, context.sqlQuery);
        if (logger.isDebugEnabled()) {
            logger.debug("The query has been successfully executed on the data source with the " + "given data map id");
        }
        return result;
    }
    /**
     * executeForResultSet(@NotNull String httpRequestJson, String connectionDetails,
                                         @NotNull String dataMapTagContent, @NotNull ApplicationProperties applicationProperties)
     * Method returns the result of sql query generated by using parameters in {@code java.sql.ResultSet} form.
     * @param  httpRequestJson         request parameters
     * @param  connectionDetails       Driver connection details   
     * @param  dataMapTagContent       efwd content
     * @param  applicationProperties   it holds the details of application setting.
     * @return it returns sql query result in ResultSet form.
     */
    @Nullable
    @Override
    public ResultSet executeForResultSet(@NotNull String httpRequestJson, String connectionDetails,
                                         @NotNull String dataMapTagContent, @NotNull ApplicationProperties applicationProperties) {

        QueryContext context = prepareQueryContext(httpRequestJson, connectionDetails, dataMapTagContent, applicationProperties);
        ResultSet result = this.jdbcService.executeForResultSet(context.connectionsFilePath, context.connectionId, context.sqlQuery);
        if (logger.isDebugEnabled()) {
            logger.debug("The query has been successfully executed on the data source with the " + "given data map id");
        }
        return result;
    }

    public String getProcessedLimitQuery() {
        return processedLimitQuery;
    }

	public void setProcessedLimitQuery(String processedLimitQuery) {
        this.processedLimitQuery = processedLimitQuery;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }
    
    @Nullable
    @Override
    public void streamForResultSet(@NotNull String httpRequestJson, String connectionDetails,
                                         @NotNull String dataMapTagContent, @NotNull ApplicationProperties applicationProperties, CallBack<ResultSet> callBack) {
        QueryContext context = prepareQueryContext(httpRequestJson, connectionDetails, dataMapTagContent, applicationProperties);
         this.jdbcService.streamForResultSet(context.connectionsFilePath, context.connectionId, context.sqlQuery, callBack);
        if (logger.isDebugEnabled()) {
            logger.debug("The query has been successfully executed on the data source with the " + "given data map id");
        }
    }

    
    private QueryContext prepareQueryContext(@NotNull String httpRequestJson, String connectionDetails,
            @NotNull String dataMapTagContent, @NotNull ApplicationProperties applicationProperties) {
    	JsonObject connection = new Gson().fromJson(connectionDetails, JsonObject.class);
        Efwd efwd;
        if(connection.has("@type"))
        	efwd= this.efwdServiceUtility.getEfwd(connectionDetails);
        else
        	efwd= this.efwdServiceUtility.getEfwd2(connectionDetails);        	

        int connectionId = efwd.getGlobalId();
        String sqlQuery;
        JsonObject dataMapFromEfwd=new Gson().fromJson(dataMapTagContent,JsonObject.class);
        if(dataMapFromEfwd.has("Query"))
        	sqlQuery= this.efwdQueryProcessor.getQuery(dataMapFromEfwd,
        			new Gson().fromJson(httpRequestJson, JsonObject.class));
        else
        	sqlQuery= this.efwdQueryProcessor.getQuery2(dataMapFromEfwd,
        			new Gson().fromJson(httpRequestJson, JsonObject.class));        	
        String connectionsFilePath = JsonUtils.getGlobalConnectionsPath();
        if (limit != null && (jdbcService instanceof JdbcServiceImpl)) {
            ((JdbcServiceImpl) jdbcService).setLimit(limit);
            if (processedLimitQuery != null) {
                sqlQuery = processedLimitQuery;
            }
        }
        return new QueryContext(connectionId, connectionsFilePath, sqlQuery);
    }
    
    
    private static class QueryContext {
        int connectionId;
        String connectionsFilePath;
        String sqlQuery;

        QueryContext(int connectionId, String connectionsFilePath, String sqlQuery) {
            this.connectionId = connectionId;
            this.connectionsFilePath = connectionsFilePath;
            this.sqlQuery = sqlQuery;
        }
    }
}
