export const storeData = {
  dataFetchedFor: {
    getDatasource: true,
    joins: false,
    viewSessionVariables: false,
    listDataSources: true,
    "89tg-10z4-jrde-jle5-vb": false,
    "pigx-hibm-6z49-xw82-ou": false,
  },
  loadingStatus: {
    getDatasource: true,
    listDataSources: true,
    "89tg-10z4-jrde-jle5-vb": false,
    "pigx-hibm-6z49-xw82-ou": false,
  },
  joinsLoadingStatus: "",
  serviceErrorStatus: {},
  fetchedDSInfo: {},
  listDataSource: [],
  supportedDataSourceTypes: [
    {
      name: "Access",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      name: "Amazon Dynamodb",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      name: "Amazon Redshift",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      name: "Dremio",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      name: "Google Bigquery",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      name: "Microsoft Sqlserver",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      name: "Oracle",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      name: "Teradata",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      name: "Ξ Add Driver Ξ",
      categoryType: "supported",
      categoryName: "Supported",
    },
  ],
  allDataSourceTypes: [
    {
      name: "Access",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      name: "Amazon Dynamodb",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      name: "Amazon Redshift",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      driver: "org.apache.drill.jdbc.Driver",
      databaseDialect: "drill",
      enabledTypes: true,
      name: "Apache Drill",
      categoryName: "Big Data",
      categoryType: "big_data",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:drill:{{hostName}}:{{port}}",
      parameters: {
        port: "31010",
        hostName: "drillbit=localhost",
      },
    },
    {
      driver: "com.simba.athena.jdbc.Driver",
      databaseDialect: "athena",
      name: "Athena",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:awsathena://{{hostName}}",
      parameters: {
        hostName: "localhost",
      },
    },
    {
      driver: "ru.yandex.clickhouse.ClickHouseDriver",
      databaseDialect: "clickhouse",
      name: "Clickhouse",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:clickhouse://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "8123",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "com.databricks.client.jdbc.Driver",
      databaseDialect: "databricks",
      name: "Databricks Client",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:databricks://{{hostName}}:{{port}};{{database}}",
      parameters: {
        port: "443",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "org.apache.derby.jdbc.ClientDriver",
      databaseDialect: "derby",
      name: "Derby",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:derby://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "1527",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "org.apache.derby.jdbc.AutoloadedDriver",
      databaseDialect: "derby",
      name: "Derby",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:derby:{{database}}",
      parameters: {
        database: "database",
      },
    },
    {
      name: "Dremio",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      driver: "dynamicSwitch",
      databaseDialect: "",
      name: "DynamicSwitch",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
    },
    {
      driver: "org.elasticsearch.xpack.sql.jdbc.EsDriver",
      databaseDialect: "",
      name: "Elasticsearch",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
    },
    {
      name: "Google Bigquery",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      driver: "com.helical.mongodb.MongoJdbcDriver",
      databaseDialect: "himongo",
      name: "Helical Mongodb",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
    },
    {
      driver: "org.apache.hive.jdbc.HiveDriver",
      databaseDialect: "spark",
      name: "Hive",
      categoryName: "Big Data",
      categoryType: "big_data",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:hive2://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "10001",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "com.ibm.db2.jcc.DB2Driver",
      databaseDialect: "db2",
      name: "IBM Db2",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:db2://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "50000",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "com.informix.jdbc.IfxDriver",
      databaseDialect: "informix",
      name: "Informix",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:informix-sqli://{{hostName}}:{{port}}/{{database}}:delimident=y",
      parameters: {
        port: "1526",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "org.mariadb.jdbc.Driver",
      databaseDialect: "mysql",
      name: "Mariadb",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:mariadb://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "3306",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      name: "Microsoft Sqlserver",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      driver: "net.sourceforge.jtds.jdbc.Driver",
      databaseDialect: "sqlserver",
      name: "Microsoft Sqlserver(sourceforge)",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:jtds:sqlserver://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "1433",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      name: "Mongodb",
      classifier: "global",
      categoryName: "No SQL & Big Data",
      categoryType: "nosql_bigdata",
      type: "global.jdbc",
      driver: "com.helicalinsight.nosql.mongo",
      url: "mongodb://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "27017",
        hostName: "localhost",
        database: "database",
        collection: "collection",
        sslPort: "3345",
      },
      dataSourceProvider: "noSql",
    },
    {
      driver: "com.mysql.jdbc.Driver",
      databaseDialect: "mysql",
      name: "Mysql",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "3306",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "com.mysql.cj.jdbc.Driver",
      databaseDialect: "mysql",
      name: "Mysql Cj",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "3306",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      name: "Oracle",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      driver: "org.postgresql.Driver",
      databaseDialect: "postgresql",
      name: "Postgresql",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:postgresql://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "5432",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "com.facebook.presto.jdbc.PrestoDriver",
      databaseDialect: "presto",
      name: "Presto",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:presto://{{hostName}}:{{port}}",
      parameters: {
        port: "8090",
        hostName: "localhost",
      },
    },
    {
      driver: "org.sqlite.JDBC",
      databaseDialect: "sqlite",
      name: "Sqlite",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:sqlite:{{database}}",
      parameters: {
        database: "database",
      },
    },
    {
      name: "Teradata",
      categoryType: "supported",
      categoryName: "Supported",
    },
    {
      name: "Ξ Add Driver Ξ",
      categoryType: "supported",
      categoryName: "Supported",
    },
  ],
  metaDataSourceList: [
    {
      driver: "org.apache.drill.jdbc.Driver",
      databaseDialect: "drill",
      enabledTypes: true,
      name: "Apache Drill",
      categoryName: "Big Data",
      categoryType: "big_data",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:drill:{{hostName}}:{{port}}",
      parameters: {
        port: "31010",
        hostName: "drillbit=localhost",
      },
    },
    {
      driver: "com.simba.athena.jdbc.Driver",
      databaseDialect: "athena",
      name: "Athena",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:awsathena://{{hostName}}",
      parameters: {
        hostName: "localhost",
      },
    },
    {
      driver: "ru.yandex.clickhouse.ClickHouseDriver",
      databaseDialect: "clickhouse",
      name: "Clickhouse",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:clickhouse://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "8123",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "com.databricks.client.jdbc.Driver",
      databaseDialect: "databricks",
      name: "Databricks Client",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:databricks://{{hostName}}:{{port}};{{database}}",
      parameters: {
        port: "443",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "org.apache.derby.jdbc.ClientDriver",
      databaseDialect: "derby",
      name: "Derby",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:derby://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "1527",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "org.apache.derby.jdbc.AutoloadedDriver",
      databaseDialect: "derby",
      name: "Derby",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:derby:{{database}}",
      parameters: {
        database: "database",
      },
    },
    {
      driver: "dynamicSwitch",
      databaseDialect: "",
      name: "DynamicSwitch",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
    },
    {
      driver: "org.elasticsearch.xpack.sql.jdbc.EsDriver",
      databaseDialect: "",
      name: "Elasticsearch",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
    },
    {
      driver: "com.helical.mongodb.MongoJdbcDriver",
      databaseDialect: "himongo",
      name: "Helical Mongodb",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
    },
    {
      driver: "org.apache.hive.jdbc.HiveDriver",
      databaseDialect: "spark",
      name: "Hive",
      categoryName: "Big Data",
      categoryType: "big_data",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:hive2://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "10001",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "com.ibm.db2.jcc.DB2Driver",
      databaseDialect: "db2",
      name: "IBM Db2",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:db2://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "50000",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "com.informix.jdbc.IfxDriver",
      databaseDialect: "informix",
      name: "Informix",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:informix-sqli://{{hostName}}:{{port}}/{{database}}:delimident=y",
      parameters: {
        port: "1526",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "org.mariadb.jdbc.Driver",
      databaseDialect: "mysql",
      name: "Mariadb",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:mariadb://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "3306",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "net.sourceforge.jtds.jdbc.Driver",
      databaseDialect: "sqlserver",
      name: "Microsoft Sqlserver(sourceforge)",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:jtds:sqlserver://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "1433",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      name: "Mongodb",
      classifier: "global",
      categoryName: "No SQL & Big Data",
      categoryType: "nosql_bigdata",
      type: "global.jdbc",
      driver: "com.helicalinsight.nosql.mongo",
      url: "mongodb://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "27017",
        hostName: "localhost",
        database: "database",
        collection: "collection",
        sslPort: "3345",
      },
      dataSourceProvider: "noSql",
    },
    {
      driver: "com.mysql.jdbc.Driver",
      databaseDialect: "mysql",
      name: "Mysql",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "3306",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "com.mysql.cj.jdbc.Driver",
      databaseDialect: "mysql",
      name: "Mysql Cj",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "3306",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "org.postgresql.Driver",
      databaseDialect: "postgresql",
      name: "Postgresql",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:postgresql://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "5432",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      driver: "com.facebook.presto.jdbc.PrestoDriver",
      databaseDialect: "presto",
      name: "Presto",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:presto://{{hostName}}:{{port}}",
      parameters: {
        port: "8090",
        hostName: "localhost",
      },
    },
    {
      driver: "org.sqlite.JDBC",
      databaseDialect: "sqlite",
      name: "Sqlite",
      categoryName: "RDBMS",
      categoryType: "rdbms",
      type: "global.jdbc",
      dataSourceProvider: "tomcat",
      classifier: "global",
      imgUrl: "../images/data_sources/defaut_datasource.png",
      url: "jdbc:sqlite:{{database}}",
      parameters: {
        database: "database",
      },
    },
  ],
  driversList: [
    {
      driver: "com.helicalinsight.nosql.mongo",
      available: "true",
      url: "mongodb://{{hostName}}:{{port}}/{{database}}",
      parameters: {
        port: "27017",
        hostName: "localhost",
        database: "database",
        collection: "collection",
        sslPort: "3345",
      },
    },
    {
      driver: "dynamicSwitch",
      showInDatasource: "false",
      available: "true",
      parameters: [],
    },
    {
      url: "jdbc:derby:{{database}}",
      driver: "org.apache.derby.jdbc.AutoloadedDriver",
      available: "true",
      parameters: {
        database: "database",
      },
    },
    {
      url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
      driver: "com.mysql.cj.jdbc.Driver",
      available: "true",
      parameters: {
        port: "3306",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      url: "jdbc:mysql://{{hostName}}:{{port}}/{{database}}",
      driver: "com.mysql.jdbc.Driver",
      available: "true",
      parameters: {
        port: "3306",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      available: "true",
      driver: "org.elasticsearch.xpack.sql.jdbc.EsDriver",
    },
    {
      url: "jdbc:awsathena://{{hostName}}",
      driver: "com.simba.athena.jdbc.Driver",
      available: "true",
      parameters: {
        hostName: "localhost",
      },
    },
    {
      url: "jdbc:jtds:sqlserver://{{hostName}}:{{port}}/{{database}}",
      driver: "net.sourceforge.jtds.jdbc.Driver",
      available: "true",
      parameters: {
        port: "1433",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      url: "jdbc:clickhouse://{{hostName}}:{{port}}/{{database}}",
      driver: "ru.yandex.clickhouse.ClickHouseDriver",
      available: "true",
      parameters: {
        port: "8123",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      url: "jdbc:postgresql://{{hostName}}:{{port}}/{{database}}",
      driver: "org.postgresql.Driver",
      available: "true",
      parameters: {
        port: "5432",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      available: "true",
      driver: "com.helical.mongodb.MongoJdbcDriver",
    },
    {
      url: "jdbc:hive2://{{hostName}}:{{port}}/{{database}}",
      driver: "org.apache.hive.jdbc.HiveDriver",
      available: "true",
      parameters: {
        port: "10001",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      url: "jdbc:drill:{{hostName}}:{{port}}",
      driver: "org.apache.drill.jdbc.Driver",
      available: "true",
      parameters: {
        port: "31010",
        hostName: "drillbit=localhost",
      },
    },
    {
      url: "jdbc:informix-sqli://{{hostName}}:{{port}}/{{database}}:delimident=y",
      driver: "com.informix.jdbc.IfxDriver",
      available: "true",
      parameters: {
        port: "1526",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      url: "jdbc:db2://{{hostName}}:{{port}}/{{database}}",
      driver: "com.ibm.db2.jcc.DB2Driver",
      available: "true",
      parameters: {
        port: "50000",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      url: "jdbc:mariadb://{{hostName}}:{{port}}/{{database}}",
      driver: "org.mariadb.jdbc.Driver",
      available: "true",
      parameters: {
        port: "3306",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      url: "jdbc:presto://{{hostName}}:{{port}}",
      driver: "com.facebook.presto.jdbc.PrestoDriver",
      available: "true",
      parameters: {
        port: "8090",
        hostName: "localhost",
      },
    },
    {
      url: "jdbc:databricks://{{hostName}}:{{port}};{{database}}",
      driver: "com.databricks.client.jdbc.Driver",
      available: "true",
      parameters: {
        port: "443",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      available: "true",
      driver: "org.elasticsearch.xpack.sql.jdbc.EsDriver",
    },
    {
      url: "jdbc:postgresql://{{hostName}}:{{port}}/{{database}}",
      driver: "org.postgresql.Driver",
      available: "true",
      parameters: {
        port: "5432",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      url: "jdbc:derby://{{hostName}}:{{port}}/{{database}}",
      driver: "org.apache.derby.jdbc.ClientDriver",
      available: "true",
      parameters: {
        port: "1527",
        hostName: "localhost",
        database: "database",
      },
    },
    {
      url: "jdbc:sqlite:{{database}}",
      driver: "org.sqlite.JDBC",
      available: "true",
      parameters: {
        database: "database",
      },
    },
  ],
  allDataSources: [
    {
      permissionLevel: 5,
      driver: "dynamicSwitch",
      name: "Groovy 1",
      classifier: "efwd",
      type: "sql.jdbc.groovy.managed",
      data: {
        dir: "Gagan",
        driverName: null,
        type: "sql.jdbc.groovy.managed",
        id: 1,
        userName: null,
        password: null,
        condition:
          'import groovy.sql.Sql;\n      import net.sf.json.JSONObject;\n      import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n      public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        if (userName.equals("hiadmin")) {\n          responseJson.put("globalId", 1001);\n        }\n      \n        if (userName.equals("hiuser")) {\n          responseJson.put("globalId", 3);\n        }\n      \n        if (userName.equals("test")) {\n          responseJson.put("globalId", 4);\n        }\n      \n        responseJson.put("type", "global.jdbc");\n      \n        //throw new RuntimeException("This is a test exception" +responseJson);\n        return responseJson;\n      }',
        jdbcUrl: null,
        driver: "dynamicSwitch",
      },
      dataSourceType: "",
    },
    {
      permissionLevel: 5,
      driver: "dynamicSwitch",
      name: "Groovy 1",
      classifier: "efwd",
      type: "sql.jdbc.groovy.managed",
      data: {
        dir: "Gagan",
        driverName: null,
        type: "sql.jdbc.groovy.managed",
        id: 1,
        userName: null,
        password: null,
        condition:
          'import groovy.sql.Sql;\n      import net.sf.json.JSONObject;\n      import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n      public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        if (userName.equals("hiadmin")) {\n          responseJson.put("globalId", 1001);\n        }\n      \n        if (userName.equals("hiuser")) {\n          responseJson.put("globalId", 3);\n        }\n      \n        if (userName.equals("test")) {\n          responseJson.put("globalId", 4);\n        }\n      \n        responseJson.put("type", "global.jdbc");\n      \n        //throw new RuntimeException("This is a test exception" +responseJson);\n        return responseJson;\n      }',
        jdbcUrl: null,
        driver: "dynamicSwitch",
      },
      dataSourceType: "",
    },
    {
      data: {
        id: "1",
        type: "dynamicDataSource",
      },
      dataSourceProvider: "tomcat",
      type: "dynamicDataSource",
      permissionLevel: 2,
      driver: "org.apache.derby.jdbc.AutoloadedDriver",
      name: "SampleTravelDataDerby",
      classifier: "global",
      dataSourceType: "Managed DataSource",
    },
    {
      data: {
        id: "1000",
        type: "dynamicDataSource",
      },
      dataSourceProvider: "tomcat",
      type: "dynamicDataSource",
      permissionLevel: 2,
      driver: "org.apache.derby.jdbc.AutoloadedDriver",
      name: "hiee",
      classifier: "global",
      dataSourceType: "Managed DataSource",
    },
    {
      data: {
        id: "1001",
        type: "dynamicDataSource",
      },
      dataSourceProvider: "tomcat",
      type: "dynamicDataSource",
      permissionLevel: 5,
      driver: "org.postgresql.Driver",
      name: "booking",
      classifier: "global",
      dataSourceType: "Managed DataSource",
    },
    {
      data: {
        id: "1101",
        type: "dynamicDataSource",
      },
      dataSourceProvider: "tomcat",
      type: "dynamicDataSource",
      permissionLevel: 5,
      driver: "org.apache.derby.jdbc.AutoloadedDriver",
      name: "derby2",
      classifier: "global",
      dataSourceType: "Managed DataSource",
    },
    {
      data: {
        id: "1201",
        type: "dynamicDataSource",
      },
      dataSourceProvider: "tomcat",
      type: "dynamicDataSource",
      permissionLevel: 5,
      driver: "org.sqlite.JDBC",
      name: "SampleTravelData",
      classifier: "global",
      dataSourceType: "Managed DataSource",
    },
    {
      data: {
        id: "1302",
        type: "dynamicDataSource",
      },
      dataSourceProvider: "tomcat",
      type: "dynamicDataSource",
      permissionLevel: 5,
      driver: "org.sqlite.JDBC",
      name: "Sqlite",
      classifier: "global",
      dataSourceType: "Managed DataSource",
    },
    {
      data: {
        id: "1401",
        type: "dynamicDataSource",
      },
      dataSourceProvider: "tomcat",
      type: "dynamicDataSource",
      permissionLevel: 5,
      driver: "org.postgresql.Driver",
      name: "booking",
      classifier: "global",
      dataSourceType: "Managed DataSource",
    },
    {
      data: {
        id: "1801",
        type: "dynamicDataSource",
      },
      dataSourceProvider: "tomcat",
      type: "dynamicDataSource",
      permissionLevel: 5,
      driver: "org.apache.derby.jdbc.AutoloadedDriver",
      name: "Dump",
      classifier: "global",
      dataSourceType: "Managed DataSource",
    },
  ],
  dataSourceTypes: [
    {
      type: "sql.jdbc.groovy.managed",
      name: "Groovy Managed Jdbc DataSource",
      classifier: "efwd",
      categoryName: "advanced",
      categoryType: "advanced",
    },
    {
      type: "sql.jdbc.groovy",
      name: "Groovy Plain Jdbc DataSource",
      classifier: "efwd",
      categoryName: "advanced",
      categoryType: "advanced",
    },
    {
      type: "global.jdbc",
      name: "Managed DataSource",
      classifier: "global",
      categoryName: "advanced",
      categoryType: "advanced",
    },
    {
      type: "sql.jdbc",
      name: "Plain Jdbc DataSource",
      classifier: "efwd",
      categoryName: "advanced",
      categoryType: "advanced",
    },
  ],
  datasourceListToRender: [
    {
      name: "Derby",
      children: [
        {
          data: {
            id: "1",
            type: "dynamicDataSource",
          },
          dataSourceProvider: "tomcat",
          type: "dynamicDataSource",
          permissionLevel: 2,
          driver: "org.apache.derby.jdbc.AutoloadedDriver",
          name: "SampleTravelDataDerby",
          classifier: "global",
          dataSourceType: "Managed DataSource",
          category: "dataSource",
          children: [
            {
              name: "SQLJ",
              children: [],
              keyPath:
                "ns2s-01o7-7onv-d8wc-cx/89tg-10z4-jrde-jle5-vb/cycw-5uuo-em17-2ik2-db",
              key: "cycw-5uuo-em17-2ik2-db",
              uuid: "cycw-5uuo-em17-2ik2-db",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
            },
            {
              name: "SYSFUN",
              children: [],
              keyPath:
                "ns2s-01o7-7onv-d8wc-cx/89tg-10z4-jrde-jle5-vb/8wlb-u1fl-nt3h-xghs-6l",
              key: "8wlb-u1fl-nt3h-xghs-6l",
              uuid: "8wlb-u1fl-nt3h-xghs-6l",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
            },
            {
              name: "SYSCAT",
              children: [],
              keyPath:
                "ns2s-01o7-7onv-d8wc-cx/89tg-10z4-jrde-jle5-vb/l4xr-c13q-1zl6-40rn-in",
              key: "l4xr-c13q-1zl6-40rn-in",
              uuid: "l4xr-c13q-1zl6-40rn-in",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
            },
            {
              name: "HIUSER",
              children: [
                {
                  id: "4ac5d9f68b58bd7c0d179146e46795be",
                  name: "dimdate",
                  data: {
                    id: "1",
                    type: "dynamicDataSource",
                  },
                  keyPath:
                    "ns2s-01o7-7onv-d8wc-cx/89tg-10z4-jrde-jle5-vb/pigx-hibm-6z49-xw82-ou/itsg-xcqu-setw-yj1w-lx",
                  key: "itsg-xcqu-setw-yj1w-lx",
                  alias: "dimdate",
                  uuid: "itsg-xcqu-setw-yj1w-lx",
                  connId: "5dv9o",
                  dataSource: {
                    id: "1",
                    type: "dynamicDataSource",
                    baseType: "global.jdbc",
                    catSchemaPredicted: false,
                    sync: false,
                    catalog: "",
                    schema: "HIUSER",
                    connId: "5dv9o",
                    classifier: "db.workflow",
                    datasourceName: "SampleTravelDataDerby",
                    dsKeyPath:
                      "ns2s-01o7-7onv-d8wc-cx/89tg-10z4-jrde-jle5-vb/pigx-hibm-6z49-xw82-ou",
                    driverType: "Derby",
                    database: "HIUSER",
                  },
                  dataSourceName: "SampleTravelDataDerby",
                  category: "table",
                  nameWithConnId: "dimdate_5dv9o",
                  database: "HIUSER",
                  schema: "HIUSER",
                  selected: true,
                },
                {
                  id: "4e1fd245f4d13b77be423a43f01d80b2",
                  name: "employee_details",
                  data: {
                    id: "1",
                    type: "dynamicDataSource",
                  },
                  keyPath:
                    "ns2s-01o7-7onv-d8wc-cx/89tg-10z4-jrde-jle5-vb/pigx-hibm-6z49-xw82-ou/sa5g-9y71-77ct-ju84-sr",
                  key: "sa5g-9y71-77ct-ju84-sr",
                  alias: "employee_details",
                  uuid: "sa5g-9y71-77ct-ju84-sr",
                  connId: "5dv9o",
                  dataSource: {
                    id: "1",
                    type: "dynamicDataSource",
                    baseType: "global.jdbc",
                    catSchemaPredicted: false,
                    sync: false,
                    catalog: "",
                    schema: "HIUSER",
                    connId: "5dv9o",
                    classifier: "db.workflow",
                    datasourceName: "SampleTravelDataDerby",
                    dsKeyPath:
                      "ns2s-01o7-7onv-d8wc-cx/89tg-10z4-jrde-jle5-vb/pigx-hibm-6z49-xw82-ou",
                    driverType: "Derby",
                    database: "HIUSER",
                  },
                  dataSourceName: "SampleTravelDataDerby",
                  category: "table",
                  nameWithConnId: "employee_details_5dv9o",
                  database: "HIUSER",
                  schema: "HIUSER",
                  selected: false,
                },
                {
                  id: "be534112989b616b194bc59c2fb25a42",
                  name: "geo_cordinates",
                  data: {
                    id: "1",
                    type: "dynamicDataSource",
                  },
                  keyPath:
                    "ns2s-01o7-7onv-d8wc-cx/89tg-10z4-jrde-jle5-vb/pigx-hibm-6z49-xw82-ou/8eav-dfol-9rtq-er21-0k",
                  key: "8eav-dfol-9rtq-er21-0k",
                  alias: "geo_cordinates",
                  uuid: "8eav-dfol-9rtq-er21-0k",
                  connId: "5dv9o",
                  dataSource: {
                    id: "1",
                    type: "dynamicDataSource",
                    baseType: "global.jdbc",
                    catSchemaPredicted: false,
                    sync: false,
                    catalog: "",
                    schema: "HIUSER",
                    connId: "5dv9o",
                    classifier: "db.workflow",
                    datasourceName: "SampleTravelDataDerby",
                    dsKeyPath:
                      "ns2s-01o7-7onv-d8wc-cx/89tg-10z4-jrde-jle5-vb/pigx-hibm-6z49-xw82-ou",
                    driverType: "Derby",
                    database: "HIUSER",
                  },
                  dataSourceName: "SampleTravelDataDerby",
                  category: "table",
                  nameWithConnId: "geo_cordinates_5dv9o",
                  database: "HIUSER",
                  schema: "HIUSER",
                  selected: false,
                },
                {
                  id: "9645c648a1c0dbeec1287aaf1e996db3",
                  name: "meeting_details",
                  data: {
                    id: "1",
                    type: "dynamicDataSource",
                  },
                  keyPath:
                    "ns2s-01o7-7onv-d8wc-cx/89tg-10z4-jrde-jle5-vb/pigx-hibm-6z49-xw82-ou/i88c-g1qd-mmkb-fl8o-qa",
                  key: "i88c-g1qd-mmkb-fl8o-qa",
                  alias: "meeting_details",
                  uuid: "i88c-g1qd-mmkb-fl8o-qa",
                  connId: "5dv9o",
                  dataSource: {
                    id: "1",
                    type: "dynamicDataSource",
                    baseType: "global.jdbc",
                    catSchemaPredicted: false,
                    sync: false,
                    catalog: "",
                    schema: "HIUSER",
                    connId: "5dv9o",
                    classifier: "db.workflow",
                    datasourceName: "SampleTravelDataDerby",
                    dsKeyPath:
                      "ns2s-01o7-7onv-d8wc-cx/89tg-10z4-jrde-jle5-vb/pigx-hibm-6z49-xw82-ou",
                    driverType: "Derby",
                    database: "HIUSER",
                  },
                  dataSourceName: "SampleTravelDataDerby",
                  category: "table",
                  nameWithConnId: "meeting_details_5dv9o",
                  database: "HIUSER",
                  schema: "HIUSER",
                  selected: false,
                },
                {
                  id: "8a28627d07d04ef096d9935f12e0c7e9",
                  name: "travel_details",
                  data: {
                    id: "1",
                    type: "dynamicDataSource",
                  },
                  keyPath:
                    "ns2s-01o7-7onv-d8wc-cx/89tg-10z4-jrde-jle5-vb/pigx-hibm-6z49-xw82-ou/y3sc-b3rz-7r19-3zky-c3",
                  key: "y3sc-b3rz-7r19-3zky-c3",
                  alias: "travel_details",
                  uuid: "y3sc-b3rz-7r19-3zky-c3",
                  connId: "5dv9o",
                  dataSource: {
                    id: "1",
                    type: "dynamicDataSource",
                    baseType: "global.jdbc",
                    catSchemaPredicted: false,
                    sync: false,
                    catalog: "",
                    schema: "HIUSER",
                    connId: "5dv9o",
                    classifier: "db.workflow",
                    datasourceName: "SampleTravelDataDerby",
                    dsKeyPath:
                      "ns2s-01o7-7onv-d8wc-cx/89tg-10z4-jrde-jle5-vb/pigx-hibm-6z49-xw82-ou",
                    driverType: "Derby",
                    database: "HIUSER",
                  },
                  dataSourceName: "SampleTravelDataDerby",
                  category: "table",
                  nameWithConnId: "travel_details_5dv9o",
                  database: "HIUSER",
                  schema: "HIUSER",
                  selected: false,
                },
              ],
              keyPath:
                "ns2s-01o7-7onv-d8wc-cx/89tg-10z4-jrde-jle5-vb/pigx-hibm-6z49-xw82-ou",
              key: "pigx-hibm-6z49-xw82-ou",
              uuid: "pigx-hibm-6z49-xw82-ou",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
              fetched: true,
            },
            {
              name: "SYSCS_DIAG",
              children: [],
              keyPath:
                "ns2s-01o7-7onv-d8wc-cx/89tg-10z4-jrde-jle5-vb/bfaz-fkf2-yvlw-eo2b-12",
              key: "bfaz-fkf2-yvlw-eo2b-12",
              uuid: "bfaz-fkf2-yvlw-eo2b-12",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
            },
            {
              name: "SYSCS_UTIL",
              children: [],
              keyPath:
                "ns2s-01o7-7onv-d8wc-cx/89tg-10z4-jrde-jle5-vb/fs8w-yjlj-4dr8-7kon-5k",
              key: "fs8w-yjlj-4dr8-7kon-5k",
              uuid: "fs8w-yjlj-4dr8-7kon-5k",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
            },
            {
              name: "SYSIBM",
              children: [],
              keyPath:
                "ns2s-01o7-7onv-d8wc-cx/89tg-10z4-jrde-jle5-vb/9ukl-8xnm-wa3z-0j7t-hi",
              key: "9ukl-8xnm-wa3z-0j7t-hi",
              uuid: "9ukl-8xnm-wa3z-0j7t-hi",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
            },
            {
              name: "APP",
              children: [],
              keyPath:
                "ns2s-01o7-7onv-d8wc-cx/89tg-10z4-jrde-jle5-vb/d2ic-bzvk-0czw-o8fv-ea",
              key: "d2ic-bzvk-0czw-o8fv-ea",
              uuid: "d2ic-bzvk-0czw-o8fv-ea",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
            },
            {
              name: "NULLID",
              children: [],
              keyPath:
                "ns2s-01o7-7onv-d8wc-cx/89tg-10z4-jrde-jle5-vb/tf0z-dbi0-io2v-7bjj-bb",
              key: "tf0z-dbi0-io2v-7bjj-bb",
              uuid: "tf0z-dbi0-io2v-7bjj-bb",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
            },
            {
              name: "SYSPROC",
              children: [],
              keyPath:
                "ns2s-01o7-7onv-d8wc-cx/89tg-10z4-jrde-jle5-vb/fgsu-h5rs-74he-2rrc-5e",
              key: "fgsu-h5rs-74he-2rrc-5e",
              uuid: "fgsu-h5rs-74he-2rrc-5e",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
            },
            {
              name: "SYS",
              children: [],
              keyPath:
                "ns2s-01o7-7onv-d8wc-cx/89tg-10z4-jrde-jle5-vb/0hta-iqkv-wvs6-khms-bi",
              key: "0hta-iqkv-wvs6-khms-bi",
              uuid: "0hta-iqkv-wvs6-khms-bi",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
            },
            {
              name: "SYSSTAT",
              children: [],
              keyPath:
                "ns2s-01o7-7onv-d8wc-cx/89tg-10z4-jrde-jle5-vb/21fh-6h9r-xw4v-kp1b-73",
              key: "21fh-6h9r-xw4v-kp1b-73",
              uuid: "21fh-6h9r-xw4v-kp1b-73",
              data: {
                id: "1",
                type: "dynamicDataSource",
              },
              category: "schema",
              datasourceName: "SampleTravelDataDerby",
            },
          ],
          driverType: "Derby",
          keyPath: "ns2s-01o7-7onv-d8wc-cx/89tg-10z4-jrde-jle5-vb",
          key: "89tg-10z4-jrde-jle5-vb",
          uuid: "89tg-10z4-jrde-jle5-vb",
          fetched: true,
        },
        {
          data: {
            id: "1000",
            type: "dynamicDataSource",
          },
          dataSourceProvider: "tomcat",
          type: "dynamicDataSource",
          permissionLevel: 2,
          driver: "org.apache.derby.jdbc.AutoloadedDriver",
          name: "hiee",
          classifier: "global",
          dataSourceType: "Managed DataSource",
          category: "dataSource",
          children: [],
          driverType: "Derby",
          keyPath: "ns2s-01o7-7onv-d8wc-cx/67cp-j9ip-ruwf-yh6l-2h",
          key: "67cp-j9ip-ruwf-yh6l-2h",
          uuid: "67cp-j9ip-ruwf-yh6l-2h",
        },
        {
          data: {
            id: "1101",
            type: "dynamicDataSource",
          },
          dataSourceProvider: "tomcat",
          type: "dynamicDataSource",
          permissionLevel: 5,
          driver: "org.apache.derby.jdbc.AutoloadedDriver",
          name: "derby2",
          classifier: "global",
          dataSourceType: "Managed DataSource",
          category: "dataSource",
          children: [],
          driverType: "Derby",
          keyPath: "ns2s-01o7-7onv-d8wc-cx/xlpn-nu89-qdp1-4ozr-se",
          key: "xlpn-nu89-qdp1-4ozr-se",
          uuid: "xlpn-nu89-qdp1-4ozr-se",
        },
        {
          data: {
            id: "1801",
            type: "dynamicDataSource",
          },
          dataSourceProvider: "tomcat",
          type: "dynamicDataSource",
          permissionLevel: 5,
          driver: "org.apache.derby.jdbc.AutoloadedDriver",
          name: "Dump",
          classifier: "global",
          dataSourceType: "Managed DataSource",
          category: "dataSource",
          children: [],
          driverType: "Derby",
          keyPath: "ns2s-01o7-7onv-d8wc-cx/keyo-txis-g4np-7751-xa",
          key: "keyo-txis-g4np-7751-xa",
          uuid: "keyo-txis-g4np-7751-xa",
        },
      ],
      key: "ns2s-01o7-7onv-d8wc-cx",
      uuid: "ns2s-01o7-7onv-d8wc-cx",
      keyPath: "ns2s-01o7-7onv-d8wc-cx",
      category: "dsGroup",
      imgUrl: "images/data_sources/defaut_datasource.png",
    },
    {
      name: "DynamicSwitch",
      children: [
        {
          permissionLevel: 5,
          driver: "dynamicSwitch",
          name: "Groovy 1",
          classifier: "efwd",
          type: "sql.jdbc.groovy.managed",
          data: {
            dir: "Gagan",
            driverName: null,
            type: "sql.jdbc.groovy.managed",
            id: 1,
            userName: null,
            password: null,
            condition:
              'import groovy.sql.Sql;\n      import net.sf.json.JSONObject;\n      import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n      public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        if (userName.equals("hiadmin")) {\n          responseJson.put("globalId", 1001);\n        }\n      \n        if (userName.equals("hiuser")) {\n          responseJson.put("globalId", 3);\n        }\n      \n        if (userName.equals("test")) {\n          responseJson.put("globalId", 4);\n        }\n      \n        responseJson.put("type", "global.jdbc");\n      \n        //throw new RuntimeException("This is a test exception" +responseJson);\n        return responseJson;\n      }',
            jdbcUrl: null,
            driver: "dynamicSwitch",
          },
          dataSourceType: "",
          category: "dataSource",
          children: [],
          driverType: "DynamicSwitch",
          keyPath: "klk4-una3-uoyz-p6xq-ka/pulq-9zi0-2ova-ifov-1n",
          key: "pulq-9zi0-2ova-ifov-1n",
          uuid: "pulq-9zi0-2ova-ifov-1n",
        },
        {
          permissionLevel: 5,
          driver: "dynamicSwitch",
          name: "Groovy 1",
          classifier: "efwd",
          type: "sql.jdbc.groovy.managed",
          data: {
            dir: "Gagan",
            driverName: null,
            type: "sql.jdbc.groovy.managed",
            id: 1,
            userName: null,
            password: null,
            condition:
              'import groovy.sql.Sql;\n      import net.sf.json.JSONObject;\n      import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n      public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        if (userName.equals("hiadmin")) {\n          responseJson.put("globalId", 1001);\n        }\n      \n        if (userName.equals("hiuser")) {\n          responseJson.put("globalId", 3);\n        }\n      \n        if (userName.equals("test")) {\n          responseJson.put("globalId", 4);\n        }\n      \n        responseJson.put("type", "global.jdbc");\n      \n        //throw new RuntimeException("This is a test exception" +responseJson);\n        return responseJson;\n      }',
            jdbcUrl: null,
            driver: "dynamicSwitch",
          },
          dataSourceType: "",
          category: "dataSource",
          children: [],
          driverType: "DynamicSwitch",
          keyPath: "klk4-una3-uoyz-p6xq-ka/jqnx-06rk-grkp-g3mz-l6",
          key: "jqnx-06rk-grkp-g3mz-l6",
          uuid: "jqnx-06rk-grkp-g3mz-l6",
        },
      ],
      key: "klk4-una3-uoyz-p6xq-ka",
      uuid: "klk4-una3-uoyz-p6xq-ka",
      keyPath: "klk4-una3-uoyz-p6xq-ka",
      category: "dsGroup",
      imgUrl: "images/data_sources/defaut_datasource.png",
    },
    {
      name: "Postgresql",
      children: [
        {
          data: {
            id: "1001",
            type: "dynamicDataSource",
          },
          dataSourceProvider: "tomcat",
          type: "dynamicDataSource",
          permissionLevel: 5,
          driver: "org.postgresql.Driver",
          name: "booking",
          classifier: "global",
          dataSourceType: "Managed DataSource",
          category: "dataSource",
          children: [],
          driverType: "Postgresql",
          keyPath: "kqdq-0kw3-er1m-vm8w-kq/8002-59y9-3tro-okzt-n4",
          key: "8002-59y9-3tro-okzt-n4",
          uuid: "8002-59y9-3tro-okzt-n4",
        },
        {
          data: {
            id: "1401",
            type: "dynamicDataSource",
          },
          dataSourceProvider: "tomcat",
          type: "dynamicDataSource",
          permissionLevel: 5,
          driver: "org.postgresql.Driver",
          name: "booking",
          classifier: "global",
          dataSourceType: "Managed DataSource",
          category: "dataSource",
          children: [],
          driverType: "Postgresql",
          keyPath: "kqdq-0kw3-er1m-vm8w-kq/fm60-f70m-c2mv-d427-6k",
          key: "fm60-f70m-c2mv-d427-6k",
          uuid: "fm60-f70m-c2mv-d427-6k",
        },
      ],
      key: "kqdq-0kw3-er1m-vm8w-kq",
      uuid: "kqdq-0kw3-er1m-vm8w-kq",
      keyPath: "kqdq-0kw3-er1m-vm8w-kq",
      category: "dsGroup",
      imgUrl: "images/data_sources/defaut_datasource.png",
    },
    {
      name: "Sqlite",
      children: [
        {
          data: {
            id: "1201",
            type: "dynamicDataSource",
          },
          dataSourceProvider: "tomcat",
          type: "dynamicDataSource",
          permissionLevel: 5,
          driver: "org.sqlite.JDBC",
          name: "SampleTravelData",
          classifier: "global",
          dataSourceType: "Managed DataSource",
          category: "dataSource",
          children: [],
          driverType: "Sqlite",
          keyPath: "qz4e-ru4e-ge94-stck-ss/d19g-65jx-wa0g-gctl-ed",
          key: "d19g-65jx-wa0g-gctl-ed",
          uuid: "d19g-65jx-wa0g-gctl-ed",
        },
        {
          data: {
            id: "1302",
            type: "dynamicDataSource",
          },
          dataSourceProvider: "tomcat",
          type: "dynamicDataSource",
          permissionLevel: 5,
          driver: "org.sqlite.JDBC",
          name: "Sqlite",
          classifier: "global",
          dataSourceType: "Managed DataSource",
          category: "dataSource",
          children: [],
          driverType: "Sqlite",
          keyPath: "qz4e-ru4e-ge94-stck-ss/vqka-fmdz-mluk-petf-vm",
          key: "vqka-fmdz-mluk-petf-vm",
          uuid: "vqka-fmdz-mluk-petf-vm",
        },
      ],
      key: "qz4e-ru4e-ge94-stck-ss",
      uuid: "qz4e-ru4e-ge94-stck-ss",
      keyPath: "qz4e-ru4e-ge94-stck-ss",
      category: "dsGroup",
      imgUrl: "images/data_sources/defaut_datasource.png",
    },
  ],
  workFlow: {
    dataList: [
      {
        fetchSchemas: true,
        fetchCatalogs: true,
        working: true,
        connData: {
          id: "1",
          type: "dynamicDataSource",
        },
        connId: "1",
        dsUUID: "89tg-10z4-jrde-jle5-vb",
        classifier: "db.workflow",
        metadata: {
          catalogs: [
            {
              name: "Null",
              schemas: [
                {
                  name: "SQLJ",
                },
                {
                  name: "SYSFUN",
                },
                {
                  name: "SYSCAT",
                },
                {
                  name: "HIUSER",
                },
                {
                  name: "SYSCS_DIAG",
                },
                {
                  name: "SYSCS_UTIL",
                },
                {
                  name: "SYSIBM",
                },
                {
                  name: "APP",
                },
                {
                  name: "NULLID",
                },
                {
                  name: "SYSPROC",
                },
                {
                  name: "SYS",
                },
                {
                  name: "SYSSTAT",
                },
              ],
            },
          ],
        },
      },
      {
        classifier: "db.workflow",
        metadata: {
          catalogs: [
            {
              name: "Null",
              schemas: [
                {
                  name: "HIUSER",
                  tables: [
                    {
                      id: "be534112989b616b194bc59c2fb25a42",
                      name: "geo_cordinates",
                    },
                    {
                      id: "9645c648a1c0dbeec1287aaf1e996db3",
                      name: "meeting_details",
                    },
                    {
                      id: "4e1fd245f4d13b77be423a43f01d80b2",
                      name: "employee_details",
                    },
                    {
                      id: "4ac5d9f68b58bd7c0d179146e46795be",
                      name: "dimdate",
                    },
                    {
                      id: "8a28627d07d04ef096d9935f12e0c7e9",
                      name: "travel_details",
                    },
                  ],
                },
              ],
            },
          ],
          dataSource: {
            id: "1",
            type: "dynamicDataSource",
            baseType: "global.jdbc",
            catSchemaPredicted: false,
            sync: false,
            catalog: "",
            schema: "HIUSER",
            connId: "5dv9o",
            classifier: "db.workflow",
            datasourceName: "SampleTravelDataDerby",
            dsKeyPath:
              "ns2s-01o7-7onv-d8wc-cx/89tg-10z4-jrde-jle5-vb/pigx-hibm-6z49-xw82-ou",
            driverType: "Derby",
            database: "HIUSER",
          },
          name: "HIUSER",
        },
      },
    ],
  },
  dataSource: [
    {
      id: "1",
      type: "dynamicDataSource",
      baseType: "global.jdbc",
      catSchemaPredicted: false,
      sync: false,
      catalog: "",
      schema: "HIUSER",
      connId: "5dv9o",
      classifier: "db.workflow",
      datasourceName: "SampleTravelDataDerby",
      dsKeyPath:
        "ns2s-01o7-7onv-d8wc-cx/89tg-10z4-jrde-jle5-vb/pigx-hibm-6z49-xw82-ou",
      driverType: "Derby",
      database: "HIUSER",
    },
  ],
  tables: {
    dimdate: {
      id: "4ac5d9f68b58bd7c0d179146e46795be",
      name: "dimdate",
      data: {
        id: "1",
        type: "dynamicDataSource",
      },
      keyPath:
        "ns2s-01o7-7onv-d8wc-cx/89tg-10z4-jrde-jle5-vb/pigx-hibm-6z49-xw82-ou/itsg-xcqu-setw-yj1w-lx",
      key: "itsg-xcqu-setw-yj1w-lx",
      alias: "dimdate",
      uuid: "itsg-xcqu-setw-yj1w-lx",
      connId: "5dv9o",
      dataSource: {
        id: "1",
        type: "dynamicDataSource",
        baseType: "global.jdbc",
        catSchemaPredicted: false,
        sync: false,
        catalog: "",
        schema: "HIUSER",
        connId: "5dv9o",
        classifier: "db.workflow",
        datasourceName: "SampleTravelDataDerby",
        dsKeyPath:
          "ns2s-01o7-7onv-d8wc-cx/89tg-10z4-jrde-jle5-vb/pigx-hibm-6z49-xw82-ou",
        driverType: "Derby",
        database: "HIUSER",
      },
      dataSourceName: "SampleTravelDataDerby",
      category: "table",
      nameWithConnId: "dimdate_5dv9o",
      database: "HIUSER",
      schema: "HIUSER",
      selected: true,
      keyName: "dimdate",
    },
  },
  views: [],
  activeView: false,
  categories: {
    "ns2s-01o7-7onv-d8wc-cx": {
      ds: {
        data: {
          id: "1",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 2,
        driver: "org.apache.derby.jdbc.AutoloadedDriver",
        name: "SampleTravelDataDerby",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
      category: {
        driver: "org.apache.derby.jdbc.AutoloadedDriver",
        databaseDialect: "derby",
        name: "Derby",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:derby:{{database}}",
        parameters: {
          database: "database",
        },
      },
    },
    "klk4-una3-uoyz-p6xq-ka": {
      ds: {
        permissionLevel: 5,
        driver: "dynamicSwitch",
        name: "Groovy 1",
        classifier: "efwd",
        type: "sql.jdbc.groovy.managed",
        data: {
          dir: "Gagan",
          driverName: null,
          type: "sql.jdbc.groovy.managed",
          id: 1,
          userName: null,
          password: null,
          condition:
            'import groovy.sql.Sql;\n      import net.sf.json.JSONObject;\n      import com.helicalinsight.adhoc.metadata.GroovyUsersSession;\n      public JSONObject evalCondition() {\n        JSONObject responseJson = new JSONObject();\n        String userName = GroovyUsersSession.getValue(\'${user}.name\');\n        userName = userName.replaceAll("\'", "");\n        if (userName.equals("hiadmin")) {\n          responseJson.put("globalId", 1001);\n        }\n      \n        if (userName.equals("hiuser")) {\n          responseJson.put("globalId", 3);\n        }\n      \n        if (userName.equals("test")) {\n          responseJson.put("globalId", 4);\n        }\n      \n        responseJson.put("type", "global.jdbc");\n      \n        //throw new RuntimeException("This is a test exception" +responseJson);\n        return responseJson;\n      }',
          jdbcUrl: null,
          driver: "dynamicSwitch",
        },
        dataSourceType: "",
      },
      category: {
        driver: "dynamicSwitch",
        databaseDialect: "",
        name: "DynamicSwitch",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
      },
    },
    "kqdq-0kw3-er1m-vm8w-kq": {
      ds: {
        data: {
          id: "1001",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.postgresql.Driver",
        name: "booking",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
      category: {
        driver: "org.postgresql.Driver",
        databaseDialect: "postgresql",
        name: "Postgresql",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:postgresql://{{hostName}}:{{port}}/{{database}}",
        parameters: {
          port: "5432",
          hostName: "localhost",
          database: "database",
        },
      },
    },
    "qz4e-ru4e-ge94-stck-ss": {
      ds: {
        data: {
          id: "1201",
          type: "dynamicDataSource",
        },
        dataSourceProvider: "tomcat",
        type: "dynamicDataSource",
        permissionLevel: 5,
        driver: "org.sqlite.JDBC",
        name: "SampleTravelData",
        classifier: "global",
        dataSourceType: "Managed DataSource",
      },
      category: {
        driver: "org.sqlite.JDBC",
        databaseDialect: "sqlite",
        name: "Sqlite",
        categoryName: "RDBMS",
        categoryType: "rdbms",
        type: "global.jdbc",
        dataSourceProvider: "tomcat",
        classifier: "global",
        imgUrl: "../images/data_sources/defaut_datasource.png",
        url: "jdbc:sqlite:{{database}}",
        parameters: {
          database: "database",
        },
      },
    },
  },
  activeEditorTab: "info",
  dataSourcesAddedToMetadata: [
    {
      id: "1",
      type: "dynamicDataSource",
      baseType: "global.jdbc",
      catSchemaPredicted: false,
      sync: false,
      catalog: "",
      schema: "HIUSER",
      connId: "5dv9o",
      classifier: "db.workflow",
      datasourceName: "SampleTravelDataDerby",
      dsKeyPath:
        "ns2s-01o7-7onv-d8wc-cx/89tg-10z4-jrde-jle5-vb/pigx-hibm-6z49-xw82-ou",
      driverType: "Derby",
      database: "HIUSER",
    },
  ],
  changeDSList: {},
  changedTables: [],
  changedColumns: [],
  removedTables: [],
  removedColumns: [],
  removedDataSources: [],
  duplicateColumnList: [],
  duplicateTableList: [],
  unsavedViews: [],
  saveDetails: false,
  savedTableIds: [],
  savedColumnIds: [],
  joins: [],
  mode: "create",
  allTablesKeys: [
    "8eav-dfol-9rtq-er21-0k",
    "i88c-g1qd-mmkb-fl8o-qa",
    "sa5g-9y71-77ct-ju84-sr",
    "itsg-xcqu-setw-yj1w-lx",
    "y3sc-b3rz-7r19-3zky-c3",
  ],
  selectedTableKeys: ["itsg-xcqu-setw-yj1w-lx"],
  metadataName: "Metadata_1",
  activeDataSource: false,
  metadataToEdit: false,
  isSavingInProgress: false,
  editViewsTempData: {},
  inititalStateFromJest: false,
  timeStamp: 1673610827002,
  initialEditResponse: false,
  editorFullView: false,
  selectedTableOrColumnKey: {},
  expressionObj: [],
  securityConstants: {},
  edit: false,
  isAllowServiceCall: true,
  isValidatedTableShow: false,
  securityTableData: [],
  addOneMoreSecurity: false,
  viewSessionVariables: false,
  textEditingObj: {},
  selectedJoinNameData: {},
  filterbyData: [
    {
      value: "All",
      isChecked: true,
    },
    {
      value: "Table",
      isChecked: true,
    },
    {
      value: "Column",
      isChecked: true,
    },
    {
      value: "Global",
      isChecked: true,
    },
  ],
  isFirstRender: true,
  securityFormData: {},
  accessType: "deny",
  entityNames: "",
  executionType: "conditionIf",
  expressionName: null,
  expressionType: "",
  isApplyDisabled: true,
  isInfoShow: true,
  securityKeysChecked: [],
  hasUnsavedData: true,
  getSecurityTableData: {
    tables: [],
    columns: [],
  },
  doResetFormData: false,
  tablesMergeType: "reload",
  activeDsInfoId: "5dv9o",
};
